// Command gen-unicode writes burrow's Unicode tables from Go's.
//
// The design (docs/design/09-packages-pure.md section 3) asks for the tables to
// be regenerated rather than typed, so that every RangeTable is bit identical
// to Go's. Go's own tables.go is already the output of its maketables run over
// the Unicode Character Database, so this reads that file instead of the UCD:
// it type checks the unicode package from GOROOT, which gives the value of
// every constant expression in it, and prints the same tables as C. The Go on
// PATH should be the release the port follows.
//
// It writes src/unicode/tables.c, and the part of include/burrow/unicode.h
// between the BEGIN and END GENERATED DECLARATIONS markers.
//
//	go run tools/gen-unicode/main.go
//
// Copyright 2026 The burrow Authors. All rights reserved.
// Use of this source code is governed by a BSD-style licence that can be found
// in the LICENSE file.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"unicode"
)

var (
	fset  = token.NewFileSet()
	info  = &types.Info{Types: map[ast.Expr]types.TypeAndValue{}, Defs: map[*ast.Ident]types.Object{}, Uses: map[*ast.Ident]types.Object{}}
	inits = map[types.Object]ast.Expr{}
	order []types.Object
	files = map[types.Object]string{}
)

func main() {
	dir := filepath.Join(runtime.GOROOT(), "src", "unicode")
	var fs []*ast.File
	for _, name := range []string{"casetables.go", "digit.go", "graphic.go", "letter.go", "tables.go"} {
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		check(err)
		fs = append(fs, f)
	}
	conf := types.Config{Importer: importer.Default()}
	_, err := conf.Check("unicode", fset, fs, info)
	check(err)
	for _, f := range fs {
		file := filepath.Base(fset.File(f.Pos()).Name())
		for _, d := range f.Decls {
			g, ok := d.(*ast.GenDecl)
			if !ok || g.Tok != token.VAR {
				continue
			}
			for _, s := range g.Specs {
				vs := s.(*ast.ValueSpec)
				for i, n := range vs.Names {
					obj := info.Defs[n]
					inits[obj] = vs.Values[i]
					order = append(order, obj)
					files[obj] = file
				}
			}
		}
	}

	var c, h bytes.Buffer
	emit(&c, &h)
	check(os.WriteFile("src/unicode/tables.c", c.Bytes(), 0o644))
	hdr, err := os.ReadFile("include/burrow/unicode.h")
	check(err)
	re := regexp.MustCompile(`(?s)(/\* BEGIN GENERATED DECLARATIONS \*/\n).*(/\* END GENERATED DECLARATIONS \*/)`)
	if !re.Match(hdr) {
		check(fmt.Errorf("include/burrow/unicode.h has no generated declarations markers"))
	}
	hdr = re.ReplaceAllFunc(hdr, func(m []byte) []byte {
		sub := re.FindSubmatch(m)
		return append(append(append([]byte{}, sub[1]...), h.Bytes()...), sub[2]...)
	})
	check(os.WriteFile("include/burrow/unicode.h", hdr, 0o644))
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-unicode:", err)
		os.Exit(1)
	}
}

// words splits a Go name the way tools/burrow-coverage does, so that the C
// names are the ones the coverage tool looks for.
func snake(name string) string {
	var out []string
	for _, part := range strings.Split(name, "_") {
		rs := []rune(part)
		i := 0
		for i < len(rs) {
			j := i + 1
			if unicode.IsUpper(rs[i]) {
				for j < len(rs) && unicode.IsUpper(rs[j]) {
					j++
				}
				if j < len(rs) && unicode.IsLower(rs[j]) && j-i > 1 {
					j--
				}
			}
			for j < len(rs) && !unicode.IsUpper(rs[j]) {
				j++
			}
			out = append(out, strings.ToLower(string(rs[i:j])))
			i = j
		}
	}
	return strings.Join(out, "_")
}

func val(e ast.Expr) int64 {
	tv, ok := info.Types[e]
	if !ok || tv.Value == nil {
		check(fmt.Errorf("%s: not a constant", fset.Position(e.Pos())))
	}
	v, ok := constant.Int64Val(tv.Value)
	if !ok {
		check(fmt.Errorf("%s: not an integer", fset.Position(e.Pos())))
	}
	return v
}

func obj(e ast.Expr) types.Object {
	id, ok := e.(*ast.Ident)
	if !ok {
		check(fmt.Errorf("%s: not an identifier", fset.Position(e.Pos())))
	}
	return info.Uses[id]
}

// canon follows var X = Y until it reaches the variable whose value is the
// table itself.
func canon(o types.Object) types.Object {
	for {
		e := inits[o]
		if id, ok := e.(*ast.Ident); ok {
			o = info.Uses[id]
			continue
		}
		return o
	}
}

func isTable(o types.Object) bool {
	u, ok := inits[o].(*ast.UnaryExpr)
	if !ok {
		return false
	}
	cl, ok := u.X.(*ast.CompositeLit)
	return ok && types.ExprString(cl.Type) == "RangeTable"
}

func static(o types.Object) string {
	return "utab_" + snake(strings.TrimPrefix(o.Name(), "_"))
}

func emit(c, h *bytes.Buffer) {
	fmt.Fprintf(c, `/* Derived from Go's src/unicode/tables.go and src/unicode/casetables.go.
 * Go source: %s.
 *
 * Generated by tools/gen-unicode/main.go from Go's own tables. Do not edit.
 *
 * Copyright 2009 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "burrow/unicode.h"

#include "tables.h"

/* clang-format off */
`, runtime.Version())

	seen := map[string]types.Object{}
	name := func(o types.Object, n string) string {
		if prev, ok := seen[n]; ok && prev != o {
			check(fmt.Errorf("%s and %s both become %s", prev.Name(), o.Name(), n))
		}
		seen[n] = o
		return n
	}

	// The tables themselves.
	for _, o := range order {
		if !isTable(o) {
			continue
		}
		s := name(o, static(o))
		cl := inits[o].(*ast.UnaryExpr).X.(*ast.CompositeLit)
		var r16, r32 []*ast.CompositeLit
		latin := int64(0)
		for _, el := range cl.Elts {
			kv := el.(*ast.KeyValueExpr)
			switch kv.Key.(*ast.Ident).Name {
			case "R16":
				for _, x := range kv.Value.(*ast.CompositeLit).Elts {
					r16 = append(r16, x.(*ast.CompositeLit))
				}
			case "R32":
				for _, x := range kv.Value.(*ast.CompositeLit).Elts {
					r32 = append(r32, x.(*ast.CompositeLit))
				}
			case "LatinOffset":
				latin = val(kv.Value)
			}
		}
		n16, n32 := "NULL", "NULL"
		if len(r16) > 0 {
			n16 = s + "_r16"
			fmt.Fprintf(c, "\nstatic const UnicodeRange16 %s[] = {\n", n16)
			for _, r := range r16 {
				fmt.Fprintf(c, "    {0x%04x, 0x%04x, %d},\n", val(r.Elts[0]), val(r.Elts[1]), val(r.Elts[2]))
			}
			c.WriteString("};\n")
		}
		if len(r32) > 0 {
			n32 = s + "_r32"
			fmt.Fprintf(c, "\nstatic const UnicodeRange32 %s[] = {\n", n32)
			for _, r := range r32 {
				fmt.Fprintf(c, "    {0x%x, 0x%x, %d},\n", val(r.Elts[0]), val(r.Elts[1]), val(r.Elts[2]))
			}
			c.WriteString("};\n")
		}
		fmt.Fprintf(c, "\nstatic const UnicodeRangeTable %s = {%s, %d, %s, %d, %d};\n", s, n16, len(r16), n32, len(r32), latin)
	}

	// The exported names for them.
	c.WriteString("\n/* The exported tables, several of them under more than one name. */\n\n")
	h.WriteString("\n/* The tables, by the names Go gives them. */\n\n")
	for _, o := range order {
		if !o.Exported() || !isTable(canon(o)) || files[o] != "tables.go" {
			continue
		}
		n := name(o, "unicode_"+snake(o.Name()))
		fmt.Fprintf(h, "extern const UnicodeRangeTable *const %s;\n", n)
		fmt.Fprintf(c, "const UnicodeRangeTable *const %s = &%s;\n", n, static(canon(o)))
	}

	// The maps, as arrays sorted by name.
	maps := []struct{ goName, what string }{
		{"Categories", "the categories, by their one or two letter names"},
		{"Scripts", "the scripts"},
		{"Properties", "the properties"},
		{"FoldCategory", "for each category, the code points outside it that are equivalent to one inside it under simple case folding"},
		{"FoldScript", "for each script, the code points outside it that are equivalent to one inside it under simple case folding"},
	}
	for _, m := range maps {
		var o types.Object
		for _, x := range order {
			if x.Name() == m.goName {
				o = x
			}
		}
		type kv struct {
			k string
			v types.Object
		}
		var ents []kv
		for _, el := range inits[o].(*ast.CompositeLit).Elts {
			e := el.(*ast.KeyValueExpr)
			ents = append(ents, kv{constant.StringVal(info.Types[e.Key].Value), canon(obj(e.Value))})
		}
		sort.Slice(ents, func(i, j int) bool { return ents[i].k < ents[j].k })
		n := "unicode_" + snake(m.goName)
		fmt.Fprintf(c, "\nstatic const UnicodeNamedTable %s_entries[] = {\n", n)
		for _, e := range ents {
			fmt.Fprintf(c, "    {BURROW_S_INIT(%q), &%s},\n", e.k, static(e.v))
		}
		fmt.Fprintf(c, "};\n\nconst UnicodeTableMap %s = {%s_entries, %d};\n", n, n, len(ents))
		fmt.Fprintf(h, "\n/* %s: %s. */\nextern const UnicodeTableMap %s;\n", m.goName, m.what, n)
	}

	// CategoryAliases.
	{
		var o types.Object
		for _, x := range order {
			if x.Name() == "CategoryAliases" {
				o = x
			}
		}
		type kv struct{ k, v string }
		var ents []kv
		for _, el := range inits[o].(*ast.CompositeLit).Elts {
			e := el.(*ast.KeyValueExpr)
			ents = append(ents, kv{constant.StringVal(info.Types[e.Key].Value), constant.StringVal(info.Types[e.Value].Value)})
		}
		sort.Slice(ents, func(i, j int) bool { return ents[i].k < ents[j].k })
		c.WriteString("\nstatic const UnicodeAlias unicode_category_aliases_entries[] = {\n")
		for _, e := range ents {
			fmt.Fprintf(c, "    {BURROW_S_INIT(%q), BURROW_S_INIT(%q)},\n", e.k, e.v)
		}
		fmt.Fprintf(c, "};\n\nconst UnicodeAliasMap unicode_category_aliases = {unicode_category_aliases_entries, %d};\n", len(ents))
		h.WriteString("\n/* CategoryAliases: the long names of the categories, mapped to the short\n * ones that Categories uses. */\nextern const UnicodeAliasMap unicode_category_aliases;\n")
	}

	// The case tables.
	caseRanges := func(n string, e ast.Expr) int {
		elts := e.(*ast.CompositeLit).Elts
		fmt.Fprintf(c, "\nstatic const UnicodeCaseRange %s[] = {\n", n)
		for _, x := range elts {
			cr := x.(*ast.CompositeLit)
			d := cr.Elts[2].(*ast.CompositeLit)
			var ds []string
			for _, y := range d.Elts {
				v := val(y)
				if v == unicode.UpperLower {
					ds = append(ds, "UNICODE_UPPER_LOWER")
				} else {
					ds = append(ds, fmt.Sprint(v))
				}
			}
			fmt.Fprintf(c, "    {0x%04X, 0x%04X, {%s}},\n", val(cr.Elts[0]), val(cr.Elts[1]), strings.Join(ds, ", "))
		}
		c.WriteString("};\n")
		return len(elts)
	}
	for _, x := range order {
		switch x.Name() {
		case "_CaseRanges":
			n := caseRanges("unicode_case_ranges_entries", inits[x])
			fmt.Fprintf(c, "\nconst UnicodeSpecialCase unicode_case_ranges = {unicode_case_ranges_entries, %d};\n", n)
			h.WriteString("\n/* CaseRanges: the table ToUpper, ToLower and ToTitle look in. Go's type for it\n * is []CaseRange, which has the same shape as SpecialCase. */\nextern const UnicodeSpecialCase unicode_case_ranges;\n")
		case "_TurkishCase":
			n := caseRanges("unicode_turkish_case_entries", inits[x])
			fmt.Fprintf(c, "\nconst UnicodeSpecialCase unicode_turkish_case = {unicode_turkish_case_entries, %d};\n", n)
			c.WriteString("const UnicodeSpecialCase unicode_azeri_case = {unicode_turkish_case_entries, " + fmt.Sprint(n) + "};\n")
			h.WriteString("\n/* The case mappings Turkish and Azeri use, which differ from the defaults\n * for the dotted and dotless i. */\nextern const UnicodeSpecialCase unicode_turkish_case;\nextern const UnicodeSpecialCase unicode_azeri_case;\n")
		}
	}

	// GraphicRanges and PrintRanges. The arrays are not const, because a Slice
	// holds a plain void pointer, the same as Go, where nothing stops a caller
	// from writing to them either.
	rangesDoc := map[string]string{
		"GraphicRanges": "the tables unicode_is_graphic checks, letters, marks, numbers, punctuation, symbols and spaces",
		"PrintRanges":   "the tables unicode_is_print checks, which are the graphic ones without the spaces",
	}
	for _, x := range order {
		if x.Name() != "GraphicRanges" && x.Name() != "PrintRanges" {
			continue
		}
		elts := inits[x].(*ast.CompositeLit).Elts
		n := "unicode_" + snake(x.Name())
		var ps []string
		for _, e := range elts {
			ps = append(ps, "&"+static(canon(obj(e))))
		}
		fmt.Fprintf(c, "\nstatic const UnicodeRangeTable *%s_entries[] = {%s};\n", n, strings.Join(ps, ", "))
		fmt.Fprintf(c, "const Slice %s = {(void *)%s_entries, %d, %d, TYPE_UNSAFE_POINTER};\n", n, n, len(elts), len(elts))
		fmt.Fprintf(h, "\n/* %s: %s, as a Slice of pointers to UnicodeRangeTable. */\nextern const Slice %s;\n", x.Name(), rangesDoc[x.Name()], n)
	}

	// The private tables behind IsPrint, SimpleFold and the ASCII fast paths.
	for _, x := range order {
		switch x.Name() {
		case "properties":
			elts := inits[x].(*ast.CompositeLit).Elts
			vals := make([]int64, 256)
			for _, e := range elts {
				kv := e.(*ast.KeyValueExpr)
				vals[val(kv.Key)] = val(kv.Value)
			}
			c.WriteString("\nconst uint8_t burrow__unicode_properties[256] = {\n")
			for i := 0; i < 256; i += 16 {
				c.WriteString("   ")
				for _, v := range vals[i : i+16] {
					fmt.Fprintf(c, " 0x%02x,", v)
				}
				c.WriteString("\n")
			}
			c.WriteString("};\n")
		case "asciiFold":
			elts := inits[x].(*ast.CompositeLit).Elts
			c.WriteString("\nconst uint16_t burrow__unicode_ascii_fold[128] = {\n")
			for i := 0; i < len(elts); i += 8 {
				c.WriteString("   ")
				for _, e := range elts[i:min(i+8, len(elts))] {
					fmt.Fprintf(c, " 0x%04X,", val(e))
				}
				c.WriteString("\n")
			}
			c.WriteString("};\n")
		case "caseOrbit":
			elts := inits[x].(*ast.CompositeLit).Elts
			c.WriteString("\nconst BurrowUnicodeFoldPair burrow__unicode_case_orbit[] = {\n")
			for _, e := range elts {
				p := e.(*ast.CompositeLit)
				fmt.Fprintf(c, "    {0x%04X, 0x%04X},\n", val(p.Elts[0]), val(p.Elts[1]))
			}
			fmt.Fprintf(c, "};\n\nconst Int burrow__unicode_case_orbit_len = %d;\n", len(elts))
		}
	}
	c.WriteString("\n/* clang-format on */\n")

	var version string
	scope := info.Defs
	for id, o := range scope {
		if id.Name == "Version" && o != nil {
			if k, ok := o.(*types.Const); ok {
				version = constant.StringVal(k.Val())
			}
		}
	}
	hv := fmt.Sprintf("\n/* The version of Unicode the tables come from. */\n#define UNICODE_VERSION %q\n", version)
	*h = *bytes.NewBuffer(append([]byte(hv), h.Bytes()...))
	h.WriteString("\n")
}
