/* The resolver's groundwork, from Go's parse_test.go, hosts_test.go,
 * dnsconfig_unix_test.go, dnsname_test.go, dnsclient_test.go and
 * TestReverseAddress in lookup_test.go. The files under Go's testdata are
 * written out here, byte for byte, into a temporary directory.
 *
 * Copyright 2009 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "burrow/burrow.h"
#include "burrow/context.h"
#include "burrow/error.h"
#include "burrow/io/fs.h"
#include "burrow/mem/arena.h"
#include "burrow/net.h"
#include "burrow/os.h"
#include "burrow/path.h"
#include "burrow/strings.h"
#include "burrow/testing.h"
#include "burrow/time.h"

#include "../src/net/internal.h"
#include "check.h"

#include <stdint.h>
#include <string.h>

typedef struct TestFile {
    const char *name;
    const char *data;
    Int len;
} TestFile;

/* Go's src/net/testdata, the files these tests read. */
static const TestFile test_files[] = {
    {"aliases",
     "127.0.0.1 test\n"
     "127.0.0.2 test2.example.com 2.test\n"
     "127.0.0.3 3.test test3.example.com\n"
     "127.0.0.4 example.com\n"
     "127.0.0.5 test4.example.com 4.test 5.test test5.example.com\n"
     "\n"
     "# must be a non resolvable domain on the internet\n"
     "127.0.1.1 invalid.test invalid.invalid\n",
     257},
    {"case-hosts",
     "127.0.0.1\tPreserveMe\tPreserveMe.local\n"
     "::1\t\tPreserveMe\tPreserveMe.local\n",
     71},
    {"domain-resolv.conf",
     "# /etc/resolv.conf\n"
     "\n"
     "search test invalid\n"
     "domain localdomain\n"
     "nameserver 8.8.8.8\n",
     78},
    {"empty-resolv.conf", "# /etc/resolv.conf\n", 19},
    {"freebsd-usevc-resolv.conf", "options usevc", 13},
    {"hosts",
     "255.255.255.255\tbroadcasthost\n"
     "127.0.0.2\todin\n"
     "127.0.0.3\todin  # inline comment \n"
     "::2             odin\n"
     "127.1.1.1\tthor\n"
     "# aliases\n"
     "127.1.1.2\tullr ullrhost\n"
     "fe80::1%lo0\tlocalhost\n"
     "# Bogus entries that must be ignored.\n"
     "123.123.123\tloki\n"
     "321.321.321.321\n",
     242},
    {"invalid-ndots-resolv.conf", "options ndots:invalid", 21},
    {"ipv4-hosts",
     "# See https://tools.ietf.org/html/rfc1123.\n"
     "\n"
     "# internet address and host name\n"
     "127.0.0.1\tlocalhost\t# inline comment separated by tab\n"
     "127.0.0.2\tlocalhost   # inline comment separated by space\n"
     "\n"
     "# internet address, host name and aliases\n"
     "127.0.0.3\tlocalhost\tlocalhost.localdomain\n",
     274},
    {"ipv6-hosts",
     "# See https://tools.ietf.org/html/rfc5952, https://tools.ietf.org/html/rfc4007.\n"
     "\n"
     "# internet address and host name\n"
     "::1\t\t\t\t\t\tlocalhost\t# inline comment separated by tab\n"
     "fe80:0000:0000:0000:0000:0000:0000:0001\t\tlocalhost       # inline comment "
     "separated by space\n"
     "\n"
     "# internet address with zone identifier and host name\n"
     "fe80:0000:0000:0000:0000:0000:0000:0002%lo0\tlocalhost\n"
     "\n"
     "# internet address, host name and aliases\n"
     "fe80::3%lo0\t\t\t\t\tlocalhost\tlocalhost.localdomain\n",
     460},
    {"large-ndots-resolv.conf", "options ndots:16", 16},
    {"linux-use-vc-resolv.conf", "options use-vc", 14},
    {"negative-ndots-resolv.conf", "options ndots:-1", 16},
    {"openbsd-resolv.conf",
     "# Generated by vio0 dhclient\n"
     "search c.symbolic-datum-552.internal.\n"
     "nameserver 169.254.169.254\n"
     "nameserver 10.240.0.1\n"
     "lookup file bind\n",
     133},
    {"openbsd-tcp-resolv.conf", "options tcp", 11},
    {"resolv.conf",
     "# /etc/resolv.conf\n"
     "\n"
     "domain localdomain\n"
     "nameserver 8.8.8.8\n"
     "nameserver 2001:4860:4860::8888\n"
     "nameserver fe80::1%lo0\n"
     "options ndots:5 timeout:10 attempts:3 rotate\n"
     "options attempts 3\n",
     177},
    {"search-resolv.conf",
     "# /etc/resolv.conf\n"
     "\n"
     "domain localdomain\n"
     "search test invalid\n"
     "nameserver 8.8.8.8\n",
     78},
    {"search-single-dot-resolv.conf",
     "# /etc/resolv.conf\n"
     "\n"
     "domain localdomain\n"
     "search .\n"
     "nameserver 8.8.8.8\n",
     67},
    {"single-request-reopen-resolv.conf", "options single-request-reopen", 29},
    {"single-request-resolv.conf", "options single-request", 22},
    {"singleline-hosts", "127.0.0.2\todin", 14},
};

/* The testdata files in a new temporary directory, which the caller removes. */
static Str write_testdata(TestingT *t, Alloc *a) {
    Error err = BURROW_NO_ERROR;
    Str dir = os_mkdir_temp(a, BURROW_STR_EMPTY, BURROW_S("net-dns"), &err);
    if (BURROW_FAILED(err)) {
        testing_t_fatalf_v(t, "MkdirTemp: %v", err);
        return BURROW_STR_EMPTY;
    }
    for (size_t i = 0; i < sizeof test_files / sizeof test_files[0]; i++) {
        const TestFile *f = &test_files[i];
        Str name = path_join_v(a, 2, dir, str_from_cstr(f->name));
        Slice data = slice_from((void *)(uintptr_t)f->data, f->len, f->len, TYPE_BYTE);
        err = os_write_file(name, data, 0644);
        if (BURROW_FAILED(err)) {
            (void)os_remove_all(dir);
            testing_t_fatalf_v(t, "WriteFile: %v", err);
            return BURROW_STR_EMPTY;
        }
    }
    return dir;
}

static Str td(Alloc *a, Str dir, const char *name) {
    return path_join_v(a, 2, dir, str_from_cstr(name));
}

/* A slice of Str the way %v prints one in Go. */
static Str strs(Alloc *a, Slice s) {
    Str j = strings_join(a, s, BURROW_S(" "));
    Str out = strings_join(
        a, slice_from((Str[]){BURROW_S("["), j, BURROW_S("]")}, 3, 3, TYPE_STRING),
        BURROW_STR_EMPTY);
    return out;
}

static Slice cstrs(Alloc *a, const char *const *v, Int n) {
    Slice s = slice_make(a, TYPE_STRING, 0, n);
    for (Int i = 0; i < n; i++) {
        Str x = str_from_cstr(v[i]);
        s = slice_append(a, s, &x, 1);
    }
    return s;
}

static bool strs_eq(Slice x, Slice y) {
    if (x.len != y.len)
        return false;
    for (Int i = 0; i < x.len; i++)
        if (!str_eq(((const Str *)x.p)[i], ((const Str *)y.p)[i]))
            return false;
    return true;
}

static Str abs_name(Alloc *a, Str s) {
    return burrow__net_abs_domain_name(a, s);
}

/* ------------------------------------------------------------- parse_test.go */

static void TestReadLine(TestingT *t) {
#if defined(BURROW_OS_WINDOWS) || defined(BURROW_OS_WASI)
    testing_t_skip_v(t, "no /etc/services here");
    return;
#else
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str filename = BURROW_S("/etc/services"); /* a nice big file */
    Error err = BURROW_NO_ERROR;
    Slice whole = os_read_file(a, filename, &err);
    if (BURROW_FAILED(err)) {
        arena_free(&ar);
        testing_t_skipf_v(t, "skipping because failed to open /etc/services: %v", err);
        return;
    }
    burrow__NetFile *file = burrow__net_open(a, filename, &err);
    if (file == NULL) {
        arena_free(&ar);
        testing_t_fatal_v(t, err);
        return;
    }
    const Byte *p = (const Byte *)whole.p;
    Int pos = 0;
    Int lineno = 1;
    Int byteno = 0;
    for (;;) {
        /* bufio's ReadString('\n') over the same bytes. */
        Str bline = BURROW_STR_EMPTY;
        bool berr = false;
        const Byte *nl =
            pos < whole.len
                ? (const Byte *)memchr(p + pos, '\n', (size_t)(whole.len - pos))
                : NULL;
        if (nl != NULL) {
            bline = str_from_bytes(p + pos, (Int)(nl - (p + pos)) + 1);
            pos += bline.len;
        } else {
            bline = str_from_bytes(p + pos, whole.len - pos);
            pos = whole.len;
            berr = true;
        }
        if (bline.len > 0)
            bline.len--;
        Str line;
        bool ok = burrow__net_file_read_line(file, &line);
        if (berr != !ok || !str_eq(bline, line)) {
            testing_t_fatalf_v(t, "%s:%d (#%d)\nbufio => %q, %v\nnet => %q, %v",
                               filename, lineno, byteno, bline, berr, line, ok);
            break;
        }
        if (!ok)
            break;
        lineno++;
        byteno += line.len + 1;
    }
    burrow__net_file_close(file, a);
    arena_free(&ar);
#endif
}

static void TestDtoi(TestingT *t) {
    static const struct {
        const char *in;
        Int out;
        Int off;
        bool ok;
    } tests[] = {
        {"", 0, 0, false},         {"0", 0, 1, true},
        {"65536", 65536, 5, true}, {"123456789", BURROW__NET_BIG, 8, false},
        {"-0", 0, 0, false},       {"-1234", 0, 0, false},
    };
    for (size_t k = 0; k < sizeof tests / sizeof tests[0]; k++) {
        Int n = -1;
        Int i = -1;
        bool ok = burrow__net_dtoi(str_from_cstr(tests[k].in), &n, &i);
        if (n != tests[k].out || i != tests[k].off || ok != tests[k].ok)
            testing_t_errorf_v(t, "got %d, %d, %v; want %d, %d, %v", n, i, ok,
                               tests[k].out, tests[k].off, tests[k].ok);
    }
}

/* ------------------------------------------------------------- hosts_test.go */

typedef struct StaticHostEntry {
    const char *in;
    const char *out[5];
    Int nout;
} StaticHostEntry;

typedef struct StaticHostTest {
    const char *name;
    StaticHostEntry ents[8];
    Int nents;
} StaticHostTest;

static const StaticHostTest lookup_static_host_tests[] = {
    {"hosts",
     {
         {"odin", {"127.0.0.2", "127.0.0.3", "::2"}, 3},
         {"thor", {"127.1.1.1"}, 1},
         {"ullr", {"127.1.1.2"}, 1},
         {"ullrhost", {"127.1.1.2"}, 1},
         {"localhost", {"fe80::1%lo0"}, 1},
     },
     5},
    {"singleline-hosts", /* see golang.org/issue/6646 */
     {
         {"odin", {"127.0.0.2"}, 1},
     },
     1},
    {"ipv4-hosts",
     {
         {"localhost", {"127.0.0.1", "127.0.0.2", "127.0.0.3"}, 3},
         {"localhost.localdomain", {"127.0.0.3"}, 1},
     },
     2},
    {"ipv6-hosts", /* see golang.org/issue/8996 */
     {
         {"localhost", {"::1", "fe80::1", "fe80::2%lo0", "fe80::3%lo0"}, 4},
         {"localhost.localdomain", {"fe80::3%lo0"}, 1},
     },
     2},
    {"case-hosts", /* see golang.org/issue/12806 */
     {
         {"PreserveMe", {"127.0.0.1", "::1"}, 2},
         {"PreserveMe.local", {"127.0.0.1", "::1"}, 2},
     },
     2},
};

static void test_static_host(TestingT *t, Alloc *a, const char *hosts_path,
                             const StaticHostEntry *ent) {
    Str in0 = str_from_cstr(ent->in);
    Str ins[4] = {in0, abs_name(a, in0), strings_to_lower(a, in0),
                  strings_to_upper(a, in0)};
    Slice want = cstrs(a, ent->out, ent->nout);
    for (int i = 0; i < 4; i++) {
        Str canonical;
        Slice addrs = burrow__net_lookup_static_host(a, ins[i], &canonical);
        if (!strs_eq(addrs, want))
            testing_t_errorf_v(t, "%s, lookupStaticHost(%s) = %s; want %s", hosts_path,
                               ins[i], strs(a, addrs), strs(a, want));
    }
}

static void TestLookupStaticHost(TestingT *t) {
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str dir = write_testdata(t, a);
    if (dir.len == 0) {
        arena_free(&ar);
        return;
    }
    for (size_t k = 0;
         k < sizeof lookup_static_host_tests / sizeof lookup_static_host_tests[0];
         k++) {
        const StaticHostTest *tt = &lookup_static_host_tests[k];
        burrow__net_set_hosts_file_path(td(a, dir, tt->name));
        for (Int i = 0; i < tt->nents; i++)
            test_static_host(t, a, tt->name, &tt->ents[i]);
    }
    burrow__net_set_hosts_file_path(BURROW_STR_EMPTY);
    (void)os_remove_all(dir);
    arena_free(&ar);
}

static const StaticHostTest lookup_static_addr_tests[] = {
    {"hosts",
     {
         {"255.255.255.255", {"broadcasthost"}, 1},
         {"127.0.0.2", {"odin"}, 1},
         {"127.0.0.3", {"odin"}, 1},
         {"::2", {"odin"}, 1},
         {"127.1.1.1", {"thor"}, 1},
         {"127.1.1.2", {"ullr", "ullrhost"}, 2},
         {"fe80::1%lo0", {"localhost"}, 1},
     },
     7},
    {"singleline-hosts", /* see golang.org/issue/6646 */
     {
         {"127.0.0.2", {"odin"}, 1},
     },
     1},
    {"ipv4-hosts",
     {
         {"127.0.0.1", {"localhost"}, 1},
         {"127.0.0.2", {"localhost"}, 1},
         {"127.0.0.3", {"localhost", "localhost.localdomain"}, 2},
     },
     3},
    {"ipv6-hosts", /* see golang.org/issue/8996 */
     {
         {"::1", {"localhost"}, 1},
         {"fe80::1", {"localhost"}, 1},
         {"fe80::2%lo0", {"localhost"}, 1},
         {"fe80::3%lo0", {"localhost", "localhost.localdomain"}, 2},
     },
     4},
    {"case-hosts", /* see golang.org/issue/12806 */
     {
         {"127.0.0.1", {"PreserveMe", "PreserveMe.local"}, 2},
         {"::1", {"PreserveMe", "PreserveMe.local"}, 2},
     },
     2},
};

static void test_static_addr(TestingT *t, Alloc *a, const char *hosts_path,
                             const StaticHostEntry *ent) {
    Slice hosts = burrow__net_lookup_static_addr(a, str_from_cstr(ent->in));
    Slice want = cstrs(a, ent->out, ent->nout);
    for (Int i = 0; i < want.len; i++)
        ((Str *)want.p)[i] = abs_name(a, ((Str *)want.p)[i]);
    if (!strs_eq(hosts, want))
        testing_t_errorf_v(t, "%s, lookupStaticAddr(%s) = %s; want %s", hosts_path,
                           ent->in, strs(a, hosts), strs(a, want));
}

static void TestLookupStaticAddr(TestingT *t) {
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str dir = write_testdata(t, a);
    if (dir.len == 0) {
        arena_free(&ar);
        return;
    }
    for (size_t k = 0;
         k < sizeof lookup_static_addr_tests / sizeof lookup_static_addr_tests[0];
         k++) {
        const StaticHostTest *tt = &lookup_static_addr_tests[k];
        burrow__net_set_hosts_file_path(td(a, dir, tt->name));
        for (Int i = 0; i < tt->nents; i++)
            test_static_addr(t, a, tt->name, &tt->ents[i]);
    }
    burrow__net_set_hosts_file_path(BURROW_STR_EMPTY);
    (void)os_remove_all(dir);
    arena_free(&ar);
}

/* What the lookups hand back is the caller's to change. Go appends "junk" to
 * each string, and here the bytes are written over, which is what would show
 * if they were the cache's own. */
static void spoil(Slice s) {
    for (Int i = 0; i < s.len; i++) {
        Str x = ((const Str *)s.p)[i];
        memset((void *)(uintptr_t)x.p, 'j', (size_t)x.len);
    }
}

static void TestHostCacheModification(TestingT *t) {
    /* See https://golang.org/issues/14212. */
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str dir = write_testdata(t, a);
    if (dir.len == 0) {
        arena_free(&ar);
        return;
    }
    burrow__net_set_hosts_file_path(td(a, dir, "ipv4-hosts"));
    StaticHostEntry ent = {"localhost", {"127.0.0.1", "127.0.0.2", "127.0.0.3"}, 3};
    test_static_host(t, a, "ipv4-hosts", &ent);
    Str canonical;
    spoil(burrow__net_lookup_static_host(a, str_from_cstr(ent.in), &canonical));
    test_static_host(t, a, "ipv4-hosts", &ent);

    burrow__net_set_hosts_file_path(td(a, dir, "ipv6-hosts"));
    StaticHostEntry ent6 = {"::1", {"localhost"}, 1};
    test_static_addr(t, a, "ipv6-hosts", &ent6);
    spoil(burrow__net_lookup_static_addr(a, str_from_cstr(ent6.in)));
    test_static_addr(t, a, "ipv6-hosts", &ent6);

    burrow__net_set_hosts_file_path(BURROW_STR_EMPTY);
    (void)os_remove_all(dir);
    arena_free(&ar);
}

static void TestLookupStaticHostAliases(TestingT *t) {
    static const struct {
        const char *lookup;
        const char *res;
    } tests[] = {
        /* 127.0.0.1 */
        {"test", "test"},
        /* 127.0.0.2 */
        {"test2.example.com", "test2.example.com"},
        {"2.test", "test2.example.com"},
        /* 127.0.0.3 */
        {"test3.example.com", "3.test"},
        {"3.test", "3.test"},
        /* 127.0.0.4 */
        {"example.com", "example.com"},
        /* 127.0.0.5 */
        {"test5.example.com", "test4.example.com"},
        {"5.test", "test4.example.com"},
        {"4.test", "test4.example.com"},
        {"test4.example.com", "test4.example.com"},
    };
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str dir = write_testdata(t, a);
    if (dir.len == 0) {
        arena_free(&ar);
        return;
    }
    burrow__net_set_hosts_file_path(td(a, dir, "aliases"));
    for (size_t k = 0; k < sizeof tests / sizeof tests[0]; k++) {
        Str lookup = str_from_cstr(tests[k].lookup);
        Str want = abs_name(a, str_from_cstr(tests[k].res));
        Str ins[4] = {lookup, abs_name(a, lookup), strings_to_lower(a, lookup),
                      strings_to_upper(a, lookup)};
        for (int i = 0; i < 4; i++) {
            Str res;
            (void)burrow__net_lookup_static_host(a, ins[i], &res);
            if (!str_eq(res, want))
                testing_t_errorf_v(t, "lookupStaticHost(%s): got %s, want %s", ins[i],
                                   res, want);
        }
    }
    burrow__net_set_hosts_file_path(BURROW_STR_EMPTY);
    (void)os_remove_all(dir);
    arena_free(&ar);
}

/* --------------------------------------------------- dnsconfig_unix_test.go */

/* Go swaps getHostname out. Here the hostname function is a parameter, and
 * this one answers with whatever the test last put in these two. */
static const char *fake_hostname_name = "host.domain.local";
static bool fake_hostname_fails;

static Str fake_hostname(Alloc *a, Error *err) {
    if (fake_hostname_fails) {
        *err = burrow__net_temporary_error(a, BURROW_S("errored"));
        return BURROW_STR_EMPTY;
    }
    *err = BURROW_NO_ERROR;
    return str_clone(a, str_from_cstr(fake_hostname_name));
}

typedef struct DNSConfigWant {
    const char *servers[3];
    Int nservers; /* -1 for defaultNS */
    const char *search[2];
    Int nsearch;
    Int ndots;
    Duration timeout;
    Int attempts;
    bool rotate;
    bool unknown_opt;
    const char *lookup[2];
    Int nlookup;
    bool single_request;
    bool use_tcp;
} DNSConfigWant;

static const struct {
    const char *name;
    DNSConfigWant want;
} dns_read_config_tests[] = {
    {"resolv.conf",
     {.servers = {"8.8.8.8:53", "[2001:4860:4860::8888]:53", "[fe80::1%lo0]:53"},
      .nservers = 3,
      .search = {"localdomain."},
      .nsearch = 1,
      .ndots = 5,
      .timeout = 10 * TIME_SECOND,
      .attempts = 3,
      .rotate = true,
      .unknown_opt = true}}, /* the "options attempts 3" line */
    {"domain-resolv.conf",
     {.servers = {"8.8.8.8:53"},
      .nservers = 1,
      .search = {"localdomain."},
      .nsearch = 1,
      .ndots = 1,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2}},
    {"search-resolv.conf",
     {.servers = {"8.8.8.8:53"},
      .nservers = 1,
      .search = {"test.", "invalid."},
      .nsearch = 2,
      .ndots = 1,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2}},
    {"search-single-dot-resolv.conf",
     {.servers = {"8.8.8.8:53"},
      .nservers = 1,
      .nsearch = 0,
      .ndots = 1,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2}},
    {"empty-resolv.conf",
     {.nservers = -1,
      .ndots = 1,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"invalid-ndots-resolv.conf",
     {.nservers = -1,
      .ndots = 0,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"large-ndots-resolv.conf",
     {.nservers = -1,
      .ndots = 15,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"negative-ndots-resolv.conf",
     {.nservers = -1,
      .ndots = 0,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"openbsd-resolv.conf",
     {.ndots = 1,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .lookup = {"file", "bind"},
      .nlookup = 2,
      .servers = {"169.254.169.254:53", "10.240.0.1:53"},
      .nservers = 2,
      .search = {"c.symbolic-datum-552.internal."},
      .nsearch = 1}},
    {"single-request-resolv.conf",
     {.nservers = -1,
      .ndots = 1,
      .single_request = true,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"single-request-reopen-resolv.conf",
     {.nservers = -1,
      .ndots = 1,
      .single_request = true,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"linux-use-vc-resolv.conf",
     {.nservers = -1,
      .ndots = 1,
      .use_tcp = true,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"freebsd-usevc-resolv.conf",
     {.nservers = -1,
      .ndots = 1,
      .use_tcp = true,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
    {"openbsd-tcp-resolv.conf",
     {.nservers = -1,
      .ndots = 1,
      .use_tcp = true,
      .timeout = 5 * TIME_SECOND,
      .attempts = 2,
      .search = {"domain.local."},
      .nsearch = 1}},
};

/* The want's search, or dnsDefaultSearch when it has none, as Go's test
 * does. */
static Slice want_search(Alloc *a, const DNSConfigWant *w) {
    if (w->nsearch == 0)
        return burrow__dns_default_search(a, fake_hostname);
    return cstrs(a, w->search, w->nsearch);
}

/* reflect.DeepEqual on the two, with mtime cleared as Go clears it. */
static bool config_eq(Alloc *a, const burrow__DNSConfig *c, const DNSConfigWant *w) {
    Slice servers = w->nservers < 0
                        ? cstrs(a, (const char *const[]){"127.0.0.1:53", "[::1]:53"}, 2)
                        : cstrs(a, w->servers, w->nservers);
    return strs_eq(c->servers, servers) && strs_eq(c->search, want_search(a, w)) &&
           c->ndots == w->ndots && c->timeout == w->timeout &&
           c->attempts == w->attempts && c->rotate == w->rotate &&
           c->unknown_opt == w->unknown_opt &&
           strs_eq(c->lookup, cstrs(a, w->lookup, w->nlookup)) && BURROW_OK(c->err) &&
           c->soffset == 0 && c->single_request == w->single_request &&
           c->use_tcp == w->use_tcp && !c->trust_ad && !c->no_reload;
}

static Str config_string(Alloc *a, const burrow__DNSConfig *c) {
    return fmt_sprintf_v(a,
                         "{servers:%s search:%s ndots:%d timeout:%d attempts:%d "
                         "rotate:%v unknownOpt:%v lookup:%s err:%v singleRequest:%v "
                         "useTCP:%v trustAD:%v noReload:%v}",
                         strs(a, c->servers), strs(a, c->search), c->ndots,
                         (Int)c->timeout, c->attempts, c->rotate, c->unknown_opt,
                         strs(a, c->lookup), c->err, c->single_request, c->use_tcp,
                         c->trust_ad, c->no_reload);
}

static void TestDNSReadConfig(TestingT *t) {
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str dir = write_testdata(t, a);
    if (dir.len == 0) {
        arena_free(&ar);
        return;
    }
    fake_hostname_name = "host.domain.local";
    fake_hostname_fails = false;
    for (size_t k = 0;
         k < sizeof dns_read_config_tests / sizeof dns_read_config_tests[0]; k++) {
        const char *name = dns_read_config_tests[k].name;
        const DNSConfigWant *w = &dns_read_config_tests[k].want;
        burrow__DNSConfig conf;
        burrow__dns_read_config(a, td(a, dir, name), fake_hostname, &conf);
        if (BURROW_FAILED(conf.err)) {
            testing_t_fatal_v(t, conf.err);
            break;
        }
        if (!config_eq(a, &conf, w))
            testing_t_errorf_v(t, "%s:\ngot: %s", name, config_string(a, &conf));
    }
    (void)os_remove_all(dir);
    arena_free(&ar);
}

static void TestDNSReadMissingFile(TestingT *t) {
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    fake_hostname_name = "host.domain.local";
    fake_hostname_fails = false;
    burrow__DNSConfig conf;
    burrow__dns_read_config(a, BURROW_S("a-nonexistent-file"), fake_hostname, &conf);
    if (!errors_is(conf.err, fs_err_not_exist))
        testing_t_errorf_v(t, "missing resolv.conf:\ngot: %v\nwant: %v", conf.err,
                           fs_err_not_exist);
    conf.err = BURROW_NO_ERROR;
    DNSConfigWant want = {.nservers = -1,
                          .ndots = 1,
                          .timeout = 5 * TIME_SECOND,
                          .attempts = 2,
                          .search = {"domain.local."},
                          .nsearch = 1};
    if (!config_eq(a, &conf, &want))
        testing_t_errorf_v(t, "missing resolv.conf:\ngot: %s", config_string(a, &conf));
    if (!burrow__dns_config_is_default_ns(&conf))
        testing_t_errorf_v(t, "missing resolv.conf: servers are not defaultNS");
    arena_free(&ar);
}

static void TestDNSDefaultSearch(TestingT *t) {
    static const struct {
        const char *name;
        bool err;
        const char *want;
    } tests[] = {
        {"host.long.domain.local", false, "long.domain.local."},
        {"host.local", false, "local."},
        {"host", false, NULL},
        {"host.domain.local", true, NULL},
        /* ensures we don't return []string{""} which causes duplicate
         * lookups */
        {"foo.", false, NULL},
    };
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    for (size_t k = 0; k < sizeof tests / sizeof tests[0]; k++) {
        fake_hostname_name = tests[k].name;
        fake_hostname_fails = tests[k].err;
        Slice got = burrow__dns_default_search(a, fake_hostname);
        Slice want = tests[k].want == NULL ? slice_nil(TYPE_STRING)
                                           : cstrs(a, &tests[k].want, 1);
        if (!strs_eq(got, want))
            testing_t_errorf_v(t,
                               "dnsDefaultSearch with hostname %q and error %v = %s, "
                               "wanted %s",
                               tests[k].name, tests[k].err, strs(a, got),
                               strs(a, want));
    }
    fake_hostname_name = "host.domain.local";
    fake_hostname_fails = false;
    arena_free(&ar);
}

/* Go's longDomain: five labels of 63 a's and then "example". */
static Str long_domain(Alloc *a) {
    Str char63 = strings_repeat(a, BURROW_S("a"), 63);
    Str label =
        strings_join(a, slice_from((Str[]){char63, BURROW_S(".")}, 2, 2, TYPE_STRING),
                     BURROW_STR_EMPTY);
    return strings_join(
        a,
        slice_from((Str[]){strings_repeat(a, label, 5), BURROW_S("example")}, 2, 2,
                   TYPE_STRING),
        BURROW_STR_EMPTY);
}

static Str cat2(Alloc *a, Str x, Str y) {
    return strings_join(a, slice_from((Str[]){x, y}, 2, 2, TYPE_STRING),
                        BURROW_STR_EMPTY);
}

static void TestDNSNameLength(TestingT *t) {
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    Str dir = write_testdata(t, a);
    if (dir.len == 0) {
        arena_free(&ar);
        return;
    }
    fake_hostname_name = "host.domain.local";
    fake_hostname_fails = false;
    Str ld = long_domain(a);
    for (size_t k = 0;
         k < sizeof dns_read_config_tests / sizeof dns_read_config_tests[0]; k++) {
        const char *name = dns_read_config_tests[k].name;
        burrow__DNSConfig conf;
        burrow__dns_read_config(a, td(a, dir, name), fake_hostname, &conf);
        if (BURROW_FAILED(conf.err)) {
            testing_t_fatal_v(t, conf.err);
            break;
        }
        Slice suffixes = want_search(a, &dns_read_config_tests[k].want);
        Int shortest = 0;
        for (Int i = 0; i < suffixes.len; i++) {
            Int n = ((const Str *)suffixes.p)[i].len;
            if (shortest == 0 || n < shortest)
                shortest = n;
        }

        /* A name that will be maximally long when prefixing the shortest
         * suffix, counting the dot between. */
        Int from = ld.len - 254 + 1 + shortest;
        Str long_name = str_from_bytes(ld.p + from, ld.len - from);
        if (long_name.p[0] == '.' || long_name.p[1] == '.')
            long_name = cat2(a, BURROW_S("aa."),
                             str_from_bytes(long_name.p + 3, long_name.len - 3));
        Slice fqdns = burrow__dns_config_name_list(&conf, a, long_name);
        for (Int i = 0; i < fqdns.len; i++) {
            Int n = ((const Str *)fqdns.p)[i].len;
            if (n > 254)
                testing_t_errorf_v(t, "got %d; want less than or equal to 254", n);
        }

        /* Now a name that's too long for suffixing. */
        Str unsuffixable =
            cat2(a, BURROW_S("a."), str_from_bytes(long_name.p + 1, long_name.len - 1));
        Slice res = burrow__dns_config_name_list(&conf, a, unsuffixable);
        if (res.len != 1)
            testing_t_errorf_v(t, "suffixed names %s; want []", strs(a, res));

        /* And a name that's too long for DNS. */
        Str too_long = cat2(a, BURROW_S("a."), ld);
        res = burrow__dns_config_name_list(&conf, a, too_long);
        if (res.p != NULL)
            testing_t_errorf_v(t, "suffixed names %s; want nil", strs(a, res));
    }
    (void)os_remove_all(dir);
    arena_free(&ar);
}

/* ----------------------------------------------------------- dnsname_test.go */

static void TestDNSName(TestingT *t) {
    static const struct {
        const char *name;
        bool result;
    } tests[] = {
        /* RFC 2181, section 11. */
        {"_xmpp-server._tcp.google.com", true},
        {"foo.com", true},
        {"1foo.com", true},
        {"26.0.0.73.com", true},
        {"10-0-0-1", true},
        {"fo-o.com", true},
        {"fo1o.com", true},
        {"foo1.com", true},
        {"a.b..com", false},
        {"a.b-.com", false},
        {"a.b.com-", false},
        {"a.b..", false},
        {"b.com.", true},
    };
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    for (size_t k = 0; k < sizeof tests / sizeof tests[0]; k++) {
        Str name = str_from_cstr(tests[k].name);
        if (burrow__net_is_domain_name(name) != tests[k].result)
            testing_t_errorf_v(t, "isDomainName(%q) = %v; want %v", name,
                               !tests[k].result, tests[k].result);
    }

    Str char63 = strings_repeat(a, BURROW_S("a"), 63);
    Str char64 = cat2(a, char63, BURROW_S("a"));
    Str ld = long_domain(a);
    struct {
        Str name;
        bool result;
    } more[] = {
        {cat2(a, char63, BURROW_S(".com")), true},
        {cat2(a, char64, BURROW_S(".com")), false},
        /* Remember: wire format is two octets longer than presentation
         * (length octets for the first and [root] last labels). 253 is
         * fine: */
        {str_from_bytes(ld.p + ld.len - 253, 253), true},
        /* A terminal dot doesn't contribute to length: */
        {cat2(a, str_from_bytes(ld.p + ld.len - 253, 253), BURROW_S(".")), true},
        /* 254 is bad: */
        {str_from_bytes(ld.p + ld.len - 254, 254), false},
    };
    for (size_t k = 0; k < sizeof more / sizeof more[0]; k++)
        if (burrow__net_is_domain_name(more[k].name) != more[k].result)
            testing_t_errorf_v(t, "isDomainName(%q) = %v; want %v", more[k].name,
                               !more[k].result, more[k].result);
    arena_free(&ar);
}

/* --------------------------------------------------------- dnsclient_test.go */

static void check_distribution(TestingT *t, NetSRV *data, Int n, double margin) {
    Int sum = 0;
    for (Int i = 0; i < n; i++)
        sum += data[i].weight;

    Int results[26] = {0};
    enum { COUNT = 10000 };
    NetSRV *d[26];
    for (int j = 0; j < COUNT; j++) {
        for (Int i = 0; i < n; i++)
            d[i] = &data[i];
        burrow__net_srv_shuffle_by_weight(d, n);
        results[d[0] - data]++;
    }

    Int actual = results[0];
    double expected = (double)COUNT * (double)data[0].weight / (double)sum;
    double diff = (double)actual - expected;
    testing_t_logf_v(t, "actual: %d diff: %v e: %v m: %v", actual, diff, expected,
                     margin);
    if (diff < 0)
        diff = -diff;
    if (diff > expected * margin)
        testing_t_errorf_v(t, "missed target weight: expected %v, %d", expected,
                           actual);
}

static void test_uniformity(TestingT *t, Int size, double margin) {
    static const char *const names[] = {"a", "b", "c", "d", "e",
                                        "f", "g", "h", "i", "j"};
    NetSRV data[10];
    for (Int i = 0; i < size; i++)
        data[i] = (NetSRV){.target = str_from_cstr(names[i]), .weight = 1};
    check_distribution(t, data, size, margin);
}

static void test_weighting(TestingT *t, double margin) {
    NetSRV data[] = {
        {.target = BURROW_S_INIT("a"), .weight = 60},
        {.target = BURROW_S_INIT("b"), .weight = 30},
        {.target = BURROW_S_INIT("c"), .weight = 10},
    };
    check_distribution(t, data, 3, margin);
}

static void TestDNSSRVUniformity(TestingT *t) {
    test_uniformity(t, 2, 0.05);
    test_uniformity(t, 3, 0.10);
    test_uniformity(t, 10, 0.20);
    test_weighting(t, 0.05);
}

static void TestWeighting(TestingT *t) {
    test_weighting(t, 0.05);
}

/* ------------------------------------------------------------ lookup_test.go */

static void TestReverseAddress(TestingT *t) {
    static const struct {
        const char *addr;
        const char *reverse;
        const char *err_prefix;
    } tests[] = {
        {"1.2.3.4", "4.3.2.1.in-addr.arpa.", ""},
        {"245.110.36.114", "114.36.110.245.in-addr.arpa.", ""},
        {"::ffff:12.34.56.78", "78.56.34.12.in-addr.arpa.", ""},
        {"::1",
         "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa.",
         ""},
        {"1::",
         "0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1.0.0.0.ip6.arpa.",
         ""},
        {"1234:567::89a:bcde",
         "e.d.c.b.a.9.8.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.7.6.5.0.4.3.2.1.ip6.arpa.",
         ""},
        {"1234:567:fefe:bcbc:adad:9e4a:89a:bcde",
         "e.d.c.b.a.9.8.0.a.4.e.9.d.a.d.a.c.b.c.b.e.f.e.f.7.6.5.0.4.3.2.1.ip6.arpa.",
         ""},
        {"1.2.3", "", "unrecognized address"},
        {"1.2.3.4.5", "", "unrecognized address"},
        {"1234:567:bcbca::89a:bcde", "", "unrecognized address"},
        {"1234:567::bcbc:adad::89a:bcde", "", "unrecognized address"},
    };
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    for (size_t i = 0; i < sizeof tests / sizeof tests[0]; i++) {
        Error err = BURROW_NO_ERROR;
        Str got = burrow__net_reverseaddr(a, str_from_cstr(tests[i].addr), &err);
        bool want_err = tests[i].err_prefix[0] != 0;
        if (want_err && BURROW_OK(err)) {
            testing_t_errorf_v(t, "#%d: expected %q, got <nil> (error)", (Int)i,
                               tests[i].err_prefix);
            continue;
        }
        if (!want_err && BURROW_FAILED(err))
            testing_t_errorf_v(t, "#%d: expected <nil>, got %q (error)", (Int)i, err);
        if (BURROW_FAILED(err)) {
            const NetDNSError *de =
                (const NetDNSError *)errors_as(err, TYPE_NET_DNS_ERROR);
            if (de == NULL)
                testing_t_errorf_v(t, "#%d: %v is not a DNSError", (Int)i, err);
            else if (!str_eq(de->err, str_from_cstr(tests[i].err_prefix)))
                testing_t_errorf_v(t, "#%d: expected %q, got %q (mismatched error)",
                                   (Int)i, tests[i].err_prefix, de->err);
        }
        if (!str_eq(got, str_from_cstr(tests[i].reverse)))
            testing_t_errorf_v(t, "#%d: expected %q, got %q (reverse address)", (Int)i,
                               tests[i].reverse, got);
    }
    arena_free(&ar);
}

/* ------------------------------------------------------------------ DNSError */

/* Not one of Go's tests, which reach newDNSError through a Resolver. This
 * checks the flags it sets and the text, which net.go spells out. */
static void TestNewDNSErrorSetsItsFlags(TestingT *t) {
    Arena ar;
    arena_init(&ar, NULL, 0);
    Alloc *a = arena_allocator(&ar);
    static const struct {
        const char *server;
        const char *text;
        int kind; /* 0 not found, 1 temporary, 2 canceled, 3 deadline */
        bool timeout;
        bool temporary;
        bool not_found;
        bool unwraps;
    } tests[] = {
        {"", "lookup example.com: no such host", 0, false, false, true, false},
        {"8.8.8.8:53", "lookup example.com on 8.8.8.8:53: no such host", 1, false, true,
         false, false},
        {"", "lookup example.com: context canceled", 2, false, false, false, true},
        {"", "lookup example.com: context deadline exceeded", 3, true, true, false,
         true},
    };
    for (size_t i = 0; i < sizeof tests / sizeof tests[0]; i++) {
        Error cause;
        switch (tests[i].kind) {
        case 0:
            cause = burrow__net_not_found_error(a, BURROW_S("no such host"));
            break;
        case 1:
            cause = burrow__net_temporary_error(a, BURROW_S("no such host"));
            break;
        case 2:
            cause = context_canceled;
            break;
        default:
            cause = context_deadline_exceeded;
            break;
        }
        Error err = burrow__net_new_dns_error(a, cause, BURROW_S("example.com"),
                                              str_from_cstr(tests[i].server));
        const NetDNSError *de = (const NetDNSError *)errors_as(err, TYPE_NET_DNS_ERROR);
        if (de == NULL) {
            testing_t_errorf_v(t, "#%d: %v is not a DNSError", (Int)i, err);
            continue;
        }
        Str text = error_text(err);
        if (!str_eq(text, str_from_cstr(tests[i].text)))
            testing_t_errorf_v(t, "#%d: Error() = %q, want %q", (Int)i, text,
                               tests[i].text);
        if (de->is_timeout != tests[i].timeout ||
            net_dns_error_timeout(de) != tests[i].timeout)
            testing_t_errorf_v(t, "#%d: IsTimeout = %v, want %v", (Int)i,
                               de->is_timeout, tests[i].timeout);
        if (net_dns_error_temporary(de) != tests[i].temporary)
            testing_t_errorf_v(t, "#%d: Temporary() = %v, want %v", (Int)i,
                               net_dns_error_temporary(de), tests[i].temporary);
        if (de->is_not_found != tests[i].not_found)
            testing_t_errorf_v(t, "#%d: IsNotFound = %v, want %v", (Int)i,
                               de->is_not_found, tests[i].not_found);
        if (errors_is(err, cause) != tests[i].unwraps)
            testing_t_errorf_v(t, "#%d: errors.Is(err, cause) = %v, want %v", (Int)i,
                               errors_is(err, cause), tests[i].unwraps);
        if (net_error_timeout(err) != tests[i].timeout)
            testing_t_errorf_v(t, "#%d: net.Error Timeout() = %v, want %v", (Int)i,
                               net_error_timeout(err), tests[i].timeout);
    }
    arena_free(&ar);
}

/* context's TestDeadlineExceededSupportsTimeout, which is here because it is
 * net that asks. */
static void TestDeadlineExceededSupportsTimeout(TestingT *t) {
    if (!net_is_error(context_deadline_exceeded)) {
        testing_t_fatal_v(t, "DeadlineExceeded does not support Timeout interface");
        return;
    }
    if (!net_error_timeout(context_deadline_exceeded))
        testing_t_fatal_v(t, "wrong value for timeout");
}

#define TESTS(X)                                                                       \
    X(TestReadLine)                                                                    \
    X(TestDtoi)                                                                        \
    X(TestLookupStaticHost)                                                            \
    X(TestLookupStaticAddr)                                                            \
    X(TestHostCacheModification)                                                       \
    X(TestLookupStaticHostAliases)                                                     \
    X(TestDNSReadConfig)                                                               \
    X(TestDNSReadMissingFile)                                                          \
    X(TestDNSDefaultSearch)                                                            \
    X(TestDNSNameLength)                                                               \
    X(TestDNSName)                                                                     \
    X(TestDNSSRVUniformity)                                                            \
    X(TestWeighting)                                                                   \
    X(TestReverseAddress)                                                              \
    X(TestNewDNSErrorSetsItsFlags)                                                     \
    X(TestDeadlineExceededSupportsTimeout)

TESTING_MAIN(TESTS)
