/* What Go's mime/quotedprintable makes, go1.27.1. Generated by
 * tools/gen-quotedprintable-tests.sh; do not edit. */

typedef struct QpReadCase {
    const char *in;
    long long in_len;
    const char *want;
    long long want_len;
    const char *err;
    const char *want1;
    long long want1_len;
    const char *err1;
} QpReadCase;

static const QpReadCase qp_read_cases[] = {
    {"", 0, "", 0, "", "", 0, ""},
    {"foo bar", 7, "foo bar", 7, "", "foo bar", 7, ""},
    {"foo bar=3D", 10, "foo bar=", 8, "", "foo bar=", 8, ""},
    {"foo bar=3d", 10, "foo bar=", 8, "", "foo bar=", 8, ""},
    {"foo bar=\012", 9, "foo bar", 7, "", "foo bar", 7, ""},
    {"foo bar\012", 8, "foo bar\012", 8, "", "foo bar\012", 8, ""},
    {"foo bar=0", 9, "foo bar=0", 9, "", "foo bar=0", 9, ""},
    {"foo bar=0D=0A", 13, "foo bar\015\012", 9, "", "foo bar\015\012", 9, ""},
    {" A B        \015\012 C ", 17, " A B\015\012 C", 8, "", " A B\015\012 C", 8, ""},
    {" A B =\015\012 C ", 11, " A B  C", 7, "", " A B  C", 7, ""},
    {" A B =\012 C ", 10, " A B  C", 7, "", " A B  C", 7, ""},
    {"foo=\012bar", 8, "foobar", 6, "", "foobar", 6, ""},
    {"foo\000bar", 7, "foo", 3, "quotedprintable: invalid unescaped byte 0x00 in body",
     "foo", 3, "quotedprintable: invalid unescaped byte 0x00 in body"},
    {"foo bar\377", 8, "foo bar\377", 8, "", "foo bar\377", 8, ""},
    {"=3D30\012", 6, "=30\012", 4, "", "=30\012", 4, ""},
    {"=00=FF0=\012", 9, "\000\3770", 3, "", "\000\3770", 3, ""},
    {"foo  \012", 6, "foo\012", 4, "", "foo\012", 4, ""},
    {"foo  \012\012foo =\012\012foo=20\012\012", 22, "foo\012\012foo \012foo \012\012",
     16, "", "foo\012\012foo \012foo \012\012", 16, ""},
    {"foo\012bar", 7, "foo\012bar", 7, "", "foo\012bar", 7, ""},
    {"foo\015bar", 7, "foo\015bar", 7, "", "foo\015bar", 7, ""},
    {"foo\015\012bar", 8, "foo\015\012bar", 8, "", "foo\015\012bar", 8, ""},
    {"foo=\015\012bar", 9, "foobar", 6, "", "foobar", 6, ""},
    {"foo=\012bar", 8, "foobar", 6, "", "foobar", 6, ""},
    {"foo=\015bar", 8, "foo", 3, "quotedprintable: invalid hex byte 0x0d", "foo", 3,
     "quotedprintable: invalid hex byte 0x0d"},
    {"foo=\015\015\015 \012bar", 12, "foo", 3,
     "quotedprintable: invalid bytes after =: \"\\r\\r\\r \\n\"", "foo", 3,
     "quotedprintable: invalid bytes after =: \"\\r\\r\\r \\n\""},
    {"foo=", 4, "foo", 3, "", "foo", 3, ""},
    {"=", 1, "", 0, "quotedprintable: invalid bytes after =: \"\"", "", 0,
     "quotedprintable: invalid bytes after =: \"\""},
    {"Now's the time =\012for all folk to come=\012 to the aid of their country.", 68,
     "Now's the time for all folk to come to the aid of their country.", 64, "",
     "Now's the time for all folk to come to the aid of their country.", 64, ""},
    {"accept UTF-8 right quotation mark: \342\200\231", 38,
     "accept UTF-8 right quotation mark: \342\200\231", 38, "",
     "accept UTF-8 right quotation mark: \342\200\231", 38, ""},
    {"foo= \015\012bar", 10, "foobar", 6, "", "foobar", 6, ""},
    {"foo=\011 \015\012bar", 11, "foobar", 6, "", "foobar", 6, ""},
    {"=4", 2, "=4", 2, "", "=4", 2, ""},
    {"=4g", 3, "=4g", 3, "", "=4g", 3, ""},
    {"=G0", 3, "=G0", 3, "", "=G0", 3, ""},
    {"a=\015", 3, "a", 1, "quotedprintable: invalid bytes after =: \"\\r\"", "a", 1,
     "quotedprintable: invalid bytes after =: \"\\r\""},
    {"a=\015\012", 4, "a", 1, "", "a", 1, ""},
    {"a=  ", 4, "a", 1, "", "a", 1, ""},
    {"a= x\012", 5, "a= x\012", 5, "", "a= x\012", 5, ""},
    {"\177", 1, "", 0, "quotedprintable: invalid unescaped byte 0x7f in body", "", 0,
     "quotedprintable: invalid unescaped byte 0x7f in body"},
    {"a\033b", 3, "a", 1, "quotedprintable: invalid unescaped byte 0x1b in body", "a",
     1, "quotedprintable: invalid unescaped byte 0x1b in body"},
    {"\011\011\015\012", 4, "\015\012", 2, "", "\015\012", 2, ""},
    {"=\015\012", 3, "", 0, "", "", 0, ""},
    {"==41", 4, "=A", 2, "", "=A", 2, ""},
    {"a=\012=\012=\012b", 8, "ab", 2, "", "ab", 2, ""},
};

typedef struct QpLongCase {
    long long want_len;
    unsigned long long want_fnv;
    const char *err;
    long long want1_len;
    unsigned long long want1_fnv;
    const char *err1;
} QpLongCase;

static const QpLongCase qp_long_cases[] = {
    {4096, 0x2ff89da7cece4c15ULL, "bufio: buffer full", 4096, 0x2ff89da7cece4c15ULL,
     "bufio: buffer full"},
    {1365, 0x1476890c3a9737aeULL, "quotedprintable: invalid bytes after =: \"\"", 1365,
     0x1476890c3a9737aeULL, "quotedprintable: invalid bytes after =: \"\""},
};

#define QP_EXHAUSTIVE_ALPHABET "0A \015\012=\011"
#define QP_EXHAUSTIVE_MAX 6
#define QP_EXHAUSTIVE_COUNT 137257
#define QP_EXHAUSTIVE_FNV 0x46244c54f6ec15bbULL

typedef struct QpWriteCase {
    const char *in;
    long long in_len;
    int rnd_seed; /* the input is rnd_text(seed) when it is not 0 */
    const char *text;
    const char *text3; /* written 3 bytes at a time */
    const char *binary;
    const char *binary3;
} QpWriteCase;

static const QpWriteCase qp_write_cases[] = {
    {"", 0, 0, "", "", "", ""},
    {"foo bar", 7, 0, "foo bar", "foo bar", "foo bar", "foo bar"},
    {"foo bar=", 8, 0, "foo bar=3D", "foo bar=3D", "foo bar=3D", "foo bar=3D"},
    {"foo bar\015", 8, 0, "foo bar\015\012", "foo bar\015\012", "foo bar=0D",
     "foo bar=0D"},
    {"foo bar\015\015", 9, 0, "foo bar\015\012\015\012", "foo bar\015\012\015\012",
     "foo bar=0D=0D", "foo bar=0D=0D"},
    {"foo bar\012", 8, 0, "foo bar\015\012", "foo bar\015\012", "foo bar=0A",
     "foo bar=0A"},
    {"foo bar\015\012", 9, 0, "foo bar\015\012", "foo bar\015\012", "foo bar=0D=0A",
     "foo bar=0D=0A"},
    {"foo bar\015\015\012", 10, 0, "foo bar\015\012\015\012", "foo bar\015\012\015\012",
     "foo bar=0D=0D=0A", "foo bar=0D=0D=0A"},
    {"foo bar ", 8, 0, "foo bar=20", "foo bar=20", "foo bar=20", "foo bar=20"},
    {"foo bar\011", 8, 0, "foo bar=09", "foo bar=09", "foo bar=09", "foo bar=09"},
    {"foo bar  ", 9, 0, "foo bar =20", "foo bar =20", "foo bar =20", "foo bar =20"},
    {"foo bar \012", 9, 0, "foo bar=20\015\012", "foo bar=20\015\012", "foo bar =0A",
     "foo bar =0A"},
    {"foo bar \015", 9, 0, "foo bar=20\015\012", "foo bar=20\015\012", "foo bar =0D",
     "foo bar =0D"},
    {"foo bar \015\012", 10, 0, "foo bar=20\015\012", "foo bar=20\015\012",
     "foo bar =0D=0A", "foo bar =0D=0A"},
    {"foo bar  \012", 10, 0, "foo bar =20\015\012", "foo bar =20\015\012",
     "foo bar  =0A", "foo bar  =0A"},
    {"foo bar  \012 ", 11, 0, "foo bar =20\015\012=20", "foo bar =20\015\012=20",
     "foo bar  =0A=20", "foo bar  =0A=20"},
    {"\302\241Hola Se\303\261or!", 14, 0, "=C2=A1Hola Se=C3=B1or!",
     "=C2=A1Hola Se=C3=B1or!", "=C2=A1Hola Se=C3=B1or!", "=C2=A1Hola Se=C3=B1or!"},
    {"\011 !\"#$%&'()*+,-./ :;<>\077@[\\]^_`{|}~", 34, 0,
     "\011 !\"#$%&'()*+,-./ :;<>\077@[\\]^_`{|}~",
     "\011 !\"#$%&'()*+,-./ :;<>\077@[\\]^_`{|}~",
     "\011 !\"#$%&'()*+,-./ :;<>\077@[\\]^_`{|}~",
     "\011 !\"#$%&'()*+,-./ :;<>\077@[\\]^_`{|}~"},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 75,
     0, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 76,
     0,
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012a",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012a",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012a",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012a"},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=", 73, 0,
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=3D"},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=", 74,
     0,
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D"},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=", 75,
     0,
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D"},
    {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=", 76,
     0,
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D",
     "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="
     "\015\012=3D"},
    {"                                                                         ", 73, 0,
     "                                                                        =20",
     "                                                                        =20",
     "                                                                        =20",
     "                                                                        =20"},
    {"                                                                          ", 74,
     0,
     "                                                                         "
     "=\015\012=20",
     "                                                                         "
     "=\015\012=20",
     "                                                                         "
     "=\015\012=20",
     "                                                                         "
     "=\015\012=20"},
    {"                                                                           ", 75,
     0,
     "                                                                          "
     "=\015\012=20",
     "                                                                          "
     "=\015\012=20",
     "                                                                          "
     "=\015\012=20",
     "                                                                          "
     "=\015\012=20"},
    {"                                                                            ", 76,
     0,
     "                                                                           "
     "=\015\012=20",
     "                                                                           "
     "=\015\012=20",
     "                                                                           "
     "=\015\012=20",
     "                                                                           "
     "=\015\012=20"},
    {"                                                                             ",
     77, 0,
     "                                                                           "
     "=\015\012 =20",
     "                                                                           "
     "=\015\012 =20",
     "                                                                           "
     "=\015\012 =20",
     "                                                                           "
     "=\015\012 =20"},
    {NULL, 1, 1, "=09", "=09", "=09", "=09"},
    {NULL, 4, 2, "\011=00gr", "\011=00gr", "\011=00gr", "\011=00gr"},
    {NULL, 9, 3, "i=7Fx~\015\012c~u=09", "i=7Fx~\015\012c~u=09", "i=7Fx~=0Ac~u=09",
     "i=7Fx~=0Ac~u=09"},
    {NULL, 16, 4, "iw=3Dru \011oob x=FF\011=80=A9", "iw=3Dru \011oob x=FF\011=80=A9",
     "iw=3Dru \011oob x=FF\011=80=A9", "iw=3Dru \011oob x=FF\011=80=A9"},
    {NULL, 25, 5, "hxh~ =FF=FF\011rsg=C3  m!ipk ~=A9sp\015\012",
     "hxh~ =FF=FF\011rsg=C3  m!ipk ~=A9sp\015\012",
     "hxh~ =FF=FF\011rsg=C3  m!ipk ~=A9sp=0D",
     "hxh~ =FF=FF\011rsg=C3  m!ipk ~=A9sp=0D"},
    {NULL, 36, 6, " =FFys\011x. =7Fj\011wk~ oh v=A9 =A9.\015\012  y!e jz   =C3",
     " =FFys\011x. =7Fj\011wk~ oh v=A9 =A9.\015\012  y!e jz   =C3",
     " =FFys\011x. =7Fj\011wk~ oh v=A9 =A9.=0A  y!e jz   =C3",
     " =FFys\011x. =7Fj\011wk~ oh v=A9 =A9.=0A  y!e jz   =C3"},
    {NULL, 49, 7,
     "  .!q=80hvzzn=C3=3Dis\011=20\015\012g!nz=3D uao d kk=80qu\011an .wut "
     "=3Dr=C3\011=20",
     "  .!q=80hvzzn=C3=3Dis\011=20\015\012g!nz=3D uao d kk=80qu\011an .wut "
     "=3Dr=C3\011=20",
     "  .!q=80hvzzn=C3=3Dis\011 =0Ag!nz=3D uao d kk=80qu\011an .wut =3Dr=C3\011=20",
     "  .!q=80hvzzn=C3=3Dis\011 =0Ag!nz=3D uao d kk=80qu\011an .wut =3Dr=C3\011=20"},
    {NULL, 64, 8,
     "  itxu=A9o =3D.w=80z\011 d smxa\015\012em=7F =7Fcykv\015\012 j=C3=C3wa  mlcb "
     "j=A9=3D .a    =3D\015\012=FFk c\011e",
     "  itxu=A9o =3D.w=80z\011 d smxa\015\012em=7F =7Fcykv\015\012 j=C3=C3wa  mlcb "
     "j=A9=3D .a    =3D\015\012=FFk c\011e",
     "  itxu=A9o =3D.w=80z\011 d smxa=0Aem=7F =7Fcykv=0A j=C3=C3wa  mlcb j=A9=3D .a "
     "=\015\012   =3D=0D=FFk c\011e",
     "  itxu=A9o =3D.w=80z\011 d smxa=0Aem=7F =7Fcykv=0A j=C3=C3wa  mlcb j=A9=3D .a "
     "=\015\012   =3D=0D=FFk c\011e"},
    {NULL, 81, 9,
     "fd !e!o\011ghu=80 q=FF=A9=20\015\012  i kaep=80ib!lgfv=FF\011=00g=C3s  "
     "ea\015\012\015\012=00c   sp\015\012z=80=C3r!.yvp=C3\015\012tyuuj!k f kg=80o=80",
     "fd !e!o\011ghu=80 q=FF=A9=20\015\012  i kaep=80ib!lgfv=FF\011=00g=C3s  "
     "ea\015\012\015\012=00c   sp\015\012z=80=C3r!.yvp=C3\015\012tyuuj!k f kg=80o=80",
     "fd !e!o\011ghu=80 q=FF=A9 =0D  i kaep=80ib!lgfv=FF\011=00g=C3s  ea=0A=0D=00=0Ac  "
     "=\015\012 sp=0Az=80=C3r!.yvp=C3=0Atyuuj!k f kg=80o=80",
     "fd !e!o\011ghu=80 q=FF=A9 =0D  i kaep=80ib!lgfv=FF\011=00g=C3s  ea=0A=0D=00=0Ac  "
     "=\015\012 sp=0Az=80=C3r!.yvp=C3=0Atyuuj!k f kg=80o=80"},
    {NULL, 100, 10,
     "eertl~g k=A9=A9=7Fh =3D=00=FFzob! iw=80\015\012=C3 "
     "=3Dmrvl\015\012=80=3Dqug\011uxy =7Fgao\011=00j awv "
     "\011jbfuga\011=3D.c=80=80ve\015\012k=80\011sdgrng =7F\011d=80ly\015\012 pl "
     "=A9g=3Dxs",
     "eertl~g k=A9=A9=7Fh =3D=00=FFzob! iw=80\015\012=C3 "
     "=3Dmrvl\015\012=80=3Dqug\011uxy =7Fgao\011=00j awv "
     "\011jbfuga\011=3D.c=80=80ve\015\012k=80\011sdgrng =7F\011d=80ly\015\012 pl "
     "=A9g=3Dxs",
     "eertl~g k=A9=A9=7Fh =3D=00=FFzob! iw=80=0D=0A=C3 =3Dmrvl=0A=80=3Dqug\011uxy "
     "=\015\012=7Fgao\011=00j awv \011jbfuga\011=3D.c=80=80ve=0Ak=80\011sdgrng "
     "=7F\011d=80ly=0D=0A pl =A9=\015\012g=3Dxs",
     "eertl~g k=A9=A9=7Fh =3D=00=FFzob! iw=80=0D=0A=C3 =3Dmrvl=0A=80=3Dqug\011uxy "
     "=\015\012=7Fgao\011=00j awv \011jbfuga\011=3D.c=80=80ve=0Ak=80\011sdgrng "
     "=7F\011d=80ly=0D=0A pl =A9=\015\012g=3Dxs"},
    {NULL, 121, 11,
     "e \011=00tqwv\015\012o u\015\012=A9fox\015\012zu df!=3D dky\015\012mcn  "
     "=09\015\012art\015\012\015\012q=C3ne~o=20\015\012hnx\015\012 "
     "si!ck!.~l=7Fq\015\012 w=C3 pn=3D\015\012nz =3D=00 .\015\012mz pyjf\015\012ow "
     "cm=80c =20\015\012i=3Dnhfqk\015\012pewmgf\015\012\015\012n\011!f",
     "e \011=00tqwv\015\012o u\015\012=A9fox\015\012zu df!=3D dky\015\012mcn  "
     "=09\015\012art\015\012\015\012q=C3ne~o=20\015\012hnx\015\012 "
     "si!ck!.~l=7Fq\015\012 w=C3 pn=3D\015\012nz =3D=00 .\015\012mz pyjf\015\012ow "
     "cm=80c =20\015\012i=3Dnhfqk\015\012pewmgf\015\012\015\012n\011!f",
     "e \011=00tqwv=0Ao u=0D=A9fox=0Azu df!=3D dky=0Dmcn  \011=0Dart=0A=0Dq=C3ne~o "
     "=0Ah=\015\012nx=0A si!ck!.~l=7Fq=0A w=C3 pn=3D=0Dnz =3D=00 .=0Amz pyjf=0Dow "
     "cm=80c  =0Ai=\015\012=3Dnhfqk=0Dpewmgf=0A=0Dn\011!f",
     "e \011=00tqwv=0Ao u=0D=A9fox=0Azu df!=3D dky=0Dmcn  \011=0Dart=0A=0Dq=C3ne~o "
     "=0Ah=\015\012nx=0A si!ck!.~l=7Fq=0A w=C3 pn=3D=0Dnz =3D=00 .=0Amz pyjf=0Dow "
     "cm=80c  =0Ai=\015\012=3Dnhfqk=0Dpewmgf=0A=0Dn\011!f"},
    {NULL, 144, 12,
     " hbua=3Dn=3Dr f=00!pvj=7F=A9lpn d=3D =FF!=FFxfn\015\012 "
     "qr=80\011\011=3Dh=3Dcjvaoe=20\015\012~=80~nwpo\015\012et!hn v qkk=C3y=00 "
     "o=00d.iza=C3=80 x qaj\015\012ta\015\012=80 ~acm.nm=00wkk t\011=20\015\012 f "
     "=C3di=7Fafy=00\015\012pn n!c\011ss =20\015\012!pg ibc =7F f",
     " hbua=3Dn=3Dr f=00!pvj=7F=A9lpn d=3D =FF!=FFxfn\015\012 "
     "qr=80\011\011=3Dh=3Dcjvaoe=20\015\012~=80~nwpo\015\012et!hn v qkk=C3y=00 "
     "o=00d.iza=C3=80 x qaj\015\012ta\015\012=80 ~acm.nm=00wkk t\011=20\015\012 f "
     "=C3di=7Fafy=00\015\012pn n!c\011ss =20\015\012!pg ibc =7F f",
     " hbua=3Dn=3Dr f=00!pvj=7F=A9lpn d=3D =FF!=FFxfn=0D qr=80\011\011=3Dh=3Dcjvaoe "
     "=0D=\015\012~=80~nwpo=0Aet!hn v qkk=C3y=00 o=00d.iza=C3=80 x qaj=0Dta=0D=80 "
     "~acm.nm=00w=\015\012kk t\011 =0A f =C3di=7Fafy=00=0Apn n!c\011ss  =0D!pg ibc =7F "
     "f",
     " hbua=3Dn=3Dr f=00!pvj=7F=A9lpn d=3D =FF!=FFxfn=0D qr=80\011\011=3Dh=3Dcjvaoe "
     "=0D=\015\012~=80~nwpo=0Aet!hn v qkk=C3y=00 o=00d.iza=C3=80 x qaj=0Dta=0D=80 "
     "~acm.nm=00w=\015\012kk t\011 =0A f =C3di=7Fafy=00=0Apn n!c\011ss  =0D!pg ibc =7F "
     "f"},
    {NULL, 169, 13,
     " it=00hn \011v=80ity l t\015\012w\011xf lyujmwbo=A9=80g "
     "\011g=00\015\012=7F=00!ct\015\012=C3p.=FF=80kw iy\015\012tomcv=09\015\012gsr py "
     "=20\015\012=3Dy!uqx\015\012=FFn\015\012 "
     "vgycbe=7F\015\012=20\015\012\011=A9qce=7Fwc\015\012 hg  d=3D! n "
     "ykb.=C3n=80s=3Dr\015\012ujywa~h\011ndd! trb=3D=A9l.fx=7F=3D ue cq=FF!n=00l =3D e "
     "l=20\015\012 =C3",
     " it=00hn \011v=80ity l t\015\012w\011xf lyujmwbo=A9=80g "
     "\011g=00\015\012=7F=00!ct\015\012=C3p.=FF=80kw iy\015\012tomcv=09\015\012gsr py "
     "=20\015\012=3Dy!uqx\015\012=FFn\015\012 "
     "vgycbe=7F\015\012=20\015\012\011=A9qce=7Fwc\015\012 hg  d=3D! n "
     "ykb.=C3n=80s=3Dr\015\012ujywa~h\011ndd! trb=3D=A9l.fx=7F=3D ue cq=FF!n=00l =3D e "
     "l=20\015\012 =C3",
     " it=00hn \011v=80ity l t=0Dw\011xf lyujmwbo=A9=80g "
     "\011g=00=0A=7F=00!ct=0D=C3p.=FF=\015\012=80kw iy=0Dtomcv\011=0Agsr py  "
     "=0D=3Dy!uqx=0D=FFn=0A vgycbe=7F=0D =0D\011=A9qce=\015\012=7Fwc=0D hg  d=3D! n "
     "ykb.=C3n=80s=3Dr=0Dujywa~h\011ndd! trb=3D=A9l.fx=7F=3D ue=\015\012 cq=FF!n=00l "
     "=3D e l =0A =C3",
     " it=00hn \011v=80ity l t=0Dw\011xf lyujmwbo=A9=80g "
     "\011g=00=0A=7F=00!ct=0D=C3p.=FF=\015\012=80kw iy=0Dtomcv\011=0Agsr py  "
     "=0D=3Dy!uqx=0D=FFn=0A vgycbe=7F=0D =0D\011=A9qce=\015\012=7Fwc=0D hg  d=3D! n "
     "ykb.=C3n=80s=3Dr=0Dujywa~h\011ndd! trb=3D=A9l.fx=7F=3D ue=\015\012 cq=FF!n=00l "
     "=3D e l =0A =C3"},
    {NULL, 196, 14,
     " =09\015\012u\015\012\015\012v =FF\015\012!ex z.=C3 di ygqo  "
     "v=C3o=09\015\012vvud k\011wk=7F~zhbfl x t=00i azfk\011gzr s !=FFc=00=80q "
     "j=A9yuvc w~\015\012=80=C3vp\015\012q\015\012\015\012.=A9=7Ffss gk=A9=FF  "
     "u=A9y.i\011v~vnh =3D =C3z\015\012=00!b =00\011g~\015\012!\015\012=3Dr dgg   s "
     "w\015\012fnwlh\015\012 k=80vb=7F xmz pvc\015\012 =C3fwh=FF  =00=7F=A9z "
     "=7F=C3\015\012=80=3D\015\012=7F lw=00  qd=80",
     " =09\015\012u\015\012\015\012v =FF\015\012!ex z.=C3 di ygqo  "
     "v=C3o=09\015\012vvud k\011wk=7F~zhbfl x t=00i azfk\011gzr s !=FFc=00=80q "
     "j=A9yuvc w~\015\012=80=C3vp\015\012q\015\012\015\012.=A9=7Ffss gk=A9=FF  "
     "u=A9y.i\011v~vnh =3D =C3z\015\012=00!b =00\011g~\015\012!\015\012=3Dr dgg   s "
     "w\015\012fnwlh\015\012 k=80vb=7F xmz pvc\015\012 =C3fwh=FF  =00=7F=A9z "
     "=7F=C3\015\012=80=3D\015\012=7F lw=00  qd=80",
     " \011=0Du=0A=0Av =FF=0D=0A!ex z.=C3 di ygqo  v=C3o\011=0Dvvud k\011wk=7F~zhbfl x "
     "t=\015\012=00i azfk\011gzr s !=FFc=00=80q j=A9yuvc "
     "w~=0A=80=C3vp=0Aq=0A=0D.=A9=7Ffss gk=\015\012=A9=FF  u=A9y.i\011v~vnh =3D "
     "=C3z=0D=00!b =00\011g~=0A!=0A=3Dr dgg   s w=0Dfnwlh=\015\012=0D k=80vb=7F xmz "
     "pvc=0A =C3fwh=FF  =00=7F=A9z =7F=C3=0A=80=3D=0A=7F lw=00 =\015\012 qd=80",
     " \011=0Du=0A=0Av =FF=0D=0A!ex z.=C3 di ygqo  v=C3o\011=0Dvvud k\011wk=7F~zhbfl x "
     "t=\015\012=00i azfk\011gzr s !=FFc=00=80q j=A9yuvc "
     "w~=0A=80=C3vp=0Aq=0A=0D.=A9=7Ffss gk=\015\012=A9=FF  u=A9y.i\011v~vnh =3D "
     "=C3z=0D=00!b =00\011g~=0A!=0A=3Dr dgg   s w=0Dfnwlh=\015\012=0D k=80vb=7F xmz "
     "pvc=0A =C3fwh=FF  =00=7F=A9z =7F=C3=0A=80=3D=0A=7F lw=00 =\015\012 qd=80"},
    {NULL, 225, 15,
     "c\015\012d=7F=7Fk\015\012=C3 dps\011=3D.=00p\011tx! w i\011qou~p=00ell amhx "
     "coqlrntx mej r  kw=00x k qsbxa gh=\015\012~ja  s  =C3hcd\015\012vp "
     "=FFl\015\012v=A9o!uih\015\012qs\015\012! g !=7F~wm  rpn=80 s=FFh\015\012wc "
     "~qw\015\012sq o=FFgsdrwas "
     "=FF=3D=3D=A9=3D\015\012t=20\015\012neetyouz=3D\011=80bw bmf=C3g=00n "
     "f=3D.\015\012 zi!!k.qj jb f=3D=00\011\011vu=3Dds!=80=C3\015\012 a=3Dgq=7Fp "
     "\011.\015\012 icg\015\012 r=A9=C3\015\012",
     "c\015\012d=7F=7Fk\015\012=C3 dps\011=3D.=00p\011tx! w i\011qou~p=00ell amhx "
     "coqlrntx mej r  kw=00x k qsbxa gh=\015\012~ja  s  =C3hcd\015\012vp "
     "=FFl\015\012v=A9o!uih\015\012qs\015\012! g !=7F~wm  rpn=80 s=FFh\015\012wc "
     "~qw\015\012sq o=FFgsdrwas "
     "=FF=3D=3D=A9=3D\015\012t=20\015\012neetyouz=3D\011=80bw bmf=C3g=00n "
     "f=3D.\015\012 zi!!k.qj jb f=3D=00\011\011vu=3Dds!=80=C3\015\012 a=3Dgq=7Fp "
     "\011.\015\012 icg\015\012 r=A9=C3\015\012",
     "c=0Dd=7F=7Fk=0A=C3 dps\011=3D.=00p\011tx! w i\011qou~p=00ell amhx coqlrntx mej r "
     " kw=\015\012=00x k qsbxa gh~ja  s  =C3hcd=0Avp =FFl=0Av=A9o!uih=0Aqs=0A! g "
     "!=7F~wm  rpn=\015\012=80 s=FFh=0Awc ~qw=0Asq o=FFgsdrwas =FF=3D=3D=A9=3D=0Dt "
     "=0Dneetyouz=3D\011=80b=\015\012w bmf=C3g=00n f=3D.=0D zi!!k.qj jb "
     "f=3D=00\011\011vu=3Dds!=80=C3=0D a=3Dgq=7Fp \011.=\015\012=0D icg=0D r=A9=C3=0A",
     "c=0Dd=7F=7Fk=0A=C3 dps\011=3D.=00p\011tx! w i\011qou~p=00ell amhx coqlrntx mej r "
     " kw=\015\012=00x k qsbxa gh~ja  s  =C3hcd=0Avp =FFl=0Av=A9o!uih=0Aqs=0A! g "
     "!=7F~wm  rpn=\015\012=80 s=FFh=0Awc ~qw=0Asq o=FFgsdrwas =FF=3D=3D=A9=3D=0Dt "
     "=0Dneetyouz=3D\011=80b=\015\012w bmf=C3g=00n f=3D.=0D zi!!k.qj jb "
     "f=3D=00\011\011vu=3Dds!=80=C3=0D a=3Dgq=7Fp \011.=\015\012=0D icg=0D r=A9=C3=0A"},
    {NULL, 256, 16,
     "bmuvc\011 =3D u!r=3Df o\015\012=7F . i=7Fy e  tnq v au=C3w l sh=3D=A9 =A9 "
     "\011\011 \011zqb lvpc\015\012y=80\015\012ctxb  sst\015\012.f=3Dqq o~m=7F "
     "uj.\011g\015\012dff.jxut=FF any "
     "=80mr=00\015\012n\015\012n\015\012st\015\012=A9ha\015\012l="
     "FFlnj\015\012\011usu\011=3D\015\012ug d\015\012zh   glziqr\015\012pf=FF=3Db v! "
     "f.aerzm =C3i~=7Fr f\015\012  bl.\015\012=09\015\012q g\015\012.\015\012=3Db  "
     "pvgw k=7F=20\015\012 q   d=FFukqlhqwwy =C3k u!\011qmbn rj!tlmh\015\012.z=7F.nt "
     ".\015\012lqs yqs=09",
     "bmuvc\011 =3D u!r=3Df o\015\012=7F . i=7Fy e  tnq v au=C3w l sh=3D=A9 =A9 "
     "\011\011 \011zqb lvpc\015\012y=80\015\012ctxb  sst\015\012.f=3Dqq o~m=7F "
     "uj.\011g\015\012dff.jxut=FF any "
     "=80mr=00\015\012n\015\012n\015\012st\015\012=A9ha\015\012l="
     "FFlnj\015\012\011usu\011=3D\015\012ug d\015\012zh   glziqr\015\012pf=FF=3Db v! "
     "f.aerzm =C3i~=7Fr f\015\012  bl.\015\012=09\015\012q g\015\012.\015\012=3Db  "
     "pvgw k=7F=20\015\012 q   d=FFukqlhqwwy =C3k u!\011qmbn rj!tlmh\015\012.z=7F.nt "
     ".\015\012lqs yqs=09",
     "bmuvc\011 =3D u!r=3Df o=0A=7F . i=7Fy e  tnq v au=C3w l sh=3D=A9 =A9 \011\011 "
     "\011zqb l=\015\012vpc=0Ay=80=0Dctxb  sst=0A.f=3Dqq o~m=7F uj.\011g=0Ddff.jxut=FF "
     "any =80mr=00=0A=\015\012n=0Dn=0Ast=0D=A9ha=0Al=FFlnj=0A\011usu\011=3D=0Dug "
     "d=0Azh   glziqr=0Dpf=FF=3Db v!=\015\012 f.aerzm =C3i~=7Fr f=0A  bl.=0A\011=0Aq "
     "g=0A.=0A=3Db  pvgw k=7F =0A q   d=FFuk=\015\012qlhqwwy =C3k u!\011qmbn "
     "rj!tlmh=0D.z=7F.nt .=0Alqs yqs=09",
     "bmuvc\011 =3D u!r=3Df o=0A=7F . i=7Fy e  tnq v au=C3w l sh=3D=A9 =A9 \011\011 "
     "\011zqb l=\015\012vpc=0Ay=80=0Dctxb  sst=0A.f=3Dqq o~m=7F uj.\011g=0Ddff.jxut=FF "
     "any =80mr=00=0A=\015\012n=0Dn=0Ast=0D=A9ha=0Al=FFlnj=0A\011usu\011=3D=0Dug "
     "d=0Azh   glziqr=0Dpf=FF=3Db v!=\015\012 f.aerzm =C3i~=7Fr f=0A  bl.=0A\011=0Aq "
     "g=0A.=0A=3Db  pvgw k=7F =0A q   d=FFuk=\015\012qlhqwwy =C3k u!\011qmbn "
     "rj!tlmh=0D.z=7F.nt .=0Alqs yqs=09"},
    {NULL, 289, 17,
     "bn\015\012=80\011h=00\011k\015\012w~vw=C3jlhp\015\012n\011~=7Fs=A9xqsjrpnq=3D "
     "=00g y \011a\015\012\015\012\015\012k=7F=C3\015\012\015\012obkw. i\015\012a=7F "
     "xouugcg  =00!h\011xo \011fcvms! ft k\015\012lu=3Dx\015\012\011cj n vg\011 "
     "n=7Fa=3Dty\011vz =3D=C3c=7Fj uu  "
     "vc~a.q=7F\011!dob=FFv=09\015\012myykg\015\012hqs !nfowmy=20\015\012ym "
     "=FF\015\012\011=C3jqb  tkrl op\011jgqb\015\012=3Dg=80b\015\012vt=7F=7F. =FF "
     "=A9\015\012as mqz.da\015\012=C3hd kq=3D=A9!d~!z=FFin\011 "
     "z\015\012ug=09\015\012dg =FF ilfykoogo=3D!~om=3D=20\015\012a =00.fti q kn~t "
     "=C3jc by~\015\012 g s=00 ed",
     "bn\015\012=80\011h=00\011k\015\012w~vw=C3jlhp\015\012n\011~=7Fs=A9xqsjrpnq=3D "
     "=00g y \011a\015\012\015\012\015\012k=7F=C3\015\012\015\012obkw. i\015\012a=7F "
     "xouugcg  =00!h\011xo \011fcvms! ft k\015\012lu=3Dx\015\012\011cj n vg\011 "
     "n=7Fa=3Dty\011vz =3D=C3c=7Fj uu  "
     "vc~a.q=7F\011!dob=FFv=09\015\012myykg\015\012hqs !nfowmy=20\015\012ym "
     "=FF\015\012\011=C3jqb  tkrl op\011jgqb\015\012=3Dg=80b\015\012vt=7F=7F. =FF "
     "=A9\015\012as mqz.da\015\012=C3hd kq=3D=A9!d~!z=FFin\011 "
     "z\015\012ug=09\015\012dg =FF ilfykoogo=3D!~om=3D=20\015\012a =00.fti q kn~t "
     "=C3jc by~\015\012 g s=00 ed",
     "bn=0D=80\011h=00\011k=0Dw~vw=C3jlhp=0An\011~=7Fs=A9xqsjrpnq=3D =00g y "
     "\011a=0D=0D=0Dk=\015\012=7F=C3=0D=0A=0Dobkw. i=0Aa=7F xouugcg  =00!h\011xo "
     "\011fcvms! ft k=0Alu=3Dx=0A\011cj=\015\012 n vg\011 n=7Fa=3Dty\011vz =3D=C3c=7Fj "
     "uu  vc~a.q=7F\011!dob=FFv\011=0Dmyykg=0Ahqs !nfo=\015\012wmy =0Dym "
     "=FF=0D\011=C3jqb  tkrl op\011jgqb=0A=3Dg=80b=0Avt=7F=7F. =FF =A9=0Das "
     "m=\015\012qz.da=0A=C3hd kq=3D=A9!d~!z=FFin\011 z=0Dug\011=0Ddg =FF "
     "ilfykoogo=3D!~om=3D =0Aa=\015\012 =00.fti q kn~t =C3jc by~=0D g s=00 ed",
     "bn=0D=80\011h=00\011k=0Dw~vw=C3jlhp=0An\011~=7Fs=A9xqsjrpnq=3D =00g y "
     "\011a=0D=0D=0Dk=\015\012=7F=C3=0D=0A=0Dobkw. i=0Aa=7F xouugcg  =00!h\011xo "
     "\011fcvms! ft k=0Alu=3Dx=0A\011cj=\015\012 n vg\011 n=7Fa=3Dty\011vz =3D=C3c=7Fj "
     "uu  vc~a.q=7F\011!dob=FFv\011=0Dmyykg=0Ahqs !nfo=\015\012wmy =0Dym "
     "=FF=0D\011=C3jqb  tkrl op\011jgqb=0A=3Dg=80b=0Avt=7F=7F. =FF =A9=0Das "
     "m=\015\012qz.da=0A=C3hd kq=3D=A9!d~!z=FFin\011 z=0Dug\011=0Ddg =FF "
     "ilfykoogo=3D!~om=3D =0Aa=\015\012 =00.fti q kn~t =C3jc by~=0D g s=00 ed"},
    {NULL, 324, 18,
     " =3Dev.=20\015\012=20\015\012 arbnn k=00 g=A9k=3Drkt\015\012 rer  g "
     "u=3D=3D=FFm\015\012 !lx=7Fwjj. re\015\012=7F!x.a=00ors\011au.\011 "
     "ir\015\012=7Fx=A9n=20\015\012l\015\012w\015\012 dirv! wjts\015\012n "
     "=C3\015\012!=3Dbbs =C3 \011=80ps jfx !=20\015\012d if brei\011r aqfw "
     "caryj\015\012t=A9.\015\012=00 \011=C3t=00 m\011  =C3 "
     "q=A9i=C3!\015\012x\015\012m=C3\011oilbjg\011qesnd "
     "brxrt=80e\015\012a\015\012\015\012bt k=C3sa=7F=3Diw!dwehgr  "
     "=FF=7Fy\015\012\011=3D=3Dv q nzntp=00 fty\011t =00\011k=00 "
     "we=00mqzmlk\011mf=80!w ~~\015\012\015\012joeq gegih q w=80  wbxw xn\015\012gb.hl "
     " i=7Fm=80 gunfc=3Drp=C3\011f.byvrx t ap=FFf",
     " =3Dev.=20\015\012=20\015\012 arbnn k=00 g=A9k=3Drkt\015\012 rer  g "
     "u=3D=3D=FFm\015\012 !lx=7Fwjj. re\015\012=7F!x.a=00ors\011au.\011 "
     "ir\015\012=7Fx=A9n=20\015\012l\015\012w\015\012 dirv! wjts\015\012n "
     "=C3\015\012!=3Dbbs =C3 \011=80ps jfx !=20\015\012d if brei\011r aqfw "
     "caryj\015\012t=A9.\015\012=00 \011=C3t=00 m\011  =C3 "
     "q=A9i=C3!\015\012x\015\012m=C3\011oilbjg\011qesnd "
     "brxrt=80e\015\012a\015\012\015\012bt k=C3sa=7F=3Diw!dwehgr  "
     "=FF=7Fy\015\012\011=3D=3Dv q nzntp=00 fty\011t =00\011k=00 "
     "we=00mqzmlk\011mf=80!w ~~\015\012\015\012joeq gegih q w=80  wbxw xn\015\012gb.hl "
     " i=7Fm=80 gunfc=3Drp=C3\011f.byvrx t ap=FFf",
     " =3Dev. =0D =0A arbnn k=00 g=A9k=3Drkt=0A rer  g u=3D=3D=FFm=0A !lx=7Fwjj. "
     "=\015\012re=0D=7F!x.a=00ors\011au.\011 ir=0A=7Fx=A9n =0Dl=0Dw=0D dirv! "
     "wjts=0D=0An =C3=0D!=\015\012=3Dbbs =C3 \011=80ps jfx ! =0Ad if brei\011r aqfw "
     "caryj=0Dt=A9.=0A=00 \011=C3t=00 m\011=\015\012  =C3 "
     "q=A9i=C3!=0Ax=0Dm=C3\011oilbjg\011qesnd brxrt=80e=0Aa=0D=0Dbt "
     "k=C3sa=7F=3Di=\015\012w!dwehgr  =FF=7Fy=0A\011=3D=3Dv q nzntp=00 fty\011t "
     "=00\011k=00 we=00mqzmlk\011mf=80!w =\015\012~~=0D=0Djoeq gegih q w=80  wbxw "
     "xn=0Agb.hl  i=7Fm=80 gunfc=3Drp=C3\011f.byvrx =\015\012t ap=FFf",
     " =3Dev. =0D =0A arbnn k=00 g=A9k=3Drkt=0A rer  g u=3D=3D=FFm=0A !lx=7Fwjj. "
     "=\015\012re=0D=7F!x.a=00ors\011au.\011 ir=0A=7Fx=A9n =0Dl=0Dw=0D dirv! "
     "wjts=0D=0An =C3=0D!=\015\012=3Dbbs =C3 \011=80ps jfx ! =0Ad if brei\011r aqfw "
     "caryj=0Dt=A9.=0A=00 \011=C3t=00 m\011=\015\012  =C3 "
     "q=A9i=C3!=0Ax=0Dm=C3\011oilbjg\011qesnd brxrt=80e=0Aa=0D=0Dbt "
     "k=C3sa=7F=3Di=\015\012w!dwehgr  =FF=7Fy=0A\011=3D=3Dv q nzntp=00 fty\011t "
     "=00\011k=00 we=00mqzmlk\011mf=80!w =\015\012~~=0D=0Djoeq gegih q w=80  wbxw "
     "xn=0Agb.hl  i=7Fm=80 gunfc=3Drp=C3\011f.byvrx =\015\012t ap=FFf"},
    {NULL, 361, 19,
     "zqw=80xfc=C3.! .  dz g\015\012ziknnc\015\012 "
     "~.zsl=7Fws=20\015\012a=80a=3D~m\011keixv=7F.=80uxe=3Dd sdc\015\012d!m=80nod\011 "
     "=FFw or\015\012\011=7Fp=3Dxqu=A9=3Dphorjcz \011 =00\015\012~d=A9p=7Fofl=7Fg=A9 "
     "u\011=00c=20\015\012\011z fih=20\015\012 \011zv=3Dr\011 ..\015\012s l "
     "=FF=A9\015\012 \011i=FFeb=20\015\012=80=C3hh=20\015\012p=C3 "
     "i=00evb=80wno=C3\015\012lo=7Fzxdz=7F vl=A9h=80rs=C3=C3m\015\012vny  tn.ukde "
     "=FF\015\012yrt~ll=80l=80=7Fj\015\012 b\011\011nl\015\012ndrnd "
     "o=80.=20\015\012hjf\015\012.=3Dg=20\015\012\011 \011!=00k  "
     "=20\015\012=A9c\011ilh=3Df! =7F qd t=00=C3\015\012nw "
     "q~nsh=C3\015\012=00=3Dbstjpiz =80 ~\011=C3\015\012=FF\011ytp axqa=80b=FF=00kc "
     "n\015\012klre=20\015\012gmh =A9k\015\012r ibby\015\012waw   p~!=00w\015\012si  "
     "\011=7Fcc=7Fiy",
     "zqw=80xfc=C3.! .  dz g\015\012ziknnc\015\012 "
     "~.zsl=7Fws=20\015\012a=80a=3D~m\011keixv=7F.=80uxe=3Dd sdc\015\012d!m=80nod\011 "
     "=FFw or\015\012\011=7Fp=3Dxqu=A9=3Dphorjcz \011 =00\015\012~d=A9p=7Fofl=7Fg=A9 "
     "u\011=00c=20\015\012\011z fih=20\015\012 \011zv=3Dr\011 ..\015\012s l "
     "=FF=A9\015\012 \011i=FFeb=20\015\012=80=C3hh=20\015\012p=C3 "
     "i=00evb=80wno=C3\015\012lo=7Fzxdz=7F vl=A9h=80rs=C3=C3m\015\012vny  tn.ukde "
     "=FF\015\012yrt~ll=80l=80=7Fj\015\012 b\011\011nl\015\012ndrnd "
     "o=80.=20\015\012hjf\015\012.=3Dg=20\015\012\011 \011!=00k  "
     "=20\015\012=A9c\011ilh=3Df! =7F qd t=00=C3\015\012nw "
     "q~nsh=C3\015\012=00=3Dbstjpiz =80 ~\011=C3\015\012=FF\011ytp axqa=80b=FF=00kc "
     "n\015\012klre=20\015\012gmh =A9k\015\012r ibby\015\012waw   p~!=00w\015\012si  "
     "\011=7Fcc=7Fiy",
     "zqw=80xfc=C3.! .  dz g=0Dziknnc=0A ~.zsl=7Fws "
     "=0Da=80a=3D~m\011keixv=7F.=80uxe=\015\012=3Dd sdc=0Ad!m=80nod\011 =FFw "
     "or=0D\011=7Fp=3Dxqu=A9=3Dphorjcz \011 =00=0D~d=A9p=7Fo=\015\012fl=7Fg=A9 "
     "u\011=00c =0D\011z fih =0D \011zv=3Dr\011 ..=0Ds l =FF=A9=0A \011i=FFeb "
     "=0A=80=\015\012=C3hh =0Dp=C3 i=00evb=80wno=C3=0Dlo=7Fzxdz=7F "
     "vl=A9h=80rs=C3=C3m=0Avny  tn.=\015\012ukde =FF=0Dyrt~ll=80l=80=7Fj=0D "
     "b\011\011nl=0Andrnd o=80. =0Ahjf=0D.=3Dg =0D\011 \011!=\015\012=00k   "
     "=0D=A9c\011ilh=3Df! =7F qd t=00=C3=0Anw q~nsh=C3=0A=00=3Dbstjpiz =80 "
     "~\011=\015\012=C3=0D=FF\011ytp axqa=80b=FF=00kc n=0Aklre =0Agmh =A9k=0Dr "
     "ibby=0Dwaw   p~!=00=\015\012w=0Asi  \011=7Fcc=7Fiy",
     "zqw=80xfc=C3.! .  dz g=0Dziknnc=0A ~.zsl=7Fws "
     "=0Da=80a=3D~m\011keixv=7F.=80uxe=\015\012=3Dd sdc=0Ad!m=80nod\011 =FFw "
     "or=0D\011=7Fp=3Dxqu=A9=3Dphorjcz \011 =00=0D~d=A9p=7Fo=\015\012fl=7Fg=A9 "
     "u\011=00c =0D\011z fih =0D \011zv=3Dr\011 ..=0Ds l =FF=A9=0A \011i=FFeb "
     "=0A=80=\015\012=C3hh =0Dp=C3 i=00evb=80wno=C3=0Dlo=7Fzxdz=7F "
     "vl=A9h=80rs=C3=C3m=0Avny  tn.=\015\012ukde =FF=0Dyrt~ll=80l=80=7Fj=0D "
     "b\011\011nl=0Andrnd o=80. =0Ahjf=0D.=3Dg =0D\011 \011!=\015\012=00k   "
     "=0D=A9c\011ilh=3Df! =7F qd t=00=C3=0Anw q~nsh=C3=0A=00=3Dbstjpiz =80 "
     "~\011=\015\012=C3=0D=FF\011ytp axqa=80b=FF=00kc n=0Aklre =0Agmh =A9k=0Dr "
     "ibby=0Dwaw   p~!=00=\015\012w=0Asi  \011=7Fcc=7Fiy"},
    {NULL, 0, 20, "", "", "", ""},
    {NULL, 41, 21,
     "=FF!g=C3lcj\011=FFz\015\012=3Dsm\011=3D f\011o mj=20\015\012dl=00=3Dqthecx  !q w",
     "=FF!g=C3lcj\011=FFz\015\012=3Dsm\011=3D f\011o mj=20\015\012dl=00=3Dqthecx  !q w",
     "=FF!g=C3lcj\011=FFz=0A=3Dsm\011=3D f\011o mj =0Adl=00=3Dqthecx  !q w",
     "=FF!g=C3lcj\011=FFz=0A=3Dsm\011=3D f\011o mj =0Adl=00=3Dqthecx  !q w"},
    {NULL, 84, 22,
     "=A9=00x=A9s becq=3D=3D=A9 zkcruio\015\012 c xci\015\012musvrmtd=20\015\012=3D q. "
     "=7F rog hjq   =7Fiv s=20\015\012=FF=80=A9e  op a~lc\015\012 ax=3Dd=00=00",
     "=A9=00x=A9s becq=3D=3D=A9 zkcruio\015\012 c xci\015\012musvrmtd=20\015\012=3D q. "
     "=7F rog hjq   =7Fiv s=20\015\012=FF=80=A9e  op a~lc\015\012 ax=3Dd=00=00",
     "=A9=00x=A9s becq=3D=3D=A9 zkcruio=0A c xci=0Dmusvrmtd =0A=3D q. =7F rog "
     "hjq=\015\012   =7Fiv s =0A=FF=80=A9e  op a~lc=0A ax=3Dd=00=00",
     "=A9=00x=A9s becq=3D=3D=A9 zkcruio=0A c xci=0Dmusvrmtd =0A=3D q. =7F rog "
     "hjq=\015\012   =7Fiv s =0A=FF=80=A9e  op a~lc=0A ax=3Dd=00=00"},
    {NULL, 129, 23,
     "xv=3Dx =FFr=A9  soeu=3Df e  =FF\015\012 =A9vrs=80\015\012 vdmhb am\015\012  "
     "i\011d ~  s\015\012=7F\015\012gr=3D  tn\015\012 =FFwk =A9bf =3Dc. wc "
     "=00=20\015\012agnelk\015\012lf=C3 \011 o \011gp=FF=3D !=A9 e\015\012xq k "
     "=3D\011n\015\012lus\011k\011ctw =FFku~",
     "xv=3Dx =FFr=A9  soeu=3Df e  =FF\015\012 =A9vrs=80\015\012 vdmhb am\015\012  "
     "i\011d ~  s\015\012=7F\015\012gr=3D  tn\015\012 =FFwk =A9bf =3Dc. wc "
     "=00=20\015\012agnelk\015\012lf=C3 \011 o \011gp=FF=3D !=A9 e\015\012xq k "
     "=3D\011n\015\012lus\011k\011ctw =FFku~",
     "xv=3Dx =FFr=A9  soeu=3Df e  =FF=0A =A9vrs=80=0A vdmhb am=0D  i\011d ~  "
     "s=0A=7F=\015\012=0Agr=3D  tn=0D =FFwk =A9bf =3Dc. wc =00 =0Dagnelk=0D=0Alf=C3 "
     "\011 o \011gp=FF=3D=\015\012 !=A9 e=0Axq k =3D\011n=0Dlus\011k\011ctw =FFku~",
     "xv=3Dx =FFr=A9  soeu=3Df e  =FF=0A =A9vrs=80=0A vdmhb am=0D  i\011d ~  "
     "s=0A=7F=\015\012=0Agr=3D  tn=0D =FFwk =A9bf =3Dc. wc =00 =0Dagnelk=0D=0Alf=C3 "
     "\011 o \011gp=FF=3D=\015\012 !=A9 e=0Axq k =3D\011n=0Dlus\011k\011ctw =FFku~"},
    {NULL, 176, 24,
     "x=C3h=A9hxi.\011=A9=80\015\012=09\015\012gz=A9qq=C3ip uo\015\012ik\015\012 "
     "v\015\012 w=3Ds=C3wir yd ubo. =3Dj~=80cz=C3geg=7F=7Fvivt=FFx\011iqoc  "
     "sjcy=7Fdx=A9odaj =\015\012z=3D~ r  y=C3=80  z\015\012hrz  .\015\012 "
     "zf=A9u=09\015\012slkzmqb=80 oq gypf=C3t!e  . =80r "
     "\011su\015\012d=3Doqkj\015\012drz a=00=00c o\015\012wqoawq wq=00t\015\012",
     "x=C3h=A9hxi.\011=A9=80\015\012=09\015\012gz=A9qq=C3ip uo\015\012ik\015\012 "
     "v\015\012 w=3Ds=C3wir yd ubo. =3Dj~=80cz=C3geg=7F=7Fvivt=FFx\011iqoc  "
     "sjcy=7Fdx=A9odaj =\015\012z=3D~ r  y=C3=80  z\015\012hrz  .\015\012 "
     "zf=A9u=09\015\012slkzmqb=80 oq gypf=C3t!e  . =80r "
     "\011su\015\012d=3Doqkj\015\012drz a=00=00c o\015\012wqoawq wq=00t\015\012",
     "x=C3h=A9hxi.\011=A9=80=0A\011=0Agz=A9qq=C3ip uo=0Dik=0D v=0D w=3Ds=C3wir yd ubo. "
     "=\015\012=3Dj~=80cz=C3geg=7F=7Fvivt=FFx\011iqoc  sjcy=7Fdx=A9odaj z=3D~ r  "
     "y=C3=80  z=\015\012=0Dhrz  .=0D zf=A9u\011=0Aslkzmqb=80 oq gypf=C3t!e  . =80r "
     "\011su=0Ad=3Doqkj=0Ddr=\015\012z a=00=00c o=0Awqoawq wq=00t=0A",
     "x=C3h=A9hxi.\011=A9=80=0A\011=0Agz=A9qq=C3ip uo=0Dik=0D v=0D w=3Ds=C3wir yd ubo. "
     "=\015\012=3Dj~=80cz=C3geg=7F=7Fvivt=FFx\011iqoc  sjcy=7Fdx=A9odaj z=3D~ r  "
     "y=C3=80  z=\015\012=0Dhrz  .=0D zf=A9u\011=0Aslkzmqb=80 oq gypf=C3t!e  . =80r "
     "\011su=0Ad=3Doqkj=0Ddr=\015\012z a=00=00c o=0Awqoawq wq=00t=0A"},
    {NULL, 225, 25,
     "w=A9yyo=80=FF\015\012noznpc=80=7Fwd q!=3Da.ghz=A9\011yw=A9=7Fm  "
     "=00gff\015\012q=80ahl  r=00xwl\015\012k=00\015\012p=FF j~!g a=7Fn\011s "
     "ndhj\015\012kw f=3D\011yt=3D =20\015\012zn "
     "=FF=3Duw\015\012m.p\011=7F=00\015\012w =3Dlj=20\015\012g g =3Dy "
     "conxaz=3D=00hctgq\011 =00d!rbcwwg pe\015\012b\015\012mk nl\015\012=C3\015\012 ~ "
     "oly=20\015\012u =3Dp wrz as\011\011=00=80\015\012qa=00 =3D=00=00 "
     "sdni\015\012=20\015\012=3Dqcfj\015\012s q=80 jv uj!! =3Dw=7Fu=FF =3Djvs=A9c",
     "w=A9yyo=80=FF\015\012noznpc=80=7Fwd q!=3Da.ghz=A9\011yw=A9=7Fm  "
     "=00gff\015\012q=80ahl  r=00xwl\015\012k=00\015\012p=FF j~!g a=7Fn\011s "
     "ndhj\015\012kw f=3D\011yt=3D =20\015\012zn "
     "=FF=3Duw\015\012m.p\011=7F=00\015\012w =3Dlj=20\015\012g g =3Dy "
     "conxaz=3D=00hctgq\011 =00d!rbcwwg pe\015\012b\015\012mk nl\015\012=C3\015\012 ~ "
     "oly=20\015\012u =3Dp wrz as\011\011=00=80\015\012qa=00 =3D=00=00 "
     "sdni\015\012=20\015\012=3Dqcfj\015\012s q=80 jv uj!! =3Dw=7Fu=FF =3Djvs=A9c",
     "w=A9yyo=80=FF=0Dnoznpc=80=7Fwd q!=3Da.ghz=A9\011yw=A9=7Fm  =00gff=0Aq=80ahl  "
     "r=\015\012=00xwl=0Ak=00=0Ap=FF j~!g a=7Fn\011s ndhj=0Dkw f=3D\011yt=3D  =0Dzn "
     "=FF=3Duw=0Dm.=\015\012p\011=7F=00=0Aw =3Dlj =0Ag g =3Dy conxaz=3D=00hctgq\011 "
     "=00d!rbcwwg pe=0Db=0Dmk n=\015\012l=0A=C3=0A ~ oly =0Du =3Dp wrz "
     "as\011\011=00=80=0Dqa=00 =3D=00=00 sdni=0D =0D=3Dq=\015\012cfj=0Ds q=80 jv uj!! "
     "=3Dw=7Fu=FF =3Djvs=A9c",
     "w=A9yyo=80=FF=0Dnoznpc=80=7Fwd q!=3Da.ghz=A9\011yw=A9=7Fm  =00gff=0Aq=80ahl  "
     "r=\015\012=00xwl=0Ak=00=0Ap=FF j~!g a=7Fn\011s ndhj=0Dkw f=3D\011yt=3D  =0Dzn "
     "=FF=3Duw=0Dm.=\015\012p\011=7F=00=0Aw =3Dlj =0Ag g =3Dy conxaz=3D=00hctgq\011 "
     "=00d!rbcwwg pe=0Db=0Dmk n=\015\012l=0A=C3=0A ~ oly =0Du =3Dp wrz "
     "as\011\011=00=80=0Dqa=00 =3D=00=00 sdni=0D =0D=3Dq=\015\012cfj=0Ds q=80 jv uj!! "
     "=3Dw=7Fu=FF =3Djvs=A9c"},
    {NULL, 276, 26,
     "=80z.=FF=7F=7Fqe~gd\015\012=7Ftm=3D=7Fp\015\012\015\012 "
     "r=A9\015\012yc=3Dm\011!x=09\015\012cts.=3D !=3D =3D=A9=00vm! "
     "ylbbyt=3Dszq\015\012=C3=3D qra~.j=00\015\012y=20\015\012=FFrs=7Fpih!j\015\012 "
     "g=00b\015\012i i=80\015\012ubc =A9tdig=00ddf  d=09\015\012q ! "
     "q=00epe=FFc=A9byyg\015\012=3D=3Du\015\012hea\015\012\015\012=80=00 "
     "w=3Deox\011hw.\015\012m~lf   du=FFl ~n=3D "
     "ws=C3\011\011.=C3e\015\012bot=A9=3Dc\015\012=00qj=7F~w!=A9=7Fdw=3D\015\012  "
     "v\015\012f\015\012=00=3Djxinywkksk\011!xif\015\012 v\011fj.rbfxsws=80vz "
     "cz=3Dqetor\011hulx =80e~q\015\012=00 xmq\011m sof o=C3u~q=80",
     "=80z.=FF=7F=7Fqe~gd\015\012=7Ftm=3D=7Fp\015\012\015\012 "
     "r=A9\015\012yc=3Dm\011!x=09\015\012cts.=3D !=3D =3D=A9=00vm! "
     "ylbbyt=3Dszq\015\012=C3=3D qra~.j=00\015\012y=20\015\012=FFrs=7Fpih!j\015\012 "
     "g=00b\015\012i i=80\015\012ubc =A9tdig=00ddf  d=09\015\012q ! "
     "q=00epe=FFc=A9byyg\015\012=3D=3Du\015\012hea\015\012\015\012=80=00 "
     "w=3Deox\011hw.\015\012m~lf   du=FFl ~n=3D "
     "ws=C3\011\011.=C3e\015\012bot=A9=3Dc\015\012=00qj=7F~w!=A9=7Fdw=3D\015\012  "
     "v\015\012f\015\012=00=3Djxinywkksk\011!xif\015\012 v\011fj.rbfxsws=80vz "
     "cz=3Dqetor\011hulx =80e~q\015\012=00 xmq\011m sof o=C3u~q=80",
     "=80z.=FF=7F=7Fqe~gd=0D=7Ftm=3D=7Fp=0A=0D r=A9=0Dyc=3Dm\011!x\011=0Dcts.=3D !=3D "
     "=\015\012=3D=A9=00vm! ylbbyt=3Dszq=0D=C3=3D qra~.j=00=0Ay =0A=FFrs=7Fpih!j=0D "
     "g=00b=\015\012=0Di i=80=0Dubc =A9tdig=00ddf  d\011=0Aq ! "
     "q=00epe=FFc=A9byyg=0D=3D=3D=0Au=0Ah=\015\012ea=0A=0A=80=00 w=3Deox\011hw.=0Am~lf "
     "  du=FFl ~n=3D "
     "ws=C3\011\011.=C3e=0Dbot=A9=3Dc=\015\012=0D=00qj=7F~w!=A9=7Fdw=3D=0D=0A  "
     "v=0Af=0D=00=3Djxinywkksk\011!xif=0A v\011fj.rbfx=\015\012sws=80vz "
     "cz=3Dqetor\011hulx =80e~q=0D=00 xmq\011m sof o=C3u~q=80",
     "=80z.=FF=7F=7Fqe~gd=0D=7Ftm=3D=7Fp=0A=0D r=A9=0Dyc=3Dm\011!x\011=0Dcts.=3D !=3D "
     "=\015\012=3D=A9=00vm! ylbbyt=3Dszq=0D=C3=3D qra~.j=00=0Ay =0A=FFrs=7Fpih!j=0D "
     "g=00b=\015\012=0Di i=80=0Dubc =A9tdig=00ddf  d\011=0Aq ! "
     "q=00epe=FFc=A9byyg=0D=3D=3D=0Au=0Ah=\015\012ea=0A=0A=80=00 w=3Deox\011hw.=0Am~lf "
     "  du=FFl ~n=3D "
     "ws=C3\011\011.=C3e=0Dbot=A9=3Dc=\015\012=0D=00qj=7F~w!=A9=7Fdw=3D=0D=0A  "
     "v=0Af=0D=00=3Djxinywkksk\011!xif=0A v\011fj.rbfx=\015\012sws=80vz "
     "cz=3Dqetor\011hulx =80e~q=0D=00 xmq\011m sof o=C3u~q=80"},
    {NULL, 329, 27,
     "=80 iycth=A9=7Fw nbk ks y o~=80jqw z =3Dy=00drj=20\015\012az !=A9 w  xg=3D "
     "zf.kd\015\012=A9\015\012j=7Fllp   o=80\015\012=80a\011g.p=7Fz!z\015\012=A9 s "
     "wf\015\012=3Dud =3Ddar=3Ds!f kwa. "
     ".zb\011r\015\012=80b=C3=80lh\015\012!q\015\012xfh "
     "=3D=00tu=3Dt=80=7F=FFv.zac=7Fi\011d w h em!=3Dn\015\012hj!  "
     "=7F.=00\011kc\015\012=3Dhwt=7Fq=00=3D\015\012b  =3Dx=C3\015\012  "
     "=7F\015\012=3D=FFi ek\011=80c=3Dx! wx=00t \011v=C3=7F=7Fr a. ozwn=3Dab "
     "m!=3Dubrbpz=3De\011\011umy=\015\012=00\015\012f=20\015\012v=A9=C3=3D\015\012cs "
     "=3Du!x=A9gwz.vg=C3a~as=3Dbu=20\015\012a xxr\011t=C3voqtbd f "
     "c=A9.=A9kenzg\015\012p\015\012al=3D=FFyr=FF=C3pp\015\012=80 !ll\015\012 "
     "a\015\012=A9 h=3Dkr=20",
     "=80 iycth=A9=7Fw nbk ks y o~=80jqw z =3Dy=00drj=20\015\012az !=A9 w  xg=3D "
     "zf.kd\015\012=A9\015\012j=7Fllp   o=80\015\012=80a\011g.p=7Fz!z\015\012=A9 s "
     "wf\015\012=3Dud =3Ddar=3Ds!f kwa. "
     ".zb\011r\015\012=80b=C3=80lh\015\012!q\015\012xfh "
     "=3D=00tu=3Dt=80=7F=FFv.zac=7Fi\011d w h em!=3Dn\015\012hj!  "
     "=7F.=00\011kc\015\012=3Dhwt=7Fq=00=3D\015\012b  =3Dx=C3\015\012  "
     "=7F\015\012=3D=FFi ek\011=80c=3Dx! wx=00t \011v=C3=7F=7Fr a. ozwn=3Dab "
     "m!=3Dubrbpz=3De\011\011umy=\015\012=00\015\012f=20\015\012v=A9=C3=3D\015\012cs "
     "=3Du!x=A9gwz.vg=C3a~as=3Dbu=20\015\012a xxr\011t=C3voqtbd f "
     "c=A9.=A9kenzg\015\012p\015\012al=3D=FFyr=FF=C3pp\015\012=80 !ll\015\012 "
     "a\015\012=A9 h=3Dkr=20",
     "=80 iycth=A9=7Fw nbk ks y o~=80jqw z =3Dy=00drj =0Daz !=A9 w  xg=3D "
     "zf.kd=\015\012=0D=A9=0Dj=7Fllp   o=80=0D=80a\011g.p=7Fz!z=0D=A9 s wf=0A=3Dud "
     "=3Ddar=3Ds!f kw=\015\012a. .zb\011r=0D=80b=C3=80lh=0D!q=0Axfh "
     "=3D=00tu=3Dt=80=7F=FFv.zac=7Fi\011d w h em!=\015\012=3Dn=0Ahj!  "
     "=7F.=00\011kc=0A=3Dhwt=7Fq=00=3D=0Ab  =3Dx=C3=0D  =7F=0A=3D=FFi "
     "ek=\015\012\011=80c=3Dx! wx=00t \011v=C3=7F=7Fr a. ozwn=3Dab "
     "m!=3Dubrbpz=3De\011\011umy=00=0Af =0D=\015\012v=A9=C3=3D=0Acs "
     "=3Du!x=A9gwz.vg=C3a~as=3Dbu =0Aa xxr\011t=C3voqtbd f "
     "c=A9.=A9k=\015\012enzg=0D=0Ap=0Dal=3D=FFyr=FF=C3pp=0A=80 !ll=0D a=0A=A9 "
     "h=3Dkr=20",
     "=80 iycth=A9=7Fw nbk ks y o~=80jqw z =3Dy=00drj =0Daz !=A9 w  xg=3D "
     "zf.kd=\015\012=0D=A9=0Dj=7Fllp   o=80=0D=80a\011g.p=7Fz!z=0D=A9 s wf=0A=3Dud "
     "=3Ddar=3Ds!f kw=\015\012a. .zb\011r=0D=80b=C3=80lh=0D!q=0Axfh "
     "=3D=00tu=3Dt=80=7F=FFv.zac=7Fi\011d w h em!=\015\012=3Dn=0Ahj!  "
     "=7F.=00\011kc=0A=3Dhwt=7Fq=00=3D=0Ab  =3Dx=C3=0D  =7F=0A=3D=FFi "
     "ek=\015\012\011=80c=3Dx! wx=00t \011v=C3=7F=7Fr a. ozwn=3Dab "
     "m!=3Dubrbpz=3De\011\011umy=00=0Af =0D=\015\012v=A9=C3=3D=0Acs "
     "=3Du!x=A9gwz.vg=C3a~as=3Dbu =0Aa xxr\011t=C3voqtbd f "
     "c=A9.=A9k=\015\012enzg=0D=0Ap=0Dal=3D=FFyr=FF=C3pp=0A=80 !ll=0D a=0A=A9 "
     "h=3Dkr=20"},
    {NULL, 384, 28,
     "=7Fc =FFj~x~y\015\012km  rf.o\011=FF=FF!tei.=C3oh\015\012y "
     "uhyr\011\011=C3=7Fw=3Db=7Ft=3D\011uc=20\015\012\011h=80m\011 vb z bmp "
     "lzlx\015\012=00 vg=FFi.k\015\012po =00m  d y "
     "yj.pfih\015\012ms\015\012u\015\012deux\011 ne\015\012=00=A9rw js!w qohqg p=A9 "
     "wjj z\015\012ru=80l\011n\015\012=3D~fzdw!\015\012 "
     "=20\015\012gc=7F\015\012nqismkqjwvtx ob=A9r\011. =7F aa=7Fiu "
     "=A9\015\012=3Dx=A9\015\012ho\011zdo ciuab\015\012~j=7F\011 "
     "ya\015\012=3D\015\012ih!=C3ywqw\011!s\015\012d=7Fj=3D=80=A9! "
     "=A9\015\012=00=09\015\012g\015\012  mowq gmrqe=80i  s d=3D=A9ws~x\015\012r  i "
     "a\015\012 b\015\012hk .m m\015\012\015\012qpjr=FF =80p. j!=3D =00qjfs \011l=A9 "
     "hkebrdj~c nnoh  zho=3D\011~  s  n "
     "=3D=20\015\012dq=00p\015\012gq\015\012jv=20\015\012i =A9=7Fs=00\011o =7F "
     "muhrryv=09\015\012 y=A9s=7Fu\015\012",
     "=7Fc =FFj~x~y\015\012km  rf.o\011=FF=FF!tei.=C3oh\015\012y "
     "uhyr\011\011=C3=7Fw=3Db=7Ft=3D\011uc=20\015\012\011h=80m\011 vb z bmp "
     "lzlx\015\012=00 vg=FFi.k\015\012po =00m  d y "
     "yj.pfih\015\012ms\015\012u\015\012deux\011 ne\015\012=00=A9rw js!w qohqg p=A9 "
     "wjj z\015\012ru=80l\011n\015\012=3D~fzdw!\015\012 "
     "=20\015\012gc=7F\015\012nqismkqjwvtx ob=A9r\011. =7F aa=7Fiu "
     "=A9\015\012=3Dx=A9\015\012ho\011zdo ciuab\015\012~j=7F\011 "
     "ya\015\012=3D\015\012ih!=C3ywqw\011!s\015\012d=7Fj=3D=80=A9! "
     "=A9\015\012=00=09\015\012g\015\012  mowq gmrqe=80i  s d=3D=A9ws~x\015\012r  i "
     "a\015\012 b\015\012hk .m m\015\012\015\012qpjr=FF =80p. j!=3D =00qjfs \011l=A9 "
     "hkebrdj~c nnoh  zho=3D\011~  s  n "
     "=3D=20\015\012dq=00p\015\012gq\015\012jv=20\015\012i =A9=7Fs=00\011o =7F "
     "muhrryv=09\015\012 y=A9s=7Fu\015\012",
     "=7Fc =FFj~x~y=0Dkm  rf.o\011=FF=FF!tei.=C3oh=0Dy "
     "uhyr\011\011=C3=7Fw=3Db=7Ft=3D\011uc =\015\012=0A\011h=80m\011 vb z bmp "
     "lzlx=0D=00 vg=FFi.k=0Apo =00m  d y yj.pfih=0Ams=0Du=0Ad=\015\012eux\011 "
     "ne=0A=00=A9rw js!w qohqg p=A9 wjj z=0Aru=80l\011n=0A=3D~fzdw!=0A  "
     "=0Agc=\015\012=7F=0Anqismkqjwvtx ob=A9r\011. =7F aa=7Fiu "
     "=A9=0A=3Dx=A9=0Aho\011zdo ciuab=0D~j=\015\012=7F\011 "
     "ya=0D=3D=0Dih!=C3ywqw\011!s=0Dd=7Fj=3D=80=A9! =A9=0D=00\011=0Dg=0D  mowq "
     "gmr=\015\012qe=80i  s d=3D=A9ws~x=0Dr  i a=0D b=0Dhk .m m=0A=0Dqpjr=FF =80p. "
     "j!=3D =00q=\015\012jfs \011l=A9 hkebrdj~c nnoh  zho=3D\011~  s  n =3D "
     "=0Adq=00p=0Dgq=0Ajv =0Ai =A9=\015\012=7Fs=00\011o =7F muhrryv\011=0D "
     "y=A9s=7Fu=0D",
     "=7Fc =FFj~x~y=0Dkm  rf.o\011=FF=FF!tei.=C3oh=0Dy "
     "uhyr\011\011=C3=7Fw=3Db=7Ft=3D\011uc =\015\012=0A\011h=80m\011 vb z bmp "
     "lzlx=0D=00 vg=FFi.k=0Apo =00m  d y yj.pfih=0Ams=0Du=0Ad=\015\012eux\011 "
     "ne=0A=00=A9rw js!w qohqg p=A9 wjj z=0Aru=80l\011n=0A=3D~fzdw!=0A  "
     "=0Agc=\015\012=7F=0Anqismkqjwvtx ob=A9r\011. =7F aa=7Fiu "
     "=A9=0A=3Dx=A9=0Aho\011zdo ciuab=0D~j=\015\012=7F\011 "
     "ya=0D=3D=0Dih!=C3ywqw\011!s=0Dd=7Fj=3D=80=A9! =A9=0D=00\011=0Dg=0D  mowq "
     "gmr=\015\012qe=80i  s d=3D=A9ws~x=0Dr  i a=0D b=0Dhk .m m=0A=0Dqpjr=FF =80p. "
     "j!=3D =00q=\015\012jfs \011l=A9 hkebrdj~c nnoh  zho=3D\011~  s  n =3D "
     "=0Adq=00p=0Dgq=0Ajv =0Ai =A9=\015\012=7Fs=00\011o =7F muhrryv\011=0D "
     "y=A9s=7Fu=0D"},
    {NULL, 41, 29,
     "u ~z.qpldd\015\012\015\012m~  =3D vt\011ur a\015\012\015\012 g zpm=C3n  "
     "s=00\011z",
     "u ~z.qpldd\015\012\015\012m~  =3D vt\011ur a\015\012\015\012 g zpm=C3n  "
     "s=00\011z",
     "u ~z.qpldd=0A=0Am~  =3D vt\011ur a=0A=0D g zpm=C3n  s=00\011z",
     "u ~z.qpldd=0A=0Am~  =3D vt\011ur a=0A=0D g zpm=C3n  s=00\011z"},
    {NULL, 100, 30,
     "t ka=A9=3D fgu.l~j=A9vnn=20\015\012!=7Fpw~ge=3Dfb   mcr  rw =A9\015\012r~  =C3 "
     "=3D=3D!\015\012~fbq.mw zx n f=20\015\012amqjgngy\015\012f!=A9j=C3c! =00 "
     "anc=3Dx=A9liojeg",
     "t ka=A9=3D fgu.l~j=A9vnn=20\015\012!=7Fpw~ge=3Dfb   mcr  rw =A9\015\012r~  =C3 "
     "=3D=3D!\015\012~fbq.mw zx n f=20\015\012amqjgngy\015\012f!=A9j=C3c! =00 "
     "anc=3Dx=A9liojeg",
     "t ka=A9=3D fgu.l~j=A9vnn =0D!=7Fpw~ge=3Dfb   mcr  rw =A9=0Dr~  =C3 "
     "=3D=3D!=\015\012=0D~fbq.mw zx n f =0Aamqjgngy=0Af!=A9j=C3c! =00 anc=3Dx=A9liojeg",
     "t ka=A9=3D fgu.l~j=A9vnn =0D!=7Fpw~ge=3Dfb   mcr  rw =A9=0Dr~  =C3 "
     "=3D=3D!=\015\012=0D~fbq.mw zx n f =0Aamqjgngy=0Af!=A9j=C3c! =00 "
     "anc=3Dx=A9liojeg"},
    {NULL, 161, 31,
     "tg   nw=FF\011lu\015\012=A9=20\015\012=3D\015\012y~  w\015\012!\011 u e=C3 "
     "l=00c. amok o =3D ~sl\015\012!d=C3d =3D=A9=80ce =3D=80i!=FF cmo "
     "y=20\015\012\015\012e\011 \011=3Dvq=00ht\011=FF\015\012!l\011cw njx xmq.ad  "
     "tcm\015\012=A9tcrig\015\012s  wn!q.   ~wol x=3D ry=00\015\012=00\015\012t =A9=3D "
     "w=A9p=FFfz.\015\012vu=7F  =3D=20",
     "tg   nw=FF\011lu\015\012=A9=20\015\012=3D\015\012y~  w\015\012!\011 u e=C3 "
     "l=00c. amok o =3D ~sl\015\012!d=C3d =3D=A9=80ce =3D=80i!=FF cmo "
     "y=20\015\012\015\012e\011 \011=3Dvq=00ht\011=FF\015\012!l\011cw njx xmq.ad  "
     "tcm\015\012=A9tcrig\015\012s  wn!q.   ~wol x=3D ry=00\015\012=00\015\012t =A9=3D "
     "w=A9p=FFfz.\015\012vu=7F  =3D=20",
     "tg   nw=FF\011lu=0D=A9 =0A=3D=0Ay~  w=0D!\011 u e=C3 l=00c. amok o =3D "
     "~sl=0A!d=\015\012=C3d =3D=A9=80ce =3D=80i!=FF cmo y =0D=0De\011 "
     "\011=3Dvq=00ht\011=FF=0A!l\011cw njx xmq=\015\012.ad  tcm=0A=A9tcrig=0Ds  wn!q.  "
     " ~wol x=3D ry=00=0A=00=0Dt =A9=3D w=A9p=FFf=\015\012z.=0Avu=7F  =3D=20",
     "tg   nw=FF\011lu=0D=A9 =0A=3D=0Ay~  w=0D!\011 u e=C3 l=00c. amok o =3D "
     "~sl=0A!d=\015\012=C3d =3D=A9=80ce =3D=80i!=FF cmo y =0D=0De\011 "
     "\011=3Dvq=00ht\011=FF=0A!l\011cw njx xmq=\015\012.ad  tcm=0A=A9tcrig=0Ds  wn!q.  "
     " ~wol x=3D ry=00=0A=00=0Dt =A9=3D w=A9p=FFf=\015\012z.=0Avu=7F  =3D=20"},
    {NULL, 224, 32,
     "!h=00a\015\012\015\012\015\012~o =A9k re\015\012j\015\012 cow\015\012=3D vk~d~ "
     "w\015\012~ r=C3w\015\012=A9\015\012 yorc zax~ "
     "~o=A9=7F=20\015\012w\015\012e!u=20\015\012 yq=3D l\015\012m=3Dun=3D ax "
     "erkyxhh=7F cf\015\012 gmu\015\012=00a=FFowcc w\011=3Dmvk  "
     "j.jwry=00~!ao=C3af=20\015\012=3D\015\012=A9b=3Dey ct wl\011iqgvm=3D c~\011~=A9i "
     "=80 zx =C3  ~!v=FFly=3D\011\011kfcv=3Dn\015\012=C3fwr.qj=80 =80 j=20\015\012 "
     "auh\015\012kq\011lznf\015\012lg! euwp\015\012bof=7F\011h",
     "!h=00a\015\012\015\012\015\012~o =A9k re\015\012j\015\012 cow\015\012=3D vk~d~ "
     "w\015\012~ r=C3w\015\012=A9\015\012 yorc zax~ "
     "~o=A9=7F=20\015\012w\015\012e!u=20\015\012 yq=3D l\015\012m=3Dun=3D ax "
     "erkyxhh=7F cf\015\012 gmu\015\012=00a=FFowcc w\011=3Dmvk  "
     "j.jwry=00~!ao=C3af=20\015\012=3D\015\012=A9b=3Dey ct wl\011iqgvm=3D c~\011~=A9i "
     "=80 zx =C3  ~!v=FFly=3D\011\011kfcv=3Dn\015\012=C3fwr.qj=80 =80 j=20\015\012 "
     "auh\015\012kq\011lznf\015\012lg! euwp\015\012bof=7F\011h",
     "!h=00a=0A=0A=0A~o =A9k re=0Aj=0D cow=0D=3D vk~d~ w=0A~ r=C3w=0A=A9=0A yorc "
     "=\015\012zax~ ~o=A9=7F =0Dw=0Ae!u =0D yq=3D l=0Dm=3Dun=3D ax erkyxhh=7F cf=0D "
     "gmu=0D=\015\012=00a=FFowcc w\011=3Dmvk  j.jwry=00~!ao=C3af =0A=3D=0D=A9b=3Dey ct "
     "wl\011iqgvm=3D =\015\012c~\011~=A9i =80 zx =C3  "
     "~!v=FFly=3D\011\011kfcv=3Dn=0D=C3fwr.qj=80 =80 j =0A "
     "auh=0Dk=\015\012q\011lznf=0Dlg! euwp=0Abof=7F\011h",
     "!h=00a=0A=0A=0A~o =A9k re=0Aj=0D cow=0D=3D vk~d~ w=0A~ r=C3w=0A=A9=0A yorc "
     "=\015\012zax~ ~o=A9=7F =0Dw=0Ae!u =0D yq=3D l=0Dm=3Dun=3D ax erkyxhh=7F cf=0D "
     "gmu=0D=\015\012=00a=FFowcc w\011=3Dmvk  j.jwry=00~!ao=C3af =0A=3D=0D=A9b=3Dey ct "
     "wl\011iqgvm=3D =\015\012c~\011~=A9i =80 zx =C3  "
     "~!v=FFly=3D\011\011kfcv=3Dn=0D=C3fwr.qj=80 =80 j =0A "
     "auh=0Dk=\015\012q\011lznf=0Dlg! euwp=0Abof=7F\011h"},
    {NULL, 289, 33,
     "~=09\015\012 !k mr! \011j\011ug x=3Dv=FF=A9 lt=3D  bn hdhv "
     "=00g\011l=3Dw~\015\012el.\015\012m gf =FF\011.h=A9pwsof\015\012=C3 "
     "=7F=7Fpex=C3\015\012vk.xg\011 =FF=3Db o=80av =FFb\015\012~ue=20\015\012z khb.=FF "
     "=7Fqe. =C3!n l=C3=FFnhz =3D=80j=7Fow.k\015\012=00!yl .=A9.r!qys=80z "
     ".!i=20\015\012fs pbuepy=80=00c=20\015\012er=7Fvai =FF\011=C3 =80 =C3r\015\012 "
     "wzx\015\012wu=FFfq .c\015\012\015\012m t=A9\015\012sg "
     "bfbcyomxiz=3D\015\012dgth=20\015\012t fh =00 =C3vy=00\015\012y\015\012 "
     "u=00n\011=C3f=7F  zbuf\015\012rb j\011xn =FFg=7Fmt  =00z =3D\011w "
     "xllf=20\015\012=20\015\012o\015\012b.zlbz",
     "~=09\015\012 !k mr! \011j\011ug x=3Dv=FF=A9 lt=3D  bn hdhv "
     "=00g\011l=3Dw~\015\012el.\015\012m gf =FF\011.h=A9pwsof\015\012=C3 "
     "=7F=7Fpex=C3\015\012vk.xg\011 =FF=3Db o=80av =FFb\015\012~ue=20\015\012z khb.=FF "
     "=7Fqe. =C3!n l=C3=FFnhz =3D=80j=7Fow.k\015\012=00!yl .=A9.r!qys=80z "
     ".!i=20\015\012fs pbuepy=80=00c=20\015\012er=7Fvai =FF\011=C3 =80 =C3r\015\012 "
     "wzx\015\012wu=FFfq .c\015\012\015\012m t=A9\015\012sg "
     "bfbcyomxiz=3D\015\012dgth=20\015\012t fh =00 =C3vy=00\015\012y\015\012 "
     "u=00n\011=C3f=7F  zbuf\015\012rb j\011xn =FFg=7Fmt  =00z =3D\011w "
     "xllf=20\015\012=20\015\012o\015\012b.zlbz",
     "~\011=0D !k mr! \011j\011ug x=3Dv=FF=A9 lt=3D  bn hdhv =00g\011l=3Dw~=0Del.=0Am "
     "gf =FF\011=\015\012.h=A9pwsof=0A=C3 =7F=7Fpex=C3=0Avk.xg\011 =FF=3Db o=80av "
     "=FFb=0D~ue =0Dz khb.=\015\012=FF =7Fqe. =C3!n l=C3=FFnhz =3D=80j=7Fow.k=0A=00!yl "
     ".=A9.r!qys=80z .!i =0Df=\015\012s pbuepy=80=00c =0Der=7Fvai =FF\011=C3 =80 "
     "=C3r=0D wzx=0Awu=FFfq .c=0D=0Dm t=\015\012=A9=0Dsg bfbcyomxiz=3D=0Adgth =0At fh "
     "=00 =C3vy=00=0Dy=0D u=00n\011=C3f=7F  zb=\015\012uf=0Arb j\011xn =FFg=7Fmt  =00z "
     "=3D\011w xllf =0D =0Ao=0Db.zlbz",
     "~\011=0D !k mr! \011j\011ug x=3Dv=FF=A9 lt=3D  bn hdhv =00g\011l=3Dw~=0Del.=0Am "
     "gf =FF\011=\015\012.h=A9pwsof=0A=C3 =7F=7Fpex=C3=0Avk.xg\011 =FF=3Db o=80av "
     "=FFb=0D~ue =0Dz khb.=\015\012=FF =7Fqe. =C3!n l=C3=FFnhz =3D=80j=7Fow.k=0A=00!yl "
     ".=A9.r!qys=80z .!i =0Df=\015\012s pbuepy=80=00c =0Der=7Fvai =FF\011=C3 =80 "
     "=C3r=0D wzx=0Awu=FFfq .c=0D=0Dm t=\015\012=A9=0Dsg bfbcyomxiz=3D=0Adgth =0At fh "
     "=00 =C3vy=00=0Dy=0D u=00n\011=C3f=7F  zb=\015\012uf=0Arb j\011xn =FFg=7Fmt  =00z "
     "=3D\011w xllf =0D =0Ao=0Db.zlbz"},
    {NULL, 356, 34,
     "~kdbz\011=7Ff=7Fjf\011=3D=FFkbf\011z=3D\011yg llr=00ai "
     "~u=C3kq.=3Dg=FF!\015\012\015\012\015\012.v cy tj=A9\015\012~\015\012\015\012ih "
     "g\015\012=3D=FF\011 !y.g\011ioa u d=00 "
     "qzl!eu=00\011.=00bv=FF\011cq=20\015\012l=00ppl=80c=09\015\012a~=3D=FFb=A9xodof="
     "80  pzs  !e~oy =FF=C3. =A9  se =FF ~. qfvohtw\015\012 ifjqs=3D=20\015\012=C3dsxv "
     "g\015\012\011hl=20\015\012\015\012yu\011 =7Fuxjc=A9=3Dn =7F =00rkwo.=3D=3D "
     "=7Fr.\015\012=3D=FFlsrb=3D=00\015\012 r=20\015\012=FFwg "
     "c\015\012w=00=7Fp\015\012=3D~ =A9njx=00\015\012wpj mijx pdl\011u "
     "c=3D\015\012=FFi\015\012e\015\012!jjd=00bde=A9ljfrm=FFe!o=A9kd=C3 c.\011 "
     "=FF=7Fq=FFjxabfx rsy=A9=FF=3D=00tv\015\012\011w=3Dwy=C3~dxqrj\015\012\015\012 "
     "q=3Dz=80!=20\015\012htu ue=20\015\012=A9=00m  s=3D bby\015\012\011u\015\012x",
     "~kdbz\011=7Ff=7Fjf\011=3D=FFkbf\011z=3D\011yg llr=00ai "
     "~u=C3kq.=3Dg=FF!\015\012\015\012\015\012.v cy tj=A9\015\012~\015\012\015\012ih "
     "g\015\012=3D=FF\011 !y.g\011ioa u d=00 "
     "qzl!eu=00\011.=00bv=FF\011cq=20\015\012l=00ppl=80c=09\015\012a~=3D=FFb=A9xodof="
     "80  pzs  !e~oy =FF=C3. =A9  se =FF ~. qfvohtw\015\012 ifjqs=3D=20\015\012=C3dsxv "
     "g\015\012\011hl=20\015\012\015\012yu\011 =7Fuxjc=A9=3Dn =7F =00rkwo.=3D=3D "
     "=7Fr.\015\012=3D=FFlsrb=3D=00\015\012 r=20\015\012=FFwg "
     "c\015\012w=00=7Fp\015\012=3D~ =A9njx=00\015\012wpj mijx pdl\011u "
     "c=3D\015\012=FFi\015\012e\015\012!jjd=00bde=A9ljfrm=FFe!o=A9kd=C3 c.\011 "
     "=FF=7Fq=FFjxabfx rsy=A9=FF=3D=00tv\015\012\011w=3Dwy=C3~dxqrj\015\012\015\012 "
     "q=3Dz=80!=20\015\012htu ue=20\015\012=A9=00m  s=3D bby\015\012\011u\015\012x",
     "~kdbz\011=7Ff=7Fjf\011=3D=FFkbf\011z=3D\011yg llr=00ai "
     "~u=C3kq.=3Dg=FF!=0A=0D=0D.v cy t=\015\012j=A9=0D~=0A=0Aih g=0D=3D=FF\011 "
     "!y.g\011ioa u d=00 qzl!eu=00\011.=00bv=FF\011cq "
     "=0Al=00=\015\012ppl=80c\011=0Da~=3D=FFb=A9xodof=80  pzs  !e~oy =FF=C3. =A9  se "
     "=FF ~. qfvohtw=\015\012=0A ifjqs=3D =0A=C3dsxv g=0A\011hl =0A=0Ayu\011 "
     "=7Fuxjc=A9=3Dn =7F =00rkwo.=3D=3D=\015\012 =7Fr.=0A=3D=FFlsrb=3D=00=0D r "
     "=0A=FFwg c=0Aw=00=7Fp=0A=3D~ =A9njx=00=0Dwpj=\015\012 mijx pdl\011u "
     "c=3D=0A=FFi=0De=0A!jjd=00bde=A9ljfrm=FFe!o=A9kd=C3 c.\011 "
     "=FF=7Fq=\015\012=FFjxabfx rsy=A9=FF=3D=00tv=0D\011w=3Dwy=C3~dxqrj=0A=0A "
     "q=3Dz=80! =0Ahtu ue =\015\012=0A=A9=00m  s=3D bby=0D\011u=0Ax",
     "~kdbz\011=7Ff=7Fjf\011=3D=FFkbf\011z=3D\011yg llr=00ai "
     "~u=C3kq.=3Dg=FF!=0A=0D=0D.v cy t=\015\012j=A9=0D~=0A=0Aih g=0D=3D=FF\011 "
     "!y.g\011ioa u d=00 qzl!eu=00\011.=00bv=FF\011cq "
     "=0Al=00=\015\012ppl=80c\011=0Da~=3D=FFb=A9xodof=80  pzs  !e~oy =FF=C3. =A9  se "
     "=FF ~. qfvohtw=\015\012=0A ifjqs=3D =0A=C3dsxv g=0A\011hl =0A=0Ayu\011 "
     "=7Fuxjc=A9=3Dn =7F =00rkwo.=3D=3D=\015\012 =7Fr.=0A=3D=FFlsrb=3D=00=0D r "
     "=0A=FFwg c=0Aw=00=7Fp=0A=3D~ =A9njx=00=0Dwpj=\015\012 mijx pdl\011u "
     "c=3D=0A=FFi=0De=0A!jjd=00bde=A9ljfrm=FFe!o=A9kd=C3 c.\011 "
     "=FF=7Fq=\015\012=FFjxabfx rsy=A9=FF=3D=00tv=0D\011w=3Dwy=C3~dxqrj=0A=0A "
     "q=3Dz=80! =0Ahtu ue =\015\012=0A=A9=00m  s=3D bby=0D\011u=0Ax"},
    {NULL, 25, 35, "rlu  h\015\012=FFya\011i=7Fq v w\015\012j=00ae d",
     "rlu  h\015\012=FFya\011i=7Fq v w\015\012j=00ae d",
     "rlu  h=0D=FFya\011i=7Fq v w=0Dj=00ae d",
     "rlu  h=0D=FFya\011i=7Fq v w=0Dj=00ae d"},
    {NULL, 96, 36,
     "q\015\012\015\012co dt qm  h..c\011=C3e abavzy=80=A9af\015\012 coq\011\011  "
     "z=80w p=3Dz =C3=3Dws h\015\012g=FF rx\011 m=00 i\015\012 ~\011j .\011i "
     "=7F=FFpiav blsg\015\012ka\015\012m.=C3t",
     "q\015\012\015\012co dt qm  h..c\011=C3e abavzy=80=A9af\015\012 coq\011\011  "
     "z=80w p=3Dz =C3=3Dws h\015\012g=FF rx\011 m=00 i\015\012 ~\011j .\011i "
     "=7F=FFpiav blsg\015\012ka\015\012m.=C3t",
     "q=0D=0Dco dt qm  h..c\011=C3e abavzy=80=A9af=0A coq\011\011  z=80w p=3Dz "
     "=C3=3Dws h=\015\012=0Dg=FF rx\011 m=00 i=0A ~\011j .\011i =7F=FFpiav "
     "blsg=0D=0Aka=0Am.=C3t",
     "q=0D=0Dco dt qm  h..c\011=C3e abavzy=80=A9af=0A coq\011\011  z=80w p=3Dz "
     "=C3=3Dws h=\015\012=0Dg=FF rx\011 m=00 i=0A ~\011j .\011i =7F=FFpiav "
     "blsg=0D=0Aka=0Am.=C3t"},
    {NULL, 169, 37,
     "q\015\012e ve=00mg =3Digy=20\015\012z=7F yo =FF=80n=7F=3Dkxug=FF=00~dc "
     "sxp=20\015\012=3Dg =FF\015\012!jt\011=C3=00!uc pk w "
     "=A9fsj=09\015\012=00l=80=3Ds=3Dy d=C3zl.g=3Dsb.a=FFvfytth=7F =C3e\011=C3\015\012 "
     "=00\015\012 =A9sp=C3\011f=FF=20\015\012wwk q c\015\012h!=7F h=3Dmn\015\012a "
     "di=3D=C3\015\012cq=7Fju.! fj=7Fr=80=3Dv =20\015\012w qs cw\011dzs =80",
     "q\015\012e ve=00mg =3Digy=20\015\012z=7F yo =FF=80n=7F=3Dkxug=FF=00~dc "
     "sxp=20\015\012=3Dg =FF\015\012!jt\011=C3=00!uc pk w "
     "=A9fsj=09\015\012=00l=80=3Ds=3Dy d=C3zl.g=3Dsb.a=FFvfytth=7F =C3e\011=C3\015\012 "
     "=00\015\012 =A9sp=C3\011f=FF=20\015\012wwk q c\015\012h!=7F h=3Dmn\015\012a "
     "di=3D=C3\015\012cq=7Fju.! fj=7Fr=80=3Dv =20\015\012w qs cw\011dzs =80",
     "q=0Ae ve=00mg =3Digy =0Az=7F yo =FF=80n=7F=3Dkxug=FF=00~dc sxp =0A=3Dg "
     "=FF=\015\012=0A!jt\011=C3=00!uc pk w =A9fsj\011=0A=00l=80=3Ds=3Dy "
     "d=C3zl.g=3Dsb.a=FFvfytth=7F=\015\012 =C3e\011=C3=0D =00=0D =A9sp=C3\011f=FF "
     "=0Awwk q c=0Ah!=7F h=3Dmn=0Da di=3D=C3=0D=\015\012cq=7Fju.! fj=7Fr=80=3Dv  =0Dw "
     "qs cw\011dzs =80",
     "q=0Ae ve=00mg =3Digy =0Az=7F yo =FF=80n=7F=3Dkxug=FF=00~dc sxp =0A=3Dg "
     "=FF=\015\012=0A!jt\011=C3=00!uc pk w =A9fsj\011=0A=00l=80=3Ds=3Dy "
     "d=C3zl.g=3Dsb.a=FFvfytth=7F=\015\012 =C3e\011=C3=0D =00=0D =A9sp=C3\011f=FF "
     "=0Awwk q c=0Ah!=7F h=3Dmn=0Da di=3D=C3=0D=\015\012cq=7Fju.! fj=7Fr=80=3Dv  =0Dw "
     "qs cw\011dzs =80"},
    {NULL, 244, 38,
     "=3Dpwcc lgj=A9t m=3D=80g=A9 !~=FFcxsg=3Dgxwqg=09\015\012h~p  =7Fd "
     "e\011eoi=C3gvxyb\011  =FFlzdp\015\012=C3\011q "
     "jfpumia!upk\015\012=7Fkoiq=FFk.=3Dtngay  w!xmrr "
     "=7F!o\011bl\015\012=A9=C3hh\015\012hy b=FFf =09\015\012\015\012c "
     "vcd=00nr\011cn=80 =C3wr.\011m dl~=3D ~izq=80ya=3Dkhkke=C3=7Fqn=A9t =80 "
     "=A9\015\012=7F !=3Dzed\011c ~z=FF!y\015\012aw~t\015\012poip=3Djja\011  "
     "dkrnoi=3D.s=A9=80\011=80e v c.~nf\015\012wbq=80p=A9zyd\015\012r g\011g =20",
     "=3Dpwcc lgj=A9t m=3D=80g=A9 !~=FFcxsg=3Dgxwqg=09\015\012h~p  =7Fd "
     "e\011eoi=C3gvxyb\011  =FFlzdp\015\012=C3\011q "
     "jfpumia!upk\015\012=7Fkoiq=FFk.=3Dtngay  w!xmrr "
     "=7F!o\011bl\015\012=A9=C3hh\015\012hy b=FFf =09\015\012\015\012c "
     "vcd=00nr\011cn=80 =C3wr.\011m dl~=3D ~izq=80ya=3Dkhkke=C3=7Fqn=A9t =80 "
     "=A9\015\012=7F !=3Dzed\011c ~z=FF!y\015\012aw~t\015\012poip=3Djja\011  "
     "dkrnoi=3D.s=A9=80\011=80e v c.~nf\015\012wbq=80p=A9zyd\015\012r g\011g =20",
     "=3Dpwcc lgj=A9t m=3D=80g=A9 !~=FFcxsg=3Dgxwqg\011=0Ah~p  =7Fd "
     "e\011eoi=C3gvxyb\011  =\015\012=FFlzdp=0A=C3\011q "
     "jfpumia!upk=0A=7Fkoiq=FFk.=3Dtngay  w!xmrr "
     "=7F!o\011bl=0D=0A=\015\012=A9=C3hh=0Ahy b=FFf \011=0D=0Dc vcd=00nr\011cn=80 "
     "=C3wr.\011m dl~=3D ~izq=80ya=3Dkhk=\015\012ke=C3=7Fqn=A9t =80 =A9=0D=7F "
     "!=3Dzed\011c ~z=FF!y=0Aaw~t=0Dpoip=3Djja\011  dkrnoi=\015\012=3D.s=A9=80\011=80e "
     "v c.~nf=0Awbq=80p=A9zyd=0Ar g\011g =20",
     "=3Dpwcc lgj=A9t m=3D=80g=A9 !~=FFcxsg=3Dgxwqg\011=0Ah~p  =7Fd "
     "e\011eoi=C3gvxyb\011  =\015\012=FFlzdp=0A=C3\011q "
     "jfpumia!upk=0A=7Fkoiq=FFk.=3Dtngay  w!xmrr "
     "=7F!o\011bl=0D=0A=\015\012=A9=C3hh=0Ahy b=FFf \011=0D=0Dc vcd=00nr\011cn=80 "
     "=C3wr.\011m dl~=3D ~izq=80ya=3Dkhk=\015\012ke=C3=7Fqn=A9t =80 =A9=0D=7F "
     "!=3Dzed\011c ~z=FF!y=0Aaw~t=0Dpoip=3Djja\011  dkrnoi=\015\012=3D.s=A9=80\011=80e "
     "v c.~nf=0Awbq=80p=A9zyd=0Ar g\011g =20"},
    {NULL, 321, 39,
     "=3Dq\015\012 jbc=FF\015\012=3Dw ~gmbv=00 m\011 uo=A9k=80mvmh=7Fc=C3 c "
     "m~q\015\012v  bs\011u =20\015\012 ypn=80.\015\012uxasu qk "
     "=00=7F\015\012ulu=FF=20\015\012=00~u.zbj  om rvxk n.\015\012c a.dhhh y "
     "i=FFm\011pye \011..=00\011.\011nl=20\015\012y=3D=20\015\012=80. =A9k.w  qxoi=3D "
     "fze\015\012=A9 t=C3twsxi cattyx=C3=00j=80 w=00  ilq\011=20\015\012a "
     "r=00ape=3D=3D d =FFi=00 awh c~r=A9t=3Dfjbm=00uat!xl=FFyn ubptu "
     "w\015\012f.h=09\015\012b .=00=3Dpsz=00i=20\015\012pn!=7F=7Fi=7Fvsq i qj "
     "m\015\012\015\012=7F\011miqii=00=FFxth f=20\015\012 "
     "hgu=3D=80s=00hfo=20\015\012=00=A9  j\015\012qj~hm ul=C3m\015\012    t\011crb",
     "=3Dq\015\012 jbc=FF\015\012=3Dw ~gmbv=00 m\011 uo=A9k=80mvmh=7Fc=C3 c "
     "m~q\015\012v  bs\011u =20\015\012 ypn=80.\015\012uxasu qk "
     "=00=7F\015\012ulu=FF=20\015\012=00~u.zbj  om rvxk n.\015\012c a.dhhh y "
     "i=FFm\011pye \011..=00\011.\011nl=20\015\012y=3D=20\015\012=80. =A9k.w  qxoi=3D "
     "fze\015\012=A9 t=C3twsxi cattyx=C3=00j=80 w=00  ilq\011=20\015\012a "
     "r=00ape=3D=3D d =FFi=00 awh c~r=A9t=3Dfjbm=00uat!xl=FFyn ubptu "
     "w\015\012f.h=09\015\012b .=00=3Dpsz=00i=20\015\012pn!=7F=7Fi=7Fvsq i qj "
     "m\015\012\015\012=7F\011miqii=00=FFxth f=20\015\012 "
     "hgu=3D=80s=00hfo=20\015\012=00=A9  j\015\012qj~hm ul=C3m\015\012    t\011crb",
     "=3Dq=0A jbc=FF=0A=3Dw ~gmbv=00 m\011 uo=A9k=80mvmh=7Fc=C3 c m~q=0Dv  bs\011u  "
     "=0D=\015\012 ypn=80.=0Duxasu qk =00=7F=0Aulu=FF =0A=00~u.zbj  om rvxk n.=0Ac "
     "a.dhhh y i=\015\012=FFm\011pye \011..=00\011.\011nl =0Dy=3D =0D=80. =A9k.w  "
     "qxoi=3D fze=0A=A9 t=C3twsxi ca=\015\012ttyx=C3=00j=80 w=00  ilq\011 =0Aa "
     "r=00ape=3D=3D d =FFi=00 awh c~r=A9t=3Dfjbm=\015\012=00uat!xl=FFyn ubptu "
     "w=0Df.h\011=0D=0Ab .=00=3Dpsz=00i =0Dpn!=7F=7Fi=7Fvsq i q=\015\012j "
     "m=0A=0A=7F\011miqii=00=FFxth f =0A hgu=3D=80s=00hfo =0D=00=A9  j=0Dqj~hm "
     "ul=\015\012=C3m=0D    t\011crb",
     "=3Dq=0A jbc=FF=0A=3Dw ~gmbv=00 m\011 uo=A9k=80mvmh=7Fc=C3 c m~q=0Dv  bs\011u  "
     "=0D=\015\012 ypn=80.=0Duxasu qk =00=7F=0Aulu=FF =0A=00~u.zbj  om rvxk n.=0Ac "
     "a.dhhh y i=\015\012=FFm\011pye \011..=00\011.\011nl =0Dy=3D =0D=80. =A9k.w  "
     "qxoi=3D fze=0A=A9 t=C3twsxi ca=\015\012ttyx=C3=00j=80 w=00  ilq\011 =0Aa "
     "r=00ape=3D=3D d =FFi=00 awh c~r=A9t=3Dfjbm=\015\012=00uat!xl=FFyn ubptu "
     "w=0Df.h\011=0D=0Ab .=00=3Dpsz=00i =0Dpn!=7F=7Fi=7Fvsq i q=\015\012j "
     "m=0A=0A=7F\011miqii=00=FFxth f =0A hgu=3D=80s=00hfo =0D=00=A9  j=0Dqj~hm "
     "ul=\015\012=C3m=0D    t\011crb"},
    {NULL, 0, 40, "", "", "", ""},
};
