/* What Go's fmt does with the cases in scan_test.go: how many operands each
 * scan fills, the error it returns and what every operand holds afterwards.
 * Regenerate it with tools/gen-scan.sh rather than editing it.
 *
 * Copyright 2010 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

static const ScanCase scan_cases[] = {
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("T\012"), 0, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("T\012"), 1, 1, 1, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("F\012"), 2, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("F\012"), 3, 1, 1, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("21\012"), 4, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("21\012"), 5, 1, 1, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2_1\012"), 6, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2_1\012"), 7, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0\012"), 8, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0\012"), 9, 1, 1, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("000\012"), 10, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("000\012"), 11, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0x10\012"), 12, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0x10\012"), 13, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0x_1_0\012"), 14, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0x_1_0\012"), 15, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-0x10\012"), 16, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-0x10\012"), 17, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0377\012"), 18, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0377\012"), 19, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0_3_7_7\012"), 20, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0_3_7_7\012"), 21, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0o377\012"), 22, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0o377\012"), 23, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0o_3_7_7\012"), 24, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0o_3_7_7\012"), 25, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-0377\012"), 26, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-0377\012"), 27, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-0o377\012"), 28, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-0o377\012"), 29, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0\012"), 30, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0\012"), 31, 1, 1, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("000\012"), 32, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("000\012"), 33, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0x10\012"), 34, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0x10\012"), 35, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0377\012"), 36, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0377\012"), 37, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("22\012"), 38, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("22\012"), 39, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("23\012"), 40, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("23\012"), 41, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("24\012"), 42, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("24\012"), 43, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("25\012"), 44, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("25\012"), 45, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("127\012"), 46, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("127\012"), 47, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-21\012"), 48, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-21\012"), 49, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-22\012"), 50, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-22\012"), 51, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-23\012"), 52, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-23\012"), 53, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-24\012"), 54, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-24\012"), 55, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-25\012"), 56, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-25\012"), 57, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-128\012"), 58, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-128\012"), 59, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("+21\012"), 60, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("+21\012"), 61, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("+22\012"), 62, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("+22\012"), 63, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("+23\012"), 64, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("+23\012"), 65, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("+24\012"), 66, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("+24\012"), 67, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("+25\012"), 68, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("+25\012"), 69, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("+127\012"), 70, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("+127\012"), 71, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("26\012"), 72, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("26\012"), 73, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("27\012"), 74, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("27\012"), 75, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("28\012"), 76, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("28\012"), 77, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("29\012"), 78, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("29\012"), 79, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("30\012"), 80, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("30\012"), 81, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("31\012"), 82, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("31\012"), 83, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("255\012"), 84, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("255\012"), 85, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("32767\012"), 86, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("32767\012"), 87, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3\012"), 88, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3\012"), 89, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3e1\012"), 90, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3e1\012"), 91, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3e2\012"), 92, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3e2\012"), 93, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p2\012"), 94, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p2\012"), 95, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p+2\012"), 96, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p+2\012"), 97, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p+66\012"), 98, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p+66\012"), 99, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p-66\012"), 100, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.3p-66\012"), 101, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0x2.3p-66\012"), 102, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0x2.3p-66\012"), 103, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2_3.4_5\012"), 104, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2_3.4_5\012"), 105, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2.35\012"), 106, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2.35\012"), 107, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2345678\012"), 108, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2345678\012"), 109, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("(3.4e1-2i)\012"), 110, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("(3.4e1-2i)\012"), 111, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-3.45e1-3i\012"), 112, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-3.45e1-3i\012"), 113, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-.45e1-1e2i\012"), 114, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-.45e1-1e2i\012"), 115, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-.4_5e1-1E2i\012"), 116, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-.4_5e1-1E2i\012"), 117, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("0x1.0p1+0x1.0P2i\012"), 118, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("0x1.0p1+0x1.0P2i\012"), 119, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-0x1p1-0x1p2i\012"), 120, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-0x1p1-0x1p2i\012"), 121, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-0x1ep-1-0x1p2i\012"), 122, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-0x1ep-1-0x1p2i\012"), 123, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-0x1_Ep-1-0x1p0_2i\012"), 124, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("-0x1_Ep-1-0x1p0_2i\012"), 125, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("hello\012"), 126, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("hello\012"), 127, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("hello\015\012"), 128, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("hello\015\012"), 129, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("27\015\012"), 130, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("27\015\012"), 131, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("true\012"), 132, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("true\012"), 133, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("F\012"), 134, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("F\012"), 135, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("101\012"), 136, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("101\012"), 137, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("102\012"), 138, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("102\012"), 139, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("103\012"), 140, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("103\012"), 141, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("104\012"), 142, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("104\012"), 143, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("105\012"), 144, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("105\012"), 145, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("106\012"), 146, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("106\012"), 147, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("107\012"), 148, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("107\012"), 149, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("108\012"), 150, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("108\012"), 151, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("109\012"), 152, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("109\012"), 153, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("110\012"), 154, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("110\012"), 155, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("111\012"), 156, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("111\012"), 157, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("112\012"), 158, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("112\012"), 159, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("113\012"), 160, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("113\012"), 161, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("114\012"), 162, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("114\012"), 163, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("115\012"), 164, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("115\012"), 165, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("  vvv "), 166, 1, 1, BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("  vvv "), 167, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT(" 1234hello"), 168, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT(" 1234hello"), 169, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("2147483648\012"), 170, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("2147483648\012"), 171, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("128"), 172, 1, 0,
     BURROW_S_INIT("integer overflow on token 128")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("32768"), 173, 1, 0,
     BURROW_S_INIT("integer overflow on token 32768")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-129"), 174, 1, 0,
     BURROW_S_INIT("integer overflow on token -129")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("-32769"), 175, 1, 0,
     BURROW_S_INIT("integer overflow on token -32769")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("256"), 176, 1, 0,
     BURROW_S_INIT("unsigned integer overflow on token 256")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("65536"), 177, 1, 0,
     BURROW_S_INIT("unsigned integer overflow on token 65536")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("1e100"), 178, 1, 0,
     BURROW_S_INIT("strconv.ParseFloat: parsing \"1e100\": value out of range")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("1e500"), 179, 1, 0,
     BURROW_S_INIT("strconv.ParseFloat: parsing \"1e500\": value out of range")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("(1e100+0i)"), 180, 1, 0,
     BURROW_S_INIT("strconv.ParseFloat: parsing \"1e100\": value out of range")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("(1+1e100i)"), 181, 1, 0,
     BURROW_S_INIT("strconv.ParseFloat: parsing \"+1e100\": value out of range")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("(1-1e500i)"), 182, 1, 0,
     BURROW_S_INIT("strconv.ParseFloat: parsing \"-1e500\": value out of range")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("TRUE\012"), 183, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%t"), BURROW_S_INIT("false\012"), 184, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("-71\012"), 185, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("-7_1\012"), 186, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0b111\012"), 187, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0b_1_1_1\012"), 188, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0377\012"), 189, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0_3_7_7\012"), 190, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0o377\012"), 191, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0o_3_7_7\012"), 192, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0x44\012"), 193, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0x_4_4\012"), 194, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("72\012"), 195, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("a\012"), 196, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("\345\201\262\012"), 197, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("\341\210\264\012"), 198, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("73\012"), 199, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("+74\012"), 200, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("75\012"), 201, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("76\012"), 202, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%b"), BURROW_S_INIT("1001001\012"), 203, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%o"), BURROW_S_INIT("075\012"), 204, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("a75\012"), 205, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("71\012"), 206, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("72\012"), 207, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("7_2\012"), 208, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("73\012"), 209, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("74\012"), 210, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("75\012"), 211, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("76\012"), 212, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("77\012"), 213, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%b"), BURROW_S_INIT("1001001\012"), 214, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%b"), BURROW_S_INIT("100_1001\012"), 215, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%o"), BURROW_S_INIT("075\012"), 216, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%o"), BURROW_S_INIT("07_5\012"), 217, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("a75\012"), 218, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("A75\012"), 219, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("A7_5\012"), 220, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%U"), BURROW_S_INIT("U+1234\012"), 221, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%U"), BURROW_S_INIT("U+4567\012"), 222, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%e"), BURROW_S_INIT("2.3\012"), 223, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%E"), BURROW_S_INIT("2.3e1\012"), 224, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%f"), BURROW_S_INIT("2.3e2\012"), 225, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%g"), BURROW_S_INIT("2.3p2\012"), 226, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%G"), BURROW_S_INIT("2.3p+2\012"), 227, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("2.3p+66\012"), 228, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%f"), BURROW_S_INIT("2.3p-66\012"), 229, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%G"), BURROW_S_INIT("0x2.3p-66\012"), 230, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%E"), BURROW_S_INIT("2_3.4_5\012"), 231, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%s"), BURROW_S_INIT("using-%s\012"), 232, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("7573696e672d2578\012"), 233, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%X"), BURROW_S_INIT("7573696E672D2558\012"), 234, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%q"),
     BURROW_S_INIT("\"quoted\\twith\\\\do\\u0075bl\\x65s\"\012"), 235, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%q"), BURROW_S_INIT("`quoted with backs`\012"), 236, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%s"), BURROW_S_INIT("bytes-%s\012"), 237, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("62797465732d2578\012"), 238, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%X"), BURROW_S_INIT("62797465732D2558\012"), 239, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%q"),
     BURROW_S_INIT("\"bytes\\rwith\\vdo\\u0075bl\\x65s\"\012"), 240, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%q"), BURROW_S_INIT("`bytes with backs`\012"), 241, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v\012"), BURROW_S_INIT("true\012"), 242, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%t\012"), BURROW_S_INIT("F\012"), 243, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("101\012"), 244, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("\304\201\012"), 245, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%o"), BURROW_S_INIT("0146\012"), 246, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("103\012"), 247, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("104\012"), 248, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("105\012"), 249, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("106\012"), 250, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("107\012"), 251, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("108\012"), 252, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("6D\012"), 253, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%o"), BURROW_S_INIT("0156\012"), 254, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("111\012"), 255, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("112\012"), 256, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("113\012"), 257, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%s"), BURROW_S_INIT("114\012"), 258, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%q"), BURROW_S_INIT("\"1155\"\012"), 259, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%g"), BURROW_S_INIT("116e1\012"), 260, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%g"), BURROW_S_INIT("-11.7e+1"), 261, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%g"), BURROW_S_INIT("11+6e1i\012"), 262, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%g"), BURROW_S_INIT("-11.+7e+1i"), 263, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("here is\011the value:%d"),
     BURROW_S_INIT("here is   the\011value:118\012"), 264, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%% %%:%d"), BURROW_S_INIT("% %:119\012"), 265, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d%%"), BURROW_S_INIT("42%"), 266, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("FFFFFFFF\012"), 267, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%s"), BURROW_S_INIT("  sss "), 268, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%2s"), BURROW_S_INIT("sssss"), 269, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012"), BURROW_S_INIT("27\012"), 270, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012"), BURROW_S_INIT("28 \012"), 271, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0"), 272, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("0"), 273, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT(" "), 274, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("\011"), 275, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("\012"), 276, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d%%"), BURROW_S_INIT("23%\012"), 277, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%%%d"), BURROW_S_INIT("%23\012"), 278, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("27"), 279, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("27 "), 280, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT(" 27"), 281, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT(" 27 "), 282, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%d"), BURROW_S_INIT("X27"), 283, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%d"), BURROW_S_INIT("X27 "), 284, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%d"), BURROW_S_INIT("X 27"), 285, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%d"), BURROW_S_INIT("X 27 "), 286, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X %d"), BURROW_S_INIT("X27"), 287, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %d"), BURROW_S_INIT("X27 "), 288, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %d"), BURROW_S_INIT("X 27"), 289, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X %d"), BURROW_S_INIT("X 27 "), 290, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%dX"), BURROW_S_INIT("27X"), 291, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%dX"), BURROW_S_INIT("27 X"), 292, 1, 1,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("%dX"), BURROW_S_INIT(" 27X"), 293, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%dX"), BURROW_S_INIT(" 27 X"), 294, 1, 1,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("%d X"), BURROW_S_INIT("27X"), 295, 1, 1,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("%d X"), BURROW_S_INIT("27 X"), 296, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d X"), BURROW_S_INIT(" 27X"), 297, 1, 1,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("%d X"), BURROW_S_INIT(" 27 X"), 298, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X %d X"), BURROW_S_INIT("X27X"), 299, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %d X"), BURROW_S_INIT("X27 X"), 300, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %d X"), BURROW_S_INIT("X 27X"), 301, 1, 1,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %d X"), BURROW_S_INIT("X 27 X"), 302, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X %s X"), BURROW_S_INIT("X27X"), 303, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %s X"), BURROW_S_INIT("X27 X"), 304, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %s X"), BURROW_S_INIT("X 27X"), 305, 1, 1,
     BURROW_S_INIT("unexpected EOF")},
    {SM_SCANF, BURROW_S_INIT("X %s X"), BURROW_S_INIT("X 27 X"), 306, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%sX"), BURROW_S_INIT("X27X"), 307, 1, 1,
     BURROW_S_INIT("unexpected EOF")},
    {SM_SCANF, BURROW_S_INIT("X%sX"), BURROW_S_INIT("X27 X"), 308, 1, 1,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%sX"), BURROW_S_INIT("X 27X"), 309, 1, 1,
     BURROW_S_INIT("unexpected EOF")},
    {SM_SCANF, BURROW_S_INIT("X%sX"), BURROW_S_INIT("X 27 X"), 310, 1, 1,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%s"), BURROW_S_INIT("X27"), 311, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%s"), BURROW_S_INIT("X27 "), 312, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%s"), BURROW_S_INIT("X 27"), 313, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%s"), BURROW_S_INIT("X 27 "), 314, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT("X27X"), 315, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT("X27 X"), 316, 1, 1,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT("X 27X"), 317, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT("X 27 X"), 318, 1, 1,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT("X27X"), 319, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT("X27X "), 320, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT(" X27X"), 321, 1, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%dX"), BURROW_S_INIT(" X27X "), 322, 1, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%dX\012"), BURROW_S_INIT("X27X"), 323, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX \012"), BURROW_S_INIT("X27X "), 324, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX\012"), BURROW_S_INIT("X27X\012"), 325, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX\012"), BURROW_S_INIT("X27X \012"), 326, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX \012"), BURROW_S_INIT("X27X"), 327, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX \012"), BURROW_S_INIT("X27X "), 328, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX \012"), BURROW_S_INIT("X27X\012"), 329, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX \012"), BURROW_S_INIT("X27X \012"), 330, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%c"), BURROW_S_INIT("X\012"), 331, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%c"), BURROW_S_INIT("X \012"), 332, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X %c"), BURROW_S_INIT("X!"), 333, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT("X %c"), BURROW_S_INIT("X\012"), 334, 1, 0,
     BURROW_S_INIT("newline in input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X %c"), BURROW_S_INIT("X !"), 335, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X %c"), BURROW_S_INIT("X \012"), 336, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT(" X%dX"), BURROW_S_INIT("X27X"), 337, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT(" X%dX"), BURROW_S_INIT("X27X "), 338, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT(" X%dX"), BURROW_S_INIT(" X27X"), 339, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT(" X%dX"), BURROW_S_INIT(" X27X "), 340, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX "), BURROW_S_INIT("X27X"), 341, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX "), BURROW_S_INIT("X27X "), 342, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("X%dX "), BURROW_S_INIT(" X27X"), 343, 1, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("X%dX "), BURROW_S_INIT(" X27X "), 344, 1, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT(" X%dX "), BURROW_S_INIT("X27X"), 345, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT(" X%dX "), BURROW_S_INIT("X27X "), 346, 1, 0,
     BURROW_S_INIT("expected space in input to match format")},
    {SM_SCANF, BURROW_S_INIT(" X%dX "), BURROW_S_INIT(" X27X"), 347, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT(" X%dX "), BURROW_S_INIT(" X27X "), 348, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012X"), BURROW_S_INIT("27\012X"), 349, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%dX\012 X"), BURROW_S_INIT("27X\012 X"), 350, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT(""), BURROW_S_INIT(""), 351, 0, 0, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d"), BURROW_S_INIT("23"), 351, 1, 1, BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%2s%3s"), BURROW_S_INIT("22333"), 352, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%2d%3d"), BURROW_S_INIT("44555"), 354, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%2d.%3d"), BURROW_S_INIT("66.777"), 356, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d, %d"), BURROW_S_INIT("23, 18"), 358, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%3d22%3d"), BURROW_S_INIT("33322333"), 360, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%6vX=%3fY"), BURROW_S_INIT("3+2iX=2.5Y"), 362, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d%s"), BURROW_S_INIT("123abc"), 364, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%c%c%c"), BURROW_S_INIT("2\345\203\202X"), 366, 3, 3,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%5s%d"), BURROW_S_INIT(" 1234567 "), 369, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%5s%d"), BURROW_S_INIT(" 12 34 567 "), 371, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%e%f"), BURROW_S_INIT("eefffff"), 373, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%4v%s"), BURROW_S_INIT("12abcd"), 375, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%t"), BURROW_S_INIT("23 18"), 377, 1, 0,
     BURROW_S_INIT("bad verb '%t' for integer")},
    {SM_SCANF, BURROW_S_INIT("%d %d %d"), BURROW_S_INIT("23 18"), 378, 2, 2,
     BURROW_S_INIT("too few operands for format '%d'")},
    {SM_SCANF, BURROW_S_INIT("%d %d"), BURROW_S_INIT("23 18 27"), 380, 3, 2,
     BURROW_S_INIT("too many operands")},
    {SM_SCANF, BURROW_S_INIT("%c"), BURROW_S_INIT("\304\200"), 383, 1, 0,
     BURROW_S_INIT("overflow on character value \304\200")},
    {SM_SCANF, BURROW_S_INIT("X%d"), BURROW_S_INIT("10X"), 384, 1, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("%d%"), BURROW_S_INIT("42%"), 385, 1, 1,
     BURROW_S_INIT("missing verb: % at end of format string")},
    {SM_SCANF, BURROW_S_INIT("%d% "), BURROW_S_INIT("42%"), 386, 1, 1,
     BURROW_S_INIT("too few operands for format '% '")},
    {SM_SCANF, BURROW_S_INIT("%%%d"), BURROW_S_INIT("xxx 42"), 387, 1, 0,
     BURROW_S_INIT("missing literal %")},
    {SM_SCANF, BURROW_S_INIT("%%%d"), BURROW_S_INIT("x42"), 388, 1, 0,
     BURROW_S_INIT("missing literal %")},
    {SM_SCANF, BURROW_S_INIT("%%%d"), BURROW_S_INIT("42"), 389, 1, 0,
     BURROW_S_INIT("missing literal %")},
    {SM_SCANF, BURROW_S_INIT("%c%c%c"), BURROW_S_INIT("\302X\302"), 390, 3, 3,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%v%v"), BURROW_S_INIT("FALSE23"), 393, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%s"), BURROW_S_INIT(""), 395, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%s"), BURROW_S_INIT("   "), 396, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%q"), BURROW_S_INIT(""), 397, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%q"), BURROW_S_INIT("   "), 398, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT(""), 399, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("   "), 400, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 401, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 402, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 403, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 404, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 405, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 406, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 407, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 408, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 409, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 410, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 411, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 412, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 413, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 414, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 415, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 416, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 417, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 418, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 419, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 420, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 421, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 422, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 423, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 424, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 425, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 426, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT(""), 427, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%v"), BURROW_S_INIT("   "), 428, 1, 0,
     BURROW_S_INIT("EOF")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("123abc"), 429, 2, 2, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("asdf"), 431, 2, 1,
     BURROW_S_INIT("EOF")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("abc"), 433, 2, 1, BURROW_S_INIT("EOF")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT(""), 435, 2, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%q"), BURROW_S_INIT("\"\""), 437, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("1 x\012"), 438, 1, 1,
     BURROW_S_INIT("expected newline")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("123\012456\012"), 439, 2, 1,
     BURROW_S_INIT("unexpected newline")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("123\012"), 441, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT(""), 442, 1, 0, BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%d %d"), BURROW_S_INIT("23"), 443, 2, 1,
     BURROW_S_INIT("EOF")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("234"), 445, 2, 1, BURROW_S_INIT("EOF")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("234 "), 447, 2, 1,
     BURROW_S_INIT("EOF")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("00010203"), 449, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x %x"), BURROW_S_INIT("00010203 00010203"), 450, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("00010203:"), 452, 1, 1,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x:%x"), BURROW_S_INIT("00010203:00010203"), 453, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%x"), BURROW_S_INIT("000102034:"), 455, 1, 0,
     BURROW_S_INIT("illegal hex digit")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("1\0122\012"), 456, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("1\0122"), 458, 2, 2, BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("1  \012  2  \012"), 460, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCAN, BURROW_S_INIT(""), BURROW_S_INIT("1  \012  2"), 462, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("1\012"), 464, 2, 1,
     BURROW_S_INIT("unexpected newline")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("   1 2    \012"), 466, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("   1 2"), 468, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANLN, BURROW_S_INIT(""), BURROW_S_INIT("1\0122\012"), 470, 2, 1,
     BURROW_S_INIT("unexpected newline")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d\012"), BURROW_S_INIT("1\0122"), 472, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d %d"), BURROW_S_INIT("1\0122"), 474, 2, 1,
     BURROW_S_INIT("newline in input does not match format")},
    {SM_SCANF, BURROW_S_INIT("%d %d"), BURROW_S_INIT("1 \0122"), 476, 2, 1,
     BURROW_S_INIT("unexpected newline")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d"), BURROW_S_INIT("1 2"), 478, 2, 1,
     BURROW_S_INIT("newline in format does not match input")},
    {SM_SCANF, BURROW_S_INIT("%d \012%d"), BURROW_S_INIT("1 2"), 480, 2, 1,
     BURROW_S_INIT("newline in format does not match input")},
    {SM_SCANF, BURROW_S_INIT("%d \012%d"), BURROW_S_INIT("1 \0122"), 482, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012 %d"), BURROW_S_INIT("1\0122"), 484, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012 %d"), BURROW_S_INIT("1\0122"), 486, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d"), BURROW_S_INIT("1\0122"), 488, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012 %d"), BURROW_S_INIT("1\0122"), 490, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012%d"), BURROW_S_INIT("1\0122"), 492, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012 %d"), BURROW_S_INIT("1\0122"), 494, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d"), BURROW_S_INIT("1\012 2"), 496, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d "), BURROW_S_INIT("1\012 2"), 498, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012%d"), BURROW_S_INIT("1\012 2"), 500, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012 %d"), BURROW_S_INIT("1\012 2"), 502, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d"), BURROW_S_INIT("1 \0122"), 504, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012 %d"), BURROW_S_INIT("1 \0122"), 506, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012%d"), BURROW_S_INIT("1 \0122"), 508, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012 %d"), BURROW_S_INIT("1 \0122"), 510, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012%d"), BURROW_S_INIT("1 \012 2"), 512, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d\012 %d"), BURROW_S_INIT("1 \012 2"), 514, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012%d"), BURROW_S_INIT("1 \012 2"), 516, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("%d \012 %d"), BURROW_S_INIT("1 \012 2"), 518, 2, 2,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1\0122"), BURROW_S_INIT("1\0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1\012 2"), BURROW_S_INIT("1\0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1 \0122"), BURROW_S_INIT("1\0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1 \012 2"), BURROW_S_INIT("1\0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1\0122"), BURROW_S_INIT("1\012 2"), 520, 0, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("1\0122 "), BURROW_S_INIT("1\012 2"), 520, 0, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("1 \0122"), BURROW_S_INIT("1\012 2"), 520, 0, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("1 \012 2"), BURROW_S_INIT("1\012 2"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1\0122"), BURROW_S_INIT("1 \0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1\012 2"), BURROW_S_INIT("1 \0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1 \0122"), BURROW_S_INIT("1 \0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1 \012 2"), BURROW_S_INIT("1 \0122"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1\0122"), BURROW_S_INIT("1 \012 2"), 520, 0, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("1\012 2"), BURROW_S_INIT("1 \012 2"), 520, 0, 0,
     BURROW_S_INIT("")},
    {SM_SCANF, BURROW_S_INIT("1 \0122"), BURROW_S_INIT("1 \012 2"), 520, 0, 0,
     BURROW_S_INIT("input does not match format")},
    {SM_SCANF, BURROW_S_INIT("1 \012 2"), BURROW_S_INIT("1 \012 2"), 520, 0, 0,
     BURROW_S_INIT("")},
};

static const ScanTarget scan_targets[] = {
    {SC_BOOL, false, BURROW_S_INIT("true")},
    {SC_BOOL, false, BURROW_S_INIT("true")},
    {SC_BOOL, false, BURROW_S_INIT("false")},
    {SC_BOOL, false, BURROW_S_INIT("false")},
    {SC_INT, false, BURROW_S_INIT("21")},
    {SC_INT, false, BURROW_S_INIT("21")},
    {SC_INT, false, BURROW_S_INIT("21")},
    {SC_INT, false, BURROW_S_INIT("21")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("16")},
    {SC_INT, false, BURROW_S_INIT("16")},
    {SC_INT, false, BURROW_S_INIT("16")},
    {SC_INT, false, BURROW_S_INIT("16")},
    {SC_INT, false, BURROW_S_INIT("-16")},
    {SC_INT, false, BURROW_S_INIT("-16")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("-255")},
    {SC_INT, false, BURROW_S_INIT("-255")},
    {SC_INT, false, BURROW_S_INIT("-255")},
    {SC_INT, false, BURROW_S_INIT("-255")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_UINT, false, BURROW_S_INIT("0x10")},
    {SC_UINT, false, BURROW_S_INIT("0x10")},
    {SC_UINT, false, BURROW_S_INIT("0xff")},
    {SC_UINT, false, BURROW_S_INIT("0xff")},
    {SC_INT8, false, BURROW_S_INIT("22")},
    {SC_INT8, false, BURROW_S_INIT("22")},
    {SC_INT16, false, BURROW_S_INIT("23")},
    {SC_INT16, false, BURROW_S_INIT("23")},
    {SC_INT32, false, BURROW_S_INIT("24")},
    {SC_INT32, false, BURROW_S_INIT("24")},
    {SC_INT64, false, BURROW_S_INIT("25")},
    {SC_INT64, false, BURROW_S_INIT("25")},
    {SC_INT8, false, BURROW_S_INIT("127")},
    {SC_INT8, false, BURROW_S_INIT("127")},
    {SC_INT, false, BURROW_S_INIT("-21")},
    {SC_INT, false, BURROW_S_INIT("-21")},
    {SC_INT8, false, BURROW_S_INIT("-22")},
    {SC_INT8, false, BURROW_S_INIT("-22")},
    {SC_INT16, false, BURROW_S_INIT("-23")},
    {SC_INT16, false, BURROW_S_INIT("-23")},
    {SC_INT32, false, BURROW_S_INIT("-24")},
    {SC_INT32, false, BURROW_S_INIT("-24")},
    {SC_INT64, false, BURROW_S_INIT("-25")},
    {SC_INT64, false, BURROW_S_INIT("-25")},
    {SC_INT8, false, BURROW_S_INIT("-128")},
    {SC_INT8, false, BURROW_S_INIT("-128")},
    {SC_INT, false, BURROW_S_INIT("21")},
    {SC_INT, false, BURROW_S_INIT("21")},
    {SC_INT8, false, BURROW_S_INIT("22")},
    {SC_INT8, false, BURROW_S_INIT("22")},
    {SC_INT16, false, BURROW_S_INIT("23")},
    {SC_INT16, false, BURROW_S_INIT("23")},
    {SC_INT32, false, BURROW_S_INIT("24")},
    {SC_INT32, false, BURROW_S_INIT("24")},
    {SC_INT64, false, BURROW_S_INIT("25")},
    {SC_INT64, false, BURROW_S_INIT("25")},
    {SC_INT8, false, BURROW_S_INIT("127")},
    {SC_INT8, false, BURROW_S_INIT("127")},
    {SC_UINT, false, BURROW_S_INIT("0x1a")},
    {SC_UINT, false, BURROW_S_INIT("0x1a")},
    {SC_UINT8, false, BURROW_S_INIT("0x1b")},
    {SC_UINT8, false, BURROW_S_INIT("0x1b")},
    {SC_UINT16, false, BURROW_S_INIT("0x1c")},
    {SC_UINT16, false, BURROW_S_INIT("0x1c")},
    {SC_UINT32, false, BURROW_S_INIT("0x1d")},
    {SC_UINT32, false, BURROW_S_INIT("0x1d")},
    {SC_UINT64, false, BURROW_S_INIT("0x1e")},
    {SC_UINT64, false, BURROW_S_INIT("0x1e")},
    {SC_UINTPTR, false, BURROW_S_INIT("0x1f")},
    {SC_UINTPTR, false, BURROW_S_INIT("0x1f")},
    {SC_UINT8, false, BURROW_S_INIT("0xff")},
    {SC_UINT8, false, BURROW_S_INIT("0xff")},
    {SC_INT16, false, BURROW_S_INIT("32767")},
    {SC_INT16, false, BURROW_S_INIT("32767")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.3")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.3")},
    {SC_FLOAT32, false, BURROW_S_INIT("23")},
    {SC_FLOAT32, false, BURROW_S_INIT("23")},
    {SC_FLOAT64, false, BURROW_S_INIT("230")},
    {SC_FLOAT64, false, BURROW_S_INIT("230")},
    {SC_FLOAT64, false, BURROW_S_INIT("9.2")},
    {SC_FLOAT64, false, BURROW_S_INIT("9.2")},
    {SC_FLOAT64, false, BURROW_S_INIT("9.2")},
    {SC_FLOAT64, false, BURROW_S_INIT("9.2")},
    {SC_FLOAT64, false, BURROW_S_INIT("1.6971004547812786e+20")},
    {SC_FLOAT64, false, BURROW_S_INIT("1.6971004547812786e+20")},
    {SC_FLOAT64, false, BURROW_S_INIT("3.117081245895825e-20")},
    {SC_FLOAT64, false, BURROW_S_INIT("3.117081245895825e-20")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.964615315390051e-20")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.964615315390051e-20")},
    {SC_FLOAT64, false, BURROW_S_INIT("23.45")},
    {SC_FLOAT64, false, BURROW_S_INIT("23.45")},
    {SC_STRING, false, BURROW_S_INIT("\"2.35\"")},
    {SC_STRING, false, BURROW_S_INIT("\"2.35\"")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38}")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38}")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(34-2i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(34-2i)")},
    {SC_COMPLEX64, false, BURROW_S_INIT("(-34.5-3i)")},
    {SC_COMPLEX64, false, BURROW_S_INIT("(-34.5-3i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-4.5-100i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-4.5-100i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-4.5-100i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-4.5-100i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(2+4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(2+4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-2-4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-2-4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-15-4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-15-4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-15-4i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(-15-4i)")},
    {SC_STRING, false, BURROW_S_INIT("\"hello\"")},
    {SC_STRING, false, BURROW_S_INIT("\"hello\"")},
    {SC_STRING, false, BURROW_S_INIT("\"hello\"")},
    {SC_STRING, false, BURROW_S_INIT("\"hello\"")},
    {SC_UINT8, false, BURROW_S_INIT("0x1b")},
    {SC_UINT8, false, BURROW_S_INIT("0x1b")},
    {SC_BOOL, true, BURROW_S_INIT("true")},
    {SC_BOOL, true, BURROW_S_INIT("true")},
    {SC_BOOL, true, BURROW_S_INIT("false")},
    {SC_BOOL, true, BURROW_S_INIT("false")},
    {SC_INT, true, BURROW_S_INIT("101")},
    {SC_INT, true, BURROW_S_INIT("101")},
    {SC_INT, true, BURROW_S_INIT("102")},
    {SC_INT, true, BURROW_S_INIT("102")},
    {SC_UINT, true, BURROW_S_INIT("0x67")},
    {SC_UINT, true, BURROW_S_INIT("0x67")},
    {SC_UINT, true, BURROW_S_INIT("0x68")},
    {SC_UINT, true, BURROW_S_INIT("0x68")},
    {SC_INT8, true, BURROW_S_INIT("105")},
    {SC_INT8, true, BURROW_S_INIT("105")},
    {SC_INT16, true, BURROW_S_INIT("106")},
    {SC_INT16, true, BURROW_S_INIT("106")},
    {SC_INT32, true, BURROW_S_INIT("107")},
    {SC_INT32, true, BURROW_S_INIT("107")},
    {SC_INT64, true, BURROW_S_INIT("108")},
    {SC_INT64, true, BURROW_S_INIT("108")},
    {SC_UINT8, true, BURROW_S_INIT("0x6d")},
    {SC_UINT8, true, BURROW_S_INIT("0x6d")},
    {SC_UINT16, true, BURROW_S_INIT("0x6e")},
    {SC_UINT16, true, BURROW_S_INIT("0x6e")},
    {SC_UINT32, true, BURROW_S_INIT("0x6f")},
    {SC_UINT32, true, BURROW_S_INIT("0x6f")},
    {SC_UINT64, true, BURROW_S_INIT("0x70")},
    {SC_UINT64, true, BURROW_S_INIT("0x70")},
    {SC_UINTPTR, true, BURROW_S_INIT("0x71")},
    {SC_UINTPTR, true, BURROW_S_INIT("0x71")},
    {SC_STRING, true, BURROW_S_INIT("\"114\"")},
    {SC_STRING, true, BURROW_S_INIT("\"114\"")},
    {SC_BYTES, true, BURROW_S_INIT("[]byte{0x31, 0x31, 0x35}")},
    {SC_BYTES, true, BURROW_S_INIT("[]byte{0x31, 0x31, 0x35}")},
    {SC_XS, false, BURROW_S_INIT("\"vvv\"")},
    {SC_XS, false, BURROW_S_INIT("\"vvv\"")},
    {SC_INTSTRING, false, BURROW_S_INIT("{1234 \"hello\"}")},
    {SC_INTSTRING, false, BURROW_S_INIT("{1234 \"hello\"}")},
    {SC_INT64, false, BURROW_S_INIT("2147483648")},
    {SC_INT64, false, BURROW_S_INIT("2147483648")},
    {SC_INT8, false, BURROW_S_INIT("0")},
    {SC_INT16, false, BURROW_S_INIT("0")},
    {SC_INT8, false, BURROW_S_INIT("0")},
    {SC_INT16, false, BURROW_S_INIT("0")},
    {SC_UINT8, false, BURROW_S_INIT("0x0")},
    {SC_UINT16, false, BURROW_S_INIT("0x0")},
    {SC_FLOAT32, false, BURROW_S_INIT("0")},
    {SC_FLOAT64, false, BURROW_S_INIT("0")},
    {SC_COMPLEX64, false, BURROW_S_INIT("(0+0i)")},
    {SC_COMPLEX64, false, BURROW_S_INIT("(0+0i)")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(0+0i)")},
    {SC_BOOL, false, BURROW_S_INIT("true")},
    {SC_BOOL, false, BURROW_S_INIT("false")},
    {SC_INT, false, BURROW_S_INIT("-71")},
    {SC_INT, false, BURROW_S_INIT("-71")},
    {SC_INT, false, BURROW_S_INIT("7")},
    {SC_INT, false, BURROW_S_INIT("7")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("255")},
    {SC_INT, false, BURROW_S_INIT("68")},
    {SC_INT, false, BURROW_S_INIT("68")},
    {SC_INT, false, BURROW_S_INIT("72")},
    {SC_INT32, false, BURROW_S_INIT("97")},
    {SC_INT32, false, BURROW_S_INIT("20594")},
    {SC_INT32, false, BURROW_S_INIT("4660")},
    {SC_INT8, false, BURROW_S_INIT("73")},
    {SC_INT16, false, BURROW_S_INIT("74")},
    {SC_INT32, false, BURROW_S_INIT("75")},
    {SC_INT64, false, BURROW_S_INIT("76")},
    {SC_INT, false, BURROW_S_INIT("73")},
    {SC_INT, false, BURROW_S_INIT("61")},
    {SC_INT, false, BURROW_S_INIT("2677")},
    {SC_UINT, false, BURROW_S_INIT("0x47")},
    {SC_UINT, false, BURROW_S_INIT("0x48")},
    {SC_UINT, false, BURROW_S_INIT("0x7")},
    {SC_UINT8, false, BURROW_S_INIT("0x49")},
    {SC_UINT16, false, BURROW_S_INIT("0x4a")},
    {SC_UINT32, false, BURROW_S_INIT("0x4b")},
    {SC_UINT64, false, BURROW_S_INIT("0x4c")},
    {SC_UINTPTR, false, BURROW_S_INIT("0x4d")},
    {SC_UINT, false, BURROW_S_INIT("0x49")},
    {SC_UINT, false, BURROW_S_INIT("0x4")},
    {SC_UINT, false, BURROW_S_INIT("0x3d")},
    {SC_UINT, false, BURROW_S_INIT("0x7")},
    {SC_UINT, false, BURROW_S_INIT("0xa75")},
    {SC_UINT, false, BURROW_S_INIT("0xa75")},
    {SC_UINT, false, BURROW_S_INIT("0xa7")},
    {SC_INT, false, BURROW_S_INIT("4660")},
    {SC_UINT, false, BURROW_S_INIT("0x4567")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.3")},
    {SC_FLOAT32, false, BURROW_S_INIT("23")},
    {SC_FLOAT64, false, BURROW_S_INIT("230")},
    {SC_FLOAT64, false, BURROW_S_INIT("9.2")},
    {SC_FLOAT64, false, BURROW_S_INIT("9.2")},
    {SC_FLOAT64, false, BURROW_S_INIT("1.6971004547812786e+20")},
    {SC_FLOAT64, false, BURROW_S_INIT("3.117081245895825e-20")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.964615315390051e-20")},
    {SC_FLOAT64, false, BURROW_S_INIT("23.45")},
    {SC_STRING, false, BURROW_S_INIT("\"using-%s\"")},
    {SC_STRING, false, BURROW_S_INIT("\"using-%x\"")},
    {SC_STRING, false, BURROW_S_INIT("\"using-%X\"")},
    {SC_STRING, false, BURROW_S_INIT("\"quoted\\twith\\\\doubles\"")},
    {SC_STRING, false, BURROW_S_INIT("\"quoted with backs\"")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x62, 0x79, 0x74, 0x65, 0x73, 0x2d, 0x25, 0x73}")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x62, 0x79, 0x74, 0x65, 0x73, 0x2d, 0x25, 0x78}")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x62, 0x79, 0x74, 0x65, 0x73, 0x2d, 0x25, 0x58}")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x62, 0x79, 0x74, 0x65, 0x73, 0xd, 0x77, 0x69, 0x74, 0x68, "
                   "0xb, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x73}")},
    {SC_BYTES, false,
     BURROW_S_INIT("[]byte{0x62, 0x79, 0x74, 0x65, 0x73, 0x20, 0x77, 0x69, 0x74, 0x68, "
                   "0x20, 0x62, 0x61, 0x63, 0x6b, 0x73}")},
    {SC_BOOL, true, BURROW_S_INIT("true")},
    {SC_BOOL, true, BURROW_S_INIT("false")},
    {SC_INT, true, BURROW_S_INIT("101")},
    {SC_INT, true, BURROW_S_INIT("257")},
    {SC_INT, true, BURROW_S_INIT("102")},
    {SC_UINT, true, BURROW_S_INIT("0x67")},
    {SC_UINT, true, BURROW_S_INIT("0x68")},
    {SC_INT8, true, BURROW_S_INIT("105")},
    {SC_INT16, true, BURROW_S_INIT("106")},
    {SC_INT32, true, BURROW_S_INIT("107")},
    {SC_INT64, true, BURROW_S_INIT("108")},
    {SC_UINT8, true, BURROW_S_INIT("0x6d")},
    {SC_UINT16, true, BURROW_S_INIT("0x6e")},
    {SC_UINT32, true, BURROW_S_INIT("0x6f")},
    {SC_UINT64, true, BURROW_S_INIT("0x70")},
    {SC_UINTPTR, true, BURROW_S_INIT("0x71")},
    {SC_STRING, true, BURROW_S_INIT("\"114\"")},
    {SC_BYTES, true, BURROW_S_INIT("[]byte{0x31, 0x31, 0x35, 0x35}")},
    {SC_FLOAT32, true, BURROW_S_INIT("1160")},
    {SC_FLOAT64, true, BURROW_S_INIT("-117")},
    {SC_COMPLEX64, true, BURROW_S_INIT("(11+60i)")},
    {SC_COMPLEX128, true, BURROW_S_INIT("(-11+70i)")},
    {SC_INT, false, BURROW_S_INIT("118")},
    {SC_INT, false, BURROW_S_INIT("119")},
    {SC_INT, false, BURROW_S_INIT("42")},
    {SC_UINT32, false, BURROW_S_INIT("0xffffffff")},
    {SC_XS, false, BURROW_S_INIT("\"sss\"")},
    {SC_XS, false, BURROW_S_INIT("\"ss\"")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("28")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_UINT, false, BURROW_S_INIT("0x20")},
    {SC_UINT, false, BURROW_S_INIT("0x9")},
    {SC_UINT, false, BURROW_S_INIT("0xa")},
    {SC_UINT, false, BURROW_S_INIT("0x17")},
    {SC_UINT, false, BURROW_S_INIT("0x17")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27X\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27X\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27X\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_STRING, false, BURROW_S_INIT("\"27\"")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT32, false, BURROW_S_INIT("10")},
    {SC_INT32, false, BURROW_S_INIT("32")},
    {SC_INT32, false, BURROW_S_INIT("0")},
    {SC_INT32, false, BURROW_S_INIT("0")},
    {SC_INT32, false, BURROW_S_INIT("33")},
    {SC_INT32, false, BURROW_S_INIT("10")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("27")},
    {SC_INT, false, BURROW_S_INIT("23")},
    {SC_STRING, false, BURROW_S_INIT("\"22\"")},
    {SC_STRING, false, BURROW_S_INIT("\"333\"")},
    {SC_INT, false, BURROW_S_INIT("44")},
    {SC_INT, false, BURROW_S_INIT("555")},
    {SC_INT, false, BURROW_S_INIT("66")},
    {SC_INT, false, BURROW_S_INIT("777")},
    {SC_INT, false, BURROW_S_INIT("23")},
    {SC_INT, false, BURROW_S_INIT("18")},
    {SC_INT, false, BURROW_S_INIT("333")},
    {SC_INT, false, BURROW_S_INIT("333")},
    {SC_COMPLEX128, false, BURROW_S_INIT("(3+2i)")},
    {SC_FLOAT64, false, BURROW_S_INIT("2.5")},
    {SC_INT, false, BURROW_S_INIT("123")},
    {SC_STRING, false, BURROW_S_INIT("\"abc\"")},
    {SC_INT32, false, BURROW_S_INIT("50")},
    {SC_INT32, false, BURROW_S_INIT("20674")},
    {SC_INT32, false, BURROW_S_INIT("88")},
    {SC_STRING, false, BURROW_S_INIT("\"12345\"")},
    {SC_INT, false, BURROW_S_INIT("67")},
    {SC_STRING, false, BURROW_S_INIT("\"12\"")},
    {SC_INT, false, BURROW_S_INIT("34")},
    {SC_XS, false, BURROW_S_INIT("\"ee\"")},
    {SC_XS, false, BURROW_S_INIT("\"fffff\"")},
    {SC_INTSTRING, false, BURROW_S_INIT("{12 \"ab\"}")},
    {SC_STRING, false, BURROW_S_INIT("\"cd\"")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("23")},
    {SC_INT, false, BURROW_S_INIT("18")},
    {SC_INT, false, BURROW_S_INIT("23")},
    {SC_INT, false, BURROW_S_INIT("18")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT8, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("42")},
    {SC_INT, false, BURROW_S_INIT("42")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT32, false, BURROW_S_INIT("65533")},
    {SC_INT32, false, BURROW_S_INIT("88")},
    {SC_INT32, false, BURROW_S_INIT("65533")},
    {SC_BOOL, false, BURROW_S_INIT("false")},
    {SC_INT, false, BURROW_S_INIT("23")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte(nil)")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte(nil)")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_UINT, false, BURROW_S_INIT("0x0")},
    {SC_BOOL, false, BURROW_S_INIT("false")},
    {SC_BOOL, false, BURROW_S_INIT("false")},
    {SC_FLOAT32, false, BURROW_S_INIT("0")},
    {SC_FLOAT32, false, BURROW_S_INIT("0")},
    {SC_COMPLEX64, false, BURROW_S_INIT("(0+0i)")},
    {SC_COMPLEX64, false, BURROW_S_INIT("(0+0i)")},
    {SC_STRING, true, BURROW_S_INIT("\"\"")},
    {SC_STRING, true, BURROW_S_INIT("\"\"")},
    {SC_BYTES, true, BURROW_S_INIT("[]byte(nil)")},
    {SC_BYTES, true, BURROW_S_INIT("[]byte(nil)")},
    {SC_INT, true, BURROW_S_INIT("0")},
    {SC_INT, true, BURROW_S_INIT("0")},
    {SC_UINT, true, BURROW_S_INIT("0x0")},
    {SC_UINT, true, BURROW_S_INIT("0x0")},
    {SC_BOOL, true, BURROW_S_INIT("false")},
    {SC_BOOL, true, BURROW_S_INIT("false")},
    {SC_FLOAT32, true, BURROW_S_INIT("0")},
    {SC_FLOAT32, true, BURROW_S_INIT("0")},
    {SC_COMPLEX64, true, BURROW_S_INIT("(0+0i)")},
    {SC_COMPLEX64, true, BURROW_S_INIT("(0+0i)")},
    {SC_INT, false, BURROW_S_INIT("123")},
    {SC_STRING, false, BURROW_S_INIT("\"abc\"")},
    {SC_STRING, false, BURROW_S_INIT("\"asdf\"")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_STRING, false, BURROW_S_INIT("\"abc\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_STRING, false, BURROW_S_INIT("\"\"")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("123")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("123")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("23")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("234")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("234")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte{0x0, 0x1, 0x2, 0x3}")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte{0x0, 0x1, 0x2, 0x3}")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte{0x0, 0x1, 0x2, 0x3}")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte{0x0, 0x1, 0x2, 0x3}")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte{0x0, 0x1, 0x2, 0x3}")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte{0x0, 0x1, 0x2, 0x3}")},
    {SC_BYTES, false, BURROW_S_INIT("[]byte(nil)")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("0")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
    {SC_INT, false, BURROW_S_INIT("1")},
    {SC_INT, false, BURROW_S_INIT("2")},
};
