/* Derived from Go's src/net/url/url_test.go.
 * Go source: go1.27.1.
 *
 * Generated by burrow-gen tests and then translated by hand. TestJSON and
 * TestGob need encoding/json and encoding/gob, which are not ported yet, so
 * TestMarshalBinary covers the round trip they make.
 *
 * Copyright 2009 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "check.h"

#include "burrow/net/url.h"

#include "burrow/declare.h"
#include "burrow/error.h"
#include "burrow/fmt.h"
#include "burrow/io.h"
#include "burrow/map.h"
#include "burrow/mem/arena.h"
#include "burrow/mem/heap.h"
#include "burrow/mem/track.h"
#include "burrow/strings.h"
#include "burrow/type.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define S BURROW_S
#define SI BURROW_S_INIT

typedef struct URLTest {
    Str in;
    const Url *out;
    Str roundtrip;
} URLTest;

typedef struct EscapeTest {
    Str in;
    Str out;
    const char *err; /* the text of the EscapeError, or NULL */
} EscapeTest;

typedef struct EncodeQueryTest {
    const char *m; /* see values_from */
    Str expected;
} EncodeQueryTest;

typedef struct ParseTest {
    Str query;
    const char *out;
    bool ok;
} ParseTest;

typedef struct RequestURITest {
    const Url *url;
    Str out;
} RequestURITest;

typedef struct ShouldEscapeTest {
    Byte in;
    int mode;
    bool escape;
} ShouldEscapeTest;

typedef struct ParseRequestURLTestsCase {
    Str url;
    bool expectedValid;
} ParseRequestURLTestsCase;

typedef struct StringURLTestsCase {
    Url url;
    Str want;
} StringURLTestsCase;

typedef struct UrlRedactedCasesCase {
    Str name;
    const Url *url;
    Str want;
} UrlRedactedCasesCase;

typedef struct ResolvePathTestsCase {
    Str base;
    Str ref;
    Str expected;
} ResolvePathTestsCase;

typedef struct ResolveReferenceTestsCase {
    Str base;
    Str rel;
    Str expected;
} ResolveReferenceTestsCase;

typedef struct ParseErrorsTestsCase {
    Str in;
    bool wantErr;
} ParseErrorsTestsCase;

/* Which of Go's test error types the case wraps, and its fields. */
enum { NET_TIMEOUT, NET_TEMPORARY, NET_BOTH, NET_EOF };

typedef struct NetErrorTestsCase {
    int kind;
    bool timeout_field;
    bool temporary_field;
    bool timeout;
    bool temporary;
} NetErrorTestsCase;

typedef struct UrlHostnameAndPortTestsCase {
    Str in;
    Str host;
    Str port;
} UrlHostnameAndPortTestsCase;

typedef struct EscapeBenchmarksCase {
    Str unescaped;
    Str query;
    Str path;
} EscapeBenchmarksCase;

typedef struct JoinPathTestsCase {
    Str base;
    const Str *elem;
    Int elem_len;
    Str out;
} JoinPathTestsCase;

typedef struct ParseStrictIpv6TestsCase {
    Str url;
} ParseStrictIpv6TestsCase;

typedef struct UrlCloneTestsCase {
    Str name;
    const Url *in;
} UrlCloneTestsCase;

typedef struct ValuesCloneTestsCase {
    Str name;
    const char *in;
} ValuesCloneTestsCase;

static const URLTest urltests[] = {
    {SI("http://www.google.com"),
     &(const Url){.scheme = SI("http"), .host = SI("www.google.com")}, SI("")},
    {SI("http://www.google.com/"),
     &(const Url){.scheme = SI("http"), .host = SI("www.google.com"), .path = SI("/")},
     SI("")},
    {SI("http://www.google.com/file%20one%26two"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/file one&two"),
                  .raw_path = SI("/file%20one%26two")},
     SI("")},
    {SI("http://www.google.com/#file%20one%26two"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .fragment = SI("file one&two"),
                  .raw_fragment = SI("file%20one%26two")},
     SI("")},
    {SI("ftp://webmaster@www.google.com/"),
     &(const Url){.scheme = SI("ftp"),
                  .user = &(UrlUserinfo){SI("webmaster"), SI(""), false},
                  .host = SI("www.google.com"),
                  .path = SI("/")},
     SI("")},
    {SI("ftp://john%20doe@www.google.com/"),
     &(const Url){.scheme = SI("ftp"),
                  .user = &(UrlUserinfo){SI("john doe"), SI(""), false},
                  .host = SI("www.google.com"),
                  .path = SI("/")},
     SI("ftp://john%20doe@www.google.com/")},
    {SI("http://www.google.com/?"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .force_query = true},
     SI("")},
    {SI("http://www.google.com/?foo=bar?"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .raw_query = SI("foo=bar?")},
     SI("")},
    {SI("http://www.google.com/?q=go+language"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .raw_query = SI("q=go+language")},
     SI("")},
    {SI("http://www.google.com/?q=go%20language"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .raw_query = SI("q=go%20language")},
     SI("")},
    {SI("http://www.google.com/a%20b?q=c+d"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/a b"),
                  .raw_query = SI("q=c+d")},
     SI("")},
    {SI("http:www.google.com/?q=go+language"),
     &(const Url){.scheme = SI("http"),
                  .opaque = SI("www.google.com/"),
                  .raw_query = SI("q=go+language")},
     SI("http:www.google.com/?q=go+language")},
    {SI("http:%2f%2fwww.google.com/?q=go+language"),
     &(const Url){.scheme = SI("http"),
                  .opaque = SI("%2f%2fwww.google.com/"),
                  .raw_query = SI("q=go+language")},
     SI("http:%2f%2fwww.google.com/?q=go+language")},
    {SI("mailto:/webmaster@golang.org"),
     &(const Url){.scheme = SI("mailto"),
                  .path = SI("/webmaster@golang.org"),
                  .omit_host = true},
     SI("")},
    {SI("mailto:webmaster@golang.org"),
     &(const Url){.scheme = SI("mailto"), .opaque = SI("webmaster@golang.org")},
     SI("")},
    {SI("/foo?query=http://bad"),
     &(const Url){.path = SI("/foo"), .raw_query = SI("query=http://bad")}, SI("")},
    {SI("//foo"), &(const Url){.host = SI("foo")}, SI("")},
    {SI("//user@foo/path?a=b"),
     &(const Url){.user = &(UrlUserinfo){SI("user"), SI(""), false},
                  .host = SI("foo"),
                  .path = SI("/path"),
                  .raw_query = SI("a=b")},
     SI("")},
    {SI("///threeslashes"), &(const Url){.path = SI("///threeslashes")}, SI("")},
    {SI("http://user:password@google.com"),
     &(const Url){.scheme = SI("http"),
                  .user = &(UrlUserinfo){SI("user"), SI("password"), true},
                  .host = SI("google.com")},
     SI("http://user:password@google.com")},
    {SI("http://j@ne:password@google.com"),
     &(const Url){.scheme = SI("http"),
                  .user = &(UrlUserinfo){SI("j@ne"), SI("password"), true},
                  .host = SI("google.com")},
     SI("http://j%40ne:password@google.com")},
    {SI("http://jane:p@ssword@google.com"),
     &(const Url){.scheme = SI("http"),
                  .user = &(UrlUserinfo){SI("jane"), SI("p@ssword"), true},
                  .host = SI("google.com")},
     SI("http://jane:p%40ssword@google.com")},
    {SI("http://j@ne:password@google.com/p@th?q=@go"),
     &(const Url){.scheme = SI("http"),
                  .user = &(UrlUserinfo){SI("j@ne"), SI("password"), true},
                  .host = SI("google.com"),
                  .path = SI("/p@th"),
                  .raw_query = SI("q=@go")},
     SI("http://j%40ne:password@google.com/p@th?q=@go")},
    {SI("http://www.google.com/?q=go+language#foo"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .raw_query = SI("q=go+language"),
                  .fragment = SI("foo")},
     SI("")},
    {SI("http://www.google.com/?q=go+language#foo&bar"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .raw_query = SI("q=go+language"),
                  .fragment = SI("foo&bar")},
     SI("http://www.google.com/?q=go+language#foo&bar")},
    {SI("http://www.google.com/?q=go+language#foo%26bar"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("www.google.com"),
                  .path = SI("/"),
                  .raw_query = SI("q=go+language"),
                  .fragment = SI("foo&bar"),
                  .raw_fragment = SI("foo%26bar")},
     SI("http://www.google.com/?q=go+language#foo%26bar")},
    {SI("file:///home/adg/rabbits"),
     &(const Url){
         .scheme = SI("file"), .host = SI(""), .path = SI("/home/adg/rabbits")},
     SI("file:///home/adg/rabbits")},
    {SI("file:///C:/FooBar/Baz.txt"),
     &(const Url){
         .scheme = SI("file"), .host = SI(""), .path = SI("/C:/FooBar/Baz.txt")},
     SI("file:///C:/FooBar/Baz.txt")},
    {SI("MaIlTo:webmaster@golang.org"),
     &(const Url){.scheme = SI("mailto"), .opaque = SI("webmaster@golang.org")},
     SI("mailto:webmaster@golang.org")},
    {SI("a/b/c"), &(const Url){.path = SI("a/b/c")}, SI("a/b/c")},
    {SI("http://%3Fam:pa%3Fsword@google.com"),
     &(const Url){.scheme = SI("http"),
                  .user = &(UrlUserinfo){SI("?am"), SI("pa?sword"), true},
                  .host = SI("google.com")},
     SI("")},
    {SI("http://192.168.0.1/"),
     &(const Url){.scheme = SI("http"), .host = SI("192.168.0.1"), .path = SI("/")},
     SI("")},
    {SI("http://192.168.0.1:8080/"),
     &(const Url){
         .scheme = SI("http"), .host = SI("192.168.0.1:8080"), .path = SI("/")},
     SI("")},
    {SI("http://[fe80::1]/"),
     &(const Url){.scheme = SI("http"), .host = SI("[fe80::1]"), .path = SI("/")},
     SI("")},
    {SI("http://[fe80::1]:8080/"),
     &(const Url){.scheme = SI("http"), .host = SI("[fe80::1]:8080"), .path = SI("/")},
     SI("")},
    {SI("https://[2001:db8::1]:8443/test/path"),
     &(const Url){.scheme = SI("https"),
                  .host = SI("[2001:db8::1]:8443"),
                  .path = SI("/test/path")},
     SI("")},
    {SI("http://[fe80::1%25en0]/"),
     &(const Url){.scheme = SI("http"), .host = SI("[fe80::1%en0]"), .path = SI("/")},
     SI("")},
    {SI("http://[fe80::1%25en0]:8080/"),
     &(const Url){
         .scheme = SI("http"), .host = SI("[fe80::1%en0]:8080"), .path = SI("/")},
     SI("")},
    {SI("http://[fe80::1%25%65%6e%301-._~]/"),
     &(const Url){
         .scheme = SI("http"), .host = SI("[fe80::1%en01-._~]"), .path = SI("/")},
     SI("http://[fe80::1%25en01-._~]/")},
    {SI("http://[fe80::1%25%65%6e%301-._~]:8080/"),
     &(const Url){
         .scheme = SI("http"), .host = SI("[fe80::1%en01-._~]:8080"), .path = SI("/")},
     SI("http://[fe80::1%25en01-._~]:8080/")},
    {SI("http://rest.rsc.io/foo%2fbar/baz%2Fquux?alt=media"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("rest.rsc.io"),
                  .path = SI("/foo/bar/baz/quux"),
                  .raw_path = SI("/foo%2fbar/baz%2Fquux"),
                  .raw_query = SI("alt=media")},
     SI("")},
    {SI("mysql://a,b,c/bar"),
     &(const Url){.scheme = SI("mysql"), .host = SI("a,b,c"), .path = SI("/bar")},
     SI("")},
    {SI("scheme://!$&'()*+,;=hello!:1/path"),
     &(const Url){.scheme = SI("scheme"),
                  .host = SI("!$&'()*+,;=hello!:1"),
                  .path = SI("/path")},
     SI("")},
    {SI("http://host/!$&'()*+,;=:@[hello]"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("host"),
                  .path = SI("/!$&'()*+,;=:@[hello]"),
                  .raw_path = SI("/!$&'()*+,;=:@[hello]")},
     SI("")},
    {SI("http://example.com/oid/[order_id]"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/oid/[order_id]"),
                  .raw_path = SI("/oid/[order_id]")},
     SI("")},
    {SI("http://192.168.0.2:8080/foo"),
     &(const Url){
         .scheme = SI("http"), .host = SI("192.168.0.2:8080"), .path = SI("/foo")},
     SI("")},
    {SI("http://192.168.0.2:/foo"),
     &(const Url){.scheme = SI("http"), .host = SI("192.168.0.2:"), .path = SI("/foo")},
     SI("")},
    {SI("http://[2b01:e34:ef40:7730:8e70:5aff:fefe:edac]:8080/foo"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("[2b01:e34:ef40:7730:8e70:5aff:fefe:edac]:8080"),
                  .path = SI("/foo")},
     SI("")},
    {SI("http://[2b01:e34:ef40:7730:8e70:5aff:fefe:edac]:/foo"),
     &(const Url){.scheme = SI("http"),
                  .host = SI("[2b01:e34:ef40:7730:8e70:5aff:fefe:edac]:"),
                  .path = SI("/foo")},
     SI("")},
    {SI("http://hello.世界.com/foo"),
     &(const Url){
         .scheme = SI("http"), .host = SI("hello.世界.com"), .path = SI("/foo")},
     SI("http://hello.%E4%B8%96%E7%95%8C.com/foo")},
    {SI("http://hello.%e4%b8%96%e7%95%8c.com/foo"),
     &(const Url){
         .scheme = SI("http"), .host = SI("hello.世界.com"), .path = SI("/foo")},
     SI("http://hello.%E4%B8%96%E7%95%8C.com/foo")},
    {SI("http://hello.%E4%B8%96%E7%95%8C.com/foo"),
     &(const Url){
         .scheme = SI("http"), .host = SI("hello.世界.com"), .path = SI("/foo")},
     SI("")},
    {SI("http://example.com//foo"),
     &(const Url){.scheme = SI("http"), .host = SI("example.com"), .path = SI("//foo")},
     SI("")},
    {SI("myscheme://authority<\"hi\">/foo"),
     &(const Url){
         .scheme = SI("myscheme"), .host = SI("authority<\"hi\">"), .path = SI("/foo")},
     SI("")},
    {SI("tcp://[2020::2020:20:2020:2020%25Windows%20Loves%20Spaces]:2020"),
     &(const Url){.scheme = SI("tcp"),
                  .host = SI("[2020::2020:20:2020:2020%Windows Loves Spaces]:2020")},
     SI("")},
    {SI("magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn"),
     &(const Url){.scheme = SI("magnet"),
                  .host = SI(""),
                  .path = SI(""),
                  .raw_query =
                      SI("xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn")},
     SI("magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn")},
    {SI("mailto:?subject=hi"),
     &(const Url){.scheme = SI("mailto"),
                  .host = SI(""),
                  .path = SI(""),
                  .raw_query = SI("subject=hi")},
     SI("mailto:?subject=hi")},
    {SI("postgres://host1:1,host2:2,host3:3"),
     &(const Url){.scheme = SI("postgres"),
                  .host = SI("host1:1,host2:2,host3:3"),
                  .path = SI("")},
     SI("postgres://host1:1,host2:2,host3:3")},
    {SI("postgresql://host1:1,host2:2,host3:3"),
     &(const Url){.scheme = SI("postgresql"),
                  .host = SI("host1:1,host2:2,host3:3"),
                  .path = SI("")},
     SI("postgresql://host1:1,host2:2,host3:3")},
    {SI("mongodb://user:password@host1:1,host2:2,host3:3"),
     &(const Url){.scheme = SI("mongodb"),
                  .user = &(UrlUserinfo){SI("user"), SI("password"), true},
                  .host = SI("host1:1,host2:2,host3:3"),
                  .path = SI("")},
     SI("")},
    {SI("mongodb+srv://user:password@host1:1,host2:2,host3:3"),
     &(const Url){.scheme = SI("mongodb+srv"),
                  .user = &(UrlUserinfo){SI("user"), SI("password"), true},
                  .host = SI("host1:1,host2:2,host3:3"),
                  .path = SI("")},
     SI("")},
    {SI(""),
     &(const Url){.scheme = SI("http"), .omit_host = true, .path = SI("//host/path")},
     SI("http:%2F/host/path")},
};

static const ParseRequestURLTestsCase parseRequestURLTests[] = {
    {SI("http://foo.com"), true},
    {SI("http://foo.com/"), true},
    {SI("http://foo.com/path"), true},
    {SI("/"), true},
    {SI("//not.a.user@not.a.host/just/a/path"), true},
    {SI("//not.a.user@%66%6f%6f.com/just/a/path/also"), true},
    {SI("*"), true},
    {SI("http://192.168.0.1/"), true},
    {SI("http://192.168.0.1:8080/"), true},
    {SI("http://[fe80::1]/"), true},
    {SI("http://[fe80::1]:8080/"), true},
    {SI("http://[fe80::1%25en0]/"), true},
    {SI("http://[fe80::1%25en0]:8080/"), true},
    {SI("http://[fe80::1%25%65%6e%301-._~]/"), true},
    {SI("http://[fe80::1%25%65%6e%301-._~]:8080/"), true},
    {SI("foo.html"), false},
    {SI("../dir/"), false},
    {SI(" http://foo.com"), false},
    {SI("http://192.168.0.%31/"), false},
    {SI("http://192.168.0.%31:8080/"), false},
    {SI("http://[fe80::%31]/"), false},
    {SI("http://[fe80::%31]:8080/"), false},
    {SI("http://[fe80::%31%25en0]/"), false},
    {SI("http://[fe80::%31%25en0]:8080/"), false},
    {SI("http://[fe80::1%en0]/"), false},
    {SI("http://[fe80::1%en0]:8080/"), false},
    {SI("https://[1:2:3:4:5:6:7:8]"), true},
    {SI("https://[2001:db8::a:b:c:d]"), true},
    {SI("https://[fe80::1%25eth0]"), true},
    {SI("https://[fe80::abc:def%254]"), true},
    {SI("https://[2001:db8::1]/path"), true},
    {SI("https://[fe80::1%25eth0]/path?query=1"), true},
    {SI("https://[::ffff:192.0.2.1]"), true},
    {SI("https://[:1] "), false},
    {SI("https://[1:2:3:4:5:6:7:8:9]"), false},
    {SI("https://[1::1::1]"), false},
    {SI("https://[1:2:3:]"), false},
    {SI("https://[ffff::127.0.0.4000]"), false},
    {SI("https://[0:0::test.com]:80"), false},
    {SI("https://[2001:db8::test.com]"), false},
    {SI("https://[test.com]"), false},
    {SI("https://1:2:3:4:5:6:7:8"), false},
    {SI("https://1:2:3:4:5:6:7:8:80"), false},
    {SI("https://example.com:80:"), false},
};

static const StringURLTestsCase stringURLTests[] BURROW_UNUSED = {
    {.url = {.scheme = SI("http"), .host = SI("www.google.com"), .path = SI("search")},
     .want = SI("http://www.google.com/search")},
    {.url = {.path = SI("this:that")}, .want = SI("./this:that")},
    {.url = {.path = SI("here/this:that")}, .want = SI("here/this:that")},
    {.url = {.scheme = SI("http"),
             .host = SI("www.google.com"),
             .path = SI("this:that")},
     .want = SI("http://www.google.com/this:that")},
};

static const UrlRedactedCasesCase url_redacted_cases[] = {
    {.name = SI("non-blank Password"),
     .url = &(const Url){.scheme = SI("http"),
                         .host = SI("host.tld"),
                         .path = SI("this:that"),
                         .user = &(UrlUserinfo){SI("user"), SI("password"), true}},
     .want = SI("http://user:xxxxx@host.tld/this:that")},
    {.name = SI("blank Password"),
     .url = &(const Url){.scheme = SI("http"),
                         .host = SI("host.tld"),
                         .path = SI("this:that"),
                         .user = &(UrlUserinfo){SI("user"), SI(""), false}},
     .want = SI("http://user@host.tld/this:that")},
    {.name = SI("nil User"),
     .url = &(const Url){.scheme = SI("http"),
                         .host = SI("host.tld"),
                         .path = SI("this:that"),
                         .user = &(UrlUserinfo){SI(""), SI("password"), true}},
     .want = SI("http://:xxxxx@host.tld/this:that")},
    {.name = SI("blank Username, blank Password"),
     .url = &(const Url){.scheme = SI("http"),
                         .host = SI("host.tld"),
                         .path = SI("this:that")},
     .want = SI("http://host.tld/this:that")},
    {.name = SI("empty URL"), .url = &(const Url){.scheme = {0}}, .want = SI("")},
    {.name = SI("nil URL"), .url = NULL, .want = SI("")},
};

static const EscapeTest unescapeTests[] = {
    {SI(""), SI(""), NULL},         {SI("abc"), SI("abc"), NULL},
    {SI("1%41"), SI("1A"), NULL},   {SI("1%41%42%43"), SI("1ABC"), NULL},
    {SI("%4a"), SI("J"), NULL},     {SI("%6F"), SI("o"), NULL},
    {SI("%"), SI(""), "%"},         {SI("%a"), SI(""), "%a"},
    {SI("%1"), SI(""), "%1"},       {SI("123%45%6"), SI(""), "%6"},
    {SI("%zzzzz"), SI(""), "%zz"},  {SI("a+b"), SI("a b"), NULL},
    {SI("a%20b"), SI("a b"), NULL},
};

static const EscapeTest queryEscapeTests[] = {
    {SI(""), SI(""), NULL},
    {SI("abc"), SI("abc"), NULL},
    {SI("one two"), SI("one+two"), NULL},
    {SI("10%"), SI("10%25"), NULL},
    {SI(" ?&=#+%!<>#\"{}|\\^[]`☺\t:/@$'()*,;"),
     SI("+%3F%26%3D%23%2B%25%21%3C%3E%23%22%7B%7D%7C%5C%5E%5B%5D%60%E2%98%BA%09%3A%2F%"
        "40%24%27%28%29%2A%2C%3B"),
     NULL},
};

static const EscapeTest pathEscapeTests[] = {
    {SI(""), SI(""), NULL},
    {SI("abc"), SI("abc"), NULL},
    {SI("abc+def"), SI("abc+def"), NULL},
    {SI("a/b"), SI("a%2Fb"), NULL},
    {SI("one two"), SI("one%20two"), NULL},
    {SI("10%"), SI("10%25"), NULL},
    {SI(" ?&=#+%!<>#\"{}|\\^[]`☺\t:/@$'()*,;"),
     SI("%20%3F&=%23+%25%21%3C%3E%23%22%7B%7D%7C%5C%5E%5B%5D%60%E2%98%BA%09:%2F@$%27%"
        "28%29%2A%2C%3B"),
     NULL},
};

static const EncodeQueryTest encodeQueryTests[] = {
    {NULL, SI("")},
    {"", SI("")},
    {"q=puppies\noe=utf8", SI("oe=utf8&q=puppies")},
    {"q=dogs\nq=&\nq=7", SI("q=dogs&q=%26&q=7")},
    {"a=a1\na=a2\na=a3\nb=b1\nb=b2\nb=b3\nc=c1\nc=c2\nc=c3",
     SI("a=a1&a=a2&a=a3&b=b1&b=b2&b=b3&c=c1&c=c2&c=c3")},
    {"a=a\nb=b\nc=c\nd=d\ne=e\nf=f\ng=g\nh=h\ni=i",
     SI("a=a&b=b&c=c&d=d&e=e&f=f&g=g&h=h&i=i")},
};

static const ResolvePathTestsCase resolvePathTests[] = {
    {SI("a/b"), SI("."), SI("/a/")},       {SI("a/b"), SI("c"), SI("/a/c")},
    {SI("a/b"), SI(".."), SI("/")},        {SI("a/"), SI(".."), SI("/")},
    {SI("a/"), SI("../.."), SI("/")},      {SI("a/b/c"), SI(".."), SI("/a/")},
    {SI("a/b/c"), SI("../d"), SI("/a/d")}, {SI("a/b/c"), SI(".././d"), SI("/a/d")},
    {SI("a/b"), SI("./.."), SI("/")},      {SI("a/./b"), SI("."), SI("/a/")},
    {SI("a/../"), SI("."), SI("/")},       {SI("a/.././b"), SI("c"), SI("/c")},
};

static const ResolveReferenceTestsCase resolveReferenceTests[] = {
    {SI("http://foo.com?a=b"), SI("https://bar.com/"), SI("https://bar.com/")},
    {SI("http://foo.com/"), SI("https://bar.com/?a=b"), SI("https://bar.com/?a=b")},
    {SI("http://foo.com/"), SI("https://bar.com/?"), SI("https://bar.com/?")},
    {SI("http://foo.com/bar"), SI("mailto:foo@example.com"),
     SI("mailto:foo@example.com")},
    {SI("http://foo.com/bar"), SI("/baz"), SI("http://foo.com/baz")},
    {SI("http://foo.com/bar?a=b#f"), SI("/baz"), SI("http://foo.com/baz")},
    {SI("http://foo.com/bar?a=b"), SI("/baz?"), SI("http://foo.com/baz?")},
    {SI("http://foo.com/bar?a=b"), SI("/baz?c=d"), SI("http://foo.com/baz?c=d")},
    {SI("http://foo.com/bar"), SI("http://foo.com//baz"), SI("http://foo.com//baz")},
    {SI("http://foo.com/bar"), SI("http://foo.com///baz/quux"),
     SI("http://foo.com///baz/quux")},
    {SI("https://foo.com/bar?a=b"), SI("//bar.com/quux"), SI("https://bar.com/quux")},
    {SI("http://foo.com"), SI("."), SI("http://foo.com/")},
    {SI("http://foo.com/bar"), SI("."), SI("http://foo.com/")},
    {SI("http://foo.com/bar/"), SI("."), SI("http://foo.com/bar/")},
    {SI("http://foo.com"), SI("bar"), SI("http://foo.com/bar")},
    {SI("http://foo.com/"), SI("bar"), SI("http://foo.com/bar")},
    {SI("http://foo.com/bar/baz"), SI("quux"), SI("http://foo.com/bar/quux")},
    {SI("http://foo.com/bar/baz/"), SI("quux"), SI("http://foo.com/bar/baz/quux")},
    {SI("http://foo.com/bar/baz"), SI("../quux"), SI("http://foo.com/quux")},
    {SI("http://foo.com/bar/baz"), SI("../../../../../quux"),
     SI("http://foo.com/quux")},
    {SI("http://foo.com/bar"), SI(".."), SI("http://foo.com/")},
    {SI("http://foo.com/bar/baz"), SI("./.."), SI("http://foo.com/")},
    {SI("http://foo.com/bar/baz"), SI("quux/dotdot/../tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"), SI("quux/./dotdot/../tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"), SI("quux/./dotdot/.././tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"), SI("quux/./dotdot/./../tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"), SI("quux/./dotdot/dotdot/././../../tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"), SI("quux/./dotdot/dotdot/./.././../tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"),
     SI("quux/./dotdot/dotdot/dotdot/./../../.././././tail"),
     SI("http://foo.com/bar/quux/tail")},
    {SI("http://foo.com/bar/baz"), SI("quux/./dotdot/../dotdot/../dot/./tail/.."),
     SI("http://foo.com/bar/quux/dot/")},
    {SI("http://foo.com/dot/./dotdot/../foo/bar"), SI("../baz"),
     SI("http://foo.com/dot/baz")},
    {SI("http://foo.com/bar"), SI("..."), SI("http://foo.com/...")},
    {SI("http://foo.com/bar"), SI(".#frag"), SI("http://foo.com/#frag")},
    {SI("http://example.org/"), SI("#!$&%27()*+,;="),
     SI("http://example.org/#!$&%27()*+,;=")},
    {SI("http://foo.com/foo%2fbar/"), SI("../baz"), SI("http://foo.com/baz")},
    {SI("http://foo.com/1/2%2f/3%2f4/5"), SI("../../a/b/c"),
     SI("http://foo.com/1/a/b/c")},
    {SI("http://foo.com/1/2/3"), SI("./a%2f../../b/..%2fc"),
     SI("http://foo.com/1/2/b/..%2fc")},
    {SI("http://foo.com/1/2%2f/3%2f4/5"), SI("./a%2f../b/../c"),
     SI("http://foo.com/1/2%2f/3%2f4/a%2f../c")},
    {SI("http://foo.com/foo%20bar/"), SI("../baz"), SI("http://foo.com/baz")},
    {SI("http://foo.com/foo"), SI("../bar%2fbaz"), SI("http://foo.com/bar%2fbaz")},
    {SI("http://foo.com/foo%2dbar/"), SI("./baz-quux"),
     SI("http://foo.com/foo%2dbar/baz-quux")},
    {SI("http://a/b/c/d;p?q"), SI("g:h"), SI("g:h")},
    {SI("http://a/b/c/d;p?q"), SI("g"), SI("http://a/b/c/g")},
    {SI("http://a/b/c/d;p?q"), SI("./g"), SI("http://a/b/c/g")},
    {SI("http://a/b/c/d;p?q"), SI("g/"), SI("http://a/b/c/g/")},
    {SI("http://a/b/c/d;p?q"), SI("/g"), SI("http://a/g")},
    {SI("http://a/b/c/d;p?q"), SI("//g"), SI("http://g")},
    {SI("http://a/b/c/d;p?q"), SI("?y"), SI("http://a/b/c/d;p?y")},
    {SI("http://a/b/c/d;p?q"), SI("g?y"), SI("http://a/b/c/g?y")},
    {SI("http://a/b/c/d;p?q"), SI("#s"), SI("http://a/b/c/d;p?q#s")},
    {SI("http://a/b/c/d;p?q"), SI("g#s"), SI("http://a/b/c/g#s")},
    {SI("http://a/b/c/d;p?q"), SI("g?y#s"), SI("http://a/b/c/g?y#s")},
    {SI("http://a/b/c/d;p?q"), SI(";x"), SI("http://a/b/c/;x")},
    {SI("http://a/b/c/d;p?q"), SI("g;x"), SI("http://a/b/c/g;x")},
    {SI("http://a/b/c/d;p?q"), SI("g;x?y#s"), SI("http://a/b/c/g;x?y#s")},
    {SI("http://a/b/c/d;p?q"), SI(""), SI("http://a/b/c/d;p?q")},
    {SI("http://a/b/c/d;p?q"), SI("."), SI("http://a/b/c/")},
    {SI("http://a/b/c/d;p?q"), SI("./"), SI("http://a/b/c/")},
    {SI("http://a/b/c/d;p?q"), SI(".."), SI("http://a/b/")},
    {SI("http://a/b/c/d;p?q"), SI("../"), SI("http://a/b/")},
    {SI("http://a/b/c/d;p?q"), SI("../g"), SI("http://a/b/g")},
    {SI("http://a/b/c/d;p?q"), SI("../.."), SI("http://a/")},
    {SI("http://a/b/c/d;p?q"), SI("../../"), SI("http://a/")},
    {SI("http://a/b/c/d;p?q"), SI("../../g"), SI("http://a/g")},
    {SI("http://a/b/c/d;p?q"), SI("../../../g"), SI("http://a/g")},
    {SI("http://a/b/c/d;p?q"), SI("../../../../g"), SI("http://a/g")},
    {SI("http://a/b/c/d;p?q"), SI("/./g"), SI("http://a/g")},
    {SI("http://a/b/c/d;p?q"), SI("/../g"), SI("http://a/g")},
    {SI("http://a/b/c/d;p?q"), SI("g."), SI("http://a/b/c/g.")},
    {SI("http://a/b/c/d;p?q"), SI(".g"), SI("http://a/b/c/.g")},
    {SI("http://a/b/c/d;p?q"), SI("g.."), SI("http://a/b/c/g..")},
    {SI("http://a/b/c/d;p?q"), SI("..g"), SI("http://a/b/c/..g")},
    {SI("http://a/b/c/d;p?q"), SI("./../g"), SI("http://a/b/g")},
    {SI("http://a/b/c/d;p?q"), SI("./g/."), SI("http://a/b/c/g/")},
    {SI("http://a/b/c/d;p?q"), SI("g/./h"), SI("http://a/b/c/g/h")},
    {SI("http://a/b/c/d;p?q"), SI("g/../h"), SI("http://a/b/c/h")},
    {SI("http://a/b/c/d;p?q"), SI("g;x=1/./y"), SI("http://a/b/c/g;x=1/y")},
    {SI("http://a/b/c/d;p?q"), SI("g;x=1/../y"), SI("http://a/b/c/y")},
    {SI("http://a/b/c/d;p?q"), SI("g?y/./x"), SI("http://a/b/c/g?y/./x")},
    {SI("http://a/b/c/d;p?q"), SI("g?y/../x"), SI("http://a/b/c/g?y/../x")},
    {SI("http://a/b/c/d;p?q"), SI("g#s/./x"), SI("http://a/b/c/g#s/./x")},
    {SI("http://a/b/c/d;p?q"), SI("g#s/../x"), SI("http://a/b/c/g#s/../x")},
    {SI("https://a/b/c/d;p?q"), SI("//g?q"), SI("https://g?q")},
    {SI("https://a/b/c/d;p?q"), SI("//g#s"), SI("https://g#s")},
    {SI("https://a/b/c/d;p?q"), SI("//g/d/e/f?y#s"), SI("https://g/d/e/f?y#s")},
    {SI("https://a/b/c/d;p#s"), SI("?y"), SI("https://a/b/c/d;p?y")},
    {SI("https://a/b/c/d;p?q#s"), SI("?y"), SI("https://a/b/c/d;p?y")},
    {SI("https://a/b/c/d;p?q#s"), SI("?"), SI("https://a/b/c/d;p?")},
    {SI("https://foo.com/bar?a=b"), SI("http:opaque"), SI("http:opaque")},
    {SI("http:opaque?x=y#zzz"), SI("https:/foo?a=b#frag"), SI("https:/foo?a=b#frag")},
    {SI("http:opaque?x=y#zzz"), SI("https:foo:bar"), SI("https:foo:bar")},
    {SI("http:opaque?x=y#zzz"), SI("https:bar/baz?a=b#frag"),
     SI("https:bar/baz?a=b#frag")},
    {SI("http:opaque?x=y#zzz"), SI("https://user@host:1234?a=b#frag"),
     SI("https://user@host:1234?a=b#frag")},
    {SI("http:opaque?x=y#zzz"), SI("?a=b#frag"), SI("http:opaque?a=b#frag")},
};

static const ParseTest parseTests[] = {
    {.query = SI("a=1"), .out = "a=1", .ok = true},
    {.query = SI("a=1&b=2"), .out = "a=1\nb=2", .ok = true},
    {.query = SI("a=1&a=2&a=banana"), .out = "a=1\na=2\na=banana", .ok = true},
    {.query = SI("ascii=%3Ckey%3A+0x90%3E"), .out = "ascii=<key: 0x90>", .ok = true},
    {.query = SI("a=1;b=2"), .out = "", .ok = false},
    {.query = SI("a;b=1"), .out = "", .ok = false},
    {.query = SI("a=%3B"), .out = "a=;", .ok = true},
    {.query = SI("a%3Bb=1"), .out = "a;b=1", .ok = true},
    {.query = SI("a=1&a=2;a=banana"), .out = "a=1", .ok = false},
    {.query = SI("a;b&c=1"), .out = "c=1", .ok = false},
    {.query = SI("a=1&b=2;a=3&c=4"), .out = "a=1\nc=4", .ok = false},
    {.query = SI("a=1&b=2;c=3"), .out = "a=1", .ok = false},
    {.query = SI(";"), .out = "", .ok = false},
    {.query = SI("a=1;"), .out = "", .ok = false},
    {.query = SI("a=1&;"), .out = "a=1", .ok = false},
    {.query = SI(";a=1&b=2"), .out = "b=2", .ok = false},
    {.query = SI("a=1&b=2;"), .out = "a=1", .ok = false},
};

static const RequestURITest requritests[] = {
    {&(const Url){.scheme = SI("http"), .host = SI("example.com"), .path = SI("")},
     SI("/")},
    {&(const Url){.scheme = SI("http"), .host = SI("example.com"), .path = SI("/a b")},
     SI("/a%20b")},
    {&(const Url){
         .scheme = SI("http"), .host = SI("example.com"), .opaque = SI("/%2F/%2F/")},
     SI("/%2F/%2F/")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .opaque = SI("//other.example.com/%2F/%2F/")},
     SI("http://other.example.com/%2F/%2F/")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/////"),
                  .raw_path = SI("/%2F/%2F/")},
     SI("/%2F/%2F/")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/////"),
                  .raw_path = SI("/WRONG/")},
     SI("/////")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/a b"),
                  .raw_query = SI("q=go+language")},
     SI("/a%20b?q=go+language")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/a b"),
                  .raw_path = SI("/a b"),
                  .raw_query = SI("q=go+language")},
     SI("/a%20b?q=go+language")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/a?b"),
                  .raw_path = SI("/a?b"),
                  .raw_query = SI("q=go+language")},
     SI("/a%3Fb?q=go+language")},
    {&(const Url){.scheme = SI("myschema"), .opaque = SI("opaque")}, SI("opaque")},
    {&(const Url){.scheme = SI("myschema"),
                  .opaque = SI("opaque"),
                  .raw_query = SI("q=go+language")},
     SI("opaque?q=go+language")},
    {&(const Url){.scheme = SI("http"), .host = SI("example.com"), .path = SI("//foo")},
     SI("//foo")},
    {&(const Url){.scheme = SI("http"),
                  .host = SI("example.com"),
                  .path = SI("/foo"),
                  .force_query = true},
     SI("/foo?")},
};

static const ParseErrorsTestsCase parse_errors_tests[] = {
    {SI("http://[::1]"), false},
    {SI("http://[::1]:80"), false},
    {SI("http://[::1]:namedport"), true},
    {SI("http://x:namedport"), true},
    {SI("http://[::1]/"), false},
    {SI("http://[::1]a"), true},
    {SI("http://[::1]%23"), true},
    {SI("http://[::1%25en0]"), false},
    {SI("http://[::1]:"), false},
    {SI("http://x:"), false},
    {SI("http://[::1]:%38%30"), true},
    {SI("http://[::1%25%41]"), false},
    {SI("http://[%10::1]"), true},
    {SI("http://[::1]/%48"), false},
    {SI("http://%41:8080/"), true},
    {SI("mysql://x@y(z:123)/foo"), true},
    {SI("mysql://x@y(1.2.3.4:123)/foo"), true},
    {SI(" http://foo.com"), true},
    {SI("ht tp://foo.com"), true},
    {SI("ahttp://foo.com"), false},
    {SI("1http://foo.com"), true},
    {SI("http://"
        "[]%20%48%54%54%50%2f%31%2e%31%0a%4d%79%48%65%61%64%65%72%3a%20%31%32%33%0a%"
        "0a/"),
     true},
    {SI("http://a b.com/"), true},
    {SI("cache_object://foo"), true},
    {SI("cache_object:foo"), true},
    {SI("cache_object:foo/bar"), true},
    {SI("cache_object/:foo/bar"), false},
    {SI("http://[192.168.0.1]/"), true},
    {SI("http://[192.168.0.1]:8080/"), true},
    {SI("http://[::ffff:192.168.0.1]/"), false},
    {SI("http://[::ffff:192.168.0.1000]/"), true},
    {SI("http://[::ffff:192.168.0.1]:8080/"), false},
    {SI("http://[::ffff:c0a8:1]/"), false},
    {SI("http://[not-an-ip]/"), true},
    {SI("http://[fe80::1%foo]/"), true},
    {SI("http://[fe80::1"), true},
    {SI("http://fe80::1]/"), true},
    {SI("http://[test.com]/"), true},
    {SI("http://example.com[::1]"), true},
    {SI("http://example.com[::1"), true},
    {SI("http://[::1"), true},
    {SI("http://.[::1]"), true},
    {SI("http:// [::1]"), true},
    {SI("hxxp://mathepqo[.]serveftp(.)com:9059"), true},
};

static const ShouldEscapeTest shouldEscapeTests[] = {
    {97, 1, false},  {97, 16, false}, {97, 32, false}, {97, 64, false}, {97, 4, false},
    {122, 1, false}, {65, 1, false},  {90, 1, false},  {48, 1, false},  {57, 1, false},
    {45, 1, false},  {45, 16, false}, {45, 32, false}, {45, 64, false}, {46, 1, false},
    {95, 1, false},  {126, 1, false}, {58, 16, true},  {47, 16, true},  {63, 16, true},
    {64, 16, true},  {36, 16, false}, {38, 16, false}, {43, 16, false}, {44, 16, false},
    {59, 16, false}, {61, 16, false}, {33, 4, false},  {36, 4, false},  {38, 4, false},
    {39, 4, false},  {40, 4, false},  {41, 4, false},  {42, 4, false},  {43, 4, false},
    {44, 4, false},  {59, 4, false},  {61, 4, false},  {58, 4, false},  {91, 4, false},
    {93, 4, false},  {48, 4, false},  {57, 4, false},  {65, 4, false},  {122, 4, false},
    {95, 4, false},  {45, 4, false},  {46, 4, false},
};

static const NetErrorTestsCase netErrorTests[] = {
    {NET_TIMEOUT, true, false, true, false},
    {NET_TIMEOUT, false, false, false, false},
    {NET_TEMPORARY, false, true, false, true},
    {NET_TEMPORARY, false, false, false, false},
    {NET_BOTH, true, true, true, true},
    {NET_BOTH, false, true, false, true},
    {NET_BOTH, true, false, true, false},
    {NET_BOTH, false, false, false, false},
    {NET_EOF, false, false, false, false},
};

static const UrlHostnameAndPortTestsCase url_hostname_and_port_tests[] = {
    {SI("foo.com:80"), SI("foo.com"), SI("80")},
    {SI("foo.com"), SI("foo.com"), SI("")},
    {SI("foo.com:"), SI("foo.com"), SI("")},
    {SI("FOO.COM"), SI("FOO.COM"), SI("")},
    {SI("1.2.3.4"), SI("1.2.3.4"), SI("")},
    {SI("1.2.3.4:80"), SI("1.2.3.4"), SI("80")},
    {SI("[1:2:3:4]"), SI("1:2:3:4"), SI("")},
    {SI("[1:2:3:4]:80"), SI("1:2:3:4"), SI("80")},
    {SI("[::1]:80"), SI("::1"), SI("80")},
    {SI("[::1]"), SI("::1"), SI("")},
    {SI("[::1]:"), SI("::1"), SI("")},
    {SI("localhost"), SI("localhost"), SI("")},
    {SI("localhost:443"), SI("localhost"), SI("443")},
    {SI("some.super.long.domain.example.org:8080"),
     SI("some.super.long.domain.example.org"), SI("8080")},
    {SI("[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:17000"),
     SI("2001:0db8:85a3:0000:0000:8a2e:0370:7334"), SI("17000")},
    {SI("[2001:0db8:85a3:0000:0000:8a2e:0370:7334]"),
     SI("2001:0db8:85a3:0000:0000:8a2e:0370:7334"), SI("")},
    {SI("[google.com]:80"), SI("google.com"), SI("80")},
    {SI("google.com]:80"), SI("google.com]"), SI("80")},
    {SI("google.com:80_invalid_port"), SI("google.com:80_invalid_port"), SI("")},
    {SI("[::1]extra]:80"), SI("::1]extra"), SI("80")},
    {SI("google.com]extra:extra"), SI("google.com]extra:extra"), SI("")},
};

static const Str reject_control_characters_tests[] = {
    SI("http://foo.com/?foo\nbar"),
    SI("http\r://foo.com/"),
    SI("http://foo\x7f.com/"),
};

static const EscapeBenchmarksCase escapeBenchmarks[] BURROW_UNUSED = {
    {.unescaped = SI("one two"), .query = SI("one+two"), .path = SI("one%20two")},
    {.unescaped = SI("Фотки собак"),
     .query = SI("%D0%A4%D0%BE%D1%82%D0%BA%D0%B8+%D1%81%D0%BE%D0%B1%D0%B0%D0%BA"),
     .path = SI("%D0%A4%D0%BE%D1%82%D0%BA%D0%B8%20%D1%81%D0%BE%D0%B1%D0%B0%D0%BA")},
    {.unescaped = SI("shortrun(break)shortrun"),
     .query = SI("shortrun%28break%29shortrun"),
     .path = SI("shortrun%28break%29shortrun")},
    {.unescaped = SI("longerrunofcharacters(break)anotherlongerrunofcharacters"),
     .query = SI("longerrunofcharacters%28break%29anotherlongerrunofcharacters"),
     .path = SI("longerrunofcharacters%28break%29anotherlongerrunofcharacters")},
    {.unescaped =
         SI("padded/with+various%characters?that=need$some@escaping+paddedsowebreak/"
            "256bytespadded/"
            "with+various%characters?that=need$some@escaping+paddedsowebreak/"
            "256bytespadded/"
            "with+various%characters?that=need$some@escaping+paddedsowebreak/"
            "256bytespadded/"
            "with+various%characters?that=need$some@escaping+paddedsowebreak/256bytes"),
     .query = SI("padded%2Fwith%2Bvarious%25characters%3Fthat%3Dneed%24some%40escaping%"
                 "2Bpaddedsowebreak%2F256bytespadded%2Fwith%2Bvarious%25characters%"
                 "3Fthat%3Dneed%24some%40escaping%2Bpaddedsowebreak%2F256bytespadded%"
                 "2Fwith%2Bvarious%25characters%3Fthat%3Dneed%24some%40escaping%"
                 "2Bpaddedsowebreak%2F256bytespadded%2Fwith%2Bvarious%25characters%"
                 "3Fthat%3Dneed%24some%40escaping%2Bpaddedsowebreak%2F256bytes"),
     .path = SI(
         "padded%2Fwith+various%25characters%3Fthat=need$some@escaping+paddedsowebreak%"
         "2F256bytespadded%2Fwith+various%25characters%3Fthat=need$some@escaping+"
         "paddedsowebreak%2F256bytespadded%2Fwith+various%25characters%3Fthat=need$"
         "some@escaping+paddedsowebreak%2F256bytespadded%2Fwith+various%25characters%"
         "3Fthat=need$some@escaping+paddedsowebreak%2F256bytes")},
};

static const JoinPathTestsCase join_path_tests[] = {
    {.base = SI("https://go.googlesource.com"),
     .elem = (const Str[]){SI("go")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com/a/b/c"),
     .elem = (const Str[]){SI("../../../go")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com/"),
     .elem = (const Str[]){SI("../go")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com"),
     .elem = (const Str[]){SI("../go"), SI("../../go"), SI("../../../go")},
     .elem_len = 3,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com/../go"),
     .elem = NULL,
     .elem_len = 0,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com/"),
     .elem = (const Str[]){SI("./go")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com//"),
     .elem = (const Str[]){SI("/go")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go")},
    {.base = SI("https://go.googlesource.com//"),
     .elem = (const Str[]){SI("/go"), SI("a"), SI("b"), SI("c")},
     .elem_len = 4,
     .out = SI("https://go.googlesource.com/go/a/b/c")},
    {.base = SI("http://[fe80::1%en0]:8080/"),
     .elem = (const Str[]){SI("/go")},
     .elem_len = 1},
    {.base = SI("https://go.googlesource.com"),
     .elem = (const Str[]){SI("go/")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go/")},
    {.base = SI("https://go.googlesource.com"),
     .elem = (const Str[]){SI("go//")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/go/")},
    {.base = SI("https://go.googlesource.com"),
     .elem = NULL,
     .elem_len = 0,
     .out = SI("https://go.googlesource.com/")},
    {.base = SI("https://go.googlesource.com/"),
     .elem = NULL,
     .elem_len = 0,
     .out = SI("https://go.googlesource.com/")},
    {.base = SI("https://go.googlesource.com/a%2fb"),
     .elem = (const Str[]){SI("c")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/a%2fb/c")},
    {.base = SI("https://go.googlesource.com/a%2fb"),
     .elem = (const Str[]){SI("c%2fd")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/a%2fb/c%2fd")},
    {.base = SI("https://go.googlesource.com/a/b"),
     .elem = (const Str[]){SI("/go")},
     .elem_len = 1,
     .out = SI("https://go.googlesource.com/a/b/go")},
    {.base = SI("https://go.googlesource.com/"),
     .elem = (const Str[]){SI("100%")},
     .elem_len = 1},
    {.base = SI("/"), .elem = NULL, .elem_len = 0, .out = SI("/")},
    {.base = SI("a"), .elem = NULL, .elem_len = 0, .out = SI("a")},
    {.base = SI("a"), .elem = (const Str[]){SI("b")}, .elem_len = 1, .out = SI("a/b")},
    {.base = SI("a"), .elem = (const Str[]){SI("../b")}, .elem_len = 1, .out = SI("b")},
    {.base = SI("a"),
     .elem = (const Str[]){SI("../../b")},
     .elem_len = 1,
     .out = SI("b")},
    {.base = SI(""), .elem = (const Str[]){SI("a")}, .elem_len = 1, .out = SI("a")},
    {.base = SI(""), .elem = (const Str[]){SI("../a")}, .elem_len = 1, .out = SI("a")},
};

static const ParseStrictIpv6TestsCase parse_strict_ipv6_tests[] = {
    {SI("https://1:2:3:4:5:6:7:8")},
    {SI("https://1:2:3:4:5:6:7:8:80")},
    {SI("https://example.com:80:")},
};

static const UrlCloneTestsCase url_clone_tests[] = {
    {SI("nil"), NULL},
    {SI("zero value"), &(const Url){.scheme = {0}}},
    {SI("Populated but nil .User"),
     &(const Url){
         .user = NULL, .host = SI("foo"), .path = SI("/path"), .raw_query = SI("a=b")}},
    {SI("non-nil .User"),
     &(const Url){.user = &(UrlUserinfo){SI("user"), SI(""), false},
                  .host = SI("foo"),
                  .path = SI("/path"),
                  .raw_query = SI("a=b")}},
    {SI("non-nil .User: user and password set"),
     &(const Url){.user = &(UrlUserinfo){SI("user"), SI("password"), true},
                  .host = SI("foo"),
                  .path = SI("/path"),
                  .raw_query = SI("a=b")}},
};

static const ValuesCloneTestsCase values_clone_tests[] = {
    {SI("nil"), NULL},
    {SI("empty"), ""},
    {SI("1 key, nil values"), "1"},
    {SI("1 key, no values"), "1!"},
    {SI("1 key, some values"), "1=a\n1=b"},
    {SI("multiple keys, diverse values"), "1=a\n1=b\nX\nB=abcdefghi"},
};

/* ------------------------------------------------------------------ helpers */

static bool str_same(Str a, Str b) {
    return a.len == b.len && (a.len == 0 || memcmp(a.p, b.p, (size_t)a.len) == 0);
}

static bool user_equal(const UrlUserinfo *a, const UrlUserinfo *b) {
    if (a == NULL || b == NULL)
        return a == b;
    return str_same(a->username, b->username) && str_same(a->password, b->password) &&
           a->password_set == b->password_set;
}

/* reflect.DeepEqual on two URLs, which the mem and size fields stay out of. */
static bool url_equal(const Url *a, const Url *b) {
    if (a == NULL || b == NULL)
        return a == b;
    return str_same(a->scheme, b->scheme) && str_same(a->opaque, b->opaque) &&
           user_equal(a->user, b->user) && str_same(a->host, b->host) &&
           str_same(a->path, b->path) && str_same(a->fragment, b->fragment) &&
           str_same(a->raw_query, b->raw_query) && str_same(a->raw_path, b->raw_path) &&
           str_same(a->raw_fragment, b->raw_fragment) &&
           a->force_query == b->force_query && a->omit_host == b->omit_host;
}

/* Go's ufmt, for the messages. */
static Str ufmt(Alloc *a, const Url *u) {
    if (u == NULL)
        return S("<nil>");
    Str user = S("<nil>");
    if (u->user != NULL) {
        bool ok;
        Str pass = url_userinfo_password(u->user, &ok);
        user =
            ok ? fmt_sprintf_v(a, "%s:%s", u->user->username, pass) : u->user->username;
    }
    return fmt_sprintf_v(a,
                         "opaque=%q, scheme=%q, user=%#v, pass=%#v, host=%q, path=%q, "
                         "rawpath=%q, rawq=%q, frag=%q, rawfrag=%q, forcequery=%v, "
                         "omithost=%t",
                         u->opaque, u->scheme, user, user, u->host, u->path,
                         u->raw_path, u->raw_query, u->fragment, u->raw_fragment,
                         u->force_query, u->omit_host);
}

static const Str no_values[1];

/* Values from a spec: NULL is a nil map and "" an empty one, and otherwise
 * each line is "k=v" to add v under k, "k" for k with a nil slice, or "k!" for
 * k with an empty one. */
static UrlValues values_from(Alloc *a, const char *spec) {
    if (spec == NULL)
        return NULL;
    UrlValues v = url_values_make(a);
    const char *p = spec;
    while (*p != '\0') {
        const char *end = strchr(p, '\n');
        if (end == NULL)
            end = p + strlen(p);
        const char *eq = memchr(p, '=', (size_t)(end - p));
        if (eq != NULL) {
            url_values_add(v, str_from_bytes(p, (Int)(eq - p)),
                           str_from_bytes(eq + 1, (Int)(end - eq - 1)));
        } else if (end > p && end[-1] == '!') {
            Str k = str_from_bytes(p, (Int)(end - p - 1));
            Slice s = slice_from((void *)(uintptr_t)no_values, 0, 0, TYPE_STRING);
            map_set(v, &k, &s);
        } else {
            Str k = str_from_bytes(p, (Int)(end - p));
            Slice s = slice_from(NULL, 0, 0, TYPE_STRING);
            map_set(v, &k, &s);
        }
        p = *end == '\n' ? end + 1 : end;
    }
    return v;
}

/* reflect.DeepEqual on two Values, where nil and empty are not the same, for
 * the map and for each slice in it. */
static bool values_equal(UrlValues a, UrlValues b) {
    if (a == NULL || b == NULL)
        return a == b;
    if (map_len(a) != map_len(b))
        return false;
    const void *k;
    void *val;
    for (MapIter it = map_iter(a); map_next(&it, &k, &val);) {
        const Slice *x = (const Slice *)val;
        const Slice *y = (const Slice *)map_get(b, k);
        if (y == NULL || (x->p == NULL) != (y->p == NULL) || x->len != y->len)
            return false;
        for (Int i = 0; i < x->len; i++)
            if (!str_same(((const Str *)x->p)[i], ((const Str *)y->p)[i]))
                return false;
    }
    return true;
}

static bool str_has(Str s, const char *sub) {
    size_t n = strlen(sub);
    for (Int i = 0; i + (Int)n <= s.len; i++)
        if (memcmp(s.p + i, sub, n) == 0)
            return true;
    return false;
}

#define ARENA_BEGIN                                                                    \
    Arena ar;                                                                          \
    arena_init(&ar, NULL, 0);                                                          \
    Alloc *a = arena_allocator(&ar)
#define ARENA_END arena_free(&ar)

/* -------------------------------------------------------------------- tests */

static void TestParse(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof urltests / sizeof urltests[0]; i++) {
        const URLTest *tt = &urltests[i];
        if (tt->in.len == 0)
            continue;
        Error err;
        Url *u = url_parse(a, tt->in, &err);
        if (BURROW_FAILED(err)) {
            testing_t_errorf_v(t, "Parse(%q) returned error %s", tt->in,
                               error_text(err));
            continue;
        }
        if (!url_equal(u, tt->out))
            testing_t_errorf_v(t, "Parse(%q):\n\tgot  %s\n\twant %s\n", tt->in,
                               ufmt(a, u), ufmt(a, tt->out));
        url_free(a, u);
    }
    ARENA_END;
}

static const Str path_that_looks_scheme_relative =
    SI("//not.a.user@not.a.host/just/a/path");

static void TestParseRequestURI(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof parseRequestURLTests / sizeof parseRequestURLTests[0];
         i++) {
        const ParseRequestURLTestsCase *test = &parseRequestURLTests[i];
        Error err;
        (void)url_parse_request_uri(a, test->url, &err);
        if (test->expectedValid && BURROW_FAILED(err))
            testing_t_errorf_v(t, "ParseRequestURI(%q) gave err %s; want no error",
                               test->url, error_text(err));
        else if (!test->expectedValid && BURROW_OK(err))
            testing_t_errorf_v(t, "ParseRequestURI(%q) gave nil error; want some error",
                               test->url);
    }
    Error err;
    Url *u = url_parse_request_uri(a, path_that_looks_scheme_relative, &err);
    if (BURROW_FAILED(err)) {
        testing_t_fatalf_v(t, "Unexpected error %s", error_text(err));
        ARENA_END;
        return;
    }
    if (!str_same(u->path, path_that_looks_scheme_relative))
        testing_t_errorf_v(t, "ParseRequestURI path:\ngot  %q\nwant %q", u->path,
                           path_that_looks_scheme_relative);
    ARENA_END;
}

static void TestURLString(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof urltests / sizeof urltests[0]; i++) {
        const URLTest *tt = &urltests[i];
        const Url *u = tt->out;
        if (tt->in.len != 0) {
            Error err;
            u = url_parse(a, tt->in, &err);
            if (BURROW_FAILED(err)) {
                testing_t_errorf_v(t, "Parse(%q) returned error %s", tt->in,
                                   error_text(err));
                continue;
            }
        }
        Str expected = tt->roundtrip.len != 0 ? tt->roundtrip : tt->in;
        Str s = url_string(u, a);
        if (!str_same(s, expected))
            testing_t_errorf_v(t, "Parse(%q).String() == %q (expected %q)", tt->in, s,
                               expected);
    }
    for (size_t i = 0; i < sizeof stringURLTests / sizeof stringURLTests[0]; i++) {
        const StringURLTestsCase *tt = &stringURLTests[i];
        Str got = url_string(&tt->url, a);
        if (!str_same(got, tt->want))
            testing_t_errorf_v(t, "%s.String() = %q; want %q", ufmt(a, &tt->url), got,
                               tt->want);
    }
    ARENA_END;
}

static void TestURLRedacted(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof url_redacted_cases / sizeof url_redacted_cases[0];
         i++) {
        const UrlRedactedCasesCase *tt = &url_redacted_cases[i];
        Str g = url_redacted(tt->url, a);
        if (!str_same(g, tt->want))
            testing_t_errorf_v(t, "%s: got: %q\nwant: %q", tt->name, g, tt->want);
    }
    ARENA_END;
}

/* Whether err is an EscapeError with the text want, or no error for NULL. */
static bool escape_err_is(Error err, const char *want) {
    if (want == NULL)
        return BURROW_OK(err);
    const Str *e = (const Str *)errors_as(err, TYPE_URL_ESCAPE_ERROR);
    if (e == NULL)
        return false;
    return str_same(*e, str_from_cstr(want));
}

static Str replace_all(Alloc *a, Str s, const char *old, const char *new_) {
    return strings_replace_all(a, s, str_from_cstr(old), str_from_cstr(new_));
}

static void TestUnescape(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof unescapeTests / sizeof unescapeTests[0]; i++) {
        const EscapeTest *tt = &unescapeTests[i];
        Error err;
        Str actual = url_query_unescape(a, tt->in, &err);
        if (!str_same(actual, tt->out) || !escape_err_is(err, tt->err))
            testing_t_errorf_v(t, "QueryUnescape(%q) = %q, %s; want %q, %s", tt->in,
                               actual, error_text(err), tt->out,
                               tt->err ? tt->err : "<nil>");
        Str in = tt->in;
        Str out = tt->out;
        if (str_has(tt->in, "+")) {
            in = replace_all(a, tt->in, "+", "%20");
            actual = url_path_unescape(a, in, &err);
            if (!str_same(actual, tt->out) || !escape_err_is(err, tt->err))
                testing_t_errorf_v(t, "PathUnescape(%q) = %q, %s; want %q, %s", in,
                                   actual, error_text(err), tt->out,
                                   tt->err ? tt->err : "<nil>");
            if (tt->err == NULL) {
                Str s = url_query_unescape(a, replace_all(a, tt->in, "+", "XXX"), &err);
                if (BURROW_FAILED(err))
                    continue;
                in = tt->in;
                out = replace_all(a, s, "XXX", "+");
            }
        }
        actual = url_path_unescape(a, in, &err);
        if (!str_same(actual, out) || !escape_err_is(err, tt->err))
            testing_t_errorf_v(t, "PathUnescape(%q) = %q, %s; want %q, %s", in, actual,
                               error_text(err), out, tt->err ? tt->err : "<nil>");
    }
    ARENA_END;
}

static void TestQueryEscape(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof queryEscapeTests / sizeof queryEscapeTests[0]; i++) {
        const EscapeTest *tt = &queryEscapeTests[i];
        Str actual = url_query_escape(a, tt->in);
        if (!str_same(tt->out, actual))
            testing_t_errorf_v(t, "QueryEscape(%q) = %q, want %q", tt->in, actual,
                               tt->out);
        Error err;
        Str roundtrip = url_query_unescape(a, actual, &err);
        if (!str_same(roundtrip, tt->in) || BURROW_FAILED(err))
            testing_t_errorf_v(t, "QueryUnescape(%q) = %q, %s; want %q, [no error]",
                               actual, roundtrip, error_text(err), tt->in);
    }
    ARENA_END;
}

static void TestPathEscape(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof pathEscapeTests / sizeof pathEscapeTests[0]; i++) {
        const EscapeTest *tt = &pathEscapeTests[i];
        Str actual = url_path_escape(a, tt->in);
        if (!str_same(tt->out, actual))
            testing_t_errorf_v(t, "PathEscape(%q) = %q, want %q", tt->in, actual,
                               tt->out);
        Error err;
        Str roundtrip = url_path_unescape(a, actual, &err);
        if (!str_same(roundtrip, tt->in) || BURROW_FAILED(err))
            testing_t_errorf_v(t, "PathUnescape(%q) = %q, %s; want %q, [no error]",
                               actual, roundtrip, error_text(err), tt->in);
    }
    ARENA_END;
}

static void TestEncodeQuery(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof encodeQueryTests / sizeof encodeQueryTests[0]; i++) {
        const EncodeQueryTest *tt = &encodeQueryTests[i];
        Str q = url_values_encode(values_from(a, tt->m), a);
        if (!str_same(q, tt->expected))
            testing_t_errorf_v(t, "EncodeQuery(%d) = %q, want %q", (Int)i, q,
                               tt->expected);
    }
    ARENA_END;
}

static void TestResolvePath(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof resolvePathTests / sizeof resolvePathTests[0]; i++) {
        const ResolvePathTestsCase *test = &resolvePathTests[i];
        Str got = burrow__url_resolve_path(a, test->base, test->ref);
        if (!str_same(got, test->expected))
            testing_t_errorf_v(t, "For %q + %q got %q; expected %q", test->base,
                               test->ref, got, test->expected);
    }
    ARENA_END;
}

static void TestResolveReference(TestingT *t) {
    ARENA_BEGIN;
    const Url opaque = {.scheme = SI("scheme"), .opaque = SI("opaque")};
    for (size_t i = 0;
         i < sizeof resolveReferenceTests / sizeof resolveReferenceTests[0]; i++) {
        const ResolveReferenceTestsCase *test = &resolveReferenceTests[i];
        Error err;
        Url *base = url_parse(a, test->base, &err);
        if (BURROW_FAILED(err)) {
            testing_t_fatalf_v(t, "Parse(%q) got err %s", test->base, error_text(err));
            break;
        }
        Url *rel = url_parse(a, test->rel, &err);
        if (BURROW_FAILED(err)) {
            testing_t_fatalf_v(t, "Parse(%q) got err %s", test->rel, error_text(err));
            break;
        }
        Url *url = url_resolve_reference(base, a, rel);
        Str got = url_string(url, a);
        if (!str_same(got, test->expected))
            testing_t_errorf_v(t, "URL(%q).ResolveReference(%q)\ngot  %q\nwant %q",
                               test->base, test->rel, got, test->expected);
        if (base == url)
            testing_t_errorf_v(
                t, "Expected URL.ResolveReference to return new URL instance.");
        url = url_parse_ref(base, a, test->rel, &err);
        if (BURROW_FAILED(err)) {
            testing_t_errorf_v(t, "URL(%q).Parse(%q) failed: %s", test->base, test->rel,
                               error_text(err));
        } else if (!str_same(got = url_string(url, a), test->expected)) {
            testing_t_errorf_v(t, "URL(%q).Parse(%q)\ngot  %q\nwant %q", test->base,
                               test->rel, got, test->expected);
        } else if (base == url) {
            testing_t_errorf_v(t, "Expected URL.Parse to return new URL instance.");
        }
        url = url_resolve_reference(base, a, &opaque);
        if (!url_equal(url, &opaque))
            testing_t_errorf_v(
                t, "ResolveReference failed to resolve opaque URL:\ngot  %s\nwant %s",
                ufmt(a, url), ufmt(a, &opaque));
        url = url_parse_ref(base, a, S("scheme:opaque"), &err);
        if (BURROW_FAILED(err))
            testing_t_errorf_v(t, "URL(%q).Parse(\"scheme:opaque\") failed: %s",
                               test->base, error_text(err));
        else if (!url_equal(url, &opaque))
            testing_t_errorf_v(t,
                               "Parse failed to resolve opaque URL:\ngot  %s\nwant %s",
                               ufmt(a, &opaque), ufmt(a, url));
        else if (base == url)
            testing_t_errorf_v(t, "Expected URL.Parse to return new URL instance.");
    }
    ARENA_END;
}

static void TestQueryValues(TestingT *t) {
    ARENA_BEGIN;
    Url *u = url_parse(a, S("http://x.com?foo=bar&bar=1&bar=2&baz"), NULL);
    UrlValues v = url_query(u, a);
    if (map_len(v) != 3)
        testing_t_errorf_v(t, "got %d keys in Query values, want 3", map_len(v));
    Str g;
    if (!str_same(g = url_values_get(v, S("foo")), S("bar")))
        testing_t_errorf_v(t, "Get(foo) = %q, want %q", g, S("bar"));
    if (!str_same(g = url_values_get(v, S("Foo")), S("")))
        testing_t_errorf_v(t, "Get(Foo) = %q, want %q", g, S(""));
    if (!str_same(g = url_values_get(v, S("bar")), S("1")))
        testing_t_errorf_v(t, "Get(bar) = %q, want %q", g, S("1"));
    if (!str_same(g = url_values_get(v, S("baz")), S("")))
        testing_t_errorf_v(t, "Get(baz) = %q, want %q", g, S(""));
    CHECK(url_values_has(v, S("foo")));
    CHECK(url_values_has(v, S("bar")));
    CHECK(url_values_has(v, S("baz")));
    CHECK(!url_values_has(v, S("noexist")));
    url_values_del(v, S("bar"));
    if (!str_same(g = url_values_get(v, S("bar")), S("")))
        testing_t_errorf_v(t, "second Get(bar) = %q, want %q", g, S(""));
    ARENA_END;
}

static void TestParseQuery(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof parseTests / sizeof parseTests[0]; i++) {
        const ParseTest *test = &parseTests[i];
        Error err;
        UrlValues form = url_parse_query(a, test->query, &err);
        if (test->ok != BURROW_OK(err))
            testing_t_errorf_v(t, "%q: Unexpected error: %s, want %s", test->query,
                               error_text(err), test->ok ? "<nil>" : "<error>");
        UrlValues want = values_from(a, test->out);
        if (map_len(form) != map_len(want))
            testing_t_errorf_v(t, "%q: len(form) = %d, want %d", test->query,
                               map_len(form), map_len(want));
        const void *k;
        void *val;
        for (MapIter it = map_iter(want); map_next(&it, &k, &val);) {
            const Slice *evs = (const Slice *)val;
            const Slice *vs = (const Slice *)map_get(form, k);
            if (vs == NULL) {
                testing_t_errorf_v(t, "%q: Missing key %q", test->query,
                                   *(const Str *)k);
                continue;
            }
            if (vs->len != evs->len) {
                testing_t_errorf_v(t, "%q: len(form[%q]) = %d, want %d", test->query,
                                   *(const Str *)k, vs->len, evs->len);
                continue;
            }
            for (Int j = 0; j < evs->len; j++) {
                Str v = ((const Str *)vs->p)[j], ev = ((const Str *)evs->p)[j];
                if (!str_same(v, ev))
                    testing_t_errorf_v(t, "%q: form[%q][%d] = %q, want %q", test->query,
                                       *(const Str *)k, j, v, ev);
            }
        }
    }
    ARENA_END;
}

static void TestParseQueryLimits(TestingT *t) {
    static const struct {
        Int params;
        const char *godebug;
        bool want_err;
    } tests[] = {
        {10, "", false},
        {10000, "", false},
        {10001, "", true},
        {10, "urlmaxqueryparams=9", true},
        {10001, "urlmaxqueryparams=0", false},
    };
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof tests / sizeof tests[0]; i++) {
        burrow__url_godebug_set(tests[i].godebug);
        Int n = tests[i].params;
        /* "p0&p1&...", counted and then written. */
        Int size = 0;
        for (Int j = 0; j < n; j++)
            size += (j > 0) + 1 + (Int)snprintf(NULL, 0, "%lld", (long long)j);
        char *q = (char *)mem_alloc_nozero(a, (size_t)size + 1, 1);
        Int w = 0;
        for (Int j = 0; j < n; j++)
            w += (Int)snprintf(q + w, (size_t)(size + 1 - w), "%sp%lld",
                               j > 0 ? "&" : "", (long long)j);
        Error err;
        UrlValues got = url_parse_query(a, str_from_bytes(q, w), &err);
        if (BURROW_FAILED(err) != tests[i].want_err)
            testing_t_errorf_v(t,
                               "GODEBUG=%s ParseQuery(%d params) = %s, want error: %t",
                               tests[i].godebug, n, error_text(err), tests[i].want_err);
        if (BURROW_FAILED(err))
            continue;
        if (map_len(got) != n)
            testing_t_errorf_v(
                t, "GODEBUG=%s ParseQuery(%d params): got %d params, want %d",
                tests[i].godebug, n, map_len(got), n);
    }
    burrow__url_godebug_set(NULL);
    ARENA_END;
}

static void TestRequestURI(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof requritests / sizeof requritests[0]; i++) {
        const RequestURITest *tt = &requritests[i];
        Str s = url_request_uri(tt->url, a);
        if (!str_same(s, tt->out))
            testing_t_errorf_v(t, "%s.RequestURI() == %q (expected %q)",
                               ufmt(a, tt->url), s, tt->out);
    }
    ARENA_END;
}

static void TestParseFailure(TestingT *t) {
    ARENA_BEGIN;
    /* The first parse error is the one returned. */
    Error err;
    (void)url_parse_query(a, S("%gh&%ij"), &err);
    Str msg = error_text(err);
    if (!str_has(msg, "%gh"))
        testing_t_errorf_v(
            t, "ParseQuery(%q) returned error %q, want something containing %q",
            S("%gh&%ij"), msg, S("%gh"));
    ARENA_END;
}

static void TestParseErrors(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof parse_errors_tests / sizeof parse_errors_tests[0];
         i++) {
        const ParseErrorsTestsCase *tt = &parse_errors_tests[i];
        Error err;
        Url *u = url_parse(a, tt->in, &err);
        if (tt->wantErr) {
            if (BURROW_OK(err))
                testing_t_errorf_v(t, "Parse(%q) = %s; want an error", tt->in,
                                   ufmt(a, u));
            continue;
        }
        if (BURROW_FAILED(err))
            testing_t_errorf_v(t, "Parse(%q) = %s; want no error", tt->in,
                               error_text(err));
    }
    ARENA_END;
}

static void TestStarRequest(TestingT *t) {
    ARENA_BEGIN;
    Error err;
    Url *u = url_parse(a, S("*"), &err);
    if (BURROW_FAILED(err)) {
        testing_t_fatalf_v(t, "%s", error_text(err));
        ARENA_END;
        return;
    }
    Str got = url_request_uri(u, a);
    if (!str_same(got, S("*")))
        testing_t_errorf_v(t, "RequestURI = %q; want %q", got, S("*"));
    ARENA_END;
}

static void TestShouldEscape(TestingT *t) {
    for (size_t i = 0; i < sizeof shouldEscapeTests / sizeof shouldEscapeTests[0];
         i++) {
        const ShouldEscapeTest *tt = &shouldEscapeTests[i];
        if (burrow__url_should_escape(tt->in, tt->mode) != tt->escape)
            testing_t_errorf_v(t, "shouldEscape(%q, %d) returned %t; expected %t",
                               (int32_t)tt->in, tt->mode, !tt->escape, tt->escape);
    }
}

/* Go's timeoutError, temporaryError and timeoutTemporaryError. */

#define TIMEOUT_ERROR_FIELDS(F, T) F(T, bool, timeout, "")
BURROW_STRUCT_DECL(TimeoutError, TIMEOUT_ERROR_FIELDS);

static Str timeout_error_error(TimeoutError *e) {
    (void)e;
    return S("timeout error");
}

static bool timeout_error_timeout(TimeoutError *e) {
    return e->timeout;
}

#define TE_SIG_Error(IN, OUT) OUT(Str)
#define TE_SIG_Bool(IN, OUT) OUT(bool)
#define TIMEOUT_ERROR_METHODS(M, T)                                                    \
    M(T, Error, timeout_error_error, TE_SIG_Error)                                     \
    M(T, Timeout, timeout_error_timeout, TE_SIG_Bool)
BURROW_STRUCT_DEFINE_METHODS(TimeoutError, TIMEOUT_ERROR_FIELDS, TIMEOUT_ERROR_METHODS);

#define TEMPORARY_ERROR_FIELDS(F, T) F(T, bool, temporary, "")
BURROW_STRUCT_DECL(TemporaryError, TEMPORARY_ERROR_FIELDS);

static Str temporary_error_error(TemporaryError *e) {
    (void)e;
    return S("temporary error");
}

static bool temporary_error_temporary(TemporaryError *e) {
    return e->temporary;
}

#define TEMPORARY_ERROR_METHODS(M, T)                                                  \
    M(T, Error, temporary_error_error, TE_SIG_Error)                                   \
    M(T, Temporary, temporary_error_temporary, TE_SIG_Bool)
BURROW_STRUCT_DEFINE_METHODS(TemporaryError, TEMPORARY_ERROR_FIELDS,
                             TEMPORARY_ERROR_METHODS);

#define BOTH_ERROR_FIELDS(F, T)                                                        \
    F(T, bool, timeout, "")                                                            \
    F(T, bool, temporary, "")
BURROW_STRUCT_DECL(TimeoutTemporaryError, BOTH_ERROR_FIELDS);

static Str both_error_error(TimeoutTemporaryError *e) {
    (void)e;
    return S("timeout/temporary error");
}

static bool both_error_temporary(TimeoutTemporaryError *e) {
    return e->temporary;
}

static bool both_error_timeout(TimeoutTemporaryError *e) {
    return e->timeout;
}

#define BOTH_ERROR_METHODS(M, T)                                                       \
    M(T, Error, both_error_error, TE_SIG_Error)                                        \
    M(T, Temporary, both_error_temporary, TE_SIG_Bool)                                 \
    M(T, Timeout, both_error_timeout, TE_SIG_Bool)
BURROW_STRUCT_DEFINE_METHODS(TimeoutTemporaryError, BOTH_ERROR_FIELDS,
                             BOTH_ERROR_METHODS);

static Str timeout_vt_message(const void *self) {
    (void)self;
    return S("timeout error");
}

static const ErrorVT timeout_vt = {.self_type = &burrow_type_TimeoutError,
                                   .message = timeout_vt_message};
static const ErrorVT temporary_vt = {.self_type = &burrow_type_TemporaryError,
                                     .message = timeout_vt_message};
static const ErrorVT both_vt = {.self_type = &burrow_type_TimeoutTemporaryError,
                                .message = timeout_vt_message};

static void TestURLErrorImplementsNetError(TestingT *t) {
    for (size_t i = 0; i < sizeof netErrorTests / sizeof netErrorTests[0]; i++) {
        const NetErrorTestsCase *tt = &netErrorTests[i];
        TimeoutError te = {tt->timeout_field};
        TemporaryError pe = {tt->temporary_field};
        TimeoutTemporaryError be = {tt->timeout_field, tt->temporary_field};
        Error inner = io_eof;
        switch (tt->kind) {
        case NET_TIMEOUT:
            inner = (Error){&timeout_vt, &te};
            break;
        case NET_TEMPORARY:
            inner = (Error){&temporary_vt, &pe};
            break;
        case NET_BOTH:
            inner = (Error){&both_vt, &be};
            break;
        default:
            break;
        }
        UrlError e = {SI("Get"), SI("http://google.com/"), inner};
        if (url_error_timeout(&e) != tt->timeout) {
            testing_t_errorf_v(t, "%d: err.Timeout(): got %t, want %t", (Int)i + 1,
                               url_error_timeout(&e), tt->timeout);
            continue;
        }
        if (url_error_temporary(&e) != tt->temporary)
            testing_t_errorf_v(t, "%d: err.Temporary(): got %t, want %t", (Int)i + 1,
                               url_error_temporary(&e), tt->temporary);
    }
}

static void TestURLHostnameAndPort(TestingT *t) {
    for (size_t i = 0;
         i < sizeof url_hostname_and_port_tests / sizeof url_hostname_and_port_tests[0];
         i++) {
        const UrlHostnameAndPortTestsCase *tt = &url_hostname_and_port_tests[i];
        Url u = {.host = tt->in};
        Str host = url_hostname(&u), port = url_port(&u);
        if (!str_same(host, tt->host))
            testing_t_errorf_v(t, "Hostname for Host %q = %q; want %q", tt->in, host,
                               tt->host);
        if (!str_same(port, tt->port))
            testing_t_errorf_v(t, "Port for Host %q = %q; want %q", tt->in, port,
                               tt->port);
    }
}

/* Go's TestJSON and TestGob go through encoding/json and encoding/gob, which
 * are not ported yet. What they test is the MarshalBinary and UnmarshalBinary
 * round trip, which this does directly. */
static void TestMarshalBinary(TestingT *t) {
    ARENA_BEGIN;
    Error err;
    Url *u = url_parse(a, S("https://www.google.com/x?y=z"), &err);
    if (BURROW_FAILED(err)) {
        testing_t_fatalf_v(t, "%s", error_text(err));
        ARENA_END;
        return;
    }
    Slice b = url_marshal_binary(u, a, &err);
    CHECK(BURROW_OK(err));
    Url u1 = {.scheme = {0}};
    err = url_unmarshal_binary(&u1, a, b);
    CHECK(BURROW_OK(err));
    Str got = url_string(&u1, a), want = url_string(u, a);
    if (!str_same(got, want))
        testing_t_errorf_v(t, "decoded to: %s\nwant: %s\n", got, want);
    Slice c =
        url_append_binary(u, a, slice_append(a, slice_nil(TYPE_BYTE), "x:", 2), &err);
    CHECK(BURROW_OK(err));
    CHECK(str_same(str_from_bytes(c.p, c.len), S("x:https://www.google.com/x?y=z")));

    /* The same through the type's methods, which is how encoding finds them. */
    const Method *m = type_method_by_name(TYPE_URL, S("String"));
    CHECK(m != NULL);
    if (m != NULL) {
        Str s;
        void *rets[1] = {&s};
        method_call(m, u, NULL, rets);
        CHECK(str_same(s, want));
    }
    ARENA_END;
}

static void TestNilUser(TestingT *t) {
    ARENA_BEGIN;
    Error err;
    Url *u = url_parse(a, S("http://foo.com/"), &err);
    if (BURROW_FAILED(err)) {
        testing_t_fatalf_v(t, "parse err: %s", error_text(err));
        ARENA_END;
        return;
    }
    Str v = url_userinfo_username(u->user);
    if (v.len != 0)
        testing_t_fatalf_v(t, "expected empty username, got %s", v);
    bool ok;
    v = url_userinfo_password(u->user, &ok);
    if (v.len != 0 || ok)
        testing_t_fatalf_v(t, "expected empty password, got %s (%t)", v, ok);
    v = url_userinfo_string(u->user, a);
    if (v.len != 0)
        testing_t_fatalf_v(t, "expected empty string, got %s", v);
    ARENA_END;
}

static void TestInvalidUserPassword(TestingT *t) {
    ARENA_BEGIN;
    Error err;
    (void)url_parse(a, S("http://user^:passwo^rd@foo.com/"), &err);
    Str got = error_text(err);
    if (!str_has(got, "net/url: invalid userinfo"))
        testing_t_errorf_v(t, "error = %q; want substring %q", got,
                           S("net/url: invalid userinfo"));
    ARENA_END;
}

static void TestRejectControlCharacters(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof reject_control_characters_tests /
                               sizeof reject_control_characters_tests[0];
         i++) {
        Str s = reject_control_characters_tests[i];
        Error err;
        (void)url_parse(a, s, &err);
        Str got = error_text(err);
        if (!str_has(got, "net/url: invalid control character in URL"))
            testing_t_errorf_v(t, "Parse(%q) error = %q; want substring %q", s, got,
                               S("net/url: invalid control character in URL"));
    }
    Error err;
    (void)url_parse(a, S("http://foo.com/ctl\x80"), &err);
    if (BURROW_FAILED(err))
        testing_t_errorf_v(t, "error parsing URL with non-ASCII control byte: %s",
                           error_text(err));
    ARENA_END;
}

static void TestJoinPath(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof join_path_tests / sizeof join_path_tests[0]; i++) {
        const JoinPathTestsCase *tt = &join_path_tests[i];
        Slice elem = slice_from((void *)(uintptr_t)tt->elem, tt->elem_len, tt->elem_len,
                                TYPE_STRING);
        Error err;
        Str out = url_join_path_str(a, tt->base, elem, &err);
        if (!str_same(out, tt->out) || BURROW_OK(err) != (tt->out.len != 0))
            testing_t_errorf_v(t, "JoinPath(%q, %d elems) = %q, %s, want %q, %s",
                               tt->base, tt->elem_len, out, error_text(err), tt->out,
                               tt->out.len == 0 ? "non-nil error" : "nil");
        Url *u = url_parse(a, tt->base, &err);
        if (BURROW_FAILED(err)) {
            if (tt->out.len != 0)
                testing_t_errorf_v(t, "Parse(%q) = %s", tt->base, error_text(err));
            continue;
        }
        Str want = tt->out.len == 0 ? tt->base : tt->out;
        out = url_string(url_join_path(u, a, elem), a);
        if (!str_same(out, want))
            testing_t_errorf_v(t, "Parse(%q).JoinPath(%d elems) = %q, want %q",
                               tt->base, tt->elem_len, out, want);
    }
    /* The variadic form is the same thing. */
    Url *u = url_parse(a, S("https://go.googlesource.com/a"), NULL);
    Str got = url_string(url_join_path_v(u, a, 3, S("b"), S("../c"), S("d/")), a);
    CHECK(str_same(got, S("https://go.googlesource.com/a/c/d/")));
    ARENA_END;
}

static void TestParseStrictIpv6(TestingT *t) {
    ARENA_BEGIN;
    burrow__url_godebug_set("urlstrictcolons=0");
    for (size_t i = 0;
         i < sizeof parse_strict_ipv6_tests / sizeof parse_strict_ipv6_tests[0]; i++) {
        const ParseStrictIpv6TestsCase *tc = &parse_strict_ipv6_tests[i];
        Error err;
        (void)url_parse(a, tc->url, &err);
        if (BURROW_FAILED(err))
            testing_t_errorf_v(t, "Parse(%q) error = %s, want nil", tc->url,
                               error_text(err));
    }
    burrow__url_godebug_set(NULL);
    ARENA_END;
}

static void TestURLClone(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof url_clone_tests / sizeof url_clone_tests[0]; i++) {
        const UrlCloneTestsCase *tt = &url_clone_tests[i];
        Url *cloned = url_clone(tt->in, a);
        if (!url_equal(tt->in, cloned)) {
            testing_t_errorf_v(t, "%s: Differing values\n%s\n%s", tt->name,
                               ufmt(a, tt->in), ufmt(a, cloned));
            continue;
        }
        if (tt->in == NULL)
            continue;
        if (tt->in == cloned) {
            testing_t_errorf_v(t, "%s: URL: same pointer returned", tt->name);
            continue;
        }
        cloned->scheme = S("https");
        if (str_same(cloned->scheme, tt->in->scheme))
            testing_t_errorf_v(t,
                               "%s: Inconsistent state: cloned.scheme changed and "
                               "reflected in the input's scheme",
                               tt->name);
        if (url_equal(tt->in, cloned))
            testing_t_errorf_v(
                t,
                "%s: Inconsistent state: cloned and input are somehow the "
                "same",
                tt->name);
        if (!user_equal(tt->in->user, cloned->user))
            testing_t_errorf_v(t, "%s: Differing .User", tt->name);
        if (tt->in->user != NULL && tt->in->user == cloned->user)
            testing_t_errorf_v(t, "%s: .User: same pointer returned", tt->name);
        url_free(a, cloned);
    }
    ARENA_END;
}

static void TestValuesClone(TestingT *t) {
    ARENA_BEGIN;
    for (size_t i = 0; i < sizeof values_clone_tests / sizeof values_clone_tests[0];
         i++) {
        const ValuesCloneTestsCase *tt = &values_clone_tests[i];
        Str name = tt->name;
        UrlValues in = values_from(a, tt->in);
        UrlValues cloned1 = url_values_clone(in, a);
        if (!values_equal(in, cloned1)) {
            testing_t_errorf_v(t, "%s: reflect.DeepEqual failed", name);
            continue;
        }
        if (cloned1 == NULL && in == NULL)
            continue;
        Str ab[2] = {SI("a"), SI("b")};
        Str xk = S("XXXXXXXXXXX");
        Slice abs = slice_from(ab, 2, 2, TYPE_STRING);
        map_set(cloned1, &xk, &abs);
        if (values_equal(in, cloned1)) {
            testing_t_errorf_v(
                t,
                "%s: Inconsistent state: cloned and input are somehow the "
                "same",
                name);
            continue;
        }
        UrlValues cloned2 = url_values_clone(in, a);
        url_values_add(cloned2, S("a"), S("A"));
        if (!url_values_has(cloned2, S("a")))
            testing_t_errorf_v(t, "%s: Cloned doesn't have the desired key: a", name);
        if (values_equal(in, cloned2)) {
            testing_t_errorf_v(t,
                               "%s: reflect.DeepEqual unexpectedly passed after modify "
                               "cloned",
                               name);
            continue;
        }
        url_values_del(cloned2, S("a"));
        if (!values_equal(in, cloned2)) {
            testing_t_errorf_v(t, "%s: reflect.DeepEqual failed", name);
            continue;
        }
        UrlValues cloned3 = url_values_clone(in, a);
        if (map_len(cloned3) == 0)
            continue;
        const void *k0;
        MapIter it = map_iter(cloned3);
        (void)map_next(&it, &k0, NULL);
        Str key0 = *(const Str *)k0;
        Slice *vs = (Slice *)map_get(cloned3, &key0);
        if (vs->len == 0) {
            Str golang = S("golang");
            *vs = slice_append(a, *vs, &golang, 1);
        } else {
            ((Str *)vs->p)[0] = S("directly modified");
            Str g = url_values_get(cloned3, key0);
            if (!str_same(g, S("directly modified")))
                testing_t_errorf_v(t, "%s: Get failed:\n\tGot:  %q\n\tWant: %q", name,
                                   g, S("directly modified"));
        }
        if (values_equal(in, cloned3)) {
            testing_t_errorf_v(t,
                               "%s: reflect.DeepEqual unexpectedly passed after modify "
                               "cloned",
                               name);
            continue;
        }
        UrlValues cloned4 = url_values_clone(in, a);
        url_values_set(cloned4, key0, S("good night"));
        if (values_equal(in, cloned4))
            testing_t_errorf_v(t,
                               "%s: reflect.DeepEqual unexpectedly passed after modify "
                               "cloned",
                               name);
        Str g = url_values_get(cloned4, key0);
        if (!str_same(g, S("good night")))
            testing_t_errorf_v(t, "%s: Get failed:\n\tGot:  %q\n\tWant: %q", name, g,
                               S("good night"));
    }
    ARENA_END;
}

/* Not in Go's tests: the error types and their texts. */
static void TestErrorTexts(TestingT *t) {
    ARENA_BEGIN;
    Error err;
    (void)url_parse(a, S("http://[::1]:namedport"), &err);
    CHECK(str_same(
        error_text(err),
        S("parse \"http://[::1]:namedport\": invalid port \":namedport\" after host")));
    const UrlError *ue = (const UrlError *)errors_as(err, TYPE_URL_ERROR);
    CHECK(ue != NULL);
    if (ue != NULL) {
        CHECK(str_same(ue->op, S("parse")));
        CHECK(str_same(ue->url, S("http://[::1]:namedport")));
        CHECK(str_same(url_error_error(ue, a), error_text(err)));
    }

    (void)url_parse(a, S("http://a b.com/#frag"), &err);
    CHECK(
        str_same(error_text(err),
                 S("parse \"http://a b.com/\": invalid character \" \" in host name")));
    const Str *he = (const Str *)errors_as(err, TYPE_URL_INVALID_HOST_ERROR);
    CHECK(he != NULL);
    if (he != NULL)
        CHECK(str_same(*he, S(" ")));

    (void)url_parse(a, S("http://x/%zz#%yy"), &err);
    CHECK(str_same(error_text(err),
                   S("parse \"http://x/%zz\": invalid URL escape \"%zz\"")));
    (void)url_parse(a, S("http://x/#%yy"), &err);
    CHECK(str_same(error_text(err),
                   S("parse \"http://x/#%yy\": invalid URL escape \"%yy\"")));

    CHECK(str_same(url_escape_error_error(S("%4"), a), S("invalid URL escape \"%4\"")));
    CHECK(str_same(url_invalid_host_error_error(S("<"), a),
                   S("invalid character \"<\" in host name")));
    Error e1 = url_escape_error_as_error(S("%4"), a);
    Error e2 = url_escape_error_as_error(S("%4"), a);
    CHECK(errors_is(e1, e2));
    CHECK(!errors_is(e1, url_invalid_host_error_as_error(S("%4"), a)));

    (void)url_parse(a, S(":foo"), &err);
    CHECK(str_same(error_text(err), S("parse \":foo\": missing protocol scheme")));
    (void)url_parse_request_uri(a, S(""), &err);
    CHECK(str_same(error_text(err), S("parse \"\": empty url")));
    (void)url_parse(a, S("http://[fe80::1%en0]/"), &err);
    CHECK(str_same(error_text(err),
                   S("parse \"http://[fe80::1%en0]/\": invalid URL escape \"%en\"")));
    (void)url_parse(a, S("http://[192.168.0.1]/"), &err);
    CHECK(str_same(error_text(err),
                   S("parse \"http://[192.168.0.1]/\": invalid IP-literal")));
    ARENA_END;
}

/* A Url from url_parse is one block, so url_free under a checking allocator
 * has to give back exactly what was taken, on success and on failure. */
static void TestParseFree(TestingT *t) {
    static const char *const ins[] = {
        "http://user:p%40ss@[fe80::1%25en0]:8080/a%20b/c?q=1#f%20g",
        "mailto:x@y",
        "http://[::1]:bad",
        "http://x/%zz",
        "",
        "*",
    };
    Track tr;
    track_init(&tr, heap_allocator());
    Alloc *a = track_allocator(&tr);
    for (size_t i = 0; i < sizeof ins / sizeof ins[0]; i++) {
        Error err;
        Url *u = url_parse(a, str_from_cstr(ins[i]), &err);
        if (u != NULL) {
            Url *c = url_clone(u, a);
            CHECK(url_equal(u, c));
            url_free(a, c);
            Url *r = url_resolve_reference(u, a, &(const Url){.path = SI("../x y")});
            url_free(a, r);
            Url *j = url_join_path_v(u, a, 2, S("p q"), S(".."));
            url_free(a, j);
        }
        url_free(a, u);
    }
    CHECK(track_check(&tr) == 0);
    track_free(&tr);
}

#define TESTS(X)                                                                       \
    X(TestParse)                                                                       \
    X(TestParseRequestURI)                                                             \
    X(TestURLString)                                                                   \
    X(TestURLRedacted)                                                                 \
    X(TestUnescape)                                                                    \
    X(TestQueryEscape)                                                                 \
    X(TestPathEscape)                                                                  \
    X(TestEncodeQuery)                                                                 \
    X(TestResolvePath)                                                                 \
    X(TestResolveReference)                                                            \
    X(TestQueryValues)                                                                 \
    X(TestParseQuery)                                                                  \
    X(TestParseQueryLimits)                                                            \
    X(TestRequestURI)                                                                  \
    X(TestParseFailure)                                                                \
    X(TestParseErrors)                                                                 \
    X(TestStarRequest)                                                                 \
    X(TestShouldEscape)                                                                \
    X(TestURLErrorImplementsNetError)                                                  \
    X(TestURLHostnameAndPort)                                                          \
    X(TestMarshalBinary)                                                               \
    X(TestNilUser)                                                                     \
    X(TestInvalidUserPassword)                                                         \
    X(TestRejectControlCharacters)                                                     \
    X(TestJoinPath)                                                                    \
    X(TestParseStrictIpv6)                                                             \
    X(TestURLClone)                                                                    \
    X(TestValuesClone)                                                                 \
    X(TestErrorTexts)                                                                  \
    X(TestParseFree)
TESTING_MAIN(TESTS)
