/* Derived from Go's src/vendor/golang.org/x/text/unicode/bidi/tables17.0.0.go.
 * Go source: go1.27.1, golang.org/x/text v0.37.0.
 *
 * Generated by tools/gen-xtext-bidi.sh from the Go tables. Do not edit.
 *
 * Copyright 2015 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#ifndef BURROW_SRC_XTEXT_BIDI_TABLES_H
#define BURROW_SRC_XTEXT_BIDI_TABLES_H

#include "bidi.h"

#include <stdint.h>

/* clang-format off */

#define BIDI_UNICODE_VERSION "17.0.0"

extern const int32_t burrow__bidi_xor_masks[8];
extern const uint8_t burrow__bidi_values[17280];
extern const uint16_t burrow__bidi_index[1664];

/* clang-format on */

#endif /* BURROW_SRC_XTEXT_BIDI_TABLES_H */
