/* Derived from Go's src/vendor/golang.org/x/net/idna/tables17.0.0.go.
 * Go source: go1.27.1, golang.org/x/net v0.55.1-0.20260731170536-c1d18010be90.
 *
 * Generated by tools/gen-xnet-idna.sh from the Go tables. Do not edit.
 *
 * Copyright 2016 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#ifndef BURROW_SRC_XNET_IDNA_TABLES_H
#define BURROW_SRC_XNET_IDNA_TABLES_H

#include "idna.h"

#include <stdint.h>

/* clang-format off */

#define IDNA_UNICODE_VERSION "17.0.0"
#define IDNA_CUTOFF 136

/* One record of a sparse trie block. The first record of a block is a
 * header, with the stride in value and the record count in lo. */
typedef struct IdnaValueRange {
    uint16_t value;
    uint8_t lo, hi;
} IdnaValueRange;

extern const uint8_t burrow__idna_mappings[6720];
extern const uint16_t burrow__idna_mapping_index[1735];
extern const uint8_t burrow__idna_xor_data[4945];
extern const uint16_t burrow__idna_values[8832];
extern const uint16_t burrow__idna_index[2496];
extern const uint16_t burrow__idna_sparse_offset[315];
extern const IdnaValueRange burrow__idna_sparse_values[2288];

/* clang-format on */

#endif /* BURROW_SRC_XNET_IDNA_TABLES_H */
