/* Derived from Go's fixture_test.go.
 * Go source: go1.27.1.
 *
 * Generated by burrow-gen tests and then translated by hand: the tables are
 * mechanical, and every test that still skips has Go left in it to port.
 *
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include <math.h>

#include "check.h"

#include "burrow/strconv.h"

#define S BURROW_S
#define SI BURROW_S_INIT

typedef struct QuoteTest {
    Str in;
    Str out;
    Rune r;
    const Error *err;
    void (*quote)(void); /* func(string) string */
} QuoteTest;

typedef struct NumberTest {
    Int i;
    int64_t i64;
    uint64_t u64;
    double f;
    float f32;
    bool ok;
    Str b;
} NumberTest;

typedef struct Nested {
    Str name;
    const Str *words;
    Int words_len;
    StrconvNumError num;
    const StrconvNumError *ptr;
    double pair[2];
} Nested;

typedef struct LocalTableTestsCase {
    Str in;
    Str want;
    const Error *err;
} LocalTableTestsCase;

static const QuoteTest quotetests[] = {
    {SI(""), SI("\"\""), 'a', NULL, (void (*)(void))strconv_quote},
    {SI("\a\b\f\r\n\t\v\\\""), SI("\"\\a\\b\\f\\r\\n\\t\\v\\\\\\\"\""), '\n',
     &strconv_err_syntax, NULL},
    {SI("\xff"
        "fe"),
     SI("\"\\xfffe\""), '\\', &strconv_err_range, (void (*)(void))strconv_quote},
    {SI("☺\xc2\xa0\xf4\x8f\xbf\xbf"), SI("?\?="), 0x263a, NULL, NULL},
};

static const NumberTest numbertests[] = {
    {0, INT64_MIN, UINT64_C(18446744073709551615), 1.5, 0.1f, true, SI("abc")},
    {INT32_MIN, INT64_C(1099511627776), 7, (double)INFINITY, NAN, false, {0}},
    {1000, -1, UINT64_C(9223372036854775808), -0.0, 3.4028235e+38f, true,
     SI("\x00\x01\xff")},
};

static const Nested nestedtests[] BURROW_UNUSED = {
    {.name = SI("ababab!"), .words = (const Str[]){SI("a"), SI("b")}, .words_len = 2},
    {.name = SI("keyed"),
     .num = {.func = SI("ParseInt"),
             .num = SI("x"),
             .err = /* by hand: ErrSyntax */ {0}},
     .ptr = &(const StrconvNumError){.func = SI("Atoi"),
                                     .err = /* by hand: ErrRange */ {0}},
     .pair = {1.0, -2.0},
     .words = NULL,
     .words_len = 0},
    {.name = SI("by hand"),
     .words = /* by hand: strings.Fields(" a b ") */ NULL,
     .words_len = 0},
};

static const double pairs[][2] = {
    {1.0, 2.0},
    {-(double)INFINITY, 0.0},
};

static const Str plain[] BURROW_UNUSED = {
    SI("one"),
    SI("two"),
};

static const LocalTableTestsCase local_table_tests[] = {
    {SI("\"a\""), SI("a"), NULL},
    {SI("'"), SI(""), &strconv_err_syntax},
};

static void TestQuote(TestingT *t) {
    for (size_t i = 0; i < sizeof quotetests / sizeof quotetests[0]; i++) {
        const QuoteTest *tt = &quotetests[i];
        (void)tt;
        /* Go, with tt as a pointer now:
         *     if got := Quote(tt.in); got != tt.out {
         *         t.Errorf("Quote(%q) = %q, want %q", tt.in, got, tt.out)
         *     }
         */
    }
    testing_t_skip_v(t, "burrow-gen tests: the loop body is still Go");
}

static void TestNumbers(TestingT *t) {
    /* Go, before the loop:
     *     var n int
     */
    for (size_t i = 0; i < sizeof numbertests / sizeof numbertests[0]; i++) {
        (void)numbertests[i];
        /* Go:
         *     n += numbertests[i].i
         */
    }
    /* Go, after the loop:
     *     if n == 0 {
     *         t.Log("zero")
     *     }
     */
    testing_t_skip_v(t, "burrow-gen tests: the loop body is still Go");
}

static void TestLocalTable(TestingT *t) {
    for (size_t i = 0; i < sizeof local_table_tests / sizeof local_table_tests[0];
         i++) {
        const LocalTableTestsCase *tc = &local_table_tests[i];
        (void)tc;
        /* Go, with tc as a pointer now:
         *     got, err := Unquote(tc.in)
         *     if got != tc.want || err != tc.err {
         *         t.Errorf("%d: Unquote(%q) = %q, %v", i, tc.in, got, err)
         *     }
         */
    }
    testing_t_skip_v(t, "burrow-gen tests: the loop body is still Go");
}

static void TestPairs(TestingT *t) {
    (void)plain;
    (void)nestedtests;
    for (size_t i = 0; i < sizeof pairs / sizeof pairs[0]; i++) {
        const double *p = pairs[i];
        (void)p;
        /* Go, with p as a pointer now:
         *     _ = p
         */
    }
    /* Go, after the loop:
     *     _ = plain
     *     _ = nestedtests
     */
    testing_t_skip_v(t, "burrow-gen tests: the loop body is still Go");
}

static void TestNotATable(TestingT *t) {
    /* Go, from fixture_test.go:118:
     *     if Quote("x") != "x" {
     *         t.Fatal("/ * not * / a table")
     *     }
     */
    testing_t_skip_v(t, "burrow-gen tests: not table driven, port by hand");
}

/* Not generated, and still to port by hand:
 *     BenchmarkQuote
 */

#define TESTS(X)                                                                       \
    X(TestQuote)                                                                       \
    X(TestNumbers)                                                                     \
    X(TestLocalTable)                                                                  \
    X(TestPairs)                                                                       \
    X(TestNotATable)

TESTING_MAIN(TESTS)
