/* Derived from Go's src/crypto/internal/fips140/nistec/p384.go.
 * Go source: go1.27.1.
 *
 * The P-384 group: its field elements, on fiat-crypto's arithmetic in
 * fiat_p384_64.h or fiat_p384_32.h, and its points, with the complete addition
 * formulas and a four bit window for scalar multiplication.
 *
 * Generated by tools/gen-nistec.sh from Go's p384.go, fiat/p384.go and
 * fiat/p384_invert.go; do not edit.
 *
 * Copyright 2022 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "nistec.h"

#include "fiat_p384_32.h"
#include "fiat_p384_64.h"

#include "burrow/core.h"
#include "burrow/crypto/subtle.h"
#include "burrow/error.h"
#include "burrow/func.h"
#include "burrow/panic.h"
#include "burrow/slice.h"
#include "burrow/sync.h"

#include <stdint.h>
#include <string.h>

/* NOLINTNEXTLINE(misc-redundant-expression) */
_Static_assert(FIAT_P384_LIMBS == NISTEC_P384_LIMBS,
               "nistec.h has the wrong number of words for a P-384 element");
_Static_assert(sizeof(fiat_p384_limb) == sizeof(NistecLimb),
               "nistec.h has the wrong word for a P-384 element");

enum { p384_element_length = 48 };

static void p384_reverse(uint8_t *v) {
    for (int i = 0; i < p384_element_length / 2; i++) {
        uint8_t t = v[i];
        v[i] = v[p384_element_length - 1 - i];
        v[p384_element_length - 1 - i] = t;
    }
}

/* ------------------------------------------------------------- element */

static NistecP384Element *p384_one(NistecP384Element *e) {
    fiat_p384_set_one(e->l);
    return e;
}

static NistecP384Element *p384_add(NistecP384Element *e, const NistecP384Element *t1,
                                   const NistecP384Element *t2) {
    fiat_p384_add(e->l, t1->l, t2->l);
    return e;
}

static NistecP384Element *p384_sub(NistecP384Element *e, const NistecP384Element *t1,
                                   const NistecP384Element *t2) {
    fiat_p384_sub(e->l, t1->l, t2->l);
    return e;
}

static NistecP384Element *p384_mul(NistecP384Element *e, const NistecP384Element *t1,
                                   const NistecP384Element *t2) {
    fiat_p384_mul(e->l, t1->l, t2->l);
    return e;
}

static NistecP384Element *p384_square(NistecP384Element *e,
                                      const NistecP384Element *t) {
    fiat_p384_square(e->l, t->l);
    return e;
}

/* Writes the 48 byte big endian encoding of e to out. */
static void p384_bytes(const NistecP384Element *e, uint8_t *out) {
    fiat_p384_non_montgomery_domain_field_element tmp;
    fiat_p384_from_montgomery(tmp, e->l);
    fiat_p384_to_bytes(out, tmp);
    p384_reverse(out);
}

static void p384_from_canonical_bytes(NistecP384Element *e, const uint8_t *in) {
    fiat_p384_non_montgomery_domain_field_element tmp;
    fiat_p384_from_bytes(tmp, in);
    fiat_p384_to_montgomery(e->l, tmp);
}

static int p384_equal(const NistecP384Element *e, const NistecP384Element *t) {
    uint8_t eb[p384_element_length], tb[p384_element_length];
    p384_bytes(e, eb);
    p384_bytes(t, tb);
    return burrow__nistec_equal_bytes(eb, tb, p384_element_length);
}

static int p384_is_zero(const NistecP384Element *e) {
    uint8_t eb[p384_element_length], zero[p384_element_length];
    memset(zero, 0, sizeof zero);
    p384_bytes(e, eb);
    return burrow__nistec_equal_bytes(eb, zero, p384_element_length);
}

/* Sets e to the value of the 48 big endian bytes at v. Go's SetBytes also
 * takes a slice of the wrong length, which nothing here passes it. */
static NistecP384Element *p384_set_bytes(NistecP384Element *e, const uint8_t *v,
                                         Error *err) {
    /* Check for non-canonical encodings (p + k, 2p + k, etc.) by comparing to
     * the encoding of -1 mod p, so p - 1, the highest canonical encoding. */
    NistecP384Element zero, one, minus_one;
    uint8_t minus_one_encoding[p384_element_length];
    memset(&zero, 0, sizeof zero);
    p384_bytes(p384_sub(&minus_one, &zero, p384_one(&one)), minus_one_encoding);
    if (burrow__nistec_less_or_eq_bytes(v, minus_one_encoding, p384_element_length) ==
        0) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("invalid P384Element encoding")));
        return NULL;
    }
    uint8_t in[p384_element_length];
    memcpy(in, v, sizeof in);
    p384_reverse(in);
    p384_from_canonical_bytes(e, in);
    return e;
}

/* Sets v to a if cond is 1 and to b if cond is 0. */
static NistecP384Element *p384_select(NistecP384Element *v, const NistecP384Element *a,
                                      const NistecP384Element *b, int cond) {
    fiat_p384_selectznz(v->l, (fiat_p384_uint1)cond, b->l, a->l);
    return v;
}

/* Sets e to 1/x and returns e. If x is 0, the result is 0. Inversion is
 * exponentiation by p - 2. */
static NistecP384Element *p384_invert(NistecP384Element *e,
                                      const NistecP384Element *x) {
    NistecP384Element z_, t0_, t1_, t2_, t3_;
    NistecP384Element *z = &z_, *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_;
    /* Inversion is implemented as exponentiation with exponent p − 2.
     * The sequence of 15 multiplications and 383 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10     = 2*1
     * _11     = 1 + _10
     * _110    = 2*_11
     * _111    = 1 + _110
     * _111000 = _111 << 3
     * _111111 = _111 + _111000
     * x12     = _111111 << 6 + _111111
     * x24     = x12 << 12 + x12
     * x30     = x24 << 6 + _111111
     * x31     = 2*x30 + 1
     * x32     = 2*x31 + 1
     * x63     = x32 << 31 + x31
     * x126    = x63 << 63 + x63
     * x252    = x126 << 126 + x126
     * x255    = x252 << 3 + _111
     * i397    = ((x255 << 33 + x32) << 94 + x30) << 2
     * return    1 + i397 */
    p384_square(z, x);
    p384_mul(z, x, z);
    p384_square(z, z);
    p384_mul(t1, x, z);
    p384_square(z, t1);
    for (int s = 1; s < 3; s++)
        p384_square(z, z);
    p384_mul(z, t1, z);
    p384_square(t0, z);
    for (int s = 1; s < 6; s++)
        p384_square(t0, t0);
    p384_mul(t0, z, t0);
    p384_square(t2, t0);
    for (int s = 1; s < 12; s++)
        p384_square(t2, t2);
    p384_mul(t0, t0, t2);
    for (int s = 0; s < 6; s++)
        p384_square(t0, t0);
    p384_mul(z, z, t0);
    p384_square(t0, z);
    p384_mul(t2, x, t0);
    p384_square(t0, t2);
    p384_mul(t0, x, t0);
    p384_square(t3, t0);
    for (int s = 1; s < 31; s++)
        p384_square(t3, t3);
    p384_mul(t2, t2, t3);
    p384_square(t3, t2);
    for (int s = 1; s < 63; s++)
        p384_square(t3, t3);
    p384_mul(t2, t2, t3);
    p384_square(t3, t2);
    for (int s = 1; s < 126; s++)
        p384_square(t3, t3);
    p384_mul(t2, t2, t3);
    for (int s = 0; s < 3; s++)
        p384_square(t2, t2);
    p384_mul(t1, t1, t2);
    for (int s = 0; s < 33; s++)
        p384_square(t1, t1);
    p384_mul(t0, t0, t1);
    for (int s = 0; s < 94; s++)
        p384_square(t0, t0);
    p384_mul(z, z, t0);
    for (int s = 0; s < 2; s++)
        p384_square(z, z);
    p384_mul(z, x, z);

    *e = *z;
    return e;
}

/* Sets z to a square root candidate for x. z and x must not overlap. */
static void p384_sqrt_candidate(NistecP384Element *z, const NistecP384Element *x) {
    NistecP384Element t0_, t1_, t2_;
    NistecP384Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_;
    /* Since p = 3 mod 4, exponentiation by (p + 1) / 4 yields a square root candidate.
     *
     * The sequence of 14 multiplications and 381 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10      = 2*1
     * _11      = 1 + _10
     * _110     = 2*_11
     * _111     = 1 + _110
     * _111000  = _111 << 3
     * _111111  = _111 + _111000
     * _1111110 = 2*_111111
     * _1111111 = 1 + _1111110
     * x12      = _1111110 << 5 + _111111
     * x24      = x12 << 12 + x12
     * x31      = x24 << 7 + _1111111
     * x32      = 2*x31 + 1
     * x63      = x32 << 31 + x31
     * x126     = x63 << 63 + x63
     * x252     = x126 << 126 + x126
     * x255     = x252 << 3 + _111
     * return     ((x255 << 33 + x32) << 64 + 1) << 30 */
    p384_square(z, x);
    p384_mul(z, x, z);
    p384_square(z, z);
    p384_mul(t0, x, z);
    p384_square(z, t0);
    for (int s = 1; s < 3; s++)
        p384_square(z, z);
    p384_mul(t1, t0, z);
    p384_square(t2, t1);
    p384_mul(z, x, t2);
    for (int s = 0; s < 5; s++)
        p384_square(t2, t2);
    p384_mul(t1, t1, t2);
    p384_square(t2, t1);
    for (int s = 1; s < 12; s++)
        p384_square(t2, t2);
    p384_mul(t1, t1, t2);
    for (int s = 0; s < 7; s++)
        p384_square(t1, t1);
    p384_mul(t1, z, t1);
    p384_square(z, t1);
    p384_mul(z, x, z);
    p384_square(t2, z);
    for (int s = 1; s < 31; s++)
        p384_square(t2, t2);
    p384_mul(t1, t1, t2);
    p384_square(t2, t1);
    for (int s = 1; s < 63; s++)
        p384_square(t2, t2);
    p384_mul(t1, t1, t2);
    p384_square(t2, t1);
    for (int s = 1; s < 126; s++)
        p384_square(t2, t2);
    p384_mul(t1, t1, t2);
    for (int s = 0; s < 3; s++)
        p384_square(t1, t1);
    p384_mul(t0, t0, t1);
    for (int s = 0; s < 33; s++)
        p384_square(t0, t0);
    p384_mul(z, z, t0);
    for (int s = 0; s < 64; s++)
        p384_square(z, z);
    p384_mul(z, x, z);
    for (int s = 0; s < 30; s++)
        p384_square(z, z);
}

/* Sets e to a square root of x. If x is not a square, returns 0 and leaves e
 * unchanged. e and x can overlap. */
static int p384_sqrt(NistecP384Element *e, const NistecP384Element *x) {
    NistecP384Element candidate, square;
    p384_sqrt_candidate(&candidate, x);
    p384_square(&square, &candidate);
    if (p384_equal(&square, x) != 1)
        return 0;
    *e = candidate;
    return 1;
}

/* --------------------------------------------------------------- point */

/* b, the constant of the curve, set the first time something needs it. */
static NistecP384Element p384_b_value;
static SyncOnce p384_b_once;

static void p384_b_init(void *env) {
    (void)env;
    static const uint8_t b[p384_element_length] = {
        0xb3, 0x31, 0x2f, 0xa7, 0xe2, 0x3e, 0xe7, 0xe4, 0x98, 0x8e, 0x05, 0x6b,
        0xe3, 0xf8, 0x2d, 0x19, 0x18, 0x1d, 0x9c, 0x6e, 0xfe, 0x81, 0x41, 0x12,
        0x03, 0x14, 0x08, 0x8f, 0x50, 0x13, 0x87, 0x5a, 0xc6, 0x56, 0x39, 0x8d,
        0x8a, 0x2e, 0xd1, 0x9d, 0x2a, 0x85, 0xc8, 0xed, 0xd3, 0xec, 0x2a, 0xef,
    };
    p384_set_bytes(&p384_b_value, b, NULL);
}

static const NistecP384Element *p384_b(void) {
    sync_once_do(&p384_b_once, BURROW_FN(Func, p384_b_init, NULL));
    return &p384_b_value;
}

/* Sets p to the point at infinity. */
static NistecP384Point *p384_point_new(NistecP384Point *p) {
    memset(&p->x, 0, sizeof p->x);
    p384_one(&p->y);
    memset(&p->z, 0, sizeof p->z);
    return p;
}

static NistecP384Point *p384_point_set_generator(NistecP384Point *p) {
    static const uint8_t x[p384_element_length] = {
        0xaa, 0x87, 0xca, 0x22, 0xbe, 0x8b, 0x05, 0x37, 0x8e, 0xb1, 0xc7, 0x1e,
        0xf3, 0x20, 0xad, 0x74, 0x6e, 0x1d, 0x3b, 0x62, 0x8b, 0xa7, 0x9b, 0x98,
        0x59, 0xf7, 0x41, 0xe0, 0x82, 0x54, 0x2a, 0x38, 0x55, 0x02, 0xf2, 0x5d,
        0xbf, 0x55, 0x29, 0x6c, 0x3a, 0x54, 0x5e, 0x38, 0x72, 0x76, 0x0a, 0xb7,
    };
    static const uint8_t y[p384_element_length] = {
        0x36, 0x17, 0xde, 0x4a, 0x96, 0x26, 0x2c, 0x6f, 0x5d, 0x9e, 0x98, 0xbf,
        0x92, 0x92, 0xdc, 0x29, 0xf8, 0xf4, 0x1d, 0xbd, 0x28, 0x9a, 0x14, 0x7c,
        0xe9, 0xda, 0x31, 0x13, 0xb5, 0xf0, 0xb8, 0xc0, 0x0a, 0x60, 0xb1, 0xce,
        0x1d, 0x7e, 0x81, 0x9d, 0x7a, 0x43, 0x1d, 0x7c, 0x90, 0xea, 0x0e, 0x5f,
    };
    p384_set_bytes(&p->x, x, NULL);
    p384_set_bytes(&p->y, y, NULL);
    p384_one(&p->z);
    return p;
}

/* Sets y2 to x^3 - 3x + b, and returns y2. */
static NistecP384Element *p384_polynomial(NistecP384Element *y2,
                                          const NistecP384Element *x) {
    p384_square(y2, x);
    p384_mul(y2, y2, x);

    NistecP384Element three_x;
    p384_add(&three_x, x, x);
    p384_add(&three_x, &three_x, x);
    p384_sub(y2, y2, &three_x);

    return p384_add(y2, y2, p384_b());
}

static int p384_check_on_curve(const NistecP384Element *x, const NistecP384Element *y,
                               Error *err) {
    /* y^2 = x^3 - 3x + b */
    NistecP384Element rhs, lhs;
    p384_polynomial(&rhs, x);
    p384_square(&lhs, y);
    if (p384_equal(&rhs, &lhs) != 1) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("P384 point not on curve")));
        return 0;
    }
    return 1;
}

/* Sets p to the compressed, uncompressed, or infinity value encoded in b, as
 * specified in SEC 1, Version 2.0, Section 2.3.4. If the point is not on the
 * curve, it returns NULL and an error, and the receiver is unchanged.
 * Otherwise, it returns p. */
static NistecP384Point *p384_point_set_bytes(NistecP384Point *p, Slice b, Error *err) {
    const uint8_t *bb = b.p;
    NistecP384Element x, y;

    /* Point at infinity. */
    if (b.len == 1 && bb[0] == 0)
        return p384_point_new(p);

    /* Uncompressed form. */
    if (b.len == 1 + 2 * p384_element_length && bb[0] == 4) {
        if (p384_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;
        if (p384_set_bytes(&y, bb + 1 + p384_element_length, err) == NULL)
            return NULL;
        if (!p384_check_on_curve(&x, &y, err))
            return NULL;
        p->x = x;
        p->y = y;
        p384_one(&p->z);
        return p;
    }

    /* Compressed form. */
    if (b.len == 1 + p384_element_length && (bb[0] == 2 || bb[0] == 3)) {
        if (p384_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;

        /* y^2 = x^3 - 3x + b */
        p384_polynomial(&y, &x);
        if (!p384_sqrt(&y, &y)) {
            BURROW_OUT(err,
                       errors_new(error_allocator(),
                                  BURROW_S("invalid P384 compressed point encoding")));
            return NULL;
        }

        /* Select the positive or negative root, as indicated by the least
         * significant bit, based on the encoding type byte. */
        NistecP384Element other_root;
        memset(&other_root, 0, sizeof other_root);
        p384_sub(&other_root, &other_root, &y);
        uint8_t yb[p384_element_length];
        p384_bytes(&y, yb);
        int cond = (yb[p384_element_length - 1] & 1) ^ (bb[0] & 1);
        p384_select(&y, &other_root, &y, cond);

        p->x = x;
        p->y = y;
        p384_one(&p->z);
        return p;
    }

    BURROW_OUT(err,
               errors_new(error_allocator(), BURROW_S("invalid P384 point encoding")));
    return NULL;
}

/* Writes the uncompressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p384_point_bytes(const NistecP384Point *p, uint8_t *out) {
    /* The SEC 1 representation of the point at infinity is a single zero byte,
     * and only infinity has z = 0. */
    if (p384_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP384Element zinv, x, y;
    p384_invert(&zinv, &p->z);
    p384_mul(&x, &p->x, &zinv);
    p384_mul(&y, &p->y, &zinv);

    out[0] = 4;
    p384_bytes(&x, out + 1);
    p384_bytes(&y, out + 1 + p384_element_length);
    return 1 + 2 * p384_element_length;
}

/* Writes the encoding of the x-coordinate of p, as specified in SEC 1, Version
 * 2.0, Section 2.3.5, or returns NULL and an error if p is the point at
 * infinity. */
static uint8_t *p384_point_bytes_x(const NistecP384Point *p, uint8_t *out, Error *err) {
    if (p384_is_zero(&p->z) == 1) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("P384 point is the point at infinity")));
        return NULL;
    }

    NistecP384Element zinv, x;
    p384_invert(&zinv, &p->z);
    p384_mul(&x, &p->x, &zinv);

    p384_bytes(&x, out);
    return out;
}

/* Writes the compressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p384_point_bytes_compressed(const NistecP384Point *p, uint8_t *out) {
    if (p384_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP384Element zinv, x, y;
    p384_invert(&zinv, &p->z);
    p384_mul(&x, &p->x, &zinv);
    p384_mul(&y, &p->y, &zinv);

    /* Encode the sign of the y coordinate (indicated by the least significant
     * bit) as the encoding type (2 or 3). */
    uint8_t yb[p384_element_length];
    p384_bytes(&y, yb);
    out[0] = (uint8_t)(2 | (yb[p384_element_length - 1] & 1));
    p384_bytes(&x, out + 1);
    return 1 + p384_element_length;
}

/* Sets q = p1 + p2, and returns q. The points may overlap. */
static NistecP384Point *p384_point_add(NistecP384Point *q, const NistecP384Point *p1,
                                       const NistecP384Point *p2) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP384Element t0_, t1_, t2_, t3_, t4_, x3_, y3_, z3_;
    NistecP384Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_, *t4 = &t4_;
    NistecP384Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP384Element *b = p384_b();

    p384_mul(t0, &p1->x, &p2->x); /* t0 := X1 * X2 */
    p384_mul(t1, &p1->y, &p2->y); /* t1 := Y1 * Y2 */
    p384_mul(t2, &p1->z, &p2->z); /* t2 := Z1 * Z2 */
    p384_add(t3, &p1->x, &p1->y); /* t3 := X1 + Y1 */
    p384_add(t4, &p2->x, &p2->y); /* t4 := X2 + Y2 */
    p384_mul(t3, t3, t4);         /* t3 := t3 * t4 */
    p384_add(t4, t0, t1);         /* t4 := t0 + t1 */
    p384_sub(t3, t3, t4);         /* t3 := t3 - t4 */
    p384_add(t4, &p1->y, &p1->z); /* t4 := Y1 + Z1 */
    p384_add(x3, &p2->y, &p2->z); /* X3 := Y2 + Z2 */
    p384_mul(t4, t4, x3);         /* t4 := t4 * X3 */
    p384_add(x3, t1, t2);         /* X3 := t1 + t2 */
    p384_sub(t4, t4, x3);         /* t4 := t4 - X3 */
    p384_add(x3, &p1->x, &p1->z); /* X3 := X1 + Z1 */
    p384_add(y3, &p2->x, &p2->z); /* Y3 := X2 + Z2 */
    p384_mul(x3, x3, y3);         /* X3 := X3 * Y3 */
    p384_add(y3, t0, t2);         /* Y3 := t0 + t2 */
    p384_sub(y3, x3, y3);         /* Y3 := X3 - Y3 */
    p384_mul(z3, b, t2);          /* Z3 := b * t2 */
    p384_sub(x3, y3, z3);         /* X3 := Y3 - Z3 */
    p384_add(z3, x3, x3);         /* Z3 := X3 + X3 */
    p384_add(x3, x3, z3);         /* X3 := X3 + Z3 */
    p384_sub(z3, t1, x3);         /* Z3 := t1 - X3 */
    p384_add(x3, t1, x3);         /* X3 := t1 + X3 */
    p384_mul(y3, b, y3);          /* Y3 := b * Y3 */
    p384_add(t1, t2, t2);         /* t1 := t2 + t2 */
    p384_add(t2, t1, t2);         /* t2 := t1 + t2 */
    p384_sub(y3, y3, t2);         /* Y3 := Y3 - t2 */
    p384_sub(y3, y3, t0);         /* Y3 := Y3 - t0 */
    p384_add(t1, y3, y3);         /* t1 := Y3 + Y3 */
    p384_add(y3, t1, y3);         /* Y3 := t1 + Y3 */
    p384_add(t1, t0, t0);         /* t1 := t0 + t0 */
    p384_add(t0, t1, t0);         /* t0 := t1 + t0 */
    p384_sub(t0, t0, t2);         /* t0 := t0 - t2 */
    p384_mul(t1, t4, y3);         /* t1 := t4 * Y3 */
    p384_mul(t2, t0, y3);         /* t2 := t0 * Y3 */
    p384_mul(y3, x3, z3);         /* Y3 := X3 * Z3 */
    p384_add(y3, y3, t2);         /* Y3 := Y3 + t2 */
    p384_mul(x3, t3, x3);         /* X3 := t3 * X3 */
    p384_sub(x3, x3, t1);         /* X3 := X3 - t1 */
    p384_mul(z3, t4, z3);         /* Z3 := t4 * Z3 */
    p384_mul(t1, t3, t0);         /* t1 := t3 * t0 */
    p384_add(z3, z3, t1);         /* Z3 := Z3 + t1 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q = p + p, and returns q. The points may overlap. */
static NistecP384Point *p384_point_double(NistecP384Point *q,
                                          const NistecP384Point *p) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP384Element t0_, t1_, t2_, t3_, x3_, y3_, z3_;
    NistecP384Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_;
    NistecP384Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP384Element *b = p384_b();

    p384_square(t0, &p->x);     /* t0 := X ^ 2 */
    p384_square(t1, &p->y);     /* t1 := Y ^ 2 */
    p384_square(t2, &p->z);     /* t2 := Z ^ 2 */
    p384_mul(t3, &p->x, &p->y); /* t3 := X * Y */
    p384_add(t3, t3, t3);       /* t3 := t3 + t3 */
    p384_mul(z3, &p->x, &p->z); /* Z3 := X * Z */
    p384_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p384_mul(y3, b, t2);        /* Y3 := b * t2 */
    p384_sub(y3, y3, z3);       /* Y3 := Y3 - Z3 */
    p384_add(x3, y3, y3);       /* X3 := Y3 + Y3 */
    p384_add(y3, x3, y3);       /* Y3 := X3 + Y3 */
    p384_sub(x3, t1, y3);       /* X3 := t1 - Y3 */
    p384_add(y3, t1, y3);       /* Y3 := t1 + Y3 */
    p384_mul(y3, x3, y3);       /* Y3 := X3 * Y3 */
    p384_mul(x3, x3, t3);       /* X3 := X3 * t3 */
    p384_add(t3, t2, t2);       /* t3 := t2 + t2 */
    p384_add(t2, t2, t3);       /* t2 := t2 + t3 */
    p384_mul(z3, b, z3);        /* Z3 := b * Z3 */
    p384_sub(z3, z3, t2);       /* Z3 := Z3 - t2 */
    p384_sub(z3, z3, t0);       /* Z3 := Z3 - t0 */
    p384_add(t3, z3, z3);       /* t3 := Z3 + Z3 */
    p384_add(z3, z3, t3);       /* Z3 := Z3 + t3 */
    p384_add(t3, t0, t0);       /* t3 := t0 + t0 */
    p384_add(t0, t3, t0);       /* t0 := t3 + t0 */
    p384_sub(t0, t0, t2);       /* t0 := t0 - t2 */
    p384_mul(t0, t0, z3);       /* t0 := t0 * Z3 */
    p384_add(y3, y3, t0);       /* Y3 := Y3 + t0 */
    p384_mul(t0, &p->y, &p->z); /* t0 := Y * Z */
    p384_add(t0, t0, t0);       /* t0 := t0 + t0 */
    p384_mul(z3, t0, z3);       /* Z3 := t0 * Z3 */
    p384_sub(x3, x3, z3);       /* X3 := X3 - Z3 */
    p384_mul(z3, t0, t1);       /* Z3 := t0 * t1 */
    p384_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p384_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q to p1 if cond == 1, and to p2 if cond == 0. */
static NistecP384Point *p384_point_select(NistecP384Point *q, const NistecP384Point *p1,
                                          const NistecP384Point *p2, int cond) {
    p384_select(&q->x, &p1->x, &p2->x, cond);
    p384_select(&q->y, &p1->y, &p2->y, cond);
    p384_select(&q->z, &p1->z, &p2->z, cond);
    return q;
}

/* ------------------------------------------------- scalar multiplication */

/* The first 15 multiples of a point at offset -1, so [1]P is at table[0],
 * [15]P is at table[14], and [0]P is implicitly the identity point. */
typedef struct P384Table {
    NistecP384Point p[15];
} P384Table;

/* Selects the n-th multiple of the table base point into p. It works in
 * constant time by iterating over every entry of the table. n must be in
 * [0, 15]. */
static void p384_table_select(const P384Table *table, NistecP384Point *p, uint8_t n) {
    if (n >= 16)
        panic_str(BURROW_S(
            "nistec: internal error: p384Table called with out-of-bounds value"));
    p384_point_new(p);
    for (uint8_t i = 1; i < 16; i++) {
        int cond = (int)subtle_constant_time_byte_eq(i, n);
        p384_point_select(p, &table->p[i - 1], p, cond);
    }
}

/* Sets p = scalar * q, and returns p. */
static NistecP384Point *p384_point_scalar_mult(NistecP384Point *p,
                                               const NistecP384Point *q, Slice scalar,
                                               Error *err) {
    (void)err;
    const uint8_t *s = scalar.p;

    /* Compute a table for the base point q. */
    P384Table table;
    table.p[0] = *q;
    for (int i = 1; i < 15; i += 2) {
        p384_point_double(&table.p[i], &table.p[i / 2]);
        p384_point_add(&table.p[i + 1], &table.p[i], q);
    }

    /* Instead of doing the classic double-and-add chain, we do it with a
     * four-bit window: we double four times, and then add [0-15]P. */
    NistecP384Point t;
    p384_point_new(&t);
    p384_point_new(p);
    for (Int i = 0; i < scalar.len; i++) {
        /* No need to double on the first iteration, as p is the identity at
         * this point, and [N]inf = inf. */
        if (i != 0) {
            p384_point_double(p, p);
            p384_point_double(p, p);
            p384_point_double(p, p);
            p384_point_double(p, p);
        }

        uint8_t window_value = (uint8_t)(s[i] >> 4);
        p384_table_select(&table, &t, window_value);
        p384_point_add(p, p, &t);

        p384_point_double(p, p);
        p384_point_double(p, p);
        p384_point_double(p, p);
        p384_point_double(p, p);

        window_value = s[i] & 0xf;
        p384_table_select(&table, &t, window_value);
        p384_point_add(p, p, &t);
    }

    return p;
}

/* A sequence of tables, built the first time a base multiplication needs it.
 * The first table contains multiples of G. Each successive table is the
 * previous table doubled four times. */
static P384Table p384_generator_table[p384_element_length * 2];
static SyncOnce p384_generator_table_once;

static void p384_generator_table_init(void *env) {
    (void)env;
    NistecP384Point base;
    p384_point_set_generator(&base);
    for (int i = 0; i < p384_element_length * 2; i++) {
        p384_generator_table[i].p[0] = base;
        for (int j = 1; j < 15; j++)
            p384_point_add(&p384_generator_table[i].p[j],
                           &p384_generator_table[i].p[j - 1], &base);
        p384_point_double(&base, &base);
        p384_point_double(&base, &base);
        p384_point_double(&base, &base);
        p384_point_double(&base, &base);
    }
}

/* Sets p = scalar * B, where B is the canonical generator, and returns p. */
static NistecP384Point *p384_point_scalar_base_mult(NistecP384Point *p, Slice scalar,
                                                    Error *err) {
    if (scalar.len != p384_element_length) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("invalid scalar length")));
        return NULL;
    }
    sync_once_do(&p384_generator_table_once,
                 BURROW_FN(Func, p384_generator_table_init, NULL));
    const uint8_t *s = scalar.p;

    /* This is also a scalar multiplication with a four-bit window like in
     * ScalarMult, but in this case the doublings are precomputed. The value
     * [windowValue]G added at iteration k would normally get doubled
     * (totIterations-k)x4 times, but with a larger precomputation we can
     * instead add [2^((totIterations-k)x4)][windowValue]G and avoid the
     * doublings between iterations. */
    NistecP384Point t;
    p384_point_new(&t);
    p384_point_new(p);
    int table_index = p384_element_length * 2 - 1;
    for (Int i = 0; i < scalar.len; i++) {
        uint8_t window_value = (uint8_t)(s[i] >> 4);
        p384_table_select(&p384_generator_table[table_index], &t, window_value);
        p384_point_add(p, p, &t);
        table_index--;

        window_value = s[i] & 0xf;
        p384_table_select(&p384_generator_table[table_index], &t, window_value);
        p384_point_add(p, p, &t);
        table_index--;
    }

    return p;
}

/* ---------------------------------------------------------------- curve */

static NistecPoint *p384_v_point_new(NistecPoint *p) {
    p384_point_new(&p->p384);
    return p;
}

static NistecPoint *p384_v_set_generator(NistecPoint *p) {
    p384_point_set_generator(&p->p384);
    return p;
}

static NistecPoint *p384_v_set(NistecPoint *p, const NistecPoint *q) {
    p->p384 = q->p384;
    return p;
}

static NistecPoint *p384_v_set_bytes(NistecPoint *p, Slice b, Error *err) {
    return p384_point_set_bytes(&p->p384, b, err) == NULL ? NULL : p;
}

static Int p384_v_bytes(const NistecPoint *p, uint8_t *out) {
    return p384_point_bytes(&p->p384, out);
}

static uint8_t *p384_v_bytes_x(const NistecPoint *p, uint8_t *out, Error *err) {
    return p384_point_bytes_x(&p->p384, out, err);
}

static Int p384_v_bytes_compressed(const NistecPoint *p, uint8_t *out) {
    return p384_point_bytes_compressed(&p->p384, out);
}

static NistecPoint *p384_v_add(NistecPoint *q, const NistecPoint *p1,
                               const NistecPoint *p2) {
    p384_point_add(&q->p384, &p1->p384, &p2->p384);
    return q;
}

static NistecPoint *p384_v_double(NistecPoint *q, const NistecPoint *p) {
    p384_point_double(&q->p384, &p->p384);
    return q;
}

static NistecPoint *p384_v_scalar_mult(NistecPoint *p, const NistecPoint *q,
                                       Slice scalar, Error *err) {
    return p384_point_scalar_mult(&p->p384, &q->p384, scalar, err) == NULL ? NULL : p;
}

static NistecPoint *p384_v_scalar_base_mult(NistecPoint *p, Slice scalar, Error *err) {
    return p384_point_scalar_base_mult(&p->p384, scalar, err) == NULL ? NULL : p;
}

const NistecCurve burrow__nistec_p384 = {
    "P-384",
    p384_element_length,
    p384_v_point_new,
    p384_v_set_generator,
    p384_v_set,
    p384_v_set_bytes,
    p384_v_bytes,
    p384_v_bytes_x,
    p384_v_bytes_compressed,
    p384_v_add,
    p384_v_double,
    p384_v_scalar_mult,
    p384_v_scalar_base_mult,
};
