/* Derived from Go's src/crypto/internal/fips140/nistec/p224.go.
 * Go source: go1.27.1.
 *
 * The P-224 group: its field elements, on fiat-crypto's arithmetic in
 * fiat_p224_64.h or fiat_p224_32.h, and its points, with the complete addition
 * formulas and a four bit window for scalar multiplication.
 *
 * Generated by tools/gen-nistec.sh from Go's p224.go, p224_sqrt.go,
 * fiat/p224.go and fiat/p224_invert.go; do not edit.
 *
 * Copyright 2022 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "nistec.h"

#include "fiat_p224_32.h"
#include "fiat_p224_64.h"

#include "burrow/core.h"
#include "burrow/crypto/subtle.h"
#include "burrow/error.h"
#include "burrow/func.h"
#include "burrow/panic.h"
#include "burrow/slice.h"
#include "burrow/sync.h"

#include <stdint.h>
#include <string.h>

/* NOLINTNEXTLINE(misc-redundant-expression) */
_Static_assert(FIAT_P224_LIMBS == NISTEC_P224_LIMBS,
               "nistec.h has the wrong number of words for a P-224 element");
_Static_assert(sizeof(fiat_p224_limb) == sizeof(NistecLimb),
               "nistec.h has the wrong word for a P-224 element");

enum { p224_element_length = 28 };

static void p224_reverse(uint8_t *v) {
    for (int i = 0; i < p224_element_length / 2; i++) {
        uint8_t t = v[i];
        v[i] = v[p224_element_length - 1 - i];
        v[p224_element_length - 1 - i] = t;
    }
}

/* ------------------------------------------------------------- element */

static NistecP224Element *p224_one(NistecP224Element *e) {
    fiat_p224_set_one(e->l);
    return e;
}

static NistecP224Element *p224_add(NistecP224Element *e, const NistecP224Element *t1,
                                   const NistecP224Element *t2) {
    fiat_p224_add(e->l, t1->l, t2->l);
    return e;
}

static NistecP224Element *p224_sub(NistecP224Element *e, const NistecP224Element *t1,
                                   const NistecP224Element *t2) {
    fiat_p224_sub(e->l, t1->l, t2->l);
    return e;
}

static NistecP224Element *p224_mul(NistecP224Element *e, const NistecP224Element *t1,
                                   const NistecP224Element *t2) {
    fiat_p224_mul(e->l, t1->l, t2->l);
    return e;
}

static NistecP224Element *p224_square(NistecP224Element *e,
                                      const NistecP224Element *t) {
    fiat_p224_square(e->l, t->l);
    return e;
}

/* Writes the 28 byte big endian encoding of e to out. */
static void p224_bytes(const NistecP224Element *e, uint8_t *out) {
    fiat_p224_non_montgomery_domain_field_element tmp;
    fiat_p224_from_montgomery(tmp, e->l);
    fiat_p224_to_bytes(out, tmp);
    p224_reverse(out);
}

static void p224_from_canonical_bytes(NistecP224Element *e, const uint8_t *in) {
    fiat_p224_non_montgomery_domain_field_element tmp;
    fiat_p224_from_bytes(tmp, in);
    fiat_p224_to_montgomery(e->l, tmp);
}

static int p224_equal(const NistecP224Element *e, const NistecP224Element *t) {
    uint8_t eb[p224_element_length], tb[p224_element_length];
    p224_bytes(e, eb);
    p224_bytes(t, tb);
    return burrow__nistec_equal_bytes(eb, tb, p224_element_length);
}

static int p224_is_zero(const NistecP224Element *e) {
    uint8_t eb[p224_element_length], zero[p224_element_length];
    memset(zero, 0, sizeof zero);
    p224_bytes(e, eb);
    return burrow__nistec_equal_bytes(eb, zero, p224_element_length);
}

/* Sets e to the value of the 28 big endian bytes at v. Go's SetBytes also
 * takes a slice of the wrong length, which nothing here passes it. */
static NistecP224Element *p224_set_bytes(NistecP224Element *e, const uint8_t *v,
                                         Error *err) {
    /* Check for non-canonical encodings (p + k, 2p + k, etc.) by comparing to
     * the encoding of -1 mod p, so p - 1, the highest canonical encoding. */
    NistecP224Element zero, one, minus_one;
    uint8_t minus_one_encoding[p224_element_length];
    memset(&zero, 0, sizeof zero);
    p224_bytes(p224_sub(&minus_one, &zero, p224_one(&one)), minus_one_encoding);
    if (burrow__nistec_less_or_eq_bytes(v, minus_one_encoding, p224_element_length) ==
        0) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("invalid P224Element encoding")));
        return NULL;
    }
    uint8_t in[p224_element_length];
    memcpy(in, v, sizeof in);
    p224_reverse(in);
    p224_from_canonical_bytes(e, in);
    return e;
}

/* Sets v to a if cond is 1 and to b if cond is 0. */
static NistecP224Element *p224_select(NistecP224Element *v, const NistecP224Element *a,
                                      const NistecP224Element *b, int cond) {
    fiat_p224_selectznz(v->l, (fiat_p224_uint1)cond, b->l, a->l);
    return v;
}

/* Sets e to 1/x and returns e. If x is 0, the result is 0. Inversion is
 * exponentiation by p - 2. */
static NistecP224Element *p224_invert(NistecP224Element *e,
                                      const NistecP224Element *x) {
    NistecP224Element z_, t0_, t1_, t2_;
    NistecP224Element *z = &z_, *t0 = &t0_, *t1 = &t1_, *t2 = &t2_;
    /* Inversion is implemented as exponentiation with exponent p − 2.
     * The sequence of 11 multiplications and 223 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10     = 2*1
     * _11     = 1 + _10
     * _110    = 2*_11
     * _111    = 1 + _110
     * _111000 = _111 << 3
     * _111111 = _111 + _111000
     * x12     = _111111 << 6 + _111111
     * x14     = x12 << 2 + _11
     * x17     = x14 << 3 + _111
     * x31     = x17 << 14 + x14
     * x48     = x31 << 17 + x17
     * x96     = x48 << 48 + x48
     * x127    = x96 << 31 + x31
     * return    x127 << 97 + x96 */
    p224_square(z, x);
    p224_mul(t0, x, z);
    p224_square(z, t0);
    p224_mul(z, x, z);
    p224_square(t1, z);
    for (int s = 1; s < 3; s++)
        p224_square(t1, t1);
    p224_mul(t1, z, t1);
    p224_square(t2, t1);
    for (int s = 1; s < 6; s++)
        p224_square(t2, t2);
    p224_mul(t1, t1, t2);
    for (int s = 0; s < 2; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    p224_square(t1, t0);
    for (int s = 1; s < 3; s++)
        p224_square(t1, t1);
    p224_mul(z, z, t1);
    p224_square(t1, z);
    for (int s = 1; s < 14; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    p224_square(t1, t0);
    for (int s = 1; s < 17; s++)
        p224_square(t1, t1);
    p224_mul(z, z, t1);
    p224_square(t1, z);
    for (int s = 1; s < 48; s++)
        p224_square(t1, t1);
    p224_mul(z, z, t1);
    p224_square(t1, z);
    for (int s = 1; s < 31; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    for (int s = 0; s < 97; s++)
        p224_square(t0, t0);
    p224_mul(z, z, t0);

    *e = *z;
    return e;
}

/* GG[j] = g^(2^j) for j from 0 to 95, where g = 11^q, built the first time a
 * square root needs it. */
static NistecP224Element p224_gg[96];
static SyncOnce p224_gg_once;

static void p224_gg_init(void *env) {
    (void)env;
    static const uint8_t g[p224_element_length] = {
        0x6a, 0x0f, 0xec, 0x67, 0x85, 0x98, 0xa7, 0x92, 0x0c, 0x55,
        0xb2, 0xd4, 0x0b, 0x2d, 0x6f, 0xfb, 0xbe, 0xa3, 0xd8, 0xce,
        0xf3, 0xfb, 0x36, 0x32, 0xdc, 0x69, 0x1b, 0x74,
    };
    p224_set_bytes(&p224_gg[0], g, NULL);
    for (int i = 1; i < 96; i++)
        p224_square(&p224_gg[i], &p224_gg[i - 1]);
}

/* Sets r to a square root candidate for x. r and x must not overlap. */
static void p224_sqrt_candidate(NistecP224Element *r, const NistecP224Element *x) {
    /* Since p = 1 mod 4, we can't use the exponentiation by (p + 1) / 4 like
     * for the other primes. Instead, implement a variation of Tonelli-Shanks.
     * The constant-time implementation is adapted from Thomas Pornin's ecGFp5.
     *
     * https://github.com/pornin/ecgfp5/blob/82325b965/rust/src/field.rs#L337-L385
     *
     * p = q*2^n + 1 with q odd -> q = 2^128 - 1 and n = 96
     * g^(2^n) = 1 -> g = 11 ^ q (where 11 is the smallest non-square)
     * GG[j] = g^(2^j) for j = 0 to n-1 */
    sync_once_do(&p224_gg_once, BURROW_FN(Func, p224_gg_init, NULL));

    /* r <- x^((q+1)/2) = x^(2^127)
     * v <- x^q = x^(2^128-1)
     *
     * Compute x^(2^127-1) first. */
    NistecP224Element t0_, t1_;
    NistecP224Element *t0 = &t0_, *t1 = &t1_;
    /* The sequence of 10 multiplications and 126 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10      = 2*1
     * _11      = 1 + _10
     * _110     = 2*_11
     * _111     = 1 + _110
     * _111000  = _111 << 3
     * _111111  = _111 + _111000
     * _1111110 = 2*_111111
     * _1111111 = 1 + _1111110
     * x12      = _1111110 << 5 + _111111
     * x24      = x12 << 12 + x12
     * i36      = x24 << 7
     * x31      = _1111111 + i36
     * x48      = i36 << 17 + x24
     * x96      = x48 << 48 + x48
     * return     x96 << 31 + x31 */
    p224_square(r, x);
    p224_mul(r, x, r);
    p224_square(r, r);
    p224_mul(r, x, r);
    p224_square(t0, r);
    for (int s = 1; s < 3; s++)
        p224_square(t0, t0);
    p224_mul(t0, r, t0);
    p224_square(t1, t0);
    p224_mul(r, x, t1);
    for (int s = 0; s < 5; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    p224_square(t1, t0);
    for (int s = 1; s < 12; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    p224_square(t1, t0);
    for (int s = 1; s < 7; s++)
        p224_square(t1, t1);
    p224_mul(r, r, t1);
    for (int s = 0; s < 17; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    p224_square(t1, t0);
    for (int s = 1; s < 48; s++)
        p224_square(t1, t1);
    p224_mul(t0, t0, t1);
    for (int s = 0; s < 31; s++)
        p224_square(t0, t0);
    p224_mul(r, r, t0);

    /* v = x^(2^127-1)^2 * x */
    NistecP224Element v;
    p224_square(&v, r);
    p224_mul(&v, &v, x);

    /* r = x^(2^127-1) * x */
    p224_mul(r, r, x);

    /* for i = n-1 down to 1:
     *     w = v^(2^(i-1))
     *     if w == -1 then:
     *         v <- v*GG[n-i]
     *         r <- r*GG[n-i-1] */
    NistecP224Element zero, one, minus_one;
    memset(&zero, 0, sizeof zero);
    p224_sub(&minus_one, &zero, p224_one(&one));

    for (int i = 96 - 1; i >= 1; i--) {
        NistecP224Element w = v;
        for (int j = 0; j < i - 1; j++)
            p224_square(&w, &w);
        int cond = p224_equal(&w, &minus_one);
        p224_select(&v, p224_mul(t0, &v, &p224_gg[96 - i]), &v, cond);
        p224_select(r, p224_mul(t0, r, &p224_gg[96 - i - 1]), r, cond);
    }
}

/* Sets e to a square root of x. If x is not a square, returns 0 and leaves e
 * unchanged. e and x can overlap. */
static int p224_sqrt(NistecP224Element *e, const NistecP224Element *x) {
    NistecP224Element candidate, square;
    p224_sqrt_candidate(&candidate, x);
    p224_square(&square, &candidate);
    if (p224_equal(&square, x) != 1)
        return 0;
    *e = candidate;
    return 1;
}

/* --------------------------------------------------------------- point */

/* b, the constant of the curve, set the first time something needs it. */
static NistecP224Element p224_b_value;
static SyncOnce p224_b_once;

static void p224_b_init(void *env) {
    (void)env;
    static const uint8_t b[p224_element_length] = {
        0xb4, 0x05, 0x0a, 0x85, 0x0c, 0x04, 0xb3, 0xab, 0xf5, 0x41,
        0x32, 0x56, 0x50, 0x44, 0xb0, 0xb7, 0xd7, 0xbf, 0xd8, 0xba,
        0x27, 0x0b, 0x39, 0x43, 0x23, 0x55, 0xff, 0xb4,
    };
    p224_set_bytes(&p224_b_value, b, NULL);
}

static const NistecP224Element *p224_b(void) {
    sync_once_do(&p224_b_once, BURROW_FN(Func, p224_b_init, NULL));
    return &p224_b_value;
}

/* Sets p to the point at infinity. */
static NistecP224Point *p224_point_new(NistecP224Point *p) {
    memset(&p->x, 0, sizeof p->x);
    p224_one(&p->y);
    memset(&p->z, 0, sizeof p->z);
    return p;
}

static NistecP224Point *p224_point_set_generator(NistecP224Point *p) {
    static const uint8_t x[p224_element_length] = {
        0xb7, 0x0e, 0x0c, 0xbd, 0x6b, 0xb4, 0xbf, 0x7f, 0x32, 0x13,
        0x90, 0xb9, 0x4a, 0x03, 0xc1, 0xd3, 0x56, 0xc2, 0x11, 0x22,
        0x34, 0x32, 0x80, 0xd6, 0x11, 0x5c, 0x1d, 0x21,
    };
    static const uint8_t y[p224_element_length] = {
        0xbd, 0x37, 0x63, 0x88, 0xb5, 0xf7, 0x23, 0xfb, 0x4c, 0x22,
        0xdf, 0xe6, 0xcd, 0x43, 0x75, 0xa0, 0x5a, 0x07, 0x47, 0x64,
        0x44, 0xd5, 0x81, 0x99, 0x85, 0x00, 0x7e, 0x34,
    };
    p224_set_bytes(&p->x, x, NULL);
    p224_set_bytes(&p->y, y, NULL);
    p224_one(&p->z);
    return p;
}

/* Sets y2 to x^3 - 3x + b, and returns y2. */
static NistecP224Element *p224_polynomial(NistecP224Element *y2,
                                          const NistecP224Element *x) {
    p224_square(y2, x);
    p224_mul(y2, y2, x);

    NistecP224Element three_x;
    p224_add(&three_x, x, x);
    p224_add(&three_x, &three_x, x);
    p224_sub(y2, y2, &three_x);

    return p224_add(y2, y2, p224_b());
}

static int p224_check_on_curve(const NistecP224Element *x, const NistecP224Element *y,
                               Error *err) {
    /* y^2 = x^3 - 3x + b */
    NistecP224Element rhs, lhs;
    p224_polynomial(&rhs, x);
    p224_square(&lhs, y);
    if (p224_equal(&rhs, &lhs) != 1) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("P224 point not on curve")));
        return 0;
    }
    return 1;
}

/* Sets p to the compressed, uncompressed, or infinity value encoded in b, as
 * specified in SEC 1, Version 2.0, Section 2.3.4. If the point is not on the
 * curve, it returns NULL and an error, and the receiver is unchanged.
 * Otherwise, it returns p. */
static NistecP224Point *p224_point_set_bytes(NistecP224Point *p, Slice b, Error *err) {
    const uint8_t *bb = b.p;
    NistecP224Element x, y;

    /* Point at infinity. */
    if (b.len == 1 && bb[0] == 0)
        return p224_point_new(p);

    /* Uncompressed form. */
    if (b.len == 1 + 2 * p224_element_length && bb[0] == 4) {
        if (p224_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;
        if (p224_set_bytes(&y, bb + 1 + p224_element_length, err) == NULL)
            return NULL;
        if (!p224_check_on_curve(&x, &y, err))
            return NULL;
        p->x = x;
        p->y = y;
        p224_one(&p->z);
        return p;
    }

    /* Compressed form. */
    if (b.len == 1 + p224_element_length && (bb[0] == 2 || bb[0] == 3)) {
        if (p224_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;

        /* y^2 = x^3 - 3x + b */
        p224_polynomial(&y, &x);
        if (!p224_sqrt(&y, &y)) {
            BURROW_OUT(err,
                       errors_new(error_allocator(),
                                  BURROW_S("invalid P224 compressed point encoding")));
            return NULL;
        }

        /* Select the positive or negative root, as indicated by the least
         * significant bit, based on the encoding type byte. */
        NistecP224Element other_root;
        memset(&other_root, 0, sizeof other_root);
        p224_sub(&other_root, &other_root, &y);
        uint8_t yb[p224_element_length];
        p224_bytes(&y, yb);
        int cond = (yb[p224_element_length - 1] & 1) ^ (bb[0] & 1);
        p224_select(&y, &other_root, &y, cond);

        p->x = x;
        p->y = y;
        p224_one(&p->z);
        return p;
    }

    BURROW_OUT(err,
               errors_new(error_allocator(), BURROW_S("invalid P224 point encoding")));
    return NULL;
}

/* Writes the uncompressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p224_point_bytes(const NistecP224Point *p, uint8_t *out) {
    /* The SEC 1 representation of the point at infinity is a single zero byte,
     * and only infinity has z = 0. */
    if (p224_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP224Element zinv, x, y;
    p224_invert(&zinv, &p->z);
    p224_mul(&x, &p->x, &zinv);
    p224_mul(&y, &p->y, &zinv);

    out[0] = 4;
    p224_bytes(&x, out + 1);
    p224_bytes(&y, out + 1 + p224_element_length);
    return 1 + 2 * p224_element_length;
}

/* Writes the encoding of the x-coordinate of p, as specified in SEC 1, Version
 * 2.0, Section 2.3.5, or returns NULL and an error if p is the point at
 * infinity. */
static uint8_t *p224_point_bytes_x(const NistecP224Point *p, uint8_t *out, Error *err) {
    if (p224_is_zero(&p->z) == 1) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("P224 point is the point at infinity")));
        return NULL;
    }

    NistecP224Element zinv, x;
    p224_invert(&zinv, &p->z);
    p224_mul(&x, &p->x, &zinv);

    p224_bytes(&x, out);
    return out;
}

/* Writes the compressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p224_point_bytes_compressed(const NistecP224Point *p, uint8_t *out) {
    if (p224_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP224Element zinv, x, y;
    p224_invert(&zinv, &p->z);
    p224_mul(&x, &p->x, &zinv);
    p224_mul(&y, &p->y, &zinv);

    /* Encode the sign of the y coordinate (indicated by the least significant
     * bit) as the encoding type (2 or 3). */
    uint8_t yb[p224_element_length];
    p224_bytes(&y, yb);
    out[0] = (uint8_t)(2 | (yb[p224_element_length - 1] & 1));
    p224_bytes(&x, out + 1);
    return 1 + p224_element_length;
}

/* Sets q = p1 + p2, and returns q. The points may overlap. */
static NistecP224Point *p224_point_add(NistecP224Point *q, const NistecP224Point *p1,
                                       const NistecP224Point *p2) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP224Element t0_, t1_, t2_, t3_, t4_, x3_, y3_, z3_;
    NistecP224Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_, *t4 = &t4_;
    NistecP224Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP224Element *b = p224_b();

    p224_mul(t0, &p1->x, &p2->x); /* t0 := X1 * X2 */
    p224_mul(t1, &p1->y, &p2->y); /* t1 := Y1 * Y2 */
    p224_mul(t2, &p1->z, &p2->z); /* t2 := Z1 * Z2 */
    p224_add(t3, &p1->x, &p1->y); /* t3 := X1 + Y1 */
    p224_add(t4, &p2->x, &p2->y); /* t4 := X2 + Y2 */
    p224_mul(t3, t3, t4);         /* t3 := t3 * t4 */
    p224_add(t4, t0, t1);         /* t4 := t0 + t1 */
    p224_sub(t3, t3, t4);         /* t3 := t3 - t4 */
    p224_add(t4, &p1->y, &p1->z); /* t4 := Y1 + Z1 */
    p224_add(x3, &p2->y, &p2->z); /* X3 := Y2 + Z2 */
    p224_mul(t4, t4, x3);         /* t4 := t4 * X3 */
    p224_add(x3, t1, t2);         /* X3 := t1 + t2 */
    p224_sub(t4, t4, x3);         /* t4 := t4 - X3 */
    p224_add(x3, &p1->x, &p1->z); /* X3 := X1 + Z1 */
    p224_add(y3, &p2->x, &p2->z); /* Y3 := X2 + Z2 */
    p224_mul(x3, x3, y3);         /* X3 := X3 * Y3 */
    p224_add(y3, t0, t2);         /* Y3 := t0 + t2 */
    p224_sub(y3, x3, y3);         /* Y3 := X3 - Y3 */
    p224_mul(z3, b, t2);          /* Z3 := b * t2 */
    p224_sub(x3, y3, z3);         /* X3 := Y3 - Z3 */
    p224_add(z3, x3, x3);         /* Z3 := X3 + X3 */
    p224_add(x3, x3, z3);         /* X3 := X3 + Z3 */
    p224_sub(z3, t1, x3);         /* Z3 := t1 - X3 */
    p224_add(x3, t1, x3);         /* X3 := t1 + X3 */
    p224_mul(y3, b, y3);          /* Y3 := b * Y3 */
    p224_add(t1, t2, t2);         /* t1 := t2 + t2 */
    p224_add(t2, t1, t2);         /* t2 := t1 + t2 */
    p224_sub(y3, y3, t2);         /* Y3 := Y3 - t2 */
    p224_sub(y3, y3, t0);         /* Y3 := Y3 - t0 */
    p224_add(t1, y3, y3);         /* t1 := Y3 + Y3 */
    p224_add(y3, t1, y3);         /* Y3 := t1 + Y3 */
    p224_add(t1, t0, t0);         /* t1 := t0 + t0 */
    p224_add(t0, t1, t0);         /* t0 := t1 + t0 */
    p224_sub(t0, t0, t2);         /* t0 := t0 - t2 */
    p224_mul(t1, t4, y3);         /* t1 := t4 * Y3 */
    p224_mul(t2, t0, y3);         /* t2 := t0 * Y3 */
    p224_mul(y3, x3, z3);         /* Y3 := X3 * Z3 */
    p224_add(y3, y3, t2);         /* Y3 := Y3 + t2 */
    p224_mul(x3, t3, x3);         /* X3 := t3 * X3 */
    p224_sub(x3, x3, t1);         /* X3 := X3 - t1 */
    p224_mul(z3, t4, z3);         /* Z3 := t4 * Z3 */
    p224_mul(t1, t3, t0);         /* t1 := t3 * t0 */
    p224_add(z3, z3, t1);         /* Z3 := Z3 + t1 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q = p + p, and returns q. The points may overlap. */
static NistecP224Point *p224_point_double(NistecP224Point *q,
                                          const NistecP224Point *p) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP224Element t0_, t1_, t2_, t3_, x3_, y3_, z3_;
    NistecP224Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_;
    NistecP224Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP224Element *b = p224_b();

    p224_square(t0, &p->x);     /* t0 := X ^ 2 */
    p224_square(t1, &p->y);     /* t1 := Y ^ 2 */
    p224_square(t2, &p->z);     /* t2 := Z ^ 2 */
    p224_mul(t3, &p->x, &p->y); /* t3 := X * Y */
    p224_add(t3, t3, t3);       /* t3 := t3 + t3 */
    p224_mul(z3, &p->x, &p->z); /* Z3 := X * Z */
    p224_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p224_mul(y3, b, t2);        /* Y3 := b * t2 */
    p224_sub(y3, y3, z3);       /* Y3 := Y3 - Z3 */
    p224_add(x3, y3, y3);       /* X3 := Y3 + Y3 */
    p224_add(y3, x3, y3);       /* Y3 := X3 + Y3 */
    p224_sub(x3, t1, y3);       /* X3 := t1 - Y3 */
    p224_add(y3, t1, y3);       /* Y3 := t1 + Y3 */
    p224_mul(y3, x3, y3);       /* Y3 := X3 * Y3 */
    p224_mul(x3, x3, t3);       /* X3 := X3 * t3 */
    p224_add(t3, t2, t2);       /* t3 := t2 + t2 */
    p224_add(t2, t2, t3);       /* t2 := t2 + t3 */
    p224_mul(z3, b, z3);        /* Z3 := b * Z3 */
    p224_sub(z3, z3, t2);       /* Z3 := Z3 - t2 */
    p224_sub(z3, z3, t0);       /* Z3 := Z3 - t0 */
    p224_add(t3, z3, z3);       /* t3 := Z3 + Z3 */
    p224_add(z3, z3, t3);       /* Z3 := Z3 + t3 */
    p224_add(t3, t0, t0);       /* t3 := t0 + t0 */
    p224_add(t0, t3, t0);       /* t0 := t3 + t0 */
    p224_sub(t0, t0, t2);       /* t0 := t0 - t2 */
    p224_mul(t0, t0, z3);       /* t0 := t0 * Z3 */
    p224_add(y3, y3, t0);       /* Y3 := Y3 + t0 */
    p224_mul(t0, &p->y, &p->z); /* t0 := Y * Z */
    p224_add(t0, t0, t0);       /* t0 := t0 + t0 */
    p224_mul(z3, t0, z3);       /* Z3 := t0 * Z3 */
    p224_sub(x3, x3, z3);       /* X3 := X3 - Z3 */
    p224_mul(z3, t0, t1);       /* Z3 := t0 * t1 */
    p224_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p224_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q to p1 if cond == 1, and to p2 if cond == 0. */
static NistecP224Point *p224_point_select(NistecP224Point *q, const NistecP224Point *p1,
                                          const NistecP224Point *p2, int cond) {
    p224_select(&q->x, &p1->x, &p2->x, cond);
    p224_select(&q->y, &p1->y, &p2->y, cond);
    p224_select(&q->z, &p1->z, &p2->z, cond);
    return q;
}

/* ------------------------------------------------- scalar multiplication */

/* The first 15 multiples of a point at offset -1, so [1]P is at table[0],
 * [15]P is at table[14], and [0]P is implicitly the identity point. */
typedef struct P224Table {
    NistecP224Point p[15];
} P224Table;

/* Selects the n-th multiple of the table base point into p. It works in
 * constant time by iterating over every entry of the table. n must be in
 * [0, 15]. */
static void p224_table_select(const P224Table *table, NistecP224Point *p, uint8_t n) {
    if (n >= 16)
        panic_str(BURROW_S(
            "nistec: internal error: p224Table called with out-of-bounds value"));
    p224_point_new(p);
    for (uint8_t i = 1; i < 16; i++) {
        int cond = (int)subtle_constant_time_byte_eq(i, n);
        p224_point_select(p, &table->p[i - 1], p, cond);
    }
}

/* Sets p = scalar * q, and returns p. */
static NistecP224Point *p224_point_scalar_mult(NistecP224Point *p,
                                               const NistecP224Point *q, Slice scalar,
                                               Error *err) {
    (void)err;
    const uint8_t *s = scalar.p;

    /* Compute a table for the base point q. */
    P224Table table;
    table.p[0] = *q;
    for (int i = 1; i < 15; i += 2) {
        p224_point_double(&table.p[i], &table.p[i / 2]);
        p224_point_add(&table.p[i + 1], &table.p[i], q);
    }

    /* Instead of doing the classic double-and-add chain, we do it with a
     * four-bit window: we double four times, and then add [0-15]P. */
    NistecP224Point t;
    p224_point_new(&t);
    p224_point_new(p);
    for (Int i = 0; i < scalar.len; i++) {
        /* No need to double on the first iteration, as p is the identity at
         * this point, and [N]inf = inf. */
        if (i != 0) {
            p224_point_double(p, p);
            p224_point_double(p, p);
            p224_point_double(p, p);
            p224_point_double(p, p);
        }

        uint8_t window_value = (uint8_t)(s[i] >> 4);
        p224_table_select(&table, &t, window_value);
        p224_point_add(p, p, &t);

        p224_point_double(p, p);
        p224_point_double(p, p);
        p224_point_double(p, p);
        p224_point_double(p, p);

        window_value = s[i] & 0xf;
        p224_table_select(&table, &t, window_value);
        p224_point_add(p, p, &t);
    }

    return p;
}

/* A sequence of tables, built the first time a base multiplication needs it.
 * The first table contains multiples of G. Each successive table is the
 * previous table doubled four times. */
static P224Table p224_generator_table[p224_element_length * 2];
static SyncOnce p224_generator_table_once;

static void p224_generator_table_init(void *env) {
    (void)env;
    NistecP224Point base;
    p224_point_set_generator(&base);
    for (int i = 0; i < p224_element_length * 2; i++) {
        p224_generator_table[i].p[0] = base;
        for (int j = 1; j < 15; j++)
            p224_point_add(&p224_generator_table[i].p[j],
                           &p224_generator_table[i].p[j - 1], &base);
        p224_point_double(&base, &base);
        p224_point_double(&base, &base);
        p224_point_double(&base, &base);
        p224_point_double(&base, &base);
    }
}

/* Sets p = scalar * B, where B is the canonical generator, and returns p. */
static NistecP224Point *p224_point_scalar_base_mult(NistecP224Point *p, Slice scalar,
                                                    Error *err) {
    if (scalar.len != p224_element_length) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("invalid scalar length")));
        return NULL;
    }
    sync_once_do(&p224_generator_table_once,
                 BURROW_FN(Func, p224_generator_table_init, NULL));
    const uint8_t *s = scalar.p;

    /* This is also a scalar multiplication with a four-bit window like in
     * ScalarMult, but in this case the doublings are precomputed. The value
     * [windowValue]G added at iteration k would normally get doubled
     * (totIterations-k)x4 times, but with a larger precomputation we can
     * instead add [2^((totIterations-k)x4)][windowValue]G and avoid the
     * doublings between iterations. */
    NistecP224Point t;
    p224_point_new(&t);
    p224_point_new(p);
    int table_index = p224_element_length * 2 - 1;
    for (Int i = 0; i < scalar.len; i++) {
        uint8_t window_value = (uint8_t)(s[i] >> 4);
        p224_table_select(&p224_generator_table[table_index], &t, window_value);
        p224_point_add(p, p, &t);
        table_index--;

        window_value = s[i] & 0xf;
        p224_table_select(&p224_generator_table[table_index], &t, window_value);
        p224_point_add(p, p, &t);
        table_index--;
    }

    return p;
}

/* ---------------------------------------------------------------- curve */

static NistecPoint *p224_v_point_new(NistecPoint *p) {
    p224_point_new(&p->p224);
    return p;
}

static NistecPoint *p224_v_set_generator(NistecPoint *p) {
    p224_point_set_generator(&p->p224);
    return p;
}

static NistecPoint *p224_v_set(NistecPoint *p, const NistecPoint *q) {
    p->p224 = q->p224;
    return p;
}

static NistecPoint *p224_v_set_bytes(NistecPoint *p, Slice b, Error *err) {
    return p224_point_set_bytes(&p->p224, b, err) == NULL ? NULL : p;
}

static Int p224_v_bytes(const NistecPoint *p, uint8_t *out) {
    return p224_point_bytes(&p->p224, out);
}

static uint8_t *p224_v_bytes_x(const NistecPoint *p, uint8_t *out, Error *err) {
    return p224_point_bytes_x(&p->p224, out, err);
}

static Int p224_v_bytes_compressed(const NistecPoint *p, uint8_t *out) {
    return p224_point_bytes_compressed(&p->p224, out);
}

static NistecPoint *p224_v_add(NistecPoint *q, const NistecPoint *p1,
                               const NistecPoint *p2) {
    p224_point_add(&q->p224, &p1->p224, &p2->p224);
    return q;
}

static NistecPoint *p224_v_double(NistecPoint *q, const NistecPoint *p) {
    p224_point_double(&q->p224, &p->p224);
    return q;
}

static NistecPoint *p224_v_scalar_mult(NistecPoint *p, const NistecPoint *q,
                                       Slice scalar, Error *err) {
    return p224_point_scalar_mult(&p->p224, &q->p224, scalar, err) == NULL ? NULL : p;
}

static NistecPoint *p224_v_scalar_base_mult(NistecPoint *p, Slice scalar, Error *err) {
    return p224_point_scalar_base_mult(&p->p224, scalar, err) == NULL ? NULL : p;
}

const NistecCurve burrow__nistec_p224 = {
    "P-224",
    p224_element_length,
    p224_v_point_new,
    p224_v_set_generator,
    p224_v_set,
    p224_v_set_bytes,
    p224_v_bytes,
    p224_v_bytes_x,
    p224_v_bytes_compressed,
    p224_v_add,
    p224_v_double,
    p224_v_scalar_mult,
    p224_v_scalar_base_mult,
};
