/* Derived from Go's src/crypto/internal/fips140/nistec/p256.go.
 * Go source: go1.27.1.
 *
 * The part of the P-256 group that is the same as the other three curves': its
 * field elements, on fiat-crypto's arithmetic in fiat_p256_64.h or
 * fiat_p256_32.h, and its points, with the complete addition formulas.
 * nistec_p256.c includes it and has the rest, which is P-256's own.
 *
 * Generated by tools/gen-nistec.sh from Go's p256.go, fiat/p256.go and
 * fiat/p256_invert.go; do not edit.
 *
 * Copyright 2022 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#ifndef BURROW_CRYPTO_NISTEC_P256_POINT_H
#define BURROW_CRYPTO_NISTEC_P256_POINT_H

#include "nistec.h"

#include "fiat_p256_32.h"
#include "fiat_p256_64.h"

#include "burrow/core.h"
#include "burrow/crypto/subtle.h"
#include "burrow/error.h"
#include "burrow/func.h"
#include "burrow/panic.h"
#include "burrow/slice.h"
#include "burrow/sync.h"

#include <stdint.h>
#include <string.h>

_Static_assert(FIAT_P256_LIMBS == NISTEC_P256_LIMBS,
               "nistec.h has the wrong number of words for a P-256 element");
_Static_assert(sizeof(fiat_p256_limb) == sizeof(NistecLimb),
               "nistec.h has the wrong word for a P-256 element");

enum { p256_element_length = 32 };

static void p256_reverse(uint8_t *v) {
    for (int i = 0; i < p256_element_length / 2; i++) {
        uint8_t t = v[i];
        v[i] = v[p256_element_length - 1 - i];
        v[p256_element_length - 1 - i] = t;
    }
}

/* ------------------------------------------------------------- element */

static NistecP256Element *p256_one(NistecP256Element *e) {
    fiat_p256_set_one(e->l);
    return e;
}

static NistecP256Element *p256_add(NistecP256Element *e, const NistecP256Element *t1,
                                   const NistecP256Element *t2) {
    fiat_p256_add(e->l, t1->l, t2->l);
    return e;
}

static NistecP256Element *p256_sub(NistecP256Element *e, const NistecP256Element *t1,
                                   const NistecP256Element *t2) {
    fiat_p256_sub(e->l, t1->l, t2->l);
    return e;
}

static NistecP256Element *p256_mul(NistecP256Element *e, const NistecP256Element *t1,
                                   const NistecP256Element *t2) {
    fiat_p256_mul(e->l, t1->l, t2->l);
    return e;
}

static NistecP256Element *p256_square(NistecP256Element *e,
                                      const NistecP256Element *t) {
    fiat_p256_square(e->l, t->l);
    return e;
}

/* Writes the 32 byte big endian encoding of e to out. */
static void p256_bytes(const NistecP256Element *e, uint8_t *out) {
    fiat_p256_non_montgomery_domain_field_element tmp;
    fiat_p256_from_montgomery(tmp, e->l);
    fiat_p256_to_bytes(out, tmp);
    p256_reverse(out);
}

static void p256_from_canonical_bytes(NistecP256Element *e, const uint8_t *in) {
    fiat_p256_non_montgomery_domain_field_element tmp;
    fiat_p256_from_bytes(tmp, in);
    fiat_p256_to_montgomery(e->l, tmp);
}

static int p256_equal(const NistecP256Element *e, const NistecP256Element *t) {
    uint8_t eb[p256_element_length], tb[p256_element_length];
    p256_bytes(e, eb);
    p256_bytes(t, tb);
    return burrow__nistec_equal_bytes(eb, tb, p256_element_length);
}

static int p256_is_zero(const NistecP256Element *e) {
    uint8_t eb[p256_element_length], zero[p256_element_length];
    memset(zero, 0, sizeof zero);
    p256_bytes(e, eb);
    return burrow__nistec_equal_bytes(eb, zero, p256_element_length);
}

/* Sets e to the value of the 32 big endian bytes at v. Go's SetBytes also
 * takes a slice of the wrong length, which nothing here passes it. */
static NistecP256Element *p256_set_bytes(NistecP256Element *e, const uint8_t *v,
                                         Error *err) {
    /* Check for non-canonical encodings (p + k, 2p + k, etc.) by comparing to
     * the encoding of -1 mod p, so p - 1, the highest canonical encoding. */
    NistecP256Element zero, one, minus_one;
    uint8_t minus_one_encoding[p256_element_length];
    memset(&zero, 0, sizeof zero);
    p256_bytes(p256_sub(&minus_one, &zero, p256_one(&one)), minus_one_encoding);
    if (burrow__nistec_less_or_eq_bytes(v, minus_one_encoding, p256_element_length) ==
        0) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("invalid P256Element encoding")));
        return NULL;
    }
    uint8_t in[p256_element_length];
    memcpy(in, v, sizeof in);
    p256_reverse(in);
    p256_from_canonical_bytes(e, in);
    return e;
}

/* Sets v to a if cond is 1 and to b if cond is 0. */
static NistecP256Element *p256_select(NistecP256Element *v, const NistecP256Element *a,
                                      const NistecP256Element *b, int cond) {
    fiat_p256_selectznz(v->l, (fiat_p256_uint1)cond, b->l, a->l);
    return v;
}

/* Sets e to 1/x and returns e. If x is 0, the result is 0. Inversion is
 * exponentiation by p - 2. */
static NistecP256Element *p256_invert(NistecP256Element *e,
                                      const NistecP256Element *x) {
    NistecP256Element z_, t0_, t1_;
    NistecP256Element *z = &z_, *t0 = &t0_, *t1 = &t1_;
    /* Inversion is implemented as exponentiation with exponent p − 2.
     * The sequence of 12 multiplications and 255 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10     = 2*1
     * _11     = 1 + _10
     * _110    = 2*_11
     * _111    = 1 + _110
     * _111000 = _111 << 3
     * _111111 = _111 + _111000
     * x12     = _111111 << 6 + _111111
     * x15     = x12 << 3 + _111
     * x16     = 2*x15 + 1
     * x32     = x16 << 16 + x16
     * i53     = x32 << 15
     * x47     = x15 + i53
     * i263    = ((i53 << 17 + 1) << 143 + x47) << 47
     * return    (x47 + i263) << 2 + 1 */
    p256_square(z, x);
    p256_mul(z, x, z);
    p256_square(z, z);
    p256_mul(z, x, z);
    p256_square(t0, z);
    for (int s = 1; s < 3; s++)
        p256_square(t0, t0);
    p256_mul(t0, z, t0);
    p256_square(t1, t0);
    for (int s = 1; s < 6; s++)
        p256_square(t1, t1);
    p256_mul(t0, t0, t1);
    for (int s = 0; s < 3; s++)
        p256_square(t0, t0);
    p256_mul(z, z, t0);
    p256_square(t0, z);
    p256_mul(t0, x, t0);
    p256_square(t1, t0);
    for (int s = 1; s < 16; s++)
        p256_square(t1, t1);
    p256_mul(t0, t0, t1);
    for (int s = 0; s < 15; s++)
        p256_square(t0, t0);
    p256_mul(z, z, t0);
    for (int s = 0; s < 17; s++)
        p256_square(t0, t0);
    p256_mul(t0, x, t0);
    for (int s = 0; s < 143; s++)
        p256_square(t0, t0);
    p256_mul(t0, z, t0);
    for (int s = 0; s < 47; s++)
        p256_square(t0, t0);
    p256_mul(z, z, t0);
    for (int s = 0; s < 2; s++)
        p256_square(z, z);
    p256_mul(z, x, z);

    *e = *z;
    return e;
}

/* Sets e to the square of x, n times over, for n of at least 1. */
static void p256_square_n(NistecP256Element *e, const NistecP256Element *x, int n) {
    p256_square(e, x);
    for (int i = 1; i < n; i++)
        p256_square(e, e);
}

/* Sets e to a square root of x. If x is not a square, returns 0 and leaves e
 * unchanged. e and x can overlap. */
static int p256_sqrt(NistecP256Element *e, const NistecP256Element *x) {
    NistecP256Element t0_, t1_;
    NistecP256Element *t0 = &t0_, *t1 = &t1_;
    /* Since p = 3 mod 4, exponentiation by (p + 1) / 4 yields a square root candidate.
     *
     * The sequence of 7 multiplications and 253 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10       = 2*1
     * _11       = 1 + _10
     * _1100     = _11 << 2
     * _1111     = _11 + _1100
     * _11110000 = _1111 << 4
     * _11111111 = _1111 + _11110000
     * x16       = _11111111 << 8 + _11111111
     * x32       = x16 << 16 + x16
     * return      ((x32 << 32 + 1) << 96 + 1) << 94 */
    p256_square_n(t0, x, 1);
    p256_mul(t0, x, t0);
    p256_square_n(t1, t0, 2);
    p256_mul(t0, t0, t1);
    p256_square_n(t1, t0, 4);
    p256_mul(t0, t0, t1);
    p256_square_n(t1, t0, 8);
    p256_mul(t0, t0, t1);
    p256_square_n(t1, t0, 16);
    p256_mul(t0, t0, t1);
    p256_square_n(t0, t0, 32);
    p256_mul(t0, x, t0);
    p256_square_n(t0, t0, 96);
    p256_mul(t0, x, t0);
    p256_square_n(t0, t0, 94);

    /* Check if the candidate t0 is indeed a square root of x. */
    p256_square(t1, t0);
    if (p256_equal(t1, x) != 1)
        return 0;
    *e = *t0;
    return 1;
}

/* --------------------------------------------------------------- point */

/* b, the constant of the curve, set the first time something needs it. */
static NistecP256Element p256_b_value;
static SyncOnce p256_b_once;

static void p256_b_init(void *env) {
    (void)env;
    static const uint8_t b[p256_element_length] = {
        0x5a, 0xc6, 0x35, 0xd8, 0xaa, 0x3a, 0x93, 0xe7, 0xb3, 0xeb, 0xbd,
        0x55, 0x76, 0x98, 0x86, 0xbc, 0x65, 0x1d, 0x06, 0xb0, 0xcc, 0x53,
        0xb0, 0xf6, 0x3b, 0xce, 0x3c, 0x3e, 0x27, 0xd2, 0x60, 0x4b,
    };
    p256_set_bytes(&p256_b_value, b, NULL);
}

static const NistecP256Element *p256_b(void) {
    sync_once_do(&p256_b_once, BURROW_FN(Func, p256_b_init, NULL));
    return &p256_b_value;
}

/* Sets p to the point at infinity. */
static NistecP256Point *p256_point_new(NistecP256Point *p) {
    memset(&p->x, 0, sizeof p->x);
    p256_one(&p->y);
    memset(&p->z, 0, sizeof p->z);
    return p;
}

static NistecP256Point *p256_point_set_generator(NistecP256Point *p) {
    static const uint8_t x[p256_element_length] = {
        0x6b, 0x17, 0xd1, 0xf2, 0xe1, 0x2c, 0x42, 0x47, 0xf8, 0xbc, 0xe6,
        0xe5, 0x63, 0xa4, 0x40, 0xf2, 0x77, 0x03, 0x7d, 0x81, 0x2d, 0xeb,
        0x33, 0xa0, 0xf4, 0xa1, 0x39, 0x45, 0xd8, 0x98, 0xc2, 0x96,
    };
    static const uint8_t y[p256_element_length] = {
        0x4f, 0xe3, 0x42, 0xe2, 0xfe, 0x1a, 0x7f, 0x9b, 0x8e, 0xe7, 0xeb,
        0x4a, 0x7c, 0x0f, 0x9e, 0x16, 0x2b, 0xce, 0x33, 0x57, 0x6b, 0x31,
        0x5e, 0xce, 0xcb, 0xb6, 0x40, 0x68, 0x37, 0xbf, 0x51, 0xf5,
    };
    p256_set_bytes(&p->x, x, NULL);
    p256_set_bytes(&p->y, y, NULL);
    p256_one(&p->z);
    return p;
}

/* Sets y2 to x^3 - 3x + b, and returns y2. */
static NistecP256Element *p256_polynomial(NistecP256Element *y2,
                                          const NistecP256Element *x) {
    p256_square(y2, x);
    p256_mul(y2, y2, x);

    NistecP256Element three_x;
    p256_add(&three_x, x, x);
    p256_add(&three_x, &three_x, x);
    p256_sub(y2, y2, &three_x);

    return p256_add(y2, y2, p256_b());
}

static int p256_check_on_curve(const NistecP256Element *x, const NistecP256Element *y,
                               Error *err) {
    /* y^2 = x^3 - 3x + b */
    NistecP256Element rhs, lhs;
    p256_polynomial(&rhs, x);
    p256_square(&lhs, y);
    if (p256_equal(&rhs, &lhs) != 1) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("P256 point not on curve")));
        return 0;
    }
    return 1;
}

/* Sets p to the compressed, uncompressed, or infinity value encoded in b, as
 * specified in SEC 1, Version 2.0, Section 2.3.4. If the point is not on the
 * curve, it returns NULL and an error, and the receiver is unchanged.
 * Otherwise, it returns p. */
static NistecP256Point *p256_point_set_bytes(NistecP256Point *p, Slice b, Error *err) {
    const uint8_t *bb = b.p;
    NistecP256Element x, y;

    /* Point at infinity. */
    if (b.len == 1 && bb[0] == 0)
        return p256_point_new(p);

    /* Uncompressed form. */
    if (b.len == 1 + 2 * p256_element_length && bb[0] == 4) {
        if (p256_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;
        if (p256_set_bytes(&y, bb + 1 + p256_element_length, err) == NULL)
            return NULL;
        if (!p256_check_on_curve(&x, &y, err))
            return NULL;
        p->x = x;
        p->y = y;
        p256_one(&p->z);
        return p;
    }

    /* Compressed form. */
    if (b.len == 1 + p256_element_length && (bb[0] == 2 || bb[0] == 3)) {
        if (p256_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;

        /* y^2 = x^3 - 3x + b */
        p256_polynomial(&y, &x);
        if (!p256_sqrt(&y, &y)) {
            BURROW_OUT(err,
                       errors_new(error_allocator(),
                                  BURROW_S("invalid P256 compressed point encoding")));
            return NULL;
        }

        /* Select the positive or negative root, as indicated by the least
         * significant bit, based on the encoding type byte. */
        NistecP256Element other_root;
        memset(&other_root, 0, sizeof other_root);
        p256_sub(&other_root, &other_root, &y);
        uint8_t yb[p256_element_length];
        p256_bytes(&y, yb);
        int cond = (yb[p256_element_length - 1] & 1) ^ (bb[0] & 1);
        p256_select(&y, &other_root, &y, cond);

        p->x = x;
        p->y = y;
        p256_one(&p->z);
        return p;
    }

    BURROW_OUT(err,
               errors_new(error_allocator(), BURROW_S("invalid P256 point encoding")));
    return NULL;
}

/* Writes the uncompressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p256_point_bytes(const NistecP256Point *p, uint8_t *out) {
    /* The SEC 1 representation of the point at infinity is a single zero byte,
     * and only infinity has z = 0. */
    if (p256_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP256Element zinv, x, y;
    p256_invert(&zinv, &p->z);
    p256_mul(&x, &p->x, &zinv);
    p256_mul(&y, &p->y, &zinv);

    out[0] = 4;
    p256_bytes(&x, out + 1);
    p256_bytes(&y, out + 1 + p256_element_length);
    return 1 + 2 * p256_element_length;
}

/* Writes the encoding of the x-coordinate of p, as specified in SEC 1, Version
 * 2.0, Section 2.3.5, or returns NULL and an error if p is the point at
 * infinity. */
static uint8_t *p256_point_bytes_x(const NistecP256Point *p, uint8_t *out, Error *err) {
    if (p256_is_zero(&p->z) == 1) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("P256 point is the point at infinity")));
        return NULL;
    }

    NistecP256Element zinv, x;
    p256_invert(&zinv, &p->z);
    p256_mul(&x, &p->x, &zinv);

    p256_bytes(&x, out);
    return out;
}

/* Writes the compressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p256_point_bytes_compressed(const NistecP256Point *p, uint8_t *out) {
    if (p256_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP256Element zinv, x, y;
    p256_invert(&zinv, &p->z);
    p256_mul(&x, &p->x, &zinv);
    p256_mul(&y, &p->y, &zinv);

    /* Encode the sign of the y coordinate (indicated by the least significant
     * bit) as the encoding type (2 or 3). */
    uint8_t yb[p256_element_length];
    p256_bytes(&y, yb);
    out[0] = (uint8_t)(2 | (yb[p256_element_length - 1] & 1));
    p256_bytes(&x, out + 1);
    return 1 + p256_element_length;
}

/* Sets q = p1 + p2, and returns q. The points may overlap. */
static NistecP256Point *p256_point_add(NistecP256Point *q, const NistecP256Point *p1,
                                       const NistecP256Point *p2) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP256Element t0_, t1_, t2_, t3_, t4_, x3_, y3_, z3_;
    NistecP256Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_, *t4 = &t4_;
    NistecP256Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP256Element *b = p256_b();

    p256_mul(t0, &p1->x, &p2->x); /* t0 := X1 * X2 */
    p256_mul(t1, &p1->y, &p2->y); /* t1 := Y1 * Y2 */
    p256_mul(t2, &p1->z, &p2->z); /* t2 := Z1 * Z2 */
    p256_add(t3, &p1->x, &p1->y); /* t3 := X1 + Y1 */
    p256_add(t4, &p2->x, &p2->y); /* t4 := X2 + Y2 */
    p256_mul(t3, t3, t4);         /* t3 := t3 * t4 */
    p256_add(t4, t0, t1);         /* t4 := t0 + t1 */
    p256_sub(t3, t3, t4);         /* t3 := t3 - t4 */
    p256_add(t4, &p1->y, &p1->z); /* t4 := Y1 + Z1 */
    p256_add(x3, &p2->y, &p2->z); /* X3 := Y2 + Z2 */
    p256_mul(t4, t4, x3);         /* t4 := t4 * X3 */
    p256_add(x3, t1, t2);         /* X3 := t1 + t2 */
    p256_sub(t4, t4, x3);         /* t4 := t4 - X3 */
    p256_add(x3, &p1->x, &p1->z); /* X3 := X1 + Z1 */
    p256_add(y3, &p2->x, &p2->z); /* Y3 := X2 + Z2 */
    p256_mul(x3, x3, y3);         /* X3 := X3 * Y3 */
    p256_add(y3, t0, t2);         /* Y3 := t0 + t2 */
    p256_sub(y3, x3, y3);         /* Y3 := X3 - Y3 */
    p256_mul(z3, b, t2);          /* Z3 := b * t2 */
    p256_sub(x3, y3, z3);         /* X3 := Y3 - Z3 */
    p256_add(z3, x3, x3);         /* Z3 := X3 + X3 */
    p256_add(x3, x3, z3);         /* X3 := X3 + Z3 */
    p256_sub(z3, t1, x3);         /* Z3 := t1 - X3 */
    p256_add(x3, t1, x3);         /* X3 := t1 + X3 */
    p256_mul(y3, b, y3);          /* Y3 := b * Y3 */
    p256_add(t1, t2, t2);         /* t1 := t2 + t2 */
    p256_add(t2, t1, t2);         /* t2 := t1 + t2 */
    p256_sub(y3, y3, t2);         /* Y3 := Y3 - t2 */
    p256_sub(y3, y3, t0);         /* Y3 := Y3 - t0 */
    p256_add(t1, y3, y3);         /* t1 := Y3 + Y3 */
    p256_add(y3, t1, y3);         /* Y3 := t1 + Y3 */
    p256_add(t1, t0, t0);         /* t1 := t0 + t0 */
    p256_add(t0, t1, t0);         /* t0 := t1 + t0 */
    p256_sub(t0, t0, t2);         /* t0 := t0 - t2 */
    p256_mul(t1, t4, y3);         /* t1 := t4 * Y3 */
    p256_mul(t2, t0, y3);         /* t2 := t0 * Y3 */
    p256_mul(y3, x3, z3);         /* Y3 := X3 * Z3 */
    p256_add(y3, y3, t2);         /* Y3 := Y3 + t2 */
    p256_mul(x3, t3, x3);         /* X3 := t3 * X3 */
    p256_sub(x3, x3, t1);         /* X3 := X3 - t1 */
    p256_mul(z3, t4, z3);         /* Z3 := t4 * Z3 */
    p256_mul(t1, t3, t0);         /* t1 := t3 * t0 */
    p256_add(z3, z3, t1);         /* Z3 := Z3 + t1 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q = p + p, and returns q. The points may overlap. */
static NistecP256Point *p256_point_double(NistecP256Point *q,
                                          const NistecP256Point *p) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP256Element t0_, t1_, t2_, t3_, x3_, y3_, z3_;
    NistecP256Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_;
    NistecP256Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP256Element *b = p256_b();

    p256_square(t0, &p->x);     /* t0 := X ^ 2 */
    p256_square(t1, &p->y);     /* t1 := Y ^ 2 */
    p256_square(t2, &p->z);     /* t2 := Z ^ 2 */
    p256_mul(t3, &p->x, &p->y); /* t3 := X * Y */
    p256_add(t3, t3, t3);       /* t3 := t3 + t3 */
    p256_mul(z3, &p->x, &p->z); /* Z3 := X * Z */
    p256_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p256_mul(y3, b, t2);        /* Y3 := b * t2 */
    p256_sub(y3, y3, z3);       /* Y3 := Y3 - Z3 */
    p256_add(x3, y3, y3);       /* X3 := Y3 + Y3 */
    p256_add(y3, x3, y3);       /* Y3 := X3 + Y3 */
    p256_sub(x3, t1, y3);       /* X3 := t1 - Y3 */
    p256_add(y3, t1, y3);       /* Y3 := t1 + Y3 */
    p256_mul(y3, x3, y3);       /* Y3 := X3 * Y3 */
    p256_mul(x3, x3, t3);       /* X3 := X3 * t3 */
    p256_add(t3, t2, t2);       /* t3 := t2 + t2 */
    p256_add(t2, t2, t3);       /* t2 := t2 + t3 */
    p256_mul(z3, b, z3);        /* Z3 := b * Z3 */
    p256_sub(z3, z3, t2);       /* Z3 := Z3 - t2 */
    p256_sub(z3, z3, t0);       /* Z3 := Z3 - t0 */
    p256_add(t3, z3, z3);       /* t3 := Z3 + Z3 */
    p256_add(z3, z3, t3);       /* Z3 := Z3 + t3 */
    p256_add(t3, t0, t0);       /* t3 := t0 + t0 */
    p256_add(t0, t3, t0);       /* t0 := t3 + t0 */
    p256_sub(t0, t0, t2);       /* t0 := t0 - t2 */
    p256_mul(t0, t0, z3);       /* t0 := t0 * Z3 */
    p256_add(y3, y3, t0);       /* Y3 := Y3 + t0 */
    p256_mul(t0, &p->y, &p->z); /* t0 := Y * Z */
    p256_add(t0, t0, t0);       /* t0 := t0 + t0 */
    p256_mul(z3, t0, z3);       /* Z3 := t0 * Z3 */
    p256_sub(x3, x3, z3);       /* X3 := X3 - Z3 */
    p256_mul(z3, t0, t1);       /* Z3 := t0 * t1 */
    p256_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p256_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q to p1 if cond == 1, and to p2 if cond == 0. */
static NistecP256Point *p256_point_select(NistecP256Point *q, const NistecP256Point *p1,
                                          const NistecP256Point *p2, int cond) {
    p256_select(&q->x, &p1->x, &p2->x, cond);
    p256_select(&q->y, &p1->y, &p2->y, cond);
    p256_select(&q->z, &p1->z, &p2->z, cond);
    return q;
}

#endif
