/* Derived from Go's src/crypto/internal/fips140/nistec/p521.go.
 * Go source: go1.27.1.
 *
 * The P-521 group: its field elements, on fiat-crypto's arithmetic in
 * fiat_p521_64.h or fiat_p521_32.h, and its points, with the complete addition
 * formulas and a four bit window for scalar multiplication.
 *
 * Generated by tools/gen-nistec.sh from Go's p521.go, fiat/p521.go and
 * fiat/p521_invert.go; do not edit.
 *
 * Copyright 2022 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "nistec.h"

#include "fiat_p521_32.h"
#include "fiat_p521_64.h"

#include "burrow/core.h"
#include "burrow/crypto/subtle.h"
#include "burrow/error.h"
#include "burrow/func.h"
#include "burrow/panic.h"
#include "burrow/slice.h"
#include "burrow/sync.h"

#include <stdint.h>
#include <string.h>

_Static_assert(FIAT_P521_LIMBS == NISTEC_P521_LIMBS,
               "nistec.h has the wrong number of words for a P-521 element");
_Static_assert(sizeof(fiat_p521_limb) == sizeof(NistecLimb),
               "nistec.h has the wrong word for a P-521 element");

enum { p521_element_length = 66 };

static void p521_reverse(uint8_t *v) {
    for (int i = 0; i < p521_element_length / 2; i++) {
        uint8_t t = v[i];
        v[i] = v[p521_element_length - 1 - i];
        v[p521_element_length - 1 - i] = t;
    }
}

/* ------------------------------------------------------------- element */

static NistecP521Element *p521_one(NistecP521Element *e) {
    memset(e, 0, sizeof *e);
    e->l[0] = 1;
    return e;
}

static NistecP521Element *p521_add(NistecP521Element *e, const NistecP521Element *t1,
                                   const NistecP521Element *t2) {
    fiat_p521_loose_field_element loose;
    fiat_p521_add(loose, t1->l, t2->l);
    fiat_p521_carry(e->l, loose);
    return e;
}

static NistecP521Element *p521_sub(NistecP521Element *e, const NistecP521Element *t1,
                                   const NistecP521Element *t2) {
    fiat_p521_loose_field_element loose;
    fiat_p521_sub(loose, t1->l, t2->l);
    fiat_p521_carry(e->l, loose);
    return e;
}

static NistecP521Element *p521_mul(NistecP521Element *e, const NistecP521Element *t1,
                                   const NistecP521Element *t2) {
    fiat_p521_carry_mul(e->l, t1->l, t2->l);
    return e;
}

static NistecP521Element *p521_square(NistecP521Element *e,
                                      const NistecP521Element *t) {
    fiat_p521_carry_square(e->l, t->l);
    return e;
}

/* Writes the 66 byte big endian encoding of e to out. */
static void p521_bytes(const NistecP521Element *e, uint8_t *out) {
    fiat_p521_to_bytes(out, e->l);
    p521_reverse(out);
}

static void p521_from_canonical_bytes(NistecP521Element *e, const uint8_t *in) {
    fiat_p521_from_bytes(e->l, in);
}

static int p521_equal(const NistecP521Element *e, const NistecP521Element *t) {
    uint8_t eb[p521_element_length], tb[p521_element_length];
    p521_bytes(e, eb);
    p521_bytes(t, tb);
    return burrow__nistec_equal_bytes(eb, tb, p521_element_length);
}

static int p521_is_zero(const NistecP521Element *e) {
    uint8_t eb[p521_element_length], zero[p521_element_length];
    memset(zero, 0, sizeof zero);
    p521_bytes(e, eb);
    return burrow__nistec_equal_bytes(eb, zero, p521_element_length);
}

/* Sets e to the value of the 66 big endian bytes at v. Go's SetBytes also
 * takes a slice of the wrong length, which nothing here passes it. */
static NistecP521Element *p521_set_bytes(NistecP521Element *e, const uint8_t *v,
                                         Error *err) {
    /* Check for non-canonical encodings (p + k, 2p + k, etc.) by comparing to
     * the encoding of -1 mod p, so p - 1, the highest canonical encoding. */
    NistecP521Element zero, one, minus_one;
    uint8_t minus_one_encoding[p521_element_length];
    memset(&zero, 0, sizeof zero);
    p521_bytes(p521_sub(&minus_one, &zero, p521_one(&one)), minus_one_encoding);
    if (burrow__nistec_less_or_eq_bytes(v, minus_one_encoding, p521_element_length) ==
        0) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("invalid P521Element encoding")));
        return NULL;
    }
    uint8_t in[p521_element_length];
    memcpy(in, v, sizeof in);
    p521_reverse(in);
    p521_from_canonical_bytes(e, in);
    return e;
}

/* Sets v to a if cond is 1 and to b if cond is 0. */
static NistecP521Element *p521_select(NistecP521Element *v, const NistecP521Element *a,
                                      const NistecP521Element *b, int cond) {
    fiat_p521_selectznz(v->l, (fiat_p521_uint1)cond, b->l, a->l);
    return v;
}

/* Sets e to 1/x and returns e. If x is 0, the result is 0. Inversion is
 * exponentiation by p - 2. */
static NistecP521Element *p521_invert(NistecP521Element *e,
                                      const NistecP521Element *x) {
    NistecP521Element z_, t0_;
    NistecP521Element *z = &z_, *t0 = &t0_;
    /* Inversion is implemented as exponentiation with exponent p − 2.
     * The sequence of 13 multiplications and 520 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * _10       = 2*1
     * _11       = 1 + _10
     * _1100     = _11 << 2
     * _1111     = _11 + _1100
     * _11110000 = _1111 << 4
     * _11111111 = _1111 + _11110000
     * x16       = _11111111 << 8 + _11111111
     * x32       = x16 << 16 + x16
     * x64       = x32 << 32 + x32
     * x65       = 2*x64 + 1
     * x129      = x65 << 64 + x64
     * x130      = 2*x129 + 1
     * x259      = x130 << 129 + x129
     * x260      = 2*x259 + 1
     * x519      = x260 << 259 + x259
     * return      x519 << 2 + 1 */
    p521_square(z, x);
    p521_mul(z, x, z);
    p521_square(t0, z);
    for (int s = 1; s < 2; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    for (int s = 1; s < 4; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    for (int s = 1; s < 8; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    for (int s = 1; s < 16; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    for (int s = 1; s < 32; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    p521_mul(t0, x, t0);
    for (int s = 0; s < 64; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    p521_mul(t0, x, t0);
    for (int s = 0; s < 129; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    p521_square(t0, z);
    p521_mul(t0, x, t0);
    for (int s = 0; s < 259; s++)
        p521_square(t0, t0);
    p521_mul(z, z, t0);
    for (int s = 0; s < 2; s++)
        p521_square(z, z);
    p521_mul(z, x, z);

    *e = *z;
    return e;
}

/* Sets z to a square root candidate for x. z and x must not overlap. */
static void p521_sqrt_candidate(NistecP521Element *z, const NistecP521Element *x) {
    /* Since p = 3 mod 4, exponentiation by (p + 1) / 4 yields a square root candidate.
     *
     * The sequence of 0 multiplications and 519 squarings is derived from the
     * following addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
     *
     * return  1 << 519 */
    p521_square(z, x);
    for (int s = 1; s < 519; s++)
        p521_square(z, z);
}

/* Sets e to a square root of x. If x is not a square, returns 0 and leaves e
 * unchanged. e and x can overlap. */
static int p521_sqrt(NistecP521Element *e, const NistecP521Element *x) {
    NistecP521Element candidate, square;
    p521_sqrt_candidate(&candidate, x);
    p521_square(&square, &candidate);
    if (p521_equal(&square, x) != 1)
        return 0;
    *e = candidate;
    return 1;
}

/* --------------------------------------------------------------- point */

/* b, the constant of the curve, set the first time something needs it. */
static NistecP521Element p521_b_value;
static SyncOnce p521_b_once;

static void p521_b_init(void *env) {
    (void)env;
    static const uint8_t b[p521_element_length] = {
        0x00, 0x51, 0x95, 0x3e, 0xb9, 0x61, 0x8e, 0x1c, 0x9a, 0x1f, 0x92,
        0x9a, 0x21, 0xa0, 0xb6, 0x85, 0x40, 0xee, 0xa2, 0xda, 0x72, 0x5b,
        0x99, 0xb3, 0x15, 0xf3, 0xb8, 0xb4, 0x89, 0x91, 0x8e, 0xf1, 0x09,
        0xe1, 0x56, 0x19, 0x39, 0x51, 0xec, 0x7e, 0x93, 0x7b, 0x16, 0x52,
        0xc0, 0xbd, 0x3b, 0xb1, 0xbf, 0x07, 0x35, 0x73, 0xdf, 0x88, 0x3d,
        0x2c, 0x34, 0xf1, 0xef, 0x45, 0x1f, 0xd4, 0x6b, 0x50, 0x3f, 0x00,
    };
    p521_set_bytes(&p521_b_value, b, NULL);
}

static const NistecP521Element *p521_b(void) {
    sync_once_do(&p521_b_once, BURROW_FN(Func, p521_b_init, NULL));
    return &p521_b_value;
}

/* Sets p to the point at infinity. */
static NistecP521Point *p521_point_new(NistecP521Point *p) {
    memset(&p->x, 0, sizeof p->x);
    p521_one(&p->y);
    memset(&p->z, 0, sizeof p->z);
    return p;
}

static NistecP521Point *p521_point_set_generator(NistecP521Point *p) {
    static const uint8_t x[p521_element_length] = {
        0x00, 0xc6, 0x85, 0x8e, 0x06, 0xb7, 0x04, 0x04, 0xe9, 0xcd, 0x9e,
        0x3e, 0xcb, 0x66, 0x23, 0x95, 0xb4, 0x42, 0x9c, 0x64, 0x81, 0x39,
        0x05, 0x3f, 0xb5, 0x21, 0xf8, 0x28, 0xaf, 0x60, 0x6b, 0x4d, 0x3d,
        0xba, 0xa1, 0x4b, 0x5e, 0x77, 0xef, 0xe7, 0x59, 0x28, 0xfe, 0x1d,
        0xc1, 0x27, 0xa2, 0xff, 0xa8, 0xde, 0x33, 0x48, 0xb3, 0xc1, 0x85,
        0x6a, 0x42, 0x9b, 0xf9, 0x7e, 0x7e, 0x31, 0xc2, 0xe5, 0xbd, 0x66,
    };
    static const uint8_t y[p521_element_length] = {
        0x01, 0x18, 0x39, 0x29, 0x6a, 0x78, 0x9a, 0x3b, 0xc0, 0x04, 0x5c,
        0x8a, 0x5f, 0xb4, 0x2c, 0x7d, 0x1b, 0xd9, 0x98, 0xf5, 0x44, 0x49,
        0x57, 0x9b, 0x44, 0x68, 0x17, 0xaf, 0xbd, 0x17, 0x27, 0x3e, 0x66,
        0x2c, 0x97, 0xee, 0x72, 0x99, 0x5e, 0xf4, 0x26, 0x40, 0xc5, 0x50,
        0xb9, 0x01, 0x3f, 0xad, 0x07, 0x61, 0x35, 0x3c, 0x70, 0x86, 0xa2,
        0x72, 0xc2, 0x40, 0x88, 0xbe, 0x94, 0x76, 0x9f, 0xd1, 0x66, 0x50,
    };
    p521_set_bytes(&p->x, x, NULL);
    p521_set_bytes(&p->y, y, NULL);
    p521_one(&p->z);
    return p;
}

/* Sets y2 to x^3 - 3x + b, and returns y2. */
static NistecP521Element *p521_polynomial(NistecP521Element *y2,
                                          const NistecP521Element *x) {
    p521_square(y2, x);
    p521_mul(y2, y2, x);

    NistecP521Element three_x;
    p521_add(&three_x, x, x);
    p521_add(&three_x, &three_x, x);
    p521_sub(y2, y2, &three_x);

    return p521_add(y2, y2, p521_b());
}

static int p521_check_on_curve(const NistecP521Element *x, const NistecP521Element *y,
                               Error *err) {
    /* y^2 = x^3 - 3x + b */
    NistecP521Element rhs, lhs;
    p521_polynomial(&rhs, x);
    p521_square(&lhs, y);
    if (p521_equal(&rhs, &lhs) != 1) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("P521 point not on curve")));
        return 0;
    }
    return 1;
}

/* Sets p to the compressed, uncompressed, or infinity value encoded in b, as
 * specified in SEC 1, Version 2.0, Section 2.3.4. If the point is not on the
 * curve, it returns NULL and an error, and the receiver is unchanged.
 * Otherwise, it returns p. */
static NistecP521Point *p521_point_set_bytes(NistecP521Point *p, Slice b, Error *err) {
    const uint8_t *bb = b.p;
    NistecP521Element x, y;

    /* Point at infinity. */
    if (b.len == 1 && bb[0] == 0)
        return p521_point_new(p);

    /* Uncompressed form. */
    if (b.len == 1 + 2 * p521_element_length && bb[0] == 4) {
        if (p521_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;
        if (p521_set_bytes(&y, bb + 1 + p521_element_length, err) == NULL)
            return NULL;
        if (!p521_check_on_curve(&x, &y, err))
            return NULL;
        p->x = x;
        p->y = y;
        p521_one(&p->z);
        return p;
    }

    /* Compressed form. */
    if (b.len == 1 + p521_element_length && (bb[0] == 2 || bb[0] == 3)) {
        if (p521_set_bytes(&x, bb + 1, err) == NULL)
            return NULL;

        /* y^2 = x^3 - 3x + b */
        p521_polynomial(&y, &x);
        if (!p521_sqrt(&y, &y)) {
            BURROW_OUT(err,
                       errors_new(error_allocator(),
                                  BURROW_S("invalid P521 compressed point encoding")));
            return NULL;
        }

        /* Select the positive or negative root, as indicated by the least
         * significant bit, based on the encoding type byte. */
        NistecP521Element other_root;
        memset(&other_root, 0, sizeof other_root);
        p521_sub(&other_root, &other_root, &y);
        uint8_t yb[p521_element_length];
        p521_bytes(&y, yb);
        int cond = (yb[p521_element_length - 1] & 1) ^ (bb[0] & 1);
        p521_select(&y, &other_root, &y, cond);

        p->x = x;
        p->y = y;
        p521_one(&p->z);
        return p;
    }

    BURROW_OUT(err,
               errors_new(error_allocator(), BURROW_S("invalid P521 point encoding")));
    return NULL;
}

/* Writes the uncompressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p521_point_bytes(const NistecP521Point *p, uint8_t *out) {
    /* The SEC 1 representation of the point at infinity is a single zero byte,
     * and only infinity has z = 0. */
    if (p521_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP521Element zinv, x, y;
    p521_invert(&zinv, &p->z);
    p521_mul(&x, &p->x, &zinv);
    p521_mul(&y, &p->y, &zinv);

    out[0] = 4;
    p521_bytes(&x, out + 1);
    p521_bytes(&y, out + 1 + p521_element_length);
    return 1 + 2 * p521_element_length;
}

/* Writes the encoding of the x-coordinate of p, as specified in SEC 1, Version
 * 2.0, Section 2.3.5, or returns NULL and an error if p is the point at
 * infinity. */
static uint8_t *p521_point_bytes_x(const NistecP521Point *p, uint8_t *out, Error *err) {
    if (p521_is_zero(&p->z) == 1) {
        BURROW_OUT(err, errors_new(error_allocator(),
                                   BURROW_S("P521 point is the point at infinity")));
        return NULL;
    }

    NistecP521Element zinv, x;
    p521_invert(&zinv, &p->z);
    p521_mul(&x, &p->x, &zinv);

    p521_bytes(&x, out);
    return out;
}

/* Writes the compressed or infinity encoding of p, as specified in SEC 1,
 * Version 2.0, Section 2.3.3, and returns its length. Note that the encoding
 * of the point at infinity is shorter than all other encodings. */
static Int p521_point_bytes_compressed(const NistecP521Point *p, uint8_t *out) {
    if (p521_is_zero(&p->z) == 1) {
        out[0] = 0;
        return 1;
    }

    NistecP521Element zinv, x, y;
    p521_invert(&zinv, &p->z);
    p521_mul(&x, &p->x, &zinv);
    p521_mul(&y, &p->y, &zinv);

    /* Encode the sign of the y coordinate (indicated by the least significant
     * bit) as the encoding type (2 or 3). */
    uint8_t yb[p521_element_length];
    p521_bytes(&y, yb);
    out[0] = (uint8_t)(2 | (yb[p521_element_length - 1] & 1));
    p521_bytes(&x, out + 1);
    return 1 + p521_element_length;
}

/* Sets q = p1 + p2, and returns q. The points may overlap. */
static NistecP521Point *p521_point_add(NistecP521Point *q, const NistecP521Point *p1,
                                       const NistecP521Point *p2) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP521Element t0_, t1_, t2_, t3_, t4_, x3_, y3_, z3_;
    NistecP521Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_, *t4 = &t4_;
    NistecP521Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP521Element *b = p521_b();

    p521_mul(t0, &p1->x, &p2->x); /* t0 := X1 * X2 */
    p521_mul(t1, &p1->y, &p2->y); /* t1 := Y1 * Y2 */
    p521_mul(t2, &p1->z, &p2->z); /* t2 := Z1 * Z2 */
    p521_add(t3, &p1->x, &p1->y); /* t3 := X1 + Y1 */
    p521_add(t4, &p2->x, &p2->y); /* t4 := X2 + Y2 */
    p521_mul(t3, t3, t4);         /* t3 := t3 * t4 */
    p521_add(t4, t0, t1);         /* t4 := t0 + t1 */
    p521_sub(t3, t3, t4);         /* t3 := t3 - t4 */
    p521_add(t4, &p1->y, &p1->z); /* t4 := Y1 + Z1 */
    p521_add(x3, &p2->y, &p2->z); /* X3 := Y2 + Z2 */
    p521_mul(t4, t4, x3);         /* t4 := t4 * X3 */
    p521_add(x3, t1, t2);         /* X3 := t1 + t2 */
    p521_sub(t4, t4, x3);         /* t4 := t4 - X3 */
    p521_add(x3, &p1->x, &p1->z); /* X3 := X1 + Z1 */
    p521_add(y3, &p2->x, &p2->z); /* Y3 := X2 + Z2 */
    p521_mul(x3, x3, y3);         /* X3 := X3 * Y3 */
    p521_add(y3, t0, t2);         /* Y3 := t0 + t2 */
    p521_sub(y3, x3, y3);         /* Y3 := X3 - Y3 */
    p521_mul(z3, b, t2);          /* Z3 := b * t2 */
    p521_sub(x3, y3, z3);         /* X3 := Y3 - Z3 */
    p521_add(z3, x3, x3);         /* Z3 := X3 + X3 */
    p521_add(x3, x3, z3);         /* X3 := X3 + Z3 */
    p521_sub(z3, t1, x3);         /* Z3 := t1 - X3 */
    p521_add(x3, t1, x3);         /* X3 := t1 + X3 */
    p521_mul(y3, b, y3);          /* Y3 := b * Y3 */
    p521_add(t1, t2, t2);         /* t1 := t2 + t2 */
    p521_add(t2, t1, t2);         /* t2 := t1 + t2 */
    p521_sub(y3, y3, t2);         /* Y3 := Y3 - t2 */
    p521_sub(y3, y3, t0);         /* Y3 := Y3 - t0 */
    p521_add(t1, y3, y3);         /* t1 := Y3 + Y3 */
    p521_add(y3, t1, y3);         /* Y3 := t1 + Y3 */
    p521_add(t1, t0, t0);         /* t1 := t0 + t0 */
    p521_add(t0, t1, t0);         /* t0 := t1 + t0 */
    p521_sub(t0, t0, t2);         /* t0 := t0 - t2 */
    p521_mul(t1, t4, y3);         /* t1 := t4 * Y3 */
    p521_mul(t2, t0, y3);         /* t2 := t0 * Y3 */
    p521_mul(y3, x3, z3);         /* Y3 := X3 * Z3 */
    p521_add(y3, y3, t2);         /* Y3 := Y3 + t2 */
    p521_mul(x3, t3, x3);         /* X3 := t3 * X3 */
    p521_sub(x3, x3, t1);         /* X3 := X3 - t1 */
    p521_mul(z3, t4, z3);         /* Z3 := t4 * Z3 */
    p521_mul(t1, t3, t0);         /* t1 := t3 * t0 */
    p521_add(z3, z3, t1);         /* Z3 := Z3 + t1 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q = p + p, and returns q. The points may overlap. */
static NistecP521Point *p521_point_double(NistecP521Point *q,
                                          const NistecP521Point *p) {
    /* Complete addition formula for a = -3 from "Complete addition formulas for
     * prime order elliptic curves" (https://eprint.iacr.org/2015/1060), A.2. */

    NistecP521Element t0_, t1_, t2_, t3_, x3_, y3_, z3_;
    NistecP521Element *t0 = &t0_, *t1 = &t1_, *t2 = &t2_, *t3 = &t3_;
    NistecP521Element *x3 = &x3_, *y3 = &y3_, *z3 = &z3_;
    const NistecP521Element *b = p521_b();

    p521_square(t0, &p->x);     /* t0 := X ^ 2 */
    p521_square(t1, &p->y);     /* t1 := Y ^ 2 */
    p521_square(t2, &p->z);     /* t2 := Z ^ 2 */
    p521_mul(t3, &p->x, &p->y); /* t3 := X * Y */
    p521_add(t3, t3, t3);       /* t3 := t3 + t3 */
    p521_mul(z3, &p->x, &p->z); /* Z3 := X * Z */
    p521_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p521_mul(y3, b, t2);        /* Y3 := b * t2 */
    p521_sub(y3, y3, z3);       /* Y3 := Y3 - Z3 */
    p521_add(x3, y3, y3);       /* X3 := Y3 + Y3 */
    p521_add(y3, x3, y3);       /* Y3 := X3 + Y3 */
    p521_sub(x3, t1, y3);       /* X3 := t1 - Y3 */
    p521_add(y3, t1, y3);       /* Y3 := t1 + Y3 */
    p521_mul(y3, x3, y3);       /* Y3 := X3 * Y3 */
    p521_mul(x3, x3, t3);       /* X3 := X3 * t3 */
    p521_add(t3, t2, t2);       /* t3 := t2 + t2 */
    p521_add(t2, t2, t3);       /* t2 := t2 + t3 */
    p521_mul(z3, b, z3);        /* Z3 := b * Z3 */
    p521_sub(z3, z3, t2);       /* Z3 := Z3 - t2 */
    p521_sub(z3, z3, t0);       /* Z3 := Z3 - t0 */
    p521_add(t3, z3, z3);       /* t3 := Z3 + Z3 */
    p521_add(z3, z3, t3);       /* Z3 := Z3 + t3 */
    p521_add(t3, t0, t0);       /* t3 := t0 + t0 */
    p521_add(t0, t3, t0);       /* t0 := t3 + t0 */
    p521_sub(t0, t0, t2);       /* t0 := t0 - t2 */
    p521_mul(t0, t0, z3);       /* t0 := t0 * Z3 */
    p521_add(y3, y3, t0);       /* Y3 := Y3 + t0 */
    p521_mul(t0, &p->y, &p->z); /* t0 := Y * Z */
    p521_add(t0, t0, t0);       /* t0 := t0 + t0 */
    p521_mul(z3, t0, z3);       /* Z3 := t0 * Z3 */
    p521_sub(x3, x3, z3);       /* X3 := X3 - Z3 */
    p521_mul(z3, t0, t1);       /* Z3 := t0 * t1 */
    p521_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */
    p521_add(z3, z3, z3);       /* Z3 := Z3 + Z3 */

    q->x = *x3;
    q->y = *y3;
    q->z = *z3;
    return q;
}

/* Sets q to p1 if cond == 1, and to p2 if cond == 0. */
static NistecP521Point *p521_point_select(NistecP521Point *q, const NistecP521Point *p1,
                                          const NistecP521Point *p2, int cond) {
    p521_select(&q->x, &p1->x, &p2->x, cond);
    p521_select(&q->y, &p1->y, &p2->y, cond);
    p521_select(&q->z, &p1->z, &p2->z, cond);
    return q;
}

/* ------------------------------------------------- scalar multiplication */

/* The first 15 multiples of a point at offset -1, so [1]P is at table[0],
 * [15]P is at table[14], and [0]P is implicitly the identity point. */
typedef struct P521Table {
    NistecP521Point p[15];
} P521Table;

/* Selects the n-th multiple of the table base point into p. It works in
 * constant time by iterating over every entry of the table. n must be in
 * [0, 15]. */
static void p521_table_select(const P521Table *table, NistecP521Point *p, uint8_t n) {
    if (n >= 16)
        panic_str(BURROW_S(
            "nistec: internal error: p521Table called with out-of-bounds value"));
    p521_point_new(p);
    for (uint8_t i = 1; i < 16; i++) {
        int cond = (int)subtle_constant_time_byte_eq(i, n);
        p521_point_select(p, &table->p[i - 1], p, cond);
    }
}

/* Sets p = scalar * q, and returns p. */
static NistecP521Point *p521_point_scalar_mult(NistecP521Point *p,
                                               const NistecP521Point *q, Slice scalar,
                                               Error *err) {
    (void)err;
    const uint8_t *s = scalar.p;

    /* Compute a table for the base point q. */
    P521Table table;
    table.p[0] = *q;
    for (int i = 1; i < 15; i += 2) {
        p521_point_double(&table.p[i], &table.p[i / 2]);
        p521_point_add(&table.p[i + 1], &table.p[i], q);
    }

    /* Instead of doing the classic double-and-add chain, we do it with a
     * four-bit window: we double four times, and then add [0-15]P. */
    NistecP521Point t;
    p521_point_new(&t);
    p521_point_new(p);
    for (Int i = 0; i < scalar.len; i++) {
        /* No need to double on the first iteration, as p is the identity at
         * this point, and [N]inf = inf. */
        if (i != 0) {
            p521_point_double(p, p);
            p521_point_double(p, p);
            p521_point_double(p, p);
            p521_point_double(p, p);
        }

        uint8_t window_value = (uint8_t)(s[i] >> 4);
        p521_table_select(&table, &t, window_value);
        p521_point_add(p, p, &t);

        p521_point_double(p, p);
        p521_point_double(p, p);
        p521_point_double(p, p);
        p521_point_double(p, p);

        window_value = s[i] & 0xf;
        p521_table_select(&table, &t, window_value);
        p521_point_add(p, p, &t);
    }

    return p;
}

/* A sequence of tables, built the first time a base multiplication needs it.
 * The first table contains multiples of G. Each successive table is the
 * previous table doubled four times. */
static P521Table p521_generator_table[p521_element_length * 2];
static SyncOnce p521_generator_table_once;

static void p521_generator_table_init(void *env) {
    (void)env;
    NistecP521Point base;
    p521_point_set_generator(&base);
    for (int i = 0; i < p521_element_length * 2; i++) {
        p521_generator_table[i].p[0] = base;
        for (int j = 1; j < 15; j++)
            p521_point_add(&p521_generator_table[i].p[j],
                           &p521_generator_table[i].p[j - 1], &base);
        p521_point_double(&base, &base);
        p521_point_double(&base, &base);
        p521_point_double(&base, &base);
        p521_point_double(&base, &base);
    }
}

/* Sets p = scalar * B, where B is the canonical generator, and returns p. */
static NistecP521Point *p521_point_scalar_base_mult(NistecP521Point *p, Slice scalar,
                                                    Error *err) {
    if (scalar.len != p521_element_length) {
        BURROW_OUT(err,
                   errors_new(error_allocator(), BURROW_S("invalid scalar length")));
        return NULL;
    }
    sync_once_do(&p521_generator_table_once,
                 BURROW_FN(Func, p521_generator_table_init, NULL));
    const uint8_t *s = scalar.p;

    /* This is also a scalar multiplication with a four-bit window like in
     * ScalarMult, but in this case the doublings are precomputed. The value
     * [windowValue]G added at iteration k would normally get doubled
     * (totIterations-k)x4 times, but with a larger precomputation we can
     * instead add [2^((totIterations-k)x4)][windowValue]G and avoid the
     * doublings between iterations. */
    NistecP521Point t;
    p521_point_new(&t);
    p521_point_new(p);
    int table_index = p521_element_length * 2 - 1;
    for (Int i = 0; i < scalar.len; i++) {
        uint8_t window_value = (uint8_t)(s[i] >> 4);
        p521_table_select(&p521_generator_table[table_index], &t, window_value);
        p521_point_add(p, p, &t);
        table_index--;

        window_value = s[i] & 0xf;
        p521_table_select(&p521_generator_table[table_index], &t, window_value);
        p521_point_add(p, p, &t);
        table_index--;
    }

    return p;
}

/* ---------------------------------------------------------------- curve */

static NistecPoint *p521_v_point_new(NistecPoint *p) {
    p521_point_new(&p->p521);
    return p;
}

static NistecPoint *p521_v_set_generator(NistecPoint *p) {
    p521_point_set_generator(&p->p521);
    return p;
}

static NistecPoint *p521_v_set(NistecPoint *p, const NistecPoint *q) {
    p->p521 = q->p521;
    return p;
}

static NistecPoint *p521_v_set_bytes(NistecPoint *p, Slice b, Error *err) {
    return p521_point_set_bytes(&p->p521, b, err) == NULL ? NULL : p;
}

static Int p521_v_bytes(const NistecPoint *p, uint8_t *out) {
    return p521_point_bytes(&p->p521, out);
}

static uint8_t *p521_v_bytes_x(const NistecPoint *p, uint8_t *out, Error *err) {
    return p521_point_bytes_x(&p->p521, out, err);
}

static Int p521_v_bytes_compressed(const NistecPoint *p, uint8_t *out) {
    return p521_point_bytes_compressed(&p->p521, out);
}

static NistecPoint *p521_v_add(NistecPoint *q, const NistecPoint *p1,
                               const NistecPoint *p2) {
    p521_point_add(&q->p521, &p1->p521, &p2->p521);
    return q;
}

static NistecPoint *p521_v_double(NistecPoint *q, const NistecPoint *p) {
    p521_point_double(&q->p521, &p->p521);
    return q;
}

static NistecPoint *p521_v_scalar_mult(NistecPoint *p, const NistecPoint *q,
                                       Slice scalar, Error *err) {
    return p521_point_scalar_mult(&p->p521, &q->p521, scalar, err) == NULL ? NULL : p;
}

static NistecPoint *p521_v_scalar_base_mult(NistecPoint *p, Slice scalar, Error *err) {
    return p521_point_scalar_base_mult(&p->p521, scalar, err) == NULL ? NULL : p;
}

const NistecCurve burrow__nistec_p521 = {
    "P-521",
    p521_element_length,
    p521_v_point_new,
    p521_v_set_generator,
    p521_v_set,
    p521_v_set_bytes,
    p521_v_bytes,
    p521_v_bytes_x,
    p521_v_bytes_compressed,
    p521_v_add,
    p521_v_double,
    p521_v_scalar_mult,
    p521_v_scalar_base_mult,
};
