/* Derived from Go's src/syscall, the zerrors, zsysnum and ztypes files and
 * the rest of the package.
 * Go source: go1.27.1.
 *
 * Generated by tools/gen-syscall-tables.sh from the Go tables. Do not edit.
 *
 * Copyright 2009 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

/* The unexported functions of syscall's zsyscall files, burrow__syscall_ and
 * the Go name, which the hand-written functions call the way Go's do. On
 * macOS, also the numbers of the libSystem functions they reach, which
 * src/syscall/zsyscall.c has the names of. */

#ifndef BURROW_SRC_SYSCALL_ZSYSCALL_H
#define BURROW_SRC_SYSCALL_ZSYSCALL_H

#include "burrow/syscall.h"

#if defined(BURROW_OS_DARWIN) || defined(BURROW_OS_IOS)

/* darwin */

enum {
    BURROW__SYSCALL_LIBC_ACCEPT,
    BURROW__SYSCALL_LIBC_ACCESS,
    BURROW__SYSCALL_LIBC_ADJTIME,
    BURROW__SYSCALL_LIBC_BIND,
    BURROW__SYSCALL_LIBC_CHDIR,
    BURROW__SYSCALL_LIBC_CHFLAGS,
    BURROW__SYSCALL_LIBC_CHMOD,
    BURROW__SYSCALL_LIBC_CHOWN,
    BURROW__SYSCALL_LIBC_CHROOT,
    BURROW__SYSCALL_LIBC_CLOSE,
    BURROW__SYSCALL_LIBC_CLOSEDIR,
    BURROW__SYSCALL_LIBC_CONNECT,
    BURROW__SYSCALL_LIBC_DUP,
    BURROW__SYSCALL_LIBC_DUP2,
    BURROW__SYSCALL_LIBC_EXCHANGEDATA,
    BURROW__SYSCALL_LIBC_EXECVE,
    BURROW__SYSCALL_LIBC_EXIT,
    BURROW__SYSCALL_LIBC_FCHDIR,
    BURROW__SYSCALL_LIBC_FCHFLAGS,
    BURROW__SYSCALL_LIBC_FCHMOD,
    BURROW__SYSCALL_LIBC_FCHOWN,
    BURROW__SYSCALL_LIBC_FCNTL,
    BURROW__SYSCALL_LIBC_FLOCK,
    BURROW__SYSCALL_LIBC_FORK,
    BURROW__SYSCALL_LIBC_FPATHCONF,
    BURROW__SYSCALL_LIBC_FSTAT,
    BURROW__SYSCALL_LIBC_FSTAT64,
    BURROW__SYSCALL_LIBC_FSTATAT,
    BURROW__SYSCALL_LIBC_FSTATAT64,
    BURROW__SYSCALL_LIBC_FSTATFS,
    BURROW__SYSCALL_LIBC_FSTATFS64,
    BURROW__SYSCALL_LIBC_FSYNC,
    BURROW__SYSCALL_LIBC_FTRUNCATE,
    BURROW__SYSCALL_LIBC_FUTIMES,
    BURROW__SYSCALL_LIBC_GETCWD,
    BURROW__SYSCALL_LIBC_GETDTABLESIZE,
    BURROW__SYSCALL_LIBC_GETEGID,
    BURROW__SYSCALL_LIBC_GETEUID,
    BURROW__SYSCALL_LIBC_GETGID,
    BURROW__SYSCALL_LIBC_GETGROUPS,
    BURROW__SYSCALL_LIBC_GETPEERNAME,
    BURROW__SYSCALL_LIBC_GETPGID,
    BURROW__SYSCALL_LIBC_GETPGRP,
    BURROW__SYSCALL_LIBC_GETPID,
    BURROW__SYSCALL_LIBC_GETPPID,
    BURROW__SYSCALL_LIBC_GETPRIORITY,
    BURROW__SYSCALL_LIBC_GETRLIMIT,
    BURROW__SYSCALL_LIBC_GETRUSAGE,
    BURROW__SYSCALL_LIBC_GETSID,
    BURROW__SYSCALL_LIBC_GETSOCKNAME,
    BURROW__SYSCALL_LIBC_GETSOCKOPT,
    BURROW__SYSCALL_LIBC_GETTIMEOFDAY,
    BURROW__SYSCALL_LIBC_GETUID,
    BURROW__SYSCALL_LIBC_IOCTL,
    BURROW__SYSCALL_LIBC_ISSETUGID,
    BURROW__SYSCALL_LIBC_KEVENT,
    BURROW__SYSCALL_LIBC_KILL,
    BURROW__SYSCALL_LIBC_KQUEUE,
    BURROW__SYSCALL_LIBC_LCHOWN,
    BURROW__SYSCALL_LIBC_LINK,
    BURROW__SYSCALL_LIBC_LISTEN,
    BURROW__SYSCALL_LIBC_LSEEK,
    BURROW__SYSCALL_LIBC_LSTAT,
    BURROW__SYSCALL_LIBC_LSTAT64,
    BURROW__SYSCALL_LIBC_MKDIR,
    BURROW__SYSCALL_LIBC_MKFIFO,
    BURROW__SYSCALL_LIBC_MKNOD,
    BURROW__SYSCALL_LIBC_MLOCK,
    BURROW__SYSCALL_LIBC_MLOCKALL,
    BURROW__SYSCALL_LIBC_MMAP,
    BURROW__SYSCALL_LIBC_MPROTECT,
    BURROW__SYSCALL_LIBC_MSYNC,
    BURROW__SYSCALL_LIBC_MUNLOCK,
    BURROW__SYSCALL_LIBC_MUNLOCKALL,
    BURROW__SYSCALL_LIBC_MUNMAP,
    BURROW__SYSCALL_LIBC_OPEN,
    BURROW__SYSCALL_LIBC_OPENAT,
    BURROW__SYSCALL_LIBC_PATHCONF,
    BURROW__SYSCALL_LIBC_PIPE,
    BURROW__SYSCALL_LIBC_PREAD,
    BURROW__SYSCALL_LIBC_PTRACE,
    BURROW__SYSCALL_LIBC_PWRITE,
    BURROW__SYSCALL_LIBC_READ,
    BURROW__SYSCALL_LIBC_READDIR_R,
    BURROW__SYSCALL_LIBC_READLINK,
    BURROW__SYSCALL_LIBC_RECVFROM,
    BURROW__SYSCALL_LIBC_RECVMSG,
    BURROW__SYSCALL_LIBC_RENAME,
    BURROW__SYSCALL_LIBC_REVOKE,
    BURROW__SYSCALL_LIBC_RMDIR,
    BURROW__SYSCALL_LIBC_SELECT,
    BURROW__SYSCALL_LIBC_SENDMSG,
    BURROW__SYSCALL_LIBC_SENDTO,
    BURROW__SYSCALL_LIBC_SETEGID,
    BURROW__SYSCALL_LIBC_SETEUID,
    BURROW__SYSCALL_LIBC_SETGID,
    BURROW__SYSCALL_LIBC_SETGROUPS,
    BURROW__SYSCALL_LIBC_SETLOGIN,
    BURROW__SYSCALL_LIBC_SETPGID,
    BURROW__SYSCALL_LIBC_SETPRIORITY,
    BURROW__SYSCALL_LIBC_SETPRIVEXEC,
    BURROW__SYSCALL_LIBC_SETREGID,
    BURROW__SYSCALL_LIBC_SETREUID,
    BURROW__SYSCALL_LIBC_SETRLIMIT,
    BURROW__SYSCALL_LIBC_SETSID,
    BURROW__SYSCALL_LIBC_SETSOCKOPT,
    BURROW__SYSCALL_LIBC_SETTIMEOFDAY,
    BURROW__SYSCALL_LIBC_SETUID,
    BURROW__SYSCALL_LIBC_SHUTDOWN,
    BURROW__SYSCALL_LIBC_SOCKET,
    BURROW__SYSCALL_LIBC_SOCKETPAIR,
    BURROW__SYSCALL_LIBC_STAT,
    BURROW__SYSCALL_LIBC_STAT64,
    BURROW__SYSCALL_LIBC_STATFS,
    BURROW__SYSCALL_LIBC_STATFS64,
    BURROW__SYSCALL_LIBC_SYMLINK,
    BURROW__SYSCALL_LIBC_SYNC,
    BURROW__SYSCALL_LIBC_SYSCTL,
    BURROW__SYSCALL_LIBC_TRUNCATE,
    BURROW__SYSCALL_LIBC_UMASK,
    BURROW__SYSCALL_LIBC_UNDELETE,
    BURROW__SYSCALL_LIBC_UNLINK,
    BURROW__SYSCALL_LIBC_UNLINKAT,
    BURROW__SYSCALL_LIBC_UNMOUNT,
    BURROW__SYSCALL_LIBC_UTIMENSAT,
    BURROW__SYSCALL_LIBC_UTIMES,
    BURROW__SYSCALL_LIBC_WAIT4,
    BURROW__SYSCALL_LIBC_WRITE,
    BURROW__SYSCALL_LIBC_WRITEV,
    BURROW__SYSCALL_NLIBC
};

/* A libSystem function: its name, and how many parameters come before the
 * "..." if it is variadic, or -1. */
typedef struct burrow__SyscallLibc {
    const char *name;
    int32_t nfixed;
} burrow__SyscallLibc;

extern const burrow__SyscallLibc burrow__syscall_libc[BURROW__SYSCALL_NLIBC];

/* Where each one is, once it has been looked up, in src/syscall/call.c. */
extern void *burrow__syscall_libc_cache[BURROW__SYSCALL_NLIBC];

Int burrow__syscall_accept(Int s, SyscallRawSockaddrAny *rsa, uint32_t *addrlen, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_bind(Int s, void *addr, uint32_t addrlen);
BURROW_OWNS(ret) Error burrow__syscall_closedir(Uintptr dir);
BURROW_OWNS(ret) Error burrow__syscall_connect(Int s, void *addr, uint32_t addrlen);
BURROW_OWNS(ret) Error burrow__syscall_execve(uint8_t *path, uint8_t **argv, uint8_t **envp);
BURROW_OWNS(ret) Error burrow__syscall_exit(Int res);
Int burrow__syscall_fcntl(Int fd, Int cmd, Int arg, Error *err);
Int burrow__syscall_fcntl_ptr(Int fd, Int cmd, void *arg, Error *err);
Int burrow__syscall_fork(Error *err);
BURROW_OWNS(ret) Error burrow__syscall_fstatat(Int fd, Str path, SyscallStat_t *stat, Int flags);
BURROW_OWNS(ret) Error burrow__syscall_futimes(Int fd, SyscallTimeval *timeval);
Int burrow__syscall_getcwd(Slice buf, Error *err);
Int burrow__syscall_getgroups(Int ngid, uint32_t *gid, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_getpeername(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen);
BURROW_OWNS(ret) Error burrow__syscall_getsockname(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen);
BURROW_OWNS(ret) Error burrow__syscall_getsockopt(Int s, Int level, Int name, void *val, uint32_t *vallen);
BURROW_OWNS(ret) Error burrow__syscall_ioctl(Int fd, Int req, Int arg);
BURROW_OWNS(ret) Error burrow__syscall_ioctl_ptr(Int fd, Uint req, void *arg);
Int burrow__syscall_kevent(Int kq, void *change, Int nchange, void *event, Int nevent, SyscallTimespec *timeout, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_kill(Int pid, Int signum, Int posix);
Uintptr burrow__syscall_mmap(Uintptr addr, Uintptr length, Int prot, Int flag, Int fd, int64_t pos, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_msync(Slice b, Int flags);
BURROW_OWNS(ret) Error burrow__syscall_munmap(Uintptr addr, Uintptr length);
Int burrow__syscall_openat(Int fd, Str path, Int flags, uint32_t perm, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_pipe(int32_t *p);
Int burrow__syscall_pread(Int fd, Slice p, int64_t offset, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_ptrace(Int request, Int pid, Uintptr addr, Uintptr data);
Int burrow__syscall_pwrite(Int fd, Slice p, int64_t offset, Error *err);
Int burrow__syscall_read(Int fd, Slice p, Error *err);
SyscallErrno burrow__syscall_readdir_r(Uintptr dir, SyscallDirent *entry, SyscallDirent **result);
Int burrow__syscall_recvfrom(Int fd, Slice p, Int flags, SyscallRawSockaddrAny *from, uint32_t *fromlen, Error *err);
Int burrow__syscall_recvmsg(Int s, SyscallMsghdr *msg, Int flags, Error *err);
Int burrow__syscall_sendmsg(Int s, SyscallMsghdr *msg, Int flags, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_sendto(Int s, Slice buf, Int flags, void *to, uint32_t addrlen);
BURROW_OWNS(ret) Error burrow__syscall_setgroups(Int ngid, uint32_t *gid);
BURROW_OWNS(ret) Error burrow__syscall_setrlimit(Int which, SyscallRlimit *lim);
BURROW_OWNS(ret) Error burrow__syscall_setsockopt(Int s, Int level, Int name, void *val, Uintptr vallen);
Int burrow__syscall_socket(Int domain, Int typ, Int proto, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_socketpair(Int domain, Int typ, Int proto, int32_t *fd);
BURROW_OWNS(ret) Error burrow__syscall_sysctl(Slice mib, uint8_t *old, Uintptr *oldlen, uint8_t *new_, Uintptr newlen);
BURROW_OWNS(ret) Error burrow__syscall_unlinkat(Int fd, Str path, Int flags);
BURROW_OWNS(ret) Error burrow__syscall_utimensat(Int dirfd, Str path, SyscallTimespec *times, Int flags);
BURROW_OWNS(ret) Error burrow__syscall_utimes(Str path, SyscallTimeval *timeval);
Int burrow__syscall_wait4(Int pid, int32_t *wstatus, Int options, SyscallRusage *rusage, Error *err);
Int burrow__syscall_write(Int fd, Slice p, Error *err);
Uintptr burrow__syscall_writev(Int fd, Slice iovecs, Error *err);

#elif defined(BURROW_OS_FREEBSD)

/* freebsd */

Int burrow__syscall_accept(Int s, SyscallRawSockaddrAny *rsa, uint32_t *addrlen, Error *err);
Int burrow__syscall_accept4(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen, Int flags, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_bind(Int s, void *addr, uint32_t addrlen);
BURROW_OWNS(ret) Error burrow__syscall_connect(Int s, void *addr, uint32_t addrlen);
Int burrow__syscall_fcntl(Int fd, Int cmd, Int arg, Error *err);
Int burrow__syscall_fcntl_ptr(Int fd, Int cmd, void *arg, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_futimes(Int fd, SyscallTimeval *timeval);
Int burrow__syscall_getcwd(Slice buf, Error *err);
Int burrow__syscall_getdirentries(Int fd, Slice buf, uint64_t *basep, Error *err);
Int burrow__syscall_getgroups(Int ngid, uint32_t *gid, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_getpeername(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen);
BURROW_OWNS(ret) Error burrow__syscall_getsockname(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen);
BURROW_OWNS(ret) Error burrow__syscall_getsockopt(Int s, Int level, Int name, void *val, uint32_t *vallen);
BURROW_OWNS(ret) Error burrow__syscall_ioctl(Int fd, Int req, Int arg);
BURROW_OWNS(ret) Error burrow__syscall_ioctl_ptr(Int fd, Uint req, void *arg);
Int burrow__syscall_kevent(Int kq, void *change, Int nchange, void *event, Int nevent, SyscallTimespec *timeout, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_mknodat(Int fd, Str path, uint32_t mode, uint64_t dev);
Uintptr burrow__syscall_mmap(Uintptr addr, Uintptr length, Int prot, Int flag, Int fd, int64_t pos, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_munmap(Uintptr addr, Uintptr length);
BURROW_OWNS(ret) Error burrow__syscall_pipe2(int32_t *p, Int flags);
Int burrow__syscall_pread(Int fd, Slice p, int64_t offset, Error *err);
Int burrow__syscall_pwrite(Int fd, Slice p, int64_t offset, Error *err);
Int burrow__syscall_read(Int fd, Slice p, Error *err);
Int burrow__syscall_readlen(Int fd, uint8_t *buf, Int nbuf, Error *err);
Int burrow__syscall_recvfrom(Int fd, Slice p, Int flags, SyscallRawSockaddrAny *from, uint32_t *fromlen, Error *err);
Int burrow__syscall_recvmsg(Int s, SyscallMsghdr *msg, Int flags, Error *err);
Int burrow__syscall_sendmsg(Int s, SyscallMsghdr *msg, Int flags, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_sendto(Int s, Slice buf, Int flags, void *to, uint32_t addrlen);
BURROW_OWNS(ret) Error burrow__syscall_setgroups(Int ngid, uint32_t *gid);
BURROW_OWNS(ret) Error burrow__syscall_setrlimit(Int which, SyscallRlimit *lim);
BURROW_OWNS(ret) Error burrow__syscall_setsockopt(Int s, Int level, Int name, void *val, Uintptr vallen);
Int burrow__syscall_socket(Int domain, Int typ, Int proto, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_socketpair(Int domain, Int typ, Int proto, int32_t *fd);
BURROW_OWNS(ret) Error burrow__syscall_sysctl(Slice mib, uint8_t *old, Uintptr *oldlen, uint8_t *new_, Uintptr newlen);
BURROW_OWNS(ret) Error burrow__syscall_utimensat(Int dirfd, Str path, SyscallTimespec *times, Int flag);
BURROW_OWNS(ret) Error burrow__syscall_utimes(Str path, SyscallTimeval *timeval);
Int burrow__syscall_wait4(Int pid, int32_t *wstatus, Int options, SyscallRusage *rusage, Error *err);
Int burrow__syscall_write(Int fd, Slice p, Error *err);

#elif defined(BURROW_OS_LINUX) || defined(BURROW_OS_COSMO) || defined(BURROW_OS_WASI)

/* linux */

#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
Int burrow__syscall_accept4(Int s, SyscallRawSockaddrAny *rsa, uint32_t *addrlen, Int flags, Error *err);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_bind(Int s, void *addr, uint32_t addrlen);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_connect(Int s, void *addr, uint32_t addrlen);
#endif
BURROW_OWNS(ret) Error burrow__syscall_exit_thread(Int code);
BURROW_OWNS(ret) Error burrow__syscall_faccessat(Int dirfd, Str path, uint32_t mode);
BURROW_OWNS(ret) Error burrow__syscall_faccessat2(Int dirfd, Str path, uint32_t mode, Int flags);
BURROW_OWNS(ret) Error burrow__syscall_fchmodat(Int dirfd, Str path, uint32_t mode);
BURROW_OWNS(ret) Error burrow__syscall_fchmodat2(Int dirfd, Str path, uint32_t mode, Int flags);
Int burrow__syscall_fcntl(Int fd, Int cmd, Int arg, Error *err);
#if defined(BURROW_ARCH_AMD64)
BURROW_OWNS(ret) Error burrow__syscall_fstatat(Int fd, Str path, SyscallStat_t *stat, Int flags);
#elif defined(BURROW_ARCH_LOONG64) || defined(BURROW_ARCH_MIPS64)
#else
BURROW_OWNS(ret) Error burrow__syscall_fstatat(Int dirfd, Str path, SyscallStat_t *stat, Int flags);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_AMD64) || defined(BURROW_ARCH_ARM) || defined(BURROW_ARCH_MIPS64) || defined(BURROW_ARCH_PPC64) || defined(BURROW_ARCH_S390X)
BURROW_OWNS(ret) Error burrow__syscall_futimesat(Int dirfd, Str path, SyscallTimeval *times);
#endif
Int burrow__syscall_getgroups(Int n, uint32_t *list, Error *err);
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_getpeername(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_getsockname(Int fd, SyscallRawSockaddrAny *rsa, uint32_t *addrlen);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_getsockopt(Int s, Int level, Int name, void *val, uint32_t *vallen);
#endif
BURROW_OWNS(ret) Error burrow__syscall_linkat(Int olddirfd, Str oldpath, Int newdirfd, Str newpath, Int flags);
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_ARM) || defined(BURROW_ARCH_S390X)
#else
Uintptr burrow__syscall_mmap(Uintptr addr, Uintptr length, Int prot, Int flags, Int fd, int64_t offset, Error *err);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_ARM)
Uintptr burrow__syscall_mmap2(Uintptr addr, Uintptr length, Int prot, Int flags, Int fd, Uintptr pageOffset, Error *err);
#endif
BURROW_OWNS(ret) Error burrow__syscall_mount(Str source, Str target, Str fstype, Uintptr flags, uint8_t *data);
BURROW_OWNS(ret) Error burrow__syscall_munmap(Uintptr addr, Uintptr length);
Int burrow__syscall_openat(Int dirfd, Str path, Int flags, uint32_t mode, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_pipe2(int32_t *p, Int flags);
Int burrow__syscall_pread(Int fd, Slice p, int64_t offset, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_prlimit1(Int pid, Int resource, SyscallRlimit *newlimit, SyscallRlimit *old);
BURROW_OWNS(ret) Error burrow__syscall_ptrace(Int request, Int pid, Uintptr addr, Uintptr data);
BURROW_OWNS(ret) Error burrow__syscall_ptrace_ptr(Int request, Int pid, Uintptr addr, void *data);
Int burrow__syscall_pwrite(Int fd, Slice p, int64_t offset, Error *err);
Int burrow__syscall_read(Int fd, Slice p, Error *err);
Int burrow__syscall_readlen(Int fd, uint8_t *p, Int np, Error *err);
Int burrow__syscall_readlinkat(Int dirfd, Str path, Slice buf, Error *err);
BURROW_OWNS(ret) Error burrow__syscall_reboot(Uint magic1, Uint magic2, Int cmd, Str arg);
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
Int burrow__syscall_recvfrom(Int fd, Slice p, Int flags, SyscallRawSockaddrAny *from, uint32_t *fromlen, Error *err);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
Int burrow__syscall_recvmsg(Int s, SyscallMsghdr *msg, Int flags, Error *err);
#endif
#if defined(BURROW_ARCH_RISCV64)
BURROW_OWNS(ret) Error burrow__syscall_renameat2(Int olddirfd, Str oldpath, Int newdirfd, Str newpath, Uint flags);
#endif
Int burrow__syscall_sendfile(Int outfd, Int infd, int64_t *offset, Int count, Error *err);
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
Int burrow__syscall_sendmsg(Int s, SyscallMsghdr *msg, Int flags, Error *err);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_sendto(Int s, Slice buf, Int flags, void *to, uint32_t addrlen);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_setsockopt(Int s, Int level, Int name, void *val, Uintptr vallen);
#endif
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
Int burrow__syscall_socket(Int domain, Int typ, Int proto, Error *err);
#endif
#if defined(BURROW_ARCH_ARM)
BURROW_OWNS(ret) Error burrow__syscall_socketpair(Int domain, Int typ, Int flags, int32_t *fd);
#elif defined(BURROW_ARCH_386) || defined(BURROW_ARCH_S390X)
#else
BURROW_OWNS(ret) Error burrow__syscall_socketpair(Int domain, Int typ, Int proto, int32_t *fd);
#endif
BURROW_OWNS(ret) Error burrow__syscall_symlinkat(Str oldpath, Int newdirfd, Str newpath);
#if defined(BURROW_ARCH_PPC64)
BURROW_OWNS(ret) Error burrow__syscall_sync_file_range2(Int fd, Int flags, int64_t off, int64_t n);
#endif
BURROW_OWNS(ret) Error burrow__syscall_unlinkat(Int dirfd, Str path, Int flags);
BURROW_OWNS(ret) Error burrow__syscall_utimensat(Int dirfd, Str path, SyscallTimespec *times, Int flag);
#if defined(BURROW_ARCH_386) || defined(BURROW_ARCH_AMD64) || defined(BURROW_ARCH_ARM) || defined(BURROW_ARCH_MIPS64) || defined(BURROW_ARCH_PPC64) || defined(BURROW_ARCH_S390X)
BURROW_OWNS(ret) Error burrow__syscall_utimes(Str path, SyscallTimeval *times);
#endif
Int burrow__syscall_wait4(Int pid, int32_t *wstatus, Int options, SyscallRusage *rusage, Error *err);
Int burrow__syscall_write(Int fd, Slice p, Error *err);

#endif

#endif /* BURROW_SRC_SYSCALL_ZSYSCALL_H */
