#!/bin/sh
# Regenerates tests/time_calendar_test_gen.h: what Go's package time says about
# a list of instants in a list of zones, and about the arithmetic on them.
#
# The zones are TZif files out of Go's own lib/time/zoneinfo.zip and the slim
# files in src/time/testdata, and their bytes go into the header, so the tests
# get the same answers on a machine with an old zoneinfo, or none. For every
# zone and instant it records the date, the clock, the weekday, the day of the
# year, the ISO week, the zone and its bounds and the binary encoding. Then
# Date with fields out of range, AddDate, Truncate, Round, Sub, the Duration
# methods, the tzset tables of Go's zoneinfo_test.go, and what happens to a
# TZif file cut short or with a byte flipped.
#
# The generator is a test file laid over the package with go test -overlay, so
# it can call tzset and loadTzinfoFromZip by name.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/time_calendar_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

goroot=$(go env GOROOT)
pkg=$goroot/src/time

cat > "$tmp/zz_gen_test.go" <<'GO'
package time_test

import (
	"archive/zip"
	"fmt"
	"io"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"testing"
	. "time"
)

func loadTzinfoFromZip(zipfile, name string) ([]byte, error) {
	z, err := zip.OpenReader(zipfile)
	if err != nil {
		return nil, err
	}
	defer z.Close()
	f, err := z.Open(name)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return io.ReadAll(f)
}

var genOut strings.Builder

func w(format string, args ...any) { fmt.Fprintf(&genOut, format, args...) }

// cq quotes s as a C string literal, every byte that is not plain printable
// ASCII as a three digit octal escape, which can not run into the next byte.
func cq(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"' || c == '\\' || c == '?':
			fmt.Fprintf(&b, "\\%03o", c)
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func cerr(err error) string {
	if err == nil {
		return "NULL"
	}
	return cq(err.Error())
}

func cbool(b bool) int {
	if b {
		return 1
	}
	return 0
}

func i64(v int64) string {
	if v == math.MinInt64 {
		return "INT64_MIN"
	}
	return fmt.Sprintf("INT64_C(%d)", v)
}

func hexf(f float64) string { return strconv.FormatFloat(f, 'x', -1, 64) }

type genZone struct {
	name string
	data []byte
	loc  *Location
}

func TestZZGen(t *testing.T) {
	zip := os.Getenv("GEN_ZIP")
	var zones []genZone
	for _, name := range []string{
		"America/New_York", "Europe/Berlin", "Australia/Sydney", "Asia/Kolkata",
		"Pacific/Chatham", "Europe/Dublin", "America/Sao_Paulo", "Etc/GMT+5",
		"Pacific/Kiritimati", "PST8PDT", "Pacific/Fakaofo", "Asia/Jerusalem",
		"Asia/Tokyo", "Europe/London", "America/St_Johns", "Africa/Casablanca",
	} {
		data, err := loadTzinfoFromZip(zip, name)
		if err != nil {
			t.Fatal(err)
		}
		zones = append(zones, genZone{name: name, data: data})
	}
	for _, f := range []string{"2020b_Europe_Berlin", "2021a_America_Nuuk", "2021a_Asia_Gaza", "2021a_Europe_Dublin"} {
		data, err := os.ReadFile("testdata/" + f)
		if err != nil {
			t.Fatal(err)
		}
		zones = append(zones, genZone{name: f, data: data})
	}
	for i := range zones {
		l, err := LoadLocationFromTZData(zones[i].name, zones[i].data)
		if err != nil {
			t.Fatal(err)
		}
		zones[i].loc = l
	}

	w("/* What Go's package time says about the cases of tools/gen-time-tests.sh,\n")
	w(" * %s. Generated by that script; do not edit. */\n\n", runtime.Version())

	w("static const TzBlob g_zones[] = {\n")
	for _, z := range zones {
		w("    {%q, %s, %d},\n", z.name, cq(string(z.data)), len(z.data))
	}
	w("};\n\n")

	// The locations a case can be in: UTC, the zones above, and a few fixed
	// zones, numbered after the zones.
	type fixed struct {
		name string
		off  int
	}
	fixeds := []fixed{{"", 3600}, {"", -5 * 3600}, {"XST", 5*3600 + 30*60}, {"", 45}, {"ODD", -(9*3600 + 30*60 + 7)}}
	w("static const TzFixed g_fixed[] = {\n")
	for _, f := range fixeds {
		w("    {%q, %d},\n", f.name, f.off)
	}
	w("};\n\n")
	locOf := func(i int) *Location {
		switch {
		case i < 0:
			return UTC
		case i < len(zones):
			return zones[i].loc
		default:
			f := fixeds[i-len(zones)]
			return FixedZone(f.name, f.off)
		}
	}
	nloc := len(zones) + len(fixeds)

	// Instants.
	secs := []int64{
		-62135596800, -62135596801, -62135596800 + 86400*59, 0, -1, 1, 1e9, 1234567890,
		1700000000, 2159200800, -1633269601, -1633269600, 1325242799, 1325242800,
		-2e9, -5e9, 4e9, 1e11, -1e11, 253402300799, 253402300800, 951782400,
		951868800, 1104537600, 1230768000, 1293753600, 1609372800, 1711846800,
		1711850400, 1730595600, 1730599200, 1616893200, -2208988800,
		-9223372036854775808 / 2, 9223372036854775807 / 2, 20000000000,
	}
	nsecs := []int64{0, 1, 999999999, 500000000}
	w("static const TCase g_times[] = {\n")
	n := 0
	for li := -1; li < nloc; li++ {
		loc := locOf(li)
		for si, s := range secs {
			ns := nsecs[si%len(nsecs)]
			tm := Unix(s, ns).In(loc)
			y, mo, d := tm.Date()
			h, mi, sc := tm.Clock()
			iy, iw := tm.ISOWeek()
			zn, zo := tm.Zone()
			bs, be := tm.ZoneBounds()
			bin, err := tm.MarshalBinary()
			w("    {%d, %s, %d, %s, %d, %d, %d, %d, %d, %d, %d, %s, %d, %s, %d, %d, %s, %d, %s, %d, %s, %s, %s, %d, %s, %s},\n",
				li, i64(s), ns, i64(int64(y)), mo, d, h, mi, sc, tm.Weekday(), tm.YearDay(),
				i64(int64(iy)), iw, cq(zn), zo, cbool(tm.IsDST()),
				i64(bs.Unix()), cbool(bs.IsZero()), i64(be.Unix()), cbool(be.IsZero()),
				cq(string(bin)), cerr(err), i64(tm.UnixMilli()), len(bin),
				i64(tm.UnixMicro()), i64(tm.UnixNano()))
			n++
		}
	}
	w("};\n\n")

	// Date with its fields out of range, and in the gaps and overlaps.
	type dcase struct {
		y, mo, d, h, mi, s, ns int
	}
	dates := []dcase{
		{2009, 11, 10, 23, 0, 0, 0}, {2011, 3, 13, 2, 30, 0, 0}, {2011, 11, 6, 1, 30, 0, 0},
		{2024, 3, 31, 2, 30, 0, 0}, {2024, 10, 27, 2, 30, 0, 0}, {2024, 13, 1, 0, 0, 0, 0},
		{2024, 0, 1, 0, 0, 0, 0}, {2024, -25, 1, 0, 0, 0, 0}, {2024, 2, 30, 0, 0, 0, 0},
		{2023, 2, 29, 0, 0, 0, 0}, {2024, 1, 0, 0, 0, 0, 0}, {2024, 1, -400, 25, 61, 61, 1e9 + 5},
		{2024, 1, 1, -1, -1, -1, -1}, {1, 1, 1, 0, 0, 0, 0}, {0, 1, 1, 0, 0, 0, 0},
		{-1, 12, 31, 23, 59, 59, 999999999}, {1970, 1, 1, 0, 0, 0, 0}, {9999, 12, 31, 23, 59, 59, 999999999},
		{2000, 2, 29, 12, 0, 0, 0}, {1900, 2, 29, 12, 0, 0, 0}, {2100, 3, 1, 0, 0, 0, 0},
		{2024, 7, 4, 1e6, 0, 0, 0}, {2024, 7, 4, 0, 1e9, 0, 0}, {2024, 7, 4, 0, 0, 1e12, 0},
		{2024, 7, 4, 0, 0, 0, -9e18}, {2024, 7, 4, 0, 0, 0, 9e18}, {1e9, 1, 1, 0, 0, 0, 0},
		{-1e9, 1, 1, 0, 0, 0, 0}, {2024, 1e9, 1, 0, 0, 0, 0}, {2024, 1, 1e9, 0, 0, 0, 0},
		{1918, 3, 31, 2, 30, 0, 0}, {2011, 12, 30, 12, 0, 0, 0}, {2021, 4, 2, 11, 12, 13, 0},
		{2020, 10, 29, 15, 30, 0, 0}, {2038, 3, 28, 2, 30, 0, 0}, {2100, 10, 31, 1, 30, 0, 0},
	}
	w("static const DCase g_dates[] = {\n")
	for li := -1; li < nloc; li++ {
		loc := locOf(li)
		for _, d := range dates {
			tm := Date(d.y, Month(d.mo), d.d, d.h, d.mi, d.s, d.ns, loc)
			zn, zo := tm.Zone()
			w("    {%d, %d, %d, %d, %d, %d, %d, %d, %s, %d, %s, %d},\n",
				li, d.y, d.mo, d.d, d.h, d.mi, d.s, d.ns, i64(tm.Unix()), tm.Nanosecond(), cq(zn), zo)
		}
	}
	w("};\n\n")

	// AddDate.
	type acase struct{ y, m, d int }
	adds := []acase{{0, 0, 0}, {0, 1, 0}, {0, 0, 1}, {1, 0, 0}, {0, -1, 0}, {-1, -1, -1}, {0, 13, 0}, {0, 0, 366}, {4, 0, -1}, {0, 0, -1e6}, {100, -1200, 0}}
	bases := []int64{1700000000, 951782400, 1711846800, 1730595600, -1633269601, 0, 1098000000}
	w("static const ACase g_adds[] = {\n")
	for _, li := range []int{-1, 0, 1, 2, 5} {
		loc := locOf(li)
		for _, b := range bases {
			for _, a := range adds {
				tm := Unix(b, 123).In(loc).AddDate(a.y, a.m, a.d)
				w("    {%d, %s, %d, %d, %d, %s, %d},\n", li, i64(b), a.y, a.m, a.d, i64(tm.Unix()), tm.Nanosecond())
			}
		}
	}
	w("};\n\n")

	// Truncate and Round, which work from the zero time and ignore the
	// location.
	durs := []Duration{0, -1, 1, 2, 3, 7, Microsecond, Millisecond, Second, 2 * Second, Minute, 10 * Minute, Hour, 3 * Hour, 24 * Hour, 7 * 24 * Hour, 1<<62 + 3, 1<<63 - 1, 17 * Second / 3, 1e18}
	tsecs := []int64{0, 1, -1, 1e9, -62135596800, 1700000000, -1e11, 1e11, 253402300799}
	tnsec := []int64{0, 1, 499999999, 500000000, 500000001, 999999999, 123456789}
	w("static const RCase g_rounds[] = {\n")
	for _, s := range tsecs {
		for _, ns := range tnsec {
			for _, d := range durs {
				tt := Unix(s, ns).Truncate(d)
				tr := Unix(s, ns).Round(d)
				w("    {%s, %d, %s, %s, %d, %s, %d},\n", i64(s), ns, i64(int64(d)), i64(tt.Unix()), tt.Nanosecond(), i64(tr.Unix()), tr.Nanosecond())
			}
		}
	}
	w("};\n\n")

	// Sub, Compare and friends.
	type sc struct{ s, ns int64 }
	subs := []sc{{0, 0}, {0, 1}, {1, 0}, {-1, 999999999}, {1e9, 5}, {-62135596800, 0}, {253402300799, 999999999}, {9223372036, 854775807}, {9223372036, 854775808}, {-9223372036, -854775808}, {-9223372036, -854775809}, {1e11, 0}, {-1e11, 0}}
	w("static const SCase g_subs[] = {\n")
	for _, a := range subs {
		for _, b := range subs {
			ta, tb := Unix(a.s, a.ns), Unix(b.s, b.ns)
			w("    {%s, %s, %s, %s, %s, %d},\n", i64(a.s), i64(a.ns), i64(b.s), i64(b.ns), i64(int64(ta.Sub(tb))), ta.Compare(tb))
		}
	}
	w("};\n\n")

	// Add, which saturates nothing and carries.
	w("static const AddCase g_add[] = {\n")
	for _, a := range subs {
		for _, d := range []Duration{0, 1, -1, 999999999, 1e9, -1e9, 1<<63 - 1, -1 << 63, 36 * Hour} {
			tm := Unix(a.s, a.ns).Add(d)
			w("    {%s, %s, %s, %s, %d},\n", i64(a.s), i64(a.ns), i64(int64(d)), i64(tm.Unix()), tm.Nanosecond())
		}
	}
	w("};\n\n")

	// The Duration methods.
	ds := []Duration{0, 1, -1, 999, 1000, 1500 * Millisecond, -1500 * Millisecond, 3*Hour + 25*Minute + 45*Second + 500*Millisecond, 1<<63 - 1, -1 << 63, -1<<63 + 1, 1e18, -1e18, 1e15 + 1}
	ms := []Duration{0, -1, 1, 2, 3, 1000, Second, Minute, Hour, 7 * Millisecond, 1<<63 - 1, 3e18}
	w("static const DurCase g_durs[] = {\n")
	for _, d := range ds {
		w("    {%s, %s, %s, %s, %s, %s, %s, %s},\n", i64(int64(d)), i64(d.Nanoseconds()), i64(d.Microseconds()), i64(d.Milliseconds()),
			hexf(d.Seconds()), hexf(d.Minutes()), hexf(d.Hours()), i64(int64(d.Abs())))
	}
	w("};\n\n")
	w("static const DurRound g_dur_rounds[] = {\n")
	for _, d := range ds {
		for _, m := range ms {
			w("    {%s, %s, %s, %s},\n", i64(int64(d)), i64(int64(m)), i64(int64(d.Truncate(m))), i64(int64(d.Round(m))))
		}
	}
	w("};\n\n")

	// Month and Weekday names, in range and out.
	w("static const NameCase g_months[] = {\n")
	for _, m := range []int{-1, 0, 1, 2, 6, 11, 12, 13, 100, math.MinInt64} {
		w("    {%s, %q},\n", i64(int64(m)), Month(m).String())
	}
	w("};\n\n")
	w("static const NameCase g_weekdays[] = {\n")
	for _, d := range []int{-1, 0, 1, 3, 6, 7, 100, math.MaxInt64} {
		w("    {%s, %q},\n", i64(int64(d)), Weekday(d).String())
	}
	w("};\n\n")

	// UnmarshalBinary on bad input.
	w("static const BinCase g_bins[] = {\n")
	for _, b := range []string{"", "\x00", "\x01", "\x02", "\x03", "\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff",
		"\x01\x00\x00\x00\x0e\x77\x91\xf7\x00\x00\x00\x00\x00\xff\xff",
		"\x01\x00\x00\x00\x0e\x77\x91\xf7\x00\x00\x00\x00\x00\xff\xff\x00",
		"\x02\x00\x00\x00\x0e\x77\x91\xf7\x00\x00\x00\x00\x00\x00\x3c\x00",
		"\x02\x00\x00\x00\x0e\x77\x91\xf7\x00\x00\x00\x00\x00\x00\x3c\x00\x2d",
		"\x01\x00\x00\x00\x0e\x77\x91\xf7\x00\x00\x00\x00\x00\x00\x3c",
		"\x01\x00\x00\x00\x0e\x77\x91\xf7\x00\x3b\x9a\xc9\xff\x02\x1c"} {
		var tm Time
		err := tm.UnmarshalBinary([]byte(b))
		zn, zo := tm.Zone()
		w("    {%s, %d, %s, %s, %d, %s, %d},\n", cq(b), len(b), cerr(err), i64(tm.Unix()), tm.Nanosecond(), cq(zn), zo)
	}
	w("};\n\n")

	// tzset and its pieces, Go's tables and a few more.
	w("static const TzsetCase g_tzset[] = {\n")
	for _, c := range []struct {
		s        string
		end, sec int64
	}{
		{"", 0, 0}, {"PST8PDT,M3.2.0,M11.1.0", 0, 2159200800}, {"PST8PDT,M3.2.0,M11.1.0", 0, 2152173599},
		{"PST8PDT,M3.2.0,M11.1.0", 0, 2152173600}, {"PST8PDT,M3.2.0,M11.1.0", 0, 2152173601},
		{"PST8PDT,M3.2.0,M11.1.0", 0, 2172733199}, {"PST8PDT,M3.2.0,M11.1.0", 0, 2172733200},
		{"PST8PDT,M3.2.0,M11.1.0", 0, 2172733201}, {"KST-9", 592333200, 1677246697},
		{"EST5EDT", 0, 2159200800}, {"AEST-10AEDT,M10.1.0,M4.1.0/3", 0, 2159200800},
		{"AEST-10AEDT,M10.1.0,M4.1.0/3", 0, 2177452800}, {"IST-1GMT0,M10.5.0,M3.5.0/1", 0, 2159200800},
		{"<-03>3<-02>,M3.5.0/-2,M10.5.0/-1", 0, 2159200800}, {"XXX3YYY,J60,J300", 0, 2159200800},
		{"XXX3YYY,59,299/1:30", 0, 2159200800}, {"XXX3YYY;59,299", 0, 2159200800}, {"XXX3YYY,59", 0, 2159200800},
		{"XXX3YYY2,M3.5.0,M10.5.0", 0, -2e9}, {"XXX3YYY,M2.5.6,M12.5.0", 0, 951782400},
		{"<+0330>-3:30", 0, 1}, {"CET-1CEST,M3.5.0,M10.5.0/3", 0, 1711846799}, {"CET-1CEST,M3.5.0,M10.5.0/3", 0, 1711846800},
		{"X", 0, 0}, {"XXX", 0, 0}, {"XXX3YY", 0, 0}, {"XXX3YYY,M3.2.0", 0, 0},
	} {
		name, off, start, end, isDST, ok := Tzset(c.s, c.end, c.sec)
		w("    {%s, %s, %s, %d, %q, %d, %s, %s, %d},\n", cq(c.s), i64(c.end), i64(c.sec), cbool(ok), name, off, i64(start), i64(end), cbool(isDST))
	}
	w("};\n\n")
	w("static const TzsetNameCase g_tzset_names[] = {\n")
	for _, s := range []string{"", "X", "PST", "PST8PDT", "PST-08", "<A+B>+08", "<A+B", "AB1", "ABCD,", "<>1"} {
		name, rest, ok := TzsetName(s)
		w("    {%s, %d, %s, %s},\n", cq(s), cbool(ok), cq(name), cq(rest))
	}
	w("};\n\n")
	w("static const TzsetOffsetCase g_tzset_offsets[] = {\n")
	for _, s := range []string{"", "X", "+", "+08", "-01:02:03", "01", "100", "1000", "8PDT", "168", "169", "1:60", "1:59:60", "-", "1:", "1:2:"} {
		off, rest, ok := TzsetOffset(s)
		w("    {%s, %d, %d, %s},\n", cq(s), cbool(ok), off, cq(rest))
	}
	w("};\n\n")
	w("static const TzsetRuleCase g_tzset_rules[] = {\n")
	for _, s := range []string{"", "X", "J10", "20", "M1.2.3", "30/03:00:00", "M4.5.6/03:00:00", "M4.5.7/03:00:00", "M4.5.6/-04", "J0", "J366", "366", "M13.1.0", "M1.6.0", "M1.1", "M1", "J1/", "0,"} {
		r, rest, ok := TzsetRule(s)
		w("    {%s, %d, %d, %d, %d, %d, %d, %s},\n", cq(s), cbool(ok), int(r.Kind), r.Day, r.Week, r.Mon, r.Time, cq(rest))
	}
	w("};\n\n")

	// A TZif file cut short at every length, and with each byte flipped.
	probes := []int64{1e9, -2e9, 2159200800}
	w("static const int64_t g_probe[] = {%s, %s, %s};\n\n", i64(probes[0]), i64(probes[1]), i64(probes[2]))
	w("static const BadCase g_bad[] = {\n")
	for _, zi := range []int{12, 9} {
		data := zones[zi].data
		emit := func(what string, d []byte, cut, pos int, x byte) {
			l, err := LoadLocationFromTZData("bad", d)
			var zn [3]string
			var zo [3]int
			if err == nil {
				for i, p := range probes {
					zn[i], zo[i] = Unix(p, 0).In(l).Zone()
				}
			}
			w("    {%d, %d, %d, %d, %s, {%s, %s, %s}, {%d, %d, %d}},\n", zi, cut, pos, x, cerr(err), cq(zn[0]), cq(zn[1]), cq(zn[2]), zo[0], zo[1], zo[2])
			_ = what
		}
		for cut := 0; cut < len(data); cut++ {
			emit("cut", data[:cut], cut, -1, 0)
		}
		for pos := 0; pos < len(data); pos++ {
			d := []byte(string(data))
			d[pos] ^= 0xff
			emit("flip", d, len(data), pos, 0xff)
		}
	}
	issue29437 := "TZif\x00000000000000000\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0000"
	_, err := LoadLocationFromTZData("abc", []byte(issue29437))
	w("};\n\nstatic const char g_issue29437[] = %s;\nstatic const char *const g_issue29437_err = %s;\n", cq(issue29437), cerr(err))
	w("\n/* %d instants. */\n", n)
	os.Stdout.WriteString(genOut.String())
}
GO

printf '{"Replace":{"%s/zz_gen_test.go":"%s/zz_gen_test.go"}}' "$pkg" "$tmp" > "$tmp/overlay.json"
GEN_ZIP="$goroot/lib/time/zoneinfo.zip" go test -overlay "$tmp/overlay.json" -run '^TestZZGen$' -count=1 -v time > "$tmp/out.txt" ||
    { grep -m1 -B2 -A30 "^panic\|^fatal\|FAIL\|cannot\|undefined\|zz_gen" "$tmp/out.txt" >&2; exit 1; }
sed -n '/^\/\* What Go/,$p' "$tmp/out.txt" | sed '/^--- PASS/,$d' > "$out"
if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$out"
fi
echo "wrote $out"
