#!/bin/sh
# Regenerates src/xtext/norm_tables.c, src/xtext/norm_tables.h and
# tests/xtext_norm_test_gen.h from golang.org/x/text/unicode/norm, at the
# version Go vendors, which is the one src/vendor/modules.txt names.
#
# The vendored copy has no tests, so the module comes from the module cache
# through go mod download. tools/gen-xtext/norm_gen_test.go is laid over a
# writable copy of it and run as a test, which lets it read the unexported
# tables and the test tables by name. Besides the tables and Go's own test
# cases, it writes what Go says about a corpus of strings and about every rune,
# as hashes, for tests/xtext_norm_test.c to compare against.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=$(go env GOROOT)
gover=$(go env GOVERSION)

ver=$(sed -n 's|^# golang.org/x/text \(v[^ ]*\)$|\1|p' "$goroot/src/vendor/modules.txt")
[ -n "$ver" ] || { echo "gen-xtext-norm: no golang.org/x/text in modules.txt" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'chmod -R u+w "$tmp" 2>/dev/null; rm -rf "$tmp"' EXIT

dir=$(cd "$tmp" && GOFLAGS=-mod=mod go mod download -json "golang.org/x/text@$ver" |
	sed -n 's|^[[:space:]]*"Dir": "\(.*\)",$|\1|p')
[ -d "$dir" ] || { echo "gen-xtext-norm: could not download golang.org/x/text@$ver" >&2; exit 1; }

cp -R "$dir" "$tmp/text"
chmod -R u+w "$tmp/text"
cp "$root/tools/gen-xtext/norm_gen_test.go" "$tmp/text/unicode/norm/zz_gen_test.go"

banner="/* Derived from Go's src/vendor/golang.org/x/text/unicode/norm/%s.
 * Go source: $gover, golang.org/x/text $ver.
 *
 * Generated by tools/gen-xtext-norm.sh from the Go tables. Do not edit.
 *
 * Copyright 2011 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

"

test_banner="/* Test data for tests/xtext_norm_test.c, from golang.org/x/text $ver's
 * unicode/norm tests, plus what that package says about a corpus of strings
 * and about every rune, as hashes.
 *
 * Generated by tools/gen-xtext-norm.sh. Do not edit.
 *
 * Copyright 2011 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

"

mkdir -p "$root/src/xtext"
(cd "$tmp/text/unicode/norm" &&
	BURROW_XTEXT_SRC="$root/src/xtext" \
	BURROW_XTEXT_TESTS="$root/tests" \
	BURROW_XTEXT_BANNER="$banner" \
	BURROW_XTEXT_TEST_BANNER="$test_banner" \
	GOFLAGS=-mod=mod go test -count=1 -run '^TestZZGen$' .)
