#!/bin/sh
# Regenerates tests/go_doc_test_gen.h for the go/doc tests. It holds what Go's
# own tests read from disk, and the tables of the tests themselves:
#
#   - every file under src/go/doc/testdata that the tests read: the package
#     sources and their .golden files, the examples and their txtar goldens,
#     and pkgdoc/doc.go;
#   - the tests table of synopsis_test.go;
#   - the strings TestComment checks against, out of comment_test.go;
#   - funcsTestFile and the funcsPackage it should give, out of doc_test.go;
#   - the sources and the wanted classification of TestClassifyExamples, and
#     the sources and the output of ExampleNewFromFiles, out of
#     example_test.go;
#   - the cases of TestImportGroupStarts, out of example_internal_test.go.
#
# A file can be bigger than the 64K MSVC takes in one string literal, so each
# one goes out as a list of pieces to put back together.
#
# GOROOT says which Go to read, and defaults to what go env says.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=${GOROOT:-$(go env GOROOT)}
out="$root/tests/go_doc_test_gen.h"

python3 - "$goroot" > "$out" <<'PY'
import os
import re
import sys

goroot = sys.argv[1]
pkg = os.path.join(goroot, "src", "go", "doc")
tdir = os.path.join(pkg, "testdata")
gover = open(os.path.join(goroot, "VERSION")).readline().strip()

# Bytes of a file to each piece, well under what MSVC takes once escaped.
CHUNK = 12000

# The libc calls tools/check-banned.sh looks for. The first letter of a name
# like that goes out as an octal escape so the check does not take the text
# for a call.
BANNED = re.compile(
    rb"(?<![A-Za-z0-9_])(strcpy|strcat|sprintf|vsprintf|gets|strtok|strncpy|"
    rb"strncat|alloca|atoi|atol|atof)[ \t]*\("
)

# And the allocator names tools/check-banned.sh wants kept in the malloc
# backend, which it looks for as words, called or not.
BANNED_ALLOC = re.compile(
    rb"(?<![A-Za-z0-9_])(malloc|calloc|realloc|free|aligned_alloc|posix_memalign|"
    rb"_aligned_malloc|_aligned_realloc|_aligned_free)(?![A-Za-z0-9_])"
)


def lit(b):
    """b as C string literals, one line of the text to each."""
    lines, cur = [], ""
    hide = {m.start() for m in BANNED.finditer(b)}
    hide |= {m.start() for m in BANNED_ALLOC.finditer(b)}
    for i, c in enumerate(b):
        if i in hide:
            s = "\\%03o" % c
        elif c == 10:
            s = "\\n"
        elif c == 9:
            s = "\\t"
        elif c == 34:
            s = '\\"'
        elif c == 92:
            s = "\\\\"
        elif c == 63 and i + 1 < len(b) and b[i + 1] == 63:
            s = "\\?"
        elif 32 <= c < 127:
            s = chr(c)
        else:
            s = "\\%03o" % c
        # an octal escape must not run into a digit after it
        if s.startswith("\\") and s[1:].isdigit() and i + 1 < len(b):
            nxt = b[i + 1]
            if 48 <= nxt <= 55:
                cur += s
                lines.append('"' + cur + '"')
                cur = ""
                continue
        cur += s
        if c == 10 or len(cur) >= 70:
            lines.append('"' + cur + '"')
            cur = ""
    if cur or not lines:
        lines.append('"' + cur + '"')
    return lines


def c_str(b, indent):
    return ("\n" + " " * indent).join(lit(b))


ESC = {"n": "\n", "t": "\t", "r": "\r", "\\": "\\", '"': '"', "'": "'"}


def go_strings(body):
    """The string literals of some Go source, comments skipped, as bytes."""
    out, i = [], 0
    while i < len(body):
        c = body[i]
        if c == "`":
            j = body.index("`", i + 1)
            out.append(body[i + 1 : j].encode())
            i = j + 1
        elif c == '"':
            s, i = "", i + 1
            while body[i] != '"':
                if body[i] == "\\":
                    s += ESC[body[i + 1]]
                    i += 2
                else:
                    s += body[i]
                    i += 1
            out.append(s.encode())
            i += 1
        elif body.startswith("//", i):
            i = body.index("\n", i)
        else:
            i += 1
    return out


def go_const(src, name):
    """The raw string constant name, wherever it is declared."""
    m = re.search(r"(?:^|\s)const %s = `([^`]*)`" % name, src)
    assert m, name
    return m.group(1).encode()


w = sys.stdout.write
w("/* What Go's go/doc tests read, from src/go/doc of %s.\n" % gover)
w(" * Generated by tools/gen-go-doc-tests.sh; do not edit. */\n\n")
w("typedef struct GdocPiece {\n    const char *p;\n    long long n;\n} GdocPiece;\n\n")
w("#define GDOC_P(x) {x, (long long)sizeof(x) - 1}\n\n")
w("typedef struct GdocFile {\n    const char *name;\n    const GdocPiece *pieces;\n")
w("    int npieces;\n} GdocFile;\n\n")

# The files, by their names under testdata.
names = []
for f in sorted(os.listdir(tdir)):
    if f.endswith(".go") or f.endswith(".golden"):
        names.append(f)
for f in sorted(os.listdir(os.path.join(tdir, "examples"))):
    if f.endswith(".go") or f.endswith(".golden"):
        names.append("examples/" + f)
names.append("pkgdoc/doc.go")

ids = []
for k, name in enumerate(names):
    data = open(os.path.join(tdir, name), "rb").read()
    ident = "gdoc_file_%d" % k
    w("static const GdocPiece %s[] = {\n" % ident)
    for off in range(0, max(len(data), 1), CHUNK):
        w("    GDOC_P(" + c_str(data[off : off + CHUNK], 11) + "),\n")
    w("};\n\n")
    ids.append((name, ident))
w("static const GdocFile gdoc_files[] = {\n")
for name, ident in ids:
    w('    {"%s", %s, (int)(sizeof(%s) / sizeof(%s[0]))},\n' % (name, ident, ident, ident))
w("};\n\n")

# synopsis_test.go
src = open(os.path.join(pkg, "synopsis_test.go")).read()
start = src.index("var tests = []struct {")
body = src[src.index("}{\n", start) + 3 : src.index("\n}\n", start)]
w("typedef struct GdocSynopsis {\n    const char *txt;\n    long long txt_len;\n")
w("    long long fsl;\n    const char *syn;\n} GdocSynopsis;\n\n")
w("static const GdocSynopsis gdoc_synopsis[] = {\n")
n = 0
for line in body.splitlines():
    line = line.strip()
    if not line.startswith("{"):
        continue
    m = re.match(r"^\{(.*), (\d+), (\".*\")\},$", line)
    assert m, line
    txt = go_strings(m.group(1))
    syn = go_strings(m.group(3))
    assert len(txt) == 1 and len(syn) == 1, line
    w("    {%s, %d, %s, %s},\n" % (c_str(txt[0], 5), len(txt[0]), m.group(2), c_str(syn[0], 5)))
    n += 1
assert n > 20, "synopsis table"
w("};\n\n")

# comment_test.go
src = open(os.path.join(pkg, "comment_test.go")).read()
start = src.index("\tvar (\n")
body = src[start + 7 : src.index("\n\t)\n", start)]
vals = {}
for line in body.splitlines():
    m = re.match(r"^\t\t(\w+)\s*=\s*(.*)$", line)
    assert m, line
    vals[m.group(1)] = b"".join(go_strings(m.group(2)))
for key in ("input", "wantHTML", "wantOldHTML", "wantMarkdown", "wantText",
            "wantOldText", "wantSynopsis", "wantOldSynopsis"):
    cname = re.sub(r"([A-Z][a-z]+|[A-Z]+)", lambda m: "_" + m.group(1).lower(), key)
    w("static const char gdoc_comment_%s[] =\n    %s;\n\n" % (cname, c_str(vals[key], 4)))

# doc_test.go: funcsTestFile and funcsPackage.
src = open(os.path.join(pkg, "doc_test.go")).read()
w("static const char gdoc_funcs_test_file[] =\n    %s;\n\n"
  % c_str(go_const(src, "funcsTestFile"), 4))

start = src.index("var funcsPackage = &Package{")
body = src[src.index("{", start) : src.index("\n}\n", start) + 2]
toks = re.findall(r'"[^"]*"|[A-Za-z_][A-Za-z0-9_]*|\d+|//[^\n]*|[{}\[\]*:,&]', body)
toks = [t for t in toks if not t.startswith("//")]
pos = [0]


def peek():
    return toks[pos[0]]


def take(want=None):
    t = toks[pos[0]]
    assert want is None or t == want, (t, want)
    pos[0] += 1
    return t


def value():
    """A Go value: a string, a number, or a composite literal."""
    t = peek()
    if t.startswith('"'):
        return take()[1:-1]
    if t.isdigit():
        return int(take())
    # a type, []*Func or Package, before the braces, or nothing at all
    while peek() != "{":
        take()
    take("{")
    fields, items = {}, []
    while peek() != "}":
        if re.match(r"^[A-Za-z_]\w*$", peek()) and toks[pos[0] + 1] == ":":
            k = take()
            take(":")
            fields[k] = value()
        else:
            items.append(value())
        if peek() == ",":
            take()
    take("}")
    return items if items else fields


want = value()
rows = []
for f in want["Funcs"]:
    rows.append(("", "f", f))
for t in want["Types"]:
    for f in t.get("Funcs", []):
        rows.append((t["Name"], "f", f))
    for f in t.get("Methods", []):
        rows.append((t["Name"], "m", f))
w("typedef struct GdocFunc {\n    const char *type, *kind, *name, *recv, *orig;\n")
w("    long long level;\n} GdocFunc;\n\n")
w("/* funcsPackage, a type of \"\" for the package's own functions, a kind of f for\n")
w(" * the functions of a type and m for its methods. */\n")
w("static const GdocFunc gdoc_funcs_package[] = {\n")
for t, kind, f in rows:
    w('    {"%s", "%s", "%s", "%s", "%s", %d},\n'
      % (t, kind, f["Name"], f.get("Recv", ""), f.get("Orig", ""), f.get("Level", 0)))
w("};\n\n")
w("static const char *const gdoc_funcs_types[] = {\n")
for t in want["Types"]:
    w('    "%s",\n' % t["Name"])
w("};\n\n")

# example_test.go. The raw strings hold Go code of their own, so the
# functions are not cut at their closing braces.
src = open(os.path.join(pkg, "example_test.go")).read()
fn = src[src.index("func TestClassifyExamples("):]
w("static const char gdoc_classify_src[] =\n    %s;\n\n" % c_str(go_const(fn, "src"), 4))
w("static const char gdoc_classify_test[] =\n    %s;\n\n" % c_str(go_const(fn, "test"), 4))
body = fn[fn.index("want := map[string][]string{") :]
body = body[: body.index("\n\t}\n")]
w("typedef struct GdocClass {\n    const char *id;\n    const char *suffixes[4];\n")
w("    int n;\n} GdocClass;\n\n")
w("static const GdocClass gdoc_classify_want[] = {\n")
n = 0
for m in re.finditer(r'^\s*"([^"]*)":\s*\{([^}]*)\},', body, re.M):
    sfx = go_strings(m.group(2))
    assert len(sfx) <= 4
    w('    {"%s", {%s}, %d},\n'
      % (m.group(1), ", ".join('"%s"' % s.decode() for s in sfx), len(sfx)))
    n += 1
assert n > 10, "classify table"
w("};\n\n")

fn = src[src.index("func ExampleNewFromFiles("):]
w("static const char gdoc_example_src[] =\n    %s;\n\n" % c_str(go_const(fn, "src"), 4))
w("static const char gdoc_example_test[] =\n    %s;\n\n" % c_str(go_const(fn, "test"), 4))
outl = fn[fn.index("\t// Output:\n") + len("\t// Output:\n") :]
outl = outl[: outl.index("\n}")]
output = "".join(l.strip()[3:] + "\n" for l in outl.splitlines()).encode()
w("static const char gdoc_example_output[] =\n    %s;\n\n" % c_str(output, 4))

# example_internal_test.go
src = open(os.path.join(pkg, "example_internal_test.go")).read()
w("typedef struct GdocImportGroups {\n    const char *name;\n    const char *in;\n")
w("    const char *want[4];\n    int n;\n} GdocImportGroups;\n\n")
w("static const GdocImportGroups gdoc_import_groups[] = {\n")
n = 0
for m in re.finditer(r'name: "([^"]*)",\s*in: `([^`]*)`,\s*want: \[\]string\{([^}]*)\}', src):
    paths = go_strings(m.group(3))
    assert len(paths) <= 4
    w('    {"%s",\n     %s,\n     {%s},\n     %d},\n'
      % (m.group(1), c_str(m.group(2).encode(), 5),
         ", ".join('"%s"' % p.decode() for p in paths), len(paths)))
    n += 1
assert n >= 6, "import group cases"
w("};\n")
PY
