#!/bin/sh
# Regenerates tests/lzw_test_gen.h: what Go's compress/lzw writer makes of a
# set of inputs in both bit orders at every literal width the input fits in,
# for tests/lzw_test.c to match byte for byte, and what Go's reader makes of
# random bytes and of cut short streams, for the reader to match. Nothing in Go's lzw depends on
# the machine, so this runs wherever go does.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/lzw_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
goroot=$(go env GOROOT)

mkdir "$tmp/testdata"
cp "$goroot/src/compress/testdata/gettysburg.txt" "$tmp/testdata/"

cat > "$tmp/main.go" <<'GO'
package main

import (
	"bytes"
	"compress/lzw"
	"crypto/sha256"
	"embed"
	"fmt"
	"io"
	"os"
	"runtime"
	"strings"
)

//go:embed testdata
var testdata embed.FS

// The same words the C test makes with lzw_words.
func words(n int) []byte {
	vocab := strings.Fields("the quick brown fox jumped over lazy dog and a of to in " +
		"is that it was for on are as with his they at be this from I have or by " +
		"one had not but what all were when we there can an your which their said " +
		"if do will each about how up out them then she many some so these would")
	var b []byte
	x := uint64(1)
	for len(b) < n {
		x = x*6364136223846793005 + 1442695040888963407
		b = append(b, vocab[(x>>33)%uint64(len(vocab))]...)
		if x>>60 == 0 {
			b = append(b, '\n')
		} else {
			b = append(b, ' ')
		}
	}
	return b[:n]
}

// Bytes from the same generator, seeded, the top byte of each step, masked.
func noise(n int, seed uint64, mask byte) []byte {
	b := make([]byte, n)
	x := seed
	for i := range b {
		x = x*6364136223846793005 + 1442695040888963407
		b[i] = byte(x>>56) & mask
	}
	return b
}

// Decimal digits from the same generator, like e.txt and pi.txt.
func digits(n int) []byte {
	b := make([]byte, n)
	x := uint64(3)
	for i := range b {
		x = x*6364136223846793005 + 1442695040888963407
		b[i] = '0' + byte((x>>33)%10)
	}
	return b
}

// The inputs, numbered as lzw_input in the C test numbers them. The noise is
// masked to the literal width so that every width has one.
func input(id, litWidth int) []byte {
	switch id {
	case 0:
		b, err := testdata.ReadFile("testdata/gettysburg.txt")
		if err != nil {
			panic(err)
		}
		return b
	case 1:
		return words(100000)
	case 2:
		return noise(70000, 7, byte(1<<litWidth-1))
	case 3:
		return nil
	case 4:
		return []byte("TOBEORNOTTOBEORTOBEORNOT")
	case 5:
		return make([]byte, 20000)
	}
	return digits(100000)
}

func fits(b []byte, litWidth int) bool {
	for _, c := range b {
		if int(c) >= 1<<litWidth {
			return false
		}
	}
	return true
}

func main() {
	var w strings.Builder
	w.WriteString(`/* What Go's compress/lzw writer makes, ` + runtime.Version() + `. The input
 * numbers are lzw_input in tests/lzw_test.c. Generated by
 * tools/gen-lzw-tests.sh; do not edit. */

typedef struct LzwVector {
    int input;
    int order;
    int lit_width;
    long long len;
    const char *sha256;
} LzwVector;

static const LzwVector lzw_vectors[] = {
`)
	for in := 0; in < 7; in++ {
		for order := lzw.LSB; order <= lzw.MSB; order++ {
			for lw := 2; lw <= 8; lw++ {
				src := input(in, lw)
				if !fits(src, lw) {
					continue
				}
				var buf bytes.Buffer
				zw := lzw.NewWriter(&buf, order, lw)
				if _, err := zw.Write(src); err != nil {
					panic(err)
				}
				if err := zw.Close(); err != nil {
					panic(err)
				}
				got, err := io.ReadAll(lzw.NewReader(bytes.NewReader(buf.Bytes()), order, lw))
				if err != nil || !bytes.Equal(got, src) {
					panic(fmt.Sprintf("input %d order %d width %d does not read back", in, order, lw))
				}
				fmt.Fprintf(&w, "    {%d, %d, %d, %d, \"%x\"},\n", in, order, lw, buf.Len(), sha256.Sum256(buf.Bytes()))
			}
		}
	}
	w.WriteString(`};

/* What Go's reader gives for compressed bytes that are either noise(n, seed)
 * or the first n bytes of what the writer made of input words at width 8:
 * how much it decoded, its SHA-256, and the error it stopped with, which is
 * empty for a stream that ended with the end code. */
typedef struct LzwDecodeVector {
    int words; /* 0 for noise, 1 for a cut short stream of words */
    int order;
    int lit_width;
    int n;
    int seed;
    long long len;
    const char *sha256;
    const char *err;
} LzwDecodeVector;

static const LzwDecodeVector lzw_decode_vectors[] = {
`)
	decode := func(words int, order lzw.Order, lw, n, seed int, src []byte) {
		got, err := io.ReadAll(lzw.NewReader(bytes.NewReader(src), order, lw))
		msg := ""
		if err != nil {
			msg = err.Error()
		}
		fmt.Fprintf(&w, "    {%d, %d, %d, %d, %d, %d, \"%x\", %q},\n", words, order, lw, n, seed, len(got), sha256.Sum256(got), msg)
	}
	for order := lzw.LSB; order <= lzw.MSB; order++ {
		for lw := 2; lw <= 8; lw++ {
			for seed := 1; seed <= 4; seed++ {
				for _, n := range []int{1, 2, 3, 16, 5000} {
					decode(0, order, lw, n, seed, noise(n, uint64(seed), 0xff))
				}
			}
		}
		var buf bytes.Buffer
		zw := lzw.NewWriter(&buf, order, 8)
		zw.Write(words(100000))
		zw.Close()
		for _, n := range []int{0, 1, 2, 100, 4096, 20000, buf.Len() - 1} {
			decode(1, order, 8, n, 0, buf.Bytes()[:n])
		}
	}
	w.WriteString("};\n")
	os.Stdout.WriteString(w.String())
}
GO
cd "$tmp"
go mod init gen >/dev/null 2>&1
go run . > "$out"
if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
echo "wrote $out"
