#!/bin/sh
# Regenerates tests/encoding_json_test_gen.h: what Go's encoding/json does with
# the cases in its own TestUnmarshal. Like tools/gen-jsonv2-tests.sh, it lays a
# copy of v2_decode_test.go over the package with go test -overlay, with the
# loop body of TestUnmarshal swapped for a call that writes the C type for the
# case and runs it. For each case it records what Valid says about the input,
# what Unmarshal and a Decoder do with it, as an error text and a dump of the
# value, and what Marshal writes for the decoded value when decoding worked.
#
# A case is left out when its type has methods, except Number, or when C has no
# spelling for it. The reflect walking is shared with the v2 generator and
# lives in tools/gen-json-common/common.go. The generated header says how many
# cases went in and how many were left out.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/encoding_json_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

pkg=$(go env GOROOT)/src/encoding/json

awk '
/^func TestUnmarshal\(/ { fn = "u" }
/^func / && !/^func TestUnmarshal\(/ { fn = "" }
/^\tfor _, tt := range unmarshalTests \{$/ && fn == "u" {
    print; print "\t\tgenCase(tt.Where.String(), tt.in, tt.ptr, tt.useNumber, tt.disallowUnknownFields)"; print "\t\tcontinue"; fn = ""; next
}
{ print }
' "$pkg/v2_decode_test.go" > "$tmp/v2_decode_test.go"

cat > "$tmp/zz_gen_test.go" <<'GO'
//go:build goexperiment.jsonv2

package json

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"encoding/json/jsontext"
)

var (
	anyType           = reflect.TypeFor[any]()
	jsontextValueType = reflect.TypeFor[jsontext.Value]()
)

// Number is a Str in C, with methods that give it its JSON behaviour.
func knownType(t reflect.Type) (string, string, bool) {
	if t == reflect.TypeFor[Number]() {
		return "JsonNumber", "&burrow_type_JsonNumber", true
	}
	return "", "", false
}

// A Number is a Str, which the common builder already writes.
func knownValue(*builder, reflect.Value, string) bool { return false }

// The C descriptor has the Go name.
func typeName(t reflect.Type) string { return t.Name() }

// How many cases each left-out type accounts for.
var leftOut = map[string]int{}

func b01(b bool) int {
	if b {
		return 1
	}
	return 0
}

func genCase(where, in string, ptr any, useNumber, disallow bool) {
	name := filepath.Base(where)
	valid := b01(Valid([]byte(in)))
	if ptr == nil {
		fmt.Fprintf(&genCases, "    {%s, NULL, %s, 0, 0, NULL, NULL, NULL, NULL, 0, QS(\"\"), NULL, %d},\n",
			lit(name), qs(in), valid)
		genKept++
		return
	}
	t := reflect.TypeOf(ptr).Elem()
	if !supported(t, map[reflect.Type]bool{}) {
		leftOut[t.String()]++
		genSkipped++
		return
	}
	_, typ := ctype(t)

	u := reflect.New(t)
	uerr := Unmarshal([]byte(in), u.Interface())
	var ud strings.Builder
	dump(&ud, u.Elem(), map[uintptr]bool{})

	d := reflect.New(t)
	dec := NewDecoder(bytes.NewReader([]byte(in)))
	if useNumber {
		dec.UseNumber()
	}
	if disallow {
		dec.DisallowUnknownFields()
	}
	derr := dec.Decode(d.Interface())
	var dd strings.Builder
	dump(&dd, d.Elem(), map[uintptr]bool{})

	marshalled, mout, merr := 0, "", error(nil)
	if derr == nil {
		b, err := Marshal(d.Interface())
		marshalled, mout, merr = 1, string(b), err
	}
	fmt.Fprintf(&genCases, "    {%s, %s, %s, %d, %d, %s, %s, %s, %s, %d, %s, %s, %d},\n",
		lit(name), typ, qs(in), b01(useNumber), b01(disallow), errText(uerr), lit(ud.String()),
		errText(derr), lit(dd.String()), marshalled, qs(mout), errText(merr), valid)
	genKept++
}

func TestZZGen(t *testing.T) {
	var w strings.Builder
	w.WriteString(`/* What Go's encoding/json does with the cases of its own TestUnmarshal,
 * go1.27.1. Generated by tools/gen-json-tests.sh; do not edit. */

typedef struct QStr {
    const char *p;
    long long n;
} QStr;

#define QS(x) {x, (long long)sizeof(x) - 1}

typedef struct JCase {
    const char *name;
    const Type *type;
    QStr in;
    int use_number;
    int disallow;
    const char *unmarshal_err;
    const char *unmarshal_dump;
    const char *decode_err;
    const char *decode_dump;
    int marshalled;
    QStr marshal_out;
    const char *marshal_err;
    int valid;
} JCase;

`)
	fmt.Fprintf(&w, "/* %d cases, %d left out. The left-out cases use these types. They\n * have JSON methods, need time, hold a complex number or an interface other\n * than any, or have a field named like its type that is not embedded, which a\n * C descriptor cannot say yet:\n *\n", genKept, genSkipped)
	names := make([]string, 0, len(leftOut))
	for n := range leftOut {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		fmt.Fprintf(&w, " *   %s (%d)\n", n, leftOut[n])
	}
	w.WriteString(" */\n\n")
	for i := range genTypeOrder {
		fmt.Fprintf(&w, "static Type gt%d;\n", i)
	}
	w.WriteString("\n")
	w.WriteString(genTypeDefs.String())
	w.WriteString("\n")
	w.WriteString(genTypeDescs.String())
	w.WriteString("\nstatic void gen_init(void) {\n")
	w.WriteString(genTypeInit.String())
	w.WriteString("}\n\n")
	w.WriteString("static const JCase j_cases[] = {\n")
	w.WriteString(genCases.String())
	w.WriteString("};\n")
	os.Stdout.WriteString(w.String())
}
GO

printf '{"Replace":{"%s/v2_decode_test.go":"%s/v2_decode_test.go","%s/zz_gen_test.go":"%s/zz_gen_test.go","%s/zz_gen_common_test.go":"%s/tools/gen-json-common/common.go"}}' \
    "$pkg" "$tmp" "$pkg" "$tmp" "$pkg" "$root" > "$tmp/overlay.json"
GOEXPERIMENT=jsonv2 go test -overlay "$tmp/overlay.json" -run '^(TestUnmarshal|TestZZGen)$' -count=1 -v \
    encoding/json > "$tmp/out.txt" || { grep -m1 -B2 -A30 "^panic\|^fatal\|stack overflow\|cannot\|undefined" "$tmp/out.txt" >&2; exit 1; }
sed -n '/^\/\* What Go/,$p' "$tmp/out.txt" | sed '/^--- PASS/,$d' > "$out"
if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$out"
fi
echo "wrote $out"
