#!/bin/sh
# Regenerates src/xtext/bidi_tables.c, src/xtext/bidi_tables.h,
# tests/xtext_bidi_test_gen.h and tests/xtext_bidirule_test_gen.h from
# golang.org/x/text/unicode/bidi and golang.org/x/text/secure/bidirule, at the
# version Go vendors, which is the one src/vendor/modules.txt names.
#
# This works the way tools/gen-xtext-norm.sh does: the module comes from the
# module cache, and tools/gen-xtext/bidi_gen_test.go and bidirule_gen_test.go
# are laid over a writable copy of it and run as tests, so that they can read
# the unexported tables and test tables by name.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=$(go env GOROOT)
gover=$(go env GOVERSION)

ver=$(sed -n 's|^# golang.org/x/text \(v[^ ]*\)$|\1|p' "$goroot/src/vendor/modules.txt")
[ -n "$ver" ] || { echo "gen-xtext-bidi: no golang.org/x/text in modules.txt" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'chmod -R u+w "$tmp" 2>/dev/null; rm -rf "$tmp"' EXIT

dir=$(cd "$tmp" && GOFLAGS=-mod=mod go mod download -json "golang.org/x/text@$ver" |
	sed -n 's|^[[:space:]]*"Dir": "\(.*\)",$|\1|p')
[ -d "$dir" ] || { echo "gen-xtext-bidi: could not download golang.org/x/text@$ver" >&2; exit 1; }

cp -R "$dir" "$tmp/text"
chmod -R u+w "$tmp/text"
cp "$root/tools/gen-xtext/bidi_gen_test.go" "$tmp/text/unicode/bidi/zz_gen_test.go"
cp "$root/tools/gen-xtext/bidirule_gen_test.go" "$tmp/text/secure/bidirule/zz_gen_test.go"

banner="/* Derived from Go's src/vendor/golang.org/x/text/unicode/bidi/%s.
 * Go source: $gover, golang.org/x/text $ver.
 *
 * Generated by tools/gen-xtext-bidi.sh from the Go tables. Do not edit.
 *
 * Copyright 2015 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

"

bidi_banner="/* Test data for tests/xtext_bidi_test.c, from golang.org/x/text $ver's
 * unicode/bidi: what that package says about random runs of classes given to
 * its core, about a corpus of strings and about every rune, as hashes.
 *
 * Generated by tools/gen-xtext-bidi.sh. Do not edit.
 *
 * Copyright 2015 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */
"

bidirule_banner="/* Test data for tests/xtext_bidirule_test.c, from golang.org/x/text $ver's
 * secure/bidirule tests, plus what that package says about a corpus of labels
 * and about every rune, as hashes.
 *
 * Generated by tools/gen-xtext-bidi.sh. Do not edit.
 *
 * Copyright 2016 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */
"

mkdir -p "$root/src/xtext"
(cd "$tmp/text/unicode/bidi" &&
	BURROW_XTEXT_SRC="$root/src/xtext" \
	BURROW_XTEXT_TESTS="$root/tests" \
	BURROW_XTEXT_BANNER="$banner" \
	BURROW_XTEXT_TEST_BANNER="$bidi_banner" \
	GOFLAGS=-mod=mod go test -count=1 -run '^TestZZGen$' .)
(cd "$tmp/text/secure/bidirule" &&
	BURROW_XTEXT_TESTS="$root/tests" \
	BURROW_XTEXT_TEST_BANNER="$bidirule_banner" \
	GOFLAGS=-mod=mod go test -count=1 -run '^TestZZGen$' .)
