#!/bin/sh
# Regenerates src/xnet/hpack_tables.c from golang.org/x/net/http2/hpack, at
# the version Go vendors.
#
# The Huffman codes and the static table are Go's, copied. Go builds the
# decoding trie from the codes the first time it decodes, behind a sync.Once.
# Here it is built by this script and checked in as a constant, so there is no
# global to set up and nothing to lock. tests/xnet_hpack_test.c builds the trie
# again from the codes, the way huffman.go does, and checks it is this one.
#
# GOROOT says which Go to read, and defaults to what go env says.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=${GOROOT:-$(go env GOROOT)}
gover=$(head -n 1 "$goroot/VERSION")
src="$goroot/src/vendor/golang.org/x/net/http2/hpack"
netver=$(sed -n 's|^# golang.org/x/net \(v[^ ]*\)$|\1|p' "$goroot/src/vendor/modules.txt")
[ -n "$netver" ] || { echo "gen-xnet-hpack: no golang.org/x/net in modules.txt" >&2; exit 1; }

python3 - "$src" "$gover" "$netver" > "$root/src/xnet/hpack_tables.c" <<'EOF'
import re
import sys

src, gover, netver = sys.argv[1:4]
tables = open(src + "/tables.go").read()
static = open(src + "/static_table.go").read()


def array(name):
    body = tables.split("var " + name)[1].split("{", 1)[1].split("}", 1)[0]
    return [int(x, 0) for x in re.findall(r"\b(?:0x[0-9a-f]+|\d+)\b", body)]


codes = array("huffmanCodes")
lens = array("huffmanCodeLen")
assert len(codes) == 256 and len(lens) == 256

# huffman.go's buildRootHuffmanNode, with the nodes numbered as they are made.
nodes = [[0] * 256]
for sym in range(256):
    code, n = codes[sym], lens[sym]
    cur = 0
    while n > 8:
        n -= 8
        i = (code >> n) & 0xFF
        if nodes[cur][i] == 0:
            nodes.append([0] * 256)
            nodes[cur][i] = 0x8000 | (len(nodes) - 1)
        cur = nodes[cur][i] & 0xFF
    shift = 8 - n
    start = (code << shift) & 0xFF
    for i in range(start, start + (1 << shift)):
        nodes[cur][i] = n << 8 | sym

ents = re.findall(r'\{Name: "([^"]*)", Value: "([^"]*)", Sensitive: false\}', static)
assert len(ents) == 61
names = {}
for i, (name, _) in enumerate(ents, 1):
    first, _ = names.get(name, (i, i))
    names[name] = (first, i)

out = []
w = out.append
w("/* Derived from Go's src/vendor/golang.org/x/net/http2/hpack/tables.go and")
w(" * static_table.go.")
w(" * Go source: %s, golang.org/x/net %s." % (gover, netver))
w(" *")
w(" * Generated by tools/gen-xnet-hpack.sh from the Go tables. Do not edit.")
w(" *")
w(" * Copyright 2014 The Go Authors. All rights reserved.")
w(" * Copyright 2026 The burrow Authors. All rights reserved.")
w(" * Use of this source code is governed by a BSD-style licence that can be found")
w(" * in the LICENSE file. */")
w("")
w('#include "hpack.h"')
w("")
w("#include <stdint.h>")
w("")
w("const uint32_t burrow__hpack_huffman_codes[256] = {")
for i in range(0, 256, 6):
    w("    " + " ".join("0x%x," % c for c in codes[i:i + 6]))
w("};")
w("")
w("const uint8_t burrow__hpack_huffman_code_len[256] = {")
for i in range(0, 256, 16):
    w("    " + " ".join("%d," % n for n in lens[i:i + 16]))
w("};")
w("")
w("const uint16_t burrow__hpack_trie[BURROW__HPACK_TRIE_NODES][256] = {")
assert len(nodes) == 15
for node in nodes:
    w("    {")
    for i in range(0, 256, 10):
        w("        " + " ".join("0x%04x," % e for e in node[i:i + 10]))
    w("    },")
w("};")
w("")
w("const HpackHeaderField burrow__hpack_static[BURROW__HPACK_STATIC_LEN] = {")
for name, value in ents:
    w('    {BURROW_S_INIT("%s"), BURROW_S_INIT("%s"), false},' % (name, value))
w("};")
w("")
w("const burrow__HpackStaticName burrow__hpack_static_names[BURROW__HPACK_STATIC_NAMES] = {")
for name in sorted(names, key=lambda s: s.encode()):
    first, last = names[name]
    w('    {BURROW_S_INIT("%s"), %d, %d},' % (name, first, last))
w("};")
print("\n".join(out))
EOF
