#!/bin/sh
# Regenerates tests/mime_test_gen.h: what Go's mime package makes of Go's own
# test tables for ParseMediaType, FormatMediaType, WordEncoder.Encode,
# WordDecoder.Decode and WordDecoder.DecodeHeader, and a digest of what it makes
# of random inputs built from pieces that the C test builds the same way. The
# tables are unexported in Go, so this copies the package next to a test file
# that prints them. Nothing here depends on the machine, so it runs wherever go
# does.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/mime_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

src=$(go env GOROOT)/src/mime
cp "$src"/encodedword.go "$src"/grammar.go "$src"/mediatype.go "$src"/type.go \
    "$src"/type_unix.go "$src"/encodedword_test.go "$src"/mediatype_test.go "$tmp"/
# type_unix.go wants these from the tests it came with.
cat > "$tmp/stub_test.go" <<'GO'
package mime

func init() { testInitMime = func() {} }
GO

cat > "$tmp/gen_test.go" <<'GO'
package mime

import (
	"fmt"
	"os"
	"runtime"
	"slices"
	"strings"
	"testing"
)

// C string literal of s, with octal escapes so nothing runs into the next
// character.
func lit(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c == '?':
			b.WriteString(`\077`)
		case c >= ' ' && c <= '~':
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func qs(s string) string { return "QS(" + lit(s) + ")" }

func errText(err error) string {
	if err == nil {
		return ""
	}
	return err.Error()
}

// FNV-1a, 64 bit, over each part with its length in front.
type fnv uint64

func (h *fnv) addLen(n int) {
	for i := 0; i < 8; i++ {
		*h ^= fnv(byte(uint64(n) >> (8 * i)))
		*h *= 1099511628211
	}
}

func (h *fnv) add(s string) {
	h.addLen(len(s))
	for i := 0; i < len(s); i++ {
		*h ^= fnv(s[i])
		*h *= 1099511628211
	}
}

// The C test's rnd: a 64 bit LCG, the top 31 bits of each step.
type rnd uint64

func (x *rnd) next() uint64 {
	*x = *x*6364136223846793005 + 1442695040888963407
	return uint64(*x) >> 33
}

// Up to max pieces, picked with the LCG from seed.
func build(seed uint64, pieces []string, max uint64) string {
	x := rnd(seed)
	n := x.next() % (max + 1)
	var b strings.Builder
	for i := uint64(0); i < n; i++ {
		b.WriteString(pieces[x.next()%uint64(len(pieces))])
	}
	return b.String()
}

func sortedParams(p map[string]string) []string {
	var kv []string
	for _, k := range slices.Sorted(func(yield func(string) bool) {
		for k := range p {
			if !yield(k) {
				return
			}
		}
	}) {
		kv = append(kv, k, p[k])
	}
	return kv
}

func params(kv []string) string {
	if len(kv) == 0 {
		return "{QS(\"\")}"
	}
	var parts []string
	for _, s := range kv {
		parts = append(parts, qs(s))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

var mtPieces = []string{
	"text", "/", "html", "plain", ";", " ", "\t", "=", "\"", "*", "0", "1", "2", "'", "%",
	"2A", "E2", "utf-8", "UTF-8", "us-ascii", "\\", "a", "B", "title", "*0", "*1*", "''",
	"charset", "name", "\r\n", "\xc3\x84", "\xff", "\xe2\x84\xaa", "(", "@", ",", "x-y",
}

var hdrPieces = []string{
	"=?", "?=", "?", "UTF-8", "utf-8", "iso-8859-1", "US-ASCII", "koi8-r", "Q", "q", "B",
	"b", "x", "=C3", "=A9", "=E9", "=4", "=g0", "_", " ", "\r\n\t", "\v", "QW5k", "cw==",
	"Q2Fmw6k=", "a", "=", "\x80", "\xc3\xa9", "!", "\x01",
}

var encPieces = []string{
	"a", "b", " ", "=", "?", "_", "\t", "\n", "\x7f", "\x80", "\xff", "\xc3\xa9",
	"\xe6\xbc\xa2", "\xf0\x9f\x98\x80", "hello world ", "\xe2\x82\xac",
}

var charsets = []string{"utf-8", "UTF-8", "iso-8859-1", "Utf-8", "US-ASCII"}

const (
	mtCount  = 20000
	hdrCount = 20000
	encCount = 5000
)

func TestGen(t *testing.T) {
	o, err := os.Create(os.Getenv("MIME_GEN_OUT"))
	if err != nil {
		t.Fatal(err)
	}
	defer o.Close()
	p := func(format string, a ...any) { fmt.Fprintf(o, format, a...) }

	p("/* What Go's mime package makes, %s. Generated by tools/gen-mime-tests.sh;\n", runtime.Version())
	p(" * do not edit. */\n\n")
	p("typedef struct QStr {\n    const char *p;\n    long long n;\n} QStr;\n\n")
	p("#define QS(x) {x, (long long)sizeof(x) - 1}\n\n")

	// ParseMediaType, on Go's good table and its bad one.
	p("typedef struct MimeParseCase {\n    QStr in;\n    QStr mediatype;\n    const char *err;\n")
	p("    int nparams; /* pairs in params, sorted by name */\n    QStr params[12];\n} MimeParseCase;\n\n")
	p("static const MimeParseCase mime_parse_cases[] = {\n")
	var ins []string
	for _, tc := range parseMediaTypeTests {
		ins = append(ins, tc.in)
	}
	for _, tc := range badMediaTypeTests {
		ins = append(ins, tc.in)
	}
	ins = append(ins, "", ";", "text/html;", "text/html; ;", "TEXT/\xe2\x84\xaa", "a/b; x*=utf-8''%", "a/b; x*0*=us-ascii'en'a%20b; x*1=c; x*2*=%zz")
	for _, in := range ins {
		mt, ps, err := ParseMediaType(in)
		kv := sortedParams(ps)
		if len(kv) > 24 {
			t.Fatalf("too many params in %q", in)
		}
		p("    {%s,\n     %s,\n     %s,\n     %d,\n     %s},\n", qs(in), qs(mt), lit(errText(err)), len(kv)/2, params(kv))
	}
	p("};\n\n")

	// FormatMediaType on Go's table.
	p("typedef struct MimeFormatCase {\n    QStr typ;\n    int nparams;\n    QStr params[8];\n    QStr want;\n} MimeFormatCase;\n\n")
	p("static const MimeFormatCase mime_format_cases[] = {\n")
	for _, tc := range formatTests {
		kv := sortedParams(tc.params)
		p("    {%s, %d, %s,\n     %s},\n", qs(tc.typ), len(kv)/2, params(kv), qs(FormatMediaType(tc.typ, tc.params)))
	}
	p("};\n\n")

	// Encode, on Go's two tables.
	type encCase struct {
		enc          WordEncoder
		charset, src string
	}
	encs := []encCase{
		{QEncoding, "utf-8", "François-Jérôme"}, {BEncoding, "utf-8", "Café"},
		{QEncoding, "iso-8859-1", "La Seleção"}, {QEncoding, "utf-8", ""},
		{QEncoding, "utf-8", "A"}, {QEncoding, "iso-8859-1", "a"},
		{QEncoding, "utf-8", "123 456"},
		{QEncoding, "utf-8", "\t !\"#$%&'()*+,-./ :;<>?@[\\]^_`{|}~"},
		{QEncoding, "utf-8", strings.Repeat("é", 10)}, {QEncoding, "utf-8", strings.Repeat("é", 11)},
		{QEncoding, "iso-8859-1", strings.Repeat("\xe9", 22)},
		{QEncoding, "utf-8", strings.Repeat("\x80", 22)},
		{BEncoding, "iso-8859-1", strings.Repeat("\xe9", 45)},
		{BEncoding, "utf-8", strings.Repeat("\x80", 48)},
		{QEncoding, "utf-8", strings.Repeat("à", 30)}, {QEncoding, "utf-8", strings.Repeat("é", 60)},
		{BEncoding, "utf-8", strings.Repeat("ï", 25)}, {BEncoding, "utf-8", strings.Repeat("ô", 37)},
		{BEncoding, "utf-8", strings.Repeat("\x80", 50)},
		{QEncoding, "utf-8", "{$firstname} Bienvendio a Apostolica, aquà inicia el camino de tu"},
	}
	p("typedef struct MimeEncodeCase {\n    char enc;\n    QStr charset;\n    QStr src;\n    QStr want;\n} MimeEncodeCase;\n\n")
	p("static const MimeEncodeCase mime_encode_cases[] = {\n")
	for _, tc := range encs {
		p("    {'%c', %s, %s,\n     %s},\n", tc.enc, qs(tc.charset), qs(tc.src), qs(tc.enc.Encode(tc.charset, tc.src)))
	}
	p("};\n\n")

	// Decode and DecodeHeader on Go's tables.
	words := []string{
		"=?UTF-8?Q?=C2=A1Hola,_se=C3=B1or!?=", "=?UTF-8?Q?Fran=C3=A7ois-J=C3=A9r=C3=B4me?=",
		"=?UTF-8?q?ascii?=", "=?utf-8?B?QW5kcsOp?=", "=?ISO-8859-1?Q?Rapha=EBl_Dupont?=",
		"=?utf-8?b?IkFudG9uaW8gSm9zw6kiIDxqb3NlQGV4YW1wbGUub3JnPg==?=", "=?UTF-8?A?Test?=",
		"=?UTF-8?Q?A=B?=", "=?UTF-8?Q?=A?=", "=?UTF-8?A?A?=", "=????=", "=?UTF-8???=",
		"=?UTF-8?Q??=", "=?utf-8?b?Q2Fmw6k=?=", "=?ISO-8859-1?Q?caf=E9?=",
		"=?US-ASCII?Q?foo_bar?=", "=?US-ASCII?Q?caf=E9?=", "=?utf-8?Q?=?=", "=?utf-8?Q?=A?=",
		"=?utf-8?b?Q2Fmw6k?=", "=?utf-8?q?=zz?=", "=?utf-8?q?a\x01?=", "=?koi8-r?q?a?=",
	}
	headers := []string{
		"Jean", "=?", "=?UTF-8?", "=?UTF-8?=", "=?UTF-8?Q", "=?UTF-8?Q?", "=?UTF-8?Q?=",
		"=?UTF-8?Q?A", "=?UTF-8?Q?A?", "=?ISO-8859-1?Q?a?=", "=?ISO-8859-1?Q?a?= b",
		"=?ISO-8859-1?Q?a?= =?ISO-8859-1?Q?b?=", "=?ISO-8859-1?Q?a?=  =?ISO-8859-1?Q?b?=",
		"=?ISO-8859-1?Q?a?= \r\n\t =?ISO-8859-1?Q?b?=", "=?ISO-8859-1?Q?a_b?=",
		"=?UTF-8?b?garbage?= =?UTF-8?b?QW5kcsOp?= =?UTF-8?b?garbage?=",
		"=?UTF-8?b?QW5kcsOp", "=?UTF-8?x?y?=?UTF-8?x?y=?", "a =?utf-8?q?x?= \v =?utf-8?q?y?= b",
		"=?charset?Q?foo?=",
	}
	headers = append(words, headers...)
	p("typedef struct MimeDecodeCase {\n    QStr in;\n    QStr want;\n    const char *err;\n} MimeDecodeCase;\n\n")
	dec := new(WordDecoder)
	p("static const MimeDecodeCase mime_decode_cases[] = {\n")
	for _, w := range words {
		s, err := dec.Decode(w)
		p("    {%s, %s, %s},\n", qs(w), qs(s), lit(errText(err)))
	}
	p("};\n\n")
	p("static const MimeDecodeCase mime_decode_header_cases[] = {\n")
	for _, h := range headers {
		s, err := dec.DecodeHeader(h)
		p("    {%s, %s, %s},\n", qs(h), qs(s), lit(errText(err)))
	}
	p("};\n\n")

	// Random inputs, as digests.
	pieces := func(name string, ps []string) {
		p("static const QStr %s[] = {\n", name)
		for _, s := range ps {
			p("    %s,\n", qs(s))
		}
		p("};\n\n")
	}
	pieces("mime_mt_pieces", mtPieces)
	pieces("mime_hdr_pieces", hdrPieces)
	pieces("mime_enc_pieces", encPieces)
	pieces("mime_charsets", charsets)

	var h fnv = 14695981039346656037
	for i := uint64(1); i <= mtCount; i++ {
		in := build(i, mtPieces, 14)
		mt, ps, err := ParseMediaType(in)
		h.add(mt)
		h.add(errText(err))
		kv := sortedParams(ps)
		h.addLen(len(kv))
		for _, s := range kv {
			h.add(s)
		}
		// Whatever parsed goes back through FormatMediaType.
		if err == nil {
			h.add(FormatMediaType(mt, ps))
		}
	}
	p("#define MIME_MT_COUNT %d\n#define MIME_MT_FNV 0x%016xULL\n\n", mtCount, uint64(h))

	h = 14695981039346656037
	for i := uint64(1); i <= hdrCount; i++ {
		in := build(i, hdrPieces, 12)
		s, err := dec.DecodeHeader(in)
		h.add(s)
		h.add(errText(err))
		s, err = dec.Decode(in)
		h.add(s)
		h.add(errText(err))
	}
	p("#define MIME_HDR_COUNT %d\n#define MIME_HDR_FNV 0x%016xULL\n\n", hdrCount, uint64(h))

	h = 14695981039346656037
	for i := uint64(1); i <= encCount; i++ {
		in := build(i, encPieces, 40)
		x := rnd(i * 7919)
		e := BEncoding
		if x.next()%2 == 1 {
			e = QEncoding
		}
		cs := charsets[x.next()%uint64(len(charsets))]
		s := e.Encode(cs, in)
		h.add(s)
		// And back again, for the charsets the decoder knows.
		d, err := dec.DecodeHeader(s)
		h.add(d)
		h.add(errText(err))
	}
	p("#define MIME_ENC_COUNT %d\n#define MIME_ENC_FNV 0x%016xULL\n", encCount, uint64(h))
}
GO

(cd "$tmp" && go mod init mimegen >/dev/null 2>&1 &&
    MIME_GEN_OUT="$out.tmp" go test -count=1 -run '^TestGen$' . >/dev/null)
mv "$out.tmp" "$out"
if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$out"
fi
