#!/bin/sh
# Regenerates tests/zlib_test_gen.h: what Go's compress/zlib writer makes of a
# set of inputs at every level, with no dictionary, an empty one and a short
# one, for tests/zlib_test.c to match byte for byte. Each vector also says
# whether Go's reader gets the input back from it, which for a few it does not:
# see dict_end in src/compress/deflate.c.
#
# The DEFLATE inside is compress/flate's, whose output can differ between
# amd64 and arm64 (tools/gen-flate-writer-tests.sh says why), so on another
# machine the program is built for linux/amd64 and run on GEN_SSH, an amd64
# host that can be reached with ssh.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/zlib_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
goroot=$(go env GOROOT)

mkdir "$tmp/testdata"
cp "$goroot/src/compress/testdata/gettysburg.txt" "$tmp/testdata/"

cat > "$tmp/main.go" <<'GO'
package main

import (
	"bytes"
	"compress/zlib"
	"crypto/sha256"
	"embed"
	"fmt"
	"io"
	"os"
	"runtime"
	"strings"
)

//go:embed testdata
var testdata embed.FS

// The same words the C test makes with flate_words.
func words(n int) []byte {
	vocab := strings.Fields("the quick brown fox jumped over lazy dog and a of to in " +
		"is that it was for on are as with his they at be this from I have or by " +
		"one had not but what all were when we there can an your which their said " +
		"if do will each about how up out them then she many some so these would")
	var b []byte
	x := uint64(1)
	for len(b) < n {
		x = x*6364136223846793005 + 1442695040888963407
		b = append(b, vocab[(x>>33)%uint64(len(vocab))]...)
		if x>>60 == 0 {
			b = append(b, '\n')
		} else {
			b = append(b, ' ')
		}
	}
	return b[:n]
}

// Bytes from the same generator, seeded, the top byte of each step.
func noise(n int, seed uint64, mask byte) []byte {
	b := make([]byte, n)
	x := seed
	for i := range b {
		x = x*6364136223846793005 + 1442695040888963407
		b[i] = byte(x>>56) & mask
	}
	return b
}

// The inputs, numbered as zlib_input in the C test numbers them.
func input(id int) []byte {
	switch id {
	case 0:
		b, err := testdata.ReadFile("testdata/gettysburg.txt")
		if err != nil {
			panic(err)
		}
		return b
	case 1:
		return words(34000)
	case 2:
		return noise(70000, 7, 0xff)
	case 3:
		return nil
	}
	return []byte("hello, world\n")
}

// The dictionaries, numbered as zlib_dict in the C test numbers them.
func dict(id int) []byte {
	switch id {
	case 0:
		return nil
	case 1:
		return []byte{}
	}
	return []byte("0123456789.")
}

func main() {
	var w strings.Builder
	w.WriteString(`/* What Go's compress/zlib writer makes, ` + runtime.Version() + ` on ` + runtime.GOARCH + `. The
 * input and dictionary numbers are zlib_input and zlib_dict in
 * tests/zlib_test.c. Generated by tools/gen-zlib-tests.sh; do not edit. */

typedef struct ZlibVector {
    int input;
    int level;
    int dict;
    long long len;
    const char *sha256;
    bool go_bug; /* Go's output does not read back */
} ZlibVector;

static const ZlibVector zlib_vectors[] = {
`)
	for in := 0; in < 5; in++ {
		for level := -2; level <= 9; level++ {
			for d := 0; d < 3; d++ {
				var buf bytes.Buffer
				zw, err := zlib.NewWriterLevelDict(&buf, level, dict(d))
				if err != nil {
					panic(err)
				}
				if _, err := zw.Write(input(in)); err != nil {
					panic(err)
				}
				if err := zw.Close(); err != nil {
					panic(err)
				}
				zr, err := zlib.NewReaderDict(bytes.NewReader(buf.Bytes()), dict(d))
				ok := err == nil
				if ok {
					got, err := io.ReadAll(zr)
					ok = err == nil && bytes.Equal(got, input(in))
				}
				fmt.Fprintf(&w, "    {%d, %d, %d, %d, \"%x\", %t},\n", in, level, d, buf.Len(), sha256.Sum256(buf.Bytes()), !ok)
			}
		}
	}
	w.WriteString("};\n")
	os.Stdout.WriteString(w.String())
}
GO
cd "$tmp"
go mod init gen >/dev/null 2>&1
if [ "$(go env GOARCH)" = amd64 ]; then
	go run . > "$out"
else
	: "${GEN_SSH:?set GEN_SSH to an amd64 host to run the generator on}"
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o gen .
	scp -q gen "$GEN_SSH:/tmp/burrow-zlib-gen"
	ssh "$GEN_SSH" '/tmp/burrow-zlib-gen; rm -f /tmp/burrow-zlib-gen' > "$out"
fi
if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
echo "wrote $out"
