#!/bin/sh
# Regenerates tests/go_doc_comment_test_gen.h for the go/doc/comment tests. It
# holds what Go's own tests read from disk or work out at run time:
#
#   - every testdata/*.txt archive of src/go/doc/comment, for TestTestdata,
#     taken apart the way internal/txtar does it, with the Printer settings of
#     its JSON header as fields, and with the test's stripDollars and its
#     trimming of the wanted output already done;
#   - the standard library's packages with a one element import path, for
#     TestStd, which runs go list std. They are worked out here from the
#     directories under src, and the script stops if that does not give
#     std.go's stdPkgs, so a Go that changes the rules shows up here first.
#
# GOROOT says which Go to read, and defaults to what go env says.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=${GOROOT:-$(go env GOROOT)}
out="$root/tests/go_doc_comment_test_gen.h"

python3 - "$goroot" > "$out" <<'EOF'
import json
import os
import re
import sys

goroot = sys.argv[1]
src = os.path.join(goroot, "src")
pkg = os.path.join(src, "go", "doc", "comment")
gover = open(os.path.join(goroot, "VERSION")).readline().strip()

# MSVC will not take a string literal over 64K, and nothing here comes near.
LIMIT = 30000

# The libc calls tools/check-banned.sh looks for. The first letter of a name
# like that goes out as an octal escape so the check does not take the text
# for a call.
BANNED = re.compile(
    rb"(?<![A-Za-z0-9_])(strcpy|strcat|sprintf|vsprintf|gets|strtok|strncpy|"
    rb"strncat|alloca|atoi|atol|atof)[ \t]*\("
)


def lit(b):
    """b as C string literals, one line of the text to each."""
    assert len(b) < LIMIT
    lines, cur = [], ""
    hide = {m.start() for m in BANNED.finditer(b)}
    for i, c in enumerate(b):
        if i in hide:
            s = "\\%03o" % c
        elif c == 10:
            s = "\\n"
        elif c == 9:
            s = "\\t"
        elif c == 34:
            s = '\\"'
        elif c == 92:
            s = "\\\\"
        elif c == 63 and i + 1 < len(b) and b[i + 1] == 63:
            s = "\\?"
        elif 32 <= c < 127:
            s = chr(c)
        else:
            s = "\\%03o" % c
        cur += s
        if c == 10 or len(cur) >= 70:
            lines.append('"' + cur + '"')
            cur = ""
    if cur or not lines:
        lines.append('"' + cur + '"')
    return lines


def piece(b, indent):
    return "GDT_P(" + ("\n" + " " * (indent + 6)).join(lit(b)) + ")"


# internal/txtar.
def fix_nl(data):
    if len(data) == 0 or data.endswith(b"\n"):
        return data
    return data + b"\n"


def is_marker(data):
    if not data.startswith(b"-- "):
        return None, None
    after = None
    i = data.find(b"\n")
    if i >= 0:
        data, after = data[:i], data[i + 1 :]
    if not (data.endswith(b" --") and len(data) >= 6):
        return None, None
    return data[3:-3].decode().strip(), after


def find_file_marker(data):
    i = 0
    while True:
        name, after = is_marker(data[i:])
        if name:
            return data[:i], name, after
        j = data[i:].find(b"\n-- ")
        if j < 0:
            return fix_nl(data), None, None
        i += j + 1


def txtar(data):
    comment, name, data = find_file_marker(data)
    files = []
    while name:
        body, nxt, data = find_file_marker(data)
        files.append((name, body))
        name = nxt
    return comment, files


def strip_dollars(b):
    return b.replace(b"$\n", b"\n")


# The fields of Printer a JSON header can set, as encoding/json matches them.
FIELDS = {
    "headinglevel": "heading_level",
    "doclinkbaseurl": "doc_link_base_url",
    "textprefix": "text_prefix",
    "textcodeprefix": "text_code_prefix",
    "textwidth": "text_width",
}

w = sys.stdout.write
w("/* What Go's go/doc/comment tests read, from src/go/doc/comment of %s.\n" % gover)
w(" * Generated by tools/gen-go-doc-comment-tests.sh; do not edit. */\n\n")
w("typedef struct GdtPiece {\n    const char *p;\n    long long n;\n} GdtPiece;\n\n")
w("#define GDT_P(x) {x, (long long)sizeof(x) - 1}\n\n")
w("typedef struct GdtOut {\n    const char *name;\n    GdtPiece want;\n} GdtOut;\n\n")
w("typedef struct GdtCase {\n    const char *name;\n    long long heading_level;\n")
w("    GdtPiece doc_link_base_url;\n    GdtPiece text_prefix;\n")
w("    GdtPiece text_code_prefix;\n    long long text_width;\n    GdtPiece input;\n")
w("    const GdtOut *outs;\n    int nouts;\n} GdtCase;\n\n")

tdir = os.path.join(pkg, "testdata")
names = sorted(f for f in os.listdir(tdir) if f.endswith(".txt"))
assert names, "no testdata"
cases = []
for k, name in enumerate(names):
    comment, files = txtar(open(os.path.join(tdir, name), "rb").read())
    cfg = {}
    if comment:
        for key, val in json.loads(comment).items():
            cfg[FIELDS[key.lower()]] = val
    assert files and files[0][0] == "input", name
    ident = "gdt_outs_%d" % k
    w("static const GdtOut %s[] = {\n" % ident)
    for fname, data in files[1:]:
        assert fname in ("dump", "gofmt", "html", "markdown", "text"), (name, fname)
        want = strip_dollars(data)
        while len(want) >= 2 and want.endswith(b"\n\n"):
            want = want[:-1]
        w('    {"%s", %s},\n' % (fname, piece(want, 4 + len(fname) + 5)))
    w("};\n\n")
    cases.append((name, cfg, strip_dollars(files[0][1]), ident))

w("static const GdtCase gdt_cases[] = {\n")
for name, cfg, inp, ident in cases:
    w('    {"%s",\n' % name)
    w("     %d,\n" % cfg.get("heading_level", 0))
    for f in ("doc_link_base_url", "text_prefix", "text_code_prefix"):
        w("     %s,\n" % piece(cfg.get(f, "").encode(), 5))
    w("     %d,\n" % cfg.get("text_width", 0))
    w("     %s,\n" % piece(inp, 5))
    w("     %s,\n     (int)(sizeof(%s) / sizeof(%s[0]))},\n" % (ident, ident, ident))
w("};\n\n")


# The single element packages go list std gives with GOEXPERIMENT=none: the
# directories right under src with a .go file that is not a test, leaving out
# builtin, which go list leaves out too, and the ones every file of which
# needs a GOEXPERIMENT.
def needs_experiment(path):
    for line in open(path, encoding="utf-8"):
        if line.startswith("//go:build "):
            return "goexperiment." in line and "!goexperiment." not in line
        if line.startswith("package "):
            return False
    return False


std = []
for d in sorted(os.listdir(src)):
    full = os.path.join(src, d)
    if not os.path.isdir(full) or d in ("builtin", "cmd", "testdata", "vendor"):
        continue
    gos = [
        f
        for f in os.listdir(full)
        if f.endswith(".go") and not f.endswith("_test.go")
    ]
    if gos and not all(needs_experiment(os.path.join(full, f)) for f in gos):
        std.append(d)

std_go = open(os.path.join(pkg, "std.go")).read()
start = std_go.index("var stdPkgs = []string{")
body = std_go[start : std_go.index("\n}\n", start)]
want = re.findall(r'"([^"]+)"', body)
assert std == want, (std, want)

w("static const char *const gdt_std[] = {\n")
for p in std:
    w('    "%s",\n' % p)
w("};\n")
EOF

if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
