#!/bin/sh
# Regenerates tests/syntax_test_gen.h: every pattern in Go's regexp/syntax
# tests, with the flags those tests parse it with, plus a few thousand random
# patterns under random flags, and what Go makes of each one: the parse error,
# or the tree as parse_test.go dumps it, the String of the tree, whether that
# String parses back to an equal tree, the simplified tree's String, the
# program compiled from it with its prefix and start condition, and the
# capture names. tests/syntax_test.c does the same with burrow and has to get
# the same text. Anything over 1 KB is kept as its FNV-1a hash.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/syntax_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
goroot=$(go env GOROOT)

# Build inside a copy of the package, so the generator can use dump from
# parse_test.go and the test tables as they are.
mkdir "$tmp/syntax"
cp "$goroot/src/regexp/syntax/"*.go "$tmp/syntax/"
rm -f "$tmp/syntax/example_test.go"
printf 'module syntax\n\ngo 1.26\n' > "$tmp/syntax/go.mod"

cat > "$tmp/syntax/gen_test.go" <<'GO'
package syntax

import (
	"fmt"
	"hash/fnv"
	"math/rand/v2"
	"os"
	"strings"
	"testing"
)

type genCase struct {
	pat   string
	flags Flags
}

// cstr writes s as a C string literal, with everything outside printable
// ASCII, and the characters that mean something in one, as octal.
func cstr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c < 0x20 || c >= 0x7f || c == '"' || c == '\\' || c == '?' {
			fmt.Fprintf(&b, "\\%03o", c)
		} else {
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// text is a SynText: the string itself, or its hash when it is long.
func text(s string) string {
	if len(s) > 1024 {
		h := fnv.New64a()
		h.Write([]byte(s))
		return fmt.Sprintf("{NULL, %d, 0x%016xULL}", len(s), h.Sum64())
	}
	return fmt.Sprintf("{%s, %d, 0}", cstr(s), len(s))
}

var genTokens = []string{
	"a", "b", "c", "A", "k", "K", "s", "S", "ſ", "K", "x", "0", "9", "_",
	"é", "☺", "\U0001f600", "-", "]", "{", "}", ",", ":", "<", ">", " ", "\n",
	".", "^", "$", "|", "|", "(", "(", ")", ")", "(?:", "(?i)", "(?i:", "(?-i:", "(?s)",
	"(?m)", "(?U)", "(?i-s:", "(?P<n>", "(?<m>", "(?P<x1>", "(?P=n)", "(?z)", "(?",
	"*", "+", "?", "*?", "+?", "??", "**", "{2}", "{0}", "{1}", "{1,3}", "{2,}", "{0,1}",
	"{,3}", "{3,2}", "{1001}", "{2,5}?",
	"[a-c]", "[^a]", "[abc]", "[a-zA-Z0-9_]", "[[:alpha:]]", "[[:^space:]]", "[[:foo:]]",
	"[\\d-z]", "[a-]", "[]a]", "[^\\n]", "[\\x00-\\x{10FFFF}]", "[^\\x00-\\x{10FFFF}]",
	"[k-l]", "[Kk]", "[Aa]", "[b-a]", "[", "[a", "[^",
	"\\d", "\\D", "\\w", "\\W", "\\s", "\\S", "\\pL", "\\pN", "\\PN", "\\p{Greek}",
	"\\p{^Greek}", "\\P{Lu}", "\\p{Any}", "\\p{Ascii}", "\\p{Assigned}", "\\p{Letter}",
	"\\p{greek}", "\\p{Foo}", "\\p{", "\\b", "\\B", "\\A", "\\z", "\\Z", "\\C", "\\Q.*\\E",
	"\\Qab", "\\x41", "\\x{263a}", "\\x{110000}", "\\xZ", "\\141", "\\0", "\\8", "\\1",
	"\\a", "\\f", "\\t", "\\v", "\\.", "\\*", "\\", "\xff", "\xc3",
}

var genFlags = []Flags{
	Perl, Perl, Perl, POSIX, Perl | FoldCase, MatchNL | PerlX | UnicodeGroups,
	Literal, Perl &^ OneLine, MatchNL | Perl &^ OneLine, FoldCase, MatchNL,
	Perl | NonGreedy, Perl | DotNL, ClassNL | PerlX, OneLine, WasDollar | Perl,
}

func TestGen(t *testing.T) {
	path := os.Getenv("SYNGEN_OUT")
	if path == "" {
		t.Skip("SYNGEN_OUT not set")
	}
	var cases []genCase
	seen := map[genCase]bool{}
	add := func(p string, f Flags) {
		c := genCase{p, f}
		if !seen[c] && len(p) <= 2000 {
			seen[c] = true
			cases = append(cases, c)
		}
	}
	for _, tt := range parseTests {
		add(tt.Regexp, testFlags)
	}
	for _, tt := range foldcaseTests {
		add(tt.Regexp, FoldCase)
	}
	for _, tt := range literalTests {
		add(tt.Regexp, Literal)
	}
	for _, tt := range matchnlTests {
		add(tt.Regexp, MatchNL)
	}
	for _, tt := range nomatchnlTests {
		add(tt.Regexp, 0)
	}
	for _, list := range [][]string{invalidRegexps, onlyPerl, onlyPOSIX} {
		for _, p := range list {
			add(p, Perl)
			add(p, POSIX)
		}
	}
	for _, tt := range stringTests {
		add(tt.re, Perl)
	}
	for _, tt := range simplifyTests {
		add(tt.Regexp, MatchNL|Perl&^OneLine)
	}
	for _, tt := range compileTests {
		add(tt.Regexp, Perl)
	}
	r := rand.New(rand.NewPCG(1, 2))
	for len(cases) < 4000 {
		n := 1 + r.IntN(10)
		var b strings.Builder
		for i := 0; i < n; i++ {
			b.WriteString(genTokens[r.IntN(len(genTokens))])
		}
		add(b.String(), genFlags[r.IntN(len(genFlags))])
	}

	var o strings.Builder
	o.WriteString("/* Generated by tools/gen-syntax-tests.sh from Go's regexp/syntax. Do not edit. */\n\n/* clang-format off */\n#define Z {NULL, 0, 0}\n")
	o.WriteString("static const SynGenCase syn_gen_cases[] = {\n")
	for _, c := range cases {
		fmt.Fprintf(&o, "{%s, %d, 0x%x, ", cstr(c.pat), len(c.pat), uint16(c.flags))
		re, err := Parse(c.pat, c.flags)
		if err != nil {
			fmt.Fprintf(&o, "%s, Z, Z, 0, Z, Z, Z, 0, 0, 0, 0, Z},\n", text(err.Error()))
			continue
		}
		fmt.Fprintf(&o, "{NULL, 0, 0}, %s, ", text(dump(re)))
		s := re.String()
		fmt.Fprintf(&o, "%s, ", text(s))
		roundtrip := 0
		if re2, err := Parse(s, c.flags); err != nil {
			roundtrip = 2
		} else if re.Equal(re2) {
			roundtrip = 1
		}
		simple := re.Simplify()
		fmt.Fprintf(&o, "%d, %s, ", roundtrip, text(simple.String()))
		prog, _ := Compile(simple)
		fmt.Fprintf(&o, "%s, ", text(prog.String()))
		prefix, complete := prog.Prefix()
		comp := 0
		if complete {
			comp = 1
		}
		fmt.Fprintf(&o, "%s, %d, %d, %d, ", text(prefix), comp, prog.StartCond(), prog.NumCap)
		fmt.Fprintf(&o, "%d, %s},\n", re.MaxCap(), text(strings.Join(re.CapNames(), ",")))
	}
	o.WriteString("};\n#undef Z\n/* clang-format on */\n")
	if err := os.WriteFile(path, []byte(o.String()), 0o644); err != nil {
		t.Fatal(err)
	}
}
GO

(cd "$tmp/syntax" && SYNGEN_OUT="$out" GOFLAGS=-mod=mod go test -run '^TestGen$' -count=1 . >/dev/null)
if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
