#!/bin/sh
# Regenerates tests/quotedprintable_test_gen.h: what Go's mime/quotedprintable
# reader makes of Go's own test inputs and of more, read all at once and one
# byte at a time, a digest of what it makes of every string of up to six bytes
# from "0A \r\n=\t", and what the writer makes of Go's inputs and of random
# ones, written whole and in pieces, as text and as binary. Nothing in the
# package depends on the machine, so this runs wherever go does.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/quotedprintable_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

cat > "$tmp/main.go" <<'GO'
package main

import (
	"fmt"
	"io"
	"mime/quotedprintable"
	"os"
	"runtime"
	"strings"
)

// C string literal of s, with octal escapes so nothing runs into the next
// character.
func lit(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c == '?':
			b.WriteString(`\077`)
		case c >= ' ' && c <= '~':
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func errText(err error) string {
	if err == nil {
		return ""
	}
	return err.Error()
}

// Everything the reader gives through io.Copy, as Go's test reads it.
func readAll(in string) (string, string) {
	var buf strings.Builder
	_, err := io.Copy(&buf, quotedprintable.NewReader(strings.NewReader(in)))
	return buf.String(), errText(err)
}

// The same one byte at a time, stopping at the first error, io.EOF included.
func readBytes(in string) (string, string) {
	r := quotedprintable.NewReader(strings.NewReader(in))
	var buf strings.Builder
	p := make([]byte, 1)
	for {
		n, err := r.Read(p)
		buf.Write(p[:n])
		if err == io.EOF {
			return buf.String(), ""
		}
		if err != nil {
			return buf.String(), errText(err)
		}
	}
}

func write(in string, binary bool, piece int) string {
	var buf strings.Builder
	w := quotedprintable.NewWriter(&buf)
	w.Binary = binary
	b := []byte(in)
	if piece == 0 {
		piece = len(b) + 1
	}
	for len(b) > 0 {
		k := min(piece, len(b))
		if _, err := w.Write(b[:k]); err != nil {
			panic(err)
		}
		b = b[k:]
	}
	if err := w.Close(); err != nil {
		panic(err)
	}
	return buf.String()
}

// The C test's rnd_text: bytes from a 64 bit LCG, mostly letters with the
// characters the encoder cares about mixed in.
func rndText(seed uint64, n int) string {
	const pick = "abcdefghijklmnopqrstuvwxyz        \t\t\r\n\r\n==.~!\x00\x7f\x80\xc3\xa9\xff"
	x := seed
	b := make([]byte, n)
	for i := range b {
		x = x*6364136223846793005 + 1442695040888963407
		b[i] = pick[(x>>33)%uint64(len(pick))]
	}
	return string(b)
}

// FNV-1a, 64 bit, over each part with its length in front.
type fnv uint64

func (h *fnv) add(s string) {
	var l [8]byte
	for i := range l {
		l[i] = byte(uint64(len(s)) >> (8 * i))
	}
	for _, c := range append(l[:], s...) {
		*h ^= fnv(c)
		*h *= 1099511628211
	}
}

func main() {
	readIns := []string{
		"", "foo bar", "foo bar=3D", "foo bar=3d", "foo bar=\n", "foo bar\n",
		"foo bar=0", "foo bar=0D=0A", " A B        \r\n C ", " A B =\r\n C ",
		" A B =\n C ", "foo=\nbar", "foo\x00bar", "foo bar\xff", "=3D30\n",
		"=00=FF0=\n", "foo  \n", "foo  \n\nfoo =\n\nfoo=20\n\n", "foo\nbar",
		"foo\rbar", "foo\r\nbar", "foo=\r\nbar", "foo=\nbar", "foo=\rbar",
		"foo=\r\r\r \nbar", "foo=", "=",
		"Now's the time =\nfor all folk to come=\n to the aid of their country.",
		"accept UTF-8 right quotation mark: ’", "foo= \r\nbar", "foo=\t \r\nbar",
		// More of the edges.
		"=4", "=4g", "=G0", "a=\r", "a=\r\n", "a=  ", "a= x\n", "\x7f", "a\x1bb",
		"\t\t\r\n", "=\r\n", "==41", "a=\n=\n=\nb",
	}
	// Lines longer than the 4096 byte bufio buffer, which C builds with
	// long_input and checks by digest, since a literal that long is past what
	// C promises to compile.
	longIns := []string{
		strings.Repeat("x", 5000) + "\n" + strings.Repeat("y", 10),
		strings.Repeat("=41", 2000) + "=\r\n" + strings.Repeat("z ", 3000) + "\r\n",
	}

	o := os.Stdout
	fmt.Fprintf(o, "/* What Go's mime/quotedprintable makes, %s. Generated by\n", runtime.Version())
	fmt.Fprintf(o, " * tools/gen-quotedprintable-tests.sh; do not edit. */\n\n")

	fmt.Fprintf(o, "typedef struct QpReadCase {\n    const char *in;\n    long long in_len;\n")
	fmt.Fprintf(o, "    const char *want;\n    long long want_len;\n    const char *err;\n")
	fmt.Fprintf(o, "    const char *want1;\n    long long want1_len;\n    const char *err1;\n} QpReadCase;\n\n")
	fmt.Fprintf(o, "static const QpReadCase qp_read_cases[] = {\n")
	for _, in := range readIns {
		got, err := readAll(in)
		got1, err1 := readBytes(in)
		fmt.Fprintf(o, "    {%s, %d,\n     %s, %d, %s,\n     %s, %d, %s},\n",
			lit(in), len(in), lit(got), len(got), lit(err), lit(got1), len(got1), lit(err1))
	}
	fmt.Fprintf(o, "};\n\n")

	fmt.Fprintf(o, "typedef struct QpLongCase {\n    long long want_len;\n    unsigned long long want_fnv;\n")
	fmt.Fprintf(o, "    const char *err;\n    long long want1_len;\n    unsigned long long want1_fnv;\n")
	fmt.Fprintf(o, "    const char *err1;\n} QpLongCase;\n\n")
	fmt.Fprintf(o, "static const QpLongCase qp_long_cases[] = {\n")
	for _, in := range longIns {
		got, err := readAll(in)
		got1, err1 := readBytes(in)
		var h, h1 fnv = 14695981039346656037, 14695981039346656037
		h.add(got)
		h1.add(got1)
		fmt.Fprintf(o, "    {%d, 0x%016xULL, %s, %d, 0x%016xULL, %s},\n",
			len(got), uint64(h), lit(err), len(got1), uint64(h1), lit(err1))
	}
	fmt.Fprintf(o, "};\n\n")

	// Every string of up to six bytes from the alphabet, in the order the C
	// test makes them: by length, then counting with the first byte as the
	// most significant digit.
	const alpha = "0A \r\n=\t"
	var h fnv = 14695981039346656037
	count := 0
	for n := 0; n <= 6; n++ {
		idx := make([]int, n)
		for {
			b := make([]byte, n)
			for i := range b {
				b[i] = alpha[idx[i]]
			}
			in := string(b)
			got, err := readAll(in)
			h.add(in)
			h.add(got)
			h.add(err)
			count++
			i := n - 1
			for i >= 0 {
				idx[i]++
				if idx[i] < len(alpha) {
					break
				}
				idx[i] = 0
				i--
			}
			if i < 0 {
				break
			}
		}
	}
	fmt.Fprintf(o, "#define QP_EXHAUSTIVE_ALPHABET %s\n", lit(alpha))
	fmt.Fprintf(o, "#define QP_EXHAUSTIVE_MAX 6\n")
	fmt.Fprintf(o, "#define QP_EXHAUSTIVE_COUNT %d\n", count)
	fmt.Fprintf(o, "#define QP_EXHAUSTIVE_FNV 0x%016xULL\n\n", uint64(h))

	writeIns := []string{
		"", "foo bar", "foo bar=", "foo bar\r", "foo bar\r\r", "foo bar\n", "foo bar\r\n",
		"foo bar\r\r\n", "foo bar ", "foo bar\t", "foo bar  ", "foo bar \n", "foo bar \r",
		"foo bar \r\n", "foo bar  \n", "foo bar  \n ", "¡Hola Señor!",
		"\t !\"#$%&'()*+,-./ :;<>?@[\\]^_`{|}~",
		strings.Repeat("a", 75), strings.Repeat("a", 76), strings.Repeat("a", 72) + "=",
		strings.Repeat("a", 73) + "=", strings.Repeat("a", 74) + "=",
		strings.Repeat("a", 75) + "=", strings.Repeat(" ", 73), strings.Repeat(" ", 74),
		strings.Repeat(" ", 75), strings.Repeat(" ", 76), strings.Repeat(" ", 77),
	}
	for seed := uint64(1); seed <= 40; seed++ {
		writeIns = append(writeIns, rndText(seed, int(seed*seed)%400))
	}
	fmt.Fprintf(o, "typedef struct QpWriteCase {\n    const char *in;\n    long long in_len;\n")
	fmt.Fprintf(o, "    int rnd_seed; /* the input is rnd_text(seed) when it is not 0 */\n")
	fmt.Fprintf(o, "    const char *text;\n    const char *text3; /* written 3 bytes at a time */\n")
	fmt.Fprintf(o, "    const char *binary;\n    const char *binary3;\n} QpWriteCase;\n\n")
	fmt.Fprintf(o, "static const QpWriteCase qp_write_cases[] = {\n")
	for i, in := range writeIns {
		seed := 0
		inLit := lit(in)
		if i >= len(writeIns)-40 {
			seed = i - (len(writeIns) - 40) + 1
			inLit = "NULL"
		}
		fmt.Fprintf(o, "    {%s, %d, %d,\n     %s,\n     %s,\n     %s,\n     %s},\n",
			inLit, len(in), seed, lit(write(in, false, 0)), lit(write(in, false, 3)),
			lit(write(in, true, 0)), lit(write(in, true, 3)))
	}
	fmt.Fprintf(o, "};\n")
}
GO

(cd "$tmp" && go mod init qpgen >/dev/null 2>&1 && go run . > "$out.tmp")
mv "$out.tmp" "$out"
if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$out"
fi
