#!/bin/sh
# Regenerates src/crypto/fiat_p224_32.h through fiat_p521_64.h: the field
# arithmetic for the four NIST curves, from fiat-crypto's C output.
#
# Go's crypto/internal/fips140/nistec/fiat is fiat-crypto's output for Go. This
# takes the C output of the same models at the commit the ed25519 scalar
# headers came from, and keeps each file byte for byte between two lines of
# dashes. P-224, P-256 and P-384 are word by word Montgomery, as in Go. Go
# generates P-521 the same way, but fiat-crypto ships it as an unsaturated
# Solinas field, so nistec_p521.c works with that instead: no Montgomery form,
# and a carry after an add or a subtract. Both are formally verified, and what
# comes out of SetBytes, Bytes and every operation in between is the same
# number.
#
# Each curve comes in 64 bit words, for compilers with a 128 bit integer, and
# 32 bit words, for MSVC and for 32 bit machines. What is around the fiat code
# keeps it to the machines it is for, quiets the warnings burrow's flags give
# for it, and says how many words an element is, so nistec.h can size the
# structs that hold them without including this.
#
# Needs curl and the network.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
commit=c79cf6061a60
base="https://raw.githubusercontent.com/mit-plv/fiat-crypto/$commit/fiat-c/src"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

words() {
	case $1 in
	4) echo four ;; 6) echo six ;; 7) echo seven ;; 8) echo eight ;;
	9) echo nine ;; 12) echo twelve ;; 19) echo nineteen ;;
	*) echo "$1" ;;
	esac
}

gen() {
	curve=$1 bits=$2 limbs=$3 kind=$4
	name=fiat_p${curve}_${bits}
	guard=$(echo "BURROW_CRYPTO_${name}_H" | tr '[:lower:]' '[:upper:]')
	upper=$(echo "$curve" | tr '[:lower:]' '[:upper:]')
	curl -sSfL -o "$tmp/src.c" "$base/p${curve}_${bits}.c"
	if [ "$bits" = 64 ]; then
		cond='defined(__SIZEOF_INT128__)'
		who='for compilers that have a 128 bit integer to multiply them with'
		limb=uint64_t
	else
		cond='!defined(__SIZEOF_INT128__)'
		who='for compilers with no 128 bit integer, which are MSVC and those for
 * 32 bit machines'
		limb=uint32_t
	fi
	if [ "$kind" = montgomery ]; then
		what="Montgomery arithmetic modulo the P-$curve prime"
	else
		what="arithmetic modulo the P-$curve prime, 2^521 - 1, as an unsaturated
 * Solinas field"
	fi
	{
		cat <<EOF
/* fiat-crypto's $what, in $(words "$limbs") $bits bit words,
 * $who. nistec_p$curve.c is the only file that includes it.
 *
 * Generated by tools/gen-fiat-nistec.sh; do not edit. Everything between the
 * two lines of dashes is fiat-c/src/p${curve}_${bits}.c from
 * https://github.com/mit-plv/fiat-crypto at commit $commit, byte for byte. It
 * is generated from a formally verified model, so it is not edited here, and
 * .clang-format-ignore keeps the formatter off it.
 *
 * fiat-crypto code comes under the following licence.
 *
 *     Copyright (c) 2015-2020 The fiat-crypto Authors. All rights reserved.
 *
 *     Redistribution and use in source and binary forms, with or without
 *     modification, are permitted provided that the following conditions are
 *     met:
 *
 *         1. Redistributions of source code must retain the above copyright
 *         notice, this list of conditions and the following disclaimer.
 *
 *     THIS SOFTWARE IS PROVIDED BY the fiat-crypto authors "AS IS"
 *     AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *     THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *     PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Berkeley Software Design,
 *     Inc. BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 *     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 *     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 *     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. */

#ifndef $guard
#define $guard

/* ecdh.h comes first so that the amalgamation files this header with
 * crypto/ecdh, the package it is part of. */
#include "burrow/crypto/ecdh.h"

#if $cond

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wconversion"
#elif defined(_MSC_VER)
/* Without __inline__ the functions nothing calls are plain statics, which
 * MSVC's level 4 reports. */
#pragma warning(push)
#pragma warning(disable : 4505)
#endif

/* ------------------------------------------------------------------------ */
EOF
		cat "$tmp/src.c"
		cat <<EOF
/* ------------------------------------------------------------------------ */

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif

/* A field element is this many of this. */
typedef $limb fiat_p${curve}_limb;
#define FIAT_P${upper}_LIMBS $limbs

#endif /* $cond */

#endif /* $guard */
EOF
	} >"$tmp/out.h"
	mv "$tmp/out.h" "$root/src/crypto/$name.h"
}

gen 224 64 4 montgomery
gen 224 32 7 montgomery
gen 256 64 4 montgomery
gen 256 32 8 montgomery
gen 384 64 6 montgomery
gen 384 32 12 montgomery
gen 521 64 9 solinas
gen 521 32 19 solinas
