#!/bin/sh
# Regenerates tests/image_color_test_gen.h: what Go's image/color makes of a
# set of colors. RGBA for every value of the one-channel colors and random
# values of the rest, every model applied to colors of every type, the
# palettes' Index and Convert for random colors, how fmt prints each type, and
# FNV-1a digests of RGBToYCbCr, YCbCrToRGB, RGBToCMYK and YCbCr.RGBA over all
# 2^24 inputs, and of CMYKToRGB and NYCbCrA.RGBA over a stride of theirs.
# Nothing depends on the machine, so this runs wherever go does.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/image_color_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

cat > "$tmp/main.go" <<'GO'
package main

import (
	"fmt"
	"image/color"
	"image/color/palette"
	"math/rand"
	"strconv"
)

// The kinds, in the order of the test's table of types.
const (
	kRGBA = iota
	kRGBA64
	kNRGBA
	kNRGBA64
	kAlpha
	kAlpha16
	kGray
	kGray16
	kYCbCr
	kNYCbCrA
	kCMYK
)

func fields(c color.Color) (int, [4]uint32) {
	switch v := c.(type) {
	case color.RGBA:
		return kRGBA, [4]uint32{uint32(v.R), uint32(v.G), uint32(v.B), uint32(v.A)}
	case color.RGBA64:
		return kRGBA64, [4]uint32{uint32(v.R), uint32(v.G), uint32(v.B), uint32(v.A)}
	case color.NRGBA:
		return kNRGBA, [4]uint32{uint32(v.R), uint32(v.G), uint32(v.B), uint32(v.A)}
	case color.NRGBA64:
		return kNRGBA64, [4]uint32{uint32(v.R), uint32(v.G), uint32(v.B), uint32(v.A)}
	case color.Alpha:
		return kAlpha, [4]uint32{uint32(v.A)}
	case color.Alpha16:
		return kAlpha16, [4]uint32{uint32(v.A)}
	case color.Gray:
		return kGray, [4]uint32{uint32(v.Y)}
	case color.Gray16:
		return kGray16, [4]uint32{uint32(v.Y)}
	case color.YCbCr:
		return kYCbCr, [4]uint32{uint32(v.Y), uint32(v.Cb), uint32(v.Cr)}
	case color.NYCbCrA:
		return kNYCbCrA, [4]uint32{uint32(v.Y), uint32(v.Cb), uint32(v.Cr), uint32(v.A)}
	case color.CMYK:
		return kCMYK, [4]uint32{uint32(v.C), uint32(v.M), uint32(v.Y), uint32(v.K)}
	}
	panic("unknown color")
}

func lit(s string) string { return strconv.Quote(s) }

func col(c color.Color) string {
	k, f := fields(c)
	return fmt.Sprintf("{%d, {%d, %d, %d, %d}}", k, f[0], f[1], f[2], f[3])
}

func rgba(c color.Color) string {
	r, g, b, a := c.RGBA()
	return fmt.Sprintf("{%d, %d, %d, %d}", r, g, b, a)
}

func random(rng *rand.Rand, k int) color.Color {
	u8 := func() uint8 {
		// Mostly anything, sometimes an end, so the special cases come up.
		switch rng.Intn(8) {
		case 0:
			return 0
		case 1:
			return 0xff
		}
		return uint8(rng.Intn(256))
	}
	u16 := func() uint16 {
		switch rng.Intn(8) {
		case 0:
			return 0
		case 1:
			return 0xffff
		}
		return uint16(rng.Intn(65536))
	}
	switch k {
	case kRGBA:
		// Premultiplied, so no channel above alpha, and sometimes not.
		a := u8()
		if rng.Intn(4) == 0 {
			return color.RGBA{u8(), u8(), u8(), a}
		}
		m := func() uint8 { return uint8(rng.Intn(int(a) + 1)) }
		return color.RGBA{m(), m(), m(), a}
	case kRGBA64:
		a := u16()
		if rng.Intn(4) == 0 {
			return color.RGBA64{u16(), u16(), u16(), a}
		}
		m := func() uint16 { return uint16(rng.Intn(int(a) + 1)) }
		return color.RGBA64{m(), m(), m(), a}
	case kNRGBA:
		return color.NRGBA{u8(), u8(), u8(), u8()}
	case kNRGBA64:
		return color.NRGBA64{u16(), u16(), u16(), u16()}
	case kAlpha:
		return color.Alpha{u8()}
	case kAlpha16:
		return color.Alpha16{u16()}
	case kGray:
		return color.Gray{u8()}
	case kGray16:
		return color.Gray16{u16()}
	case kYCbCr:
		return color.YCbCr{u8(), u8(), u8()}
	case kNYCbCrA:
		return color.NYCbCrA{color.YCbCr{u8(), u8(), u8()}, u8()}
	case kCMYK:
		return color.CMYK{u8(), u8(), u8(), u8()}
	}
	panic("kind")
}

type fnv struct{ h uint64 }

func (f *fnv) byte(b uint8) {
	f.h ^= uint64(b)
	f.h *= 1099511628211
}

func (f *fnv) u16(v uint32) {
	f.byte(uint8(v))
	f.byte(uint8(v >> 8))
}

func main() {
	rng := rand.New(rand.NewSource(2143))

	fmt.Print(`/* Generated by tools/gen-image-color-tests.sh from Go's image/color. Do not
 * edit. */

`)

	// RGBA of every value of the one-channel colors, and of random others.
	fmt.Println("static const ClRGBACase cl_rgba_cases[] = {")
	for v := 0; v < 256; v++ {
		for _, c := range []color.Color{color.Alpha{uint8(v)}, color.Gray{uint8(v)}} {
			fmt.Printf("    {%s, %s},\n", col(c), rgba(c))
		}
	}
	for v := 0; v < 65536; v += 257 {
		for _, c := range []color.Color{color.Alpha16{uint16(v)}, color.Gray16{uint16(v)}, color.Alpha16{uint16(v + 1)}, color.Gray16{uint16(v + 1)}} {
			fmt.Printf("    {%s, %s},\n", col(c), rgba(c))
		}
	}
	for k := kRGBA; k <= kCMYK; k++ {
		for i := 0; i < 200; i++ {
			c := random(rng, k)
			fmt.Printf("    {%s, %s},\n", col(c), rgba(c))
		}
	}
	fmt.Print("};\n\n")

	// Every model on colors of every type.
	models := []color.Model{
		color.RGBAModel, color.RGBA64Model, color.NRGBAModel, color.NRGBA64Model,
		color.AlphaModel, color.Alpha16Model, color.GrayModel, color.Gray16Model,
		color.YCbCrModel, color.NYCbCrAModel, color.CMYKModel,
	}
	fmt.Println("static const ClModelCase cl_model_cases[] = {")
	for m, model := range models {
		for k := kRGBA; k <= kCMYK; k++ {
			for i := 0; i < 60; i++ {
				c := random(rng, k)
				fmt.Printf("    {%d, %s, %s},\n", m, col(c), col(model.Convert(c)))
			}
		}
	}
	fmt.Print("};\n\n")

	// The palettes on random colors of every type, plus every palette color
	// itself, which has to find its own index.
	pals := []color.Palette{palette.Plan9, palette.WebSafe}
	fmt.Println("static const ClPaletteCase cl_palette_cases[] = {")
	for p, pal := range pals {
		for k := kRGBA; k <= kCMYK; k++ {
			for i := 0; i < 100; i++ {
				c := random(rng, k)
				fmt.Printf("    {%d, %s, %d, %s},\n", p, col(c), pal.Index(c), col(pal.Convert(c)))
			}
		}
		for _, c := range pal {
			fmt.Printf("    {%d, %s, %d, %s},\n", p, col(c), pal.Index(c), col(pal.Convert(c)))
		}
	}
	// A small palette of mixed types, where ties and types matter.
	small := color.Palette{color.Gray{0x80}, color.RGBA{0x80, 0x80, 0x80, 0xff}, color.Alpha16{0}, color.CMYK{0, 0xff, 0xff, 0}, color.NRGBA{0xff, 0, 0, 0x80}}
	for k := kRGBA; k <= kCMYK; k++ {
		for i := 0; i < 50; i++ {
			c := random(rng, k)
			fmt.Printf("    {2, %s, %d, %s},\n", col(c), small.Index(c), col(small.Convert(c)))
		}
	}
	fmt.Print("};\n\n")

	// How fmt prints one of each type.
	fmt.Println("static const ClFmtCase cl_fmt_cases[] = {")
	for k := kRGBA; k <= kCMYK; k++ {
		for i := 0; i < 3; i++ {
			c := random(rng, k)
			fmt.Printf("    {%s, %s, %s, %s},\n", col(c), lit(fmt.Sprintf("%v", c)), lit(fmt.Sprintf("%+v", c)), lit(fmt.Sprintf("%#v", c)))
		}
	}
	fmt.Print("};\n\n")

	// The conversion functions over every input, as digests.
	var yc, rgb, cmyk, ycrgba fnv
	yc.h, rgb.h, cmyk.h, ycrgba.h = 14695981039346656037, 14695981039346656037, 14695981039346656037, 14695981039346656037
	for i := 0; i < 1<<24; i++ {
		a, b, c := uint8(i>>16), uint8(i>>8), uint8(i)
		y, cb, cr := color.RGBToYCbCr(a, b, c)
		yc.byte(y)
		yc.byte(cb)
		yc.byte(cr)
		r, g, bb := color.YCbCrToRGB(a, b, c)
		rgb.byte(r)
		rgb.byte(g)
		rgb.byte(bb)
		cc, m, yy, k := color.RGBToCMYK(a, b, c)
		cmyk.byte(cc)
		cmyk.byte(m)
		cmyk.byte(yy)
		cmyk.byte(k)
		r32, g32, b32, a32 := color.YCbCr{a, b, c}.RGBA()
		ycrgba.u16(r32)
		ycrgba.u16(g32)
		ycrgba.u16(b32)
		ycrgba.u16(a32)
	}
	var cmykrgb, nyc fnv
	cmykrgb.h, nyc.h = 14695981039346656037, 14695981039346656037
	for i := 0; i < 1<<32; i += 257 {
		a, b, c, d := uint8(i>>24), uint8(i>>16), uint8(i>>8), uint8(i)
		r, g, bb := color.CMYKToRGB(a, b, c, d)
		cmykrgb.byte(r)
		cmykrgb.byte(g)
		cmykrgb.byte(bb)
		r32, g32, b32, a32 := color.NYCbCrA{color.YCbCr{a, b, c}, d}.RGBA()
		nyc.u16(r32)
		nyc.u16(g32)
		nyc.u16(b32)
		nyc.u16(a32)
	}
	fmt.Printf("#define CL_DIGEST_RGB_TO_Y_CB_CR UINT64_C(0x%016x)\n", yc.h)
	fmt.Printf("#define CL_DIGEST_Y_CB_CR_TO_RGB UINT64_C(0x%016x)\n", rgb.h)
	fmt.Printf("#define CL_DIGEST_RGB_TO_CMYK UINT64_C(0x%016x)\n", cmyk.h)
	fmt.Printf("#define CL_DIGEST_Y_CB_CR_RGBA UINT64_C(0x%016x)\n", ycrgba.h)
	fmt.Printf("#define CL_DIGEST_CMYK_TO_RGB UINT64_C(0x%016x)\n", cmykrgb.h)
	fmt.Printf("#define CL_DIGEST_NY_CB_CR_A_RGBA UINT64_C(0x%016x)\n", nyc.h)
}
GO

(cd "$tmp" && go mod init gen >/dev/null 2>&1 && go run . > "$out.tmp")
mv "$out.tmp" "$out"
if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$out"
fi
