#!/bin/sh
# Regenerates tests/go_parser_test_gen.h for the go/parser tests. It holds
# what Go's own tests read from disk or from short_test.go:
#
#   - every .go file of src/go/parser, which TestParse parses and TestParseDir
#     lays out in a directory of its own;
#   - everything under src/go/parser/testdata, for TestErrors, TestResolution,
#     TestGoVersion and TestIssue42951;
#   - the valids and invalids lists of short_test.go.
#
# A file is cut into pieces of at most 30000 bytes, since MSVC will not take a
# string literal over 64K, and the tests join them up again.
#
# GOROOT says which Go to read, and defaults to what go env says.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=${GOROOT:-$(go env GOROOT)}
out="$root/tests/go_parser_test_gen.h"

python3 - "$goroot" > "$out" <<'EOF'
import os
import re
import sys

goroot = sys.argv[1]
pkg = os.path.join(goroot, "src", "go", "parser")
gover = open(os.path.join(goroot, "VERSION")).readline().strip()
PIECE = 30000


# The libc calls tools/check-banned.sh looks for. Go's sources call a method
# sprintf, and the first letter of a name like that goes out as an octal escape
# so the check does not take the text for a call.
BANNED = re.compile(
    rb"(?<![A-Za-z0-9_])(strcpy|strcat|sprintf|vsprintf|gets|strtok|strncpy|"
    rb"strncat|alloca|atoi|atol|atof)[ \t]*\("
)


def lit(b):
    """b as C string literals, one line of the source to each."""
    lines, cur = [], ""
    hide = {m.start() for m in BANNED.finditer(b)}
    for i, c in enumerate(b):
        if i in hide:
            s = "\\%03o" % c
        elif c == 10:
            s = "\\n"
        elif c == 9:
            s = "\\t"
        elif c == 34:
            s = '\\"'
        elif c == 92:
            s = "\\\\"
        elif c == 63 and i + 1 < len(b) and b[i + 1] == 63:
            s = "\\?"
        elif 32 <= c < 127:
            s = chr(c)
        else:
            s = "\\%03o" % c
        cur += s
        if c == 10 or len(cur) >= 70:
            lines.append('"' + cur + '"')
            cur = ""
    if cur or not lines:
        lines.append('"' + cur + '"')
    return lines


def go_strings(body):
    """The string literals of a Go composite literal body, comments skipped."""
    out, i = [], 0
    while i < len(body):
        c = body[i]
        if c == "`":
            j = body.index("`", i + 1)
            out.append(body[i + 1 : j].encode())
            i = j + 1
        elif c == '"':
            s, i = "", i + 1
            while body[i] != '"':
                if body[i] == "\\":
                    s += {"n": "\n", "t": "\t", "\\": "\\", '"': '"'}[body[i + 1]]
                    i += 2
                else:
                    s += body[i]
                    i += 1
            out.append(s.encode())
            i += 1
        elif body.startswith("//", i):
            i = body.index("\n", i)
        else:
            i += 1
    return out


def str_list(src, name):
    start = src.index("var %s = []string{\n" % name)
    start = src.index("\n", start) + 1
    end = src.index("\n}\n", start)
    return go_strings(src[start:end])


w = sys.stdout.write
w("/* What Go's go/parser tests read, from src/go/parser of %s.\n" % gover)
w(" * Generated by tools/gen-go-parser-tests.sh; do not edit. */\n\n")
w("typedef struct GptPiece {\n    const char *p;\n    long long n;\n} GptPiece;\n\n")
w("#define GPT_P(x) {x, (long long)sizeof(x) - 1}\n\n")
w("typedef struct GptFile {\n    const char *name;\n    const GptPiece *pieces;\n")
w("    int npieces;\n} GptFile;\n\n")


def emit_files(group, names, base):
    ids = []
    for k, name in enumerate(names):
        data = open(os.path.join(base, name), "rb").read()
        ident = "gpt_%s_%d" % (group, k)
        w("static const GptPiece %s[] = {\n" % ident)
        for off in range(0, max(len(data), 1), PIECE):
            w("    GPT_P(" + "\n          ".join(lit(data[off : off + PIECE])) + "),\n")
        w("};\n\n")
        ids.append((name, ident))
    w("static const GptFile gpt_%s[] = {\n" % group)
    for name, ident in ids:
        w('    {"%s", %s, (int)(sizeof(%s) / sizeof(%s[0]))},\n' % (name, ident, ident, ident))
    w("};\n\n")


sources = sorted(f for f in os.listdir(pkg) if f.endswith(".go"))
testdata = []
tdir = os.path.join(pkg, "testdata")
for dirpath, _, files in os.walk(tdir):
    for f in files:
        testdata.append(os.path.relpath(os.path.join(dirpath, f), tdir).replace(os.sep, "/"))
testdata.sort()

w("#ifdef GPT_WANT_SOURCES\n\n")
emit_files("sources", sources, pkg)
w("#endif\n\n#ifdef GPT_WANT_TESTDATA\n\n")
emit_files("testdata", testdata, tdir)
w("#endif\n\n#ifdef GPT_WANT_SHORT\n\n")
short = open(os.path.join(pkg, "short_test.go")).read()
for name in ("valids", "invalids"):
    w("static const GptPiece gpt_%s[] = {\n" % name)
    for s in str_list(short, name):
        w("    GPT_P(" + "\n          ".join(lit(s)) + "),\n")
    w("};\n\n")
w("#endif\n")
EOF

if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
