#!/bin/sh
# Regenerates tests/go_printer_test_gen.h for the go/printer tests. It holds
# what Go's own tests read from disk:
#
#   - the data table of printer_test.go, the source and golden file pairs
#     TestFiles checks and the modes it checks them in, with every file the
#     table names out of src/go/printer/testdata;
#   - src/go/printer/printer.go itself, which TestBaseIndent and
#     TestWriteErrors parse and print.
#
# A file can be bigger than the 64K MSVC takes in one string literal, so each
# one goes out as a list of pieces to put back together.
#
# GOROOT says which Go to read, and defaults to what go env says.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=${GOROOT:-$(go env GOROOT)}
out="$root/tests/go_printer_test_gen.h"

python3 - "$goroot" > "$out" <<'PY'
import os
import re
import sys

goroot = sys.argv[1]
pkg = os.path.join(goroot, "src", "go", "printer")
gover = open(os.path.join(goroot, "VERSION")).readline().strip()

# Bytes of a file to each piece, well under what MSVC takes once escaped.
CHUNK = 12000

# The libc calls tools/check-banned.sh looks for. The first letter of a name
# like that goes out as an octal escape so the check does not take the text
# for a call.
BANNED = re.compile(
    rb"(?<![A-Za-z0-9_])(strcpy|strcat|sprintf|vsprintf|gets|strtok|strncpy|"
    rb"strncat|alloca|atoi|atol|atof)[ \t]*\("
)


def lit(b):
    """b as C string literals, one line of the text to each."""
    lines, cur = [], ""
    hide = {m.start() for m in BANNED.finditer(b)}
    for i, c in enumerate(b):
        if i in hide:
            s = "\\%03o" % c
        elif c == 10:
            s = "\\n"
        elif c == 9:
            s = "\\t"
        elif c == 34:
            s = '\\"'
        elif c == 92:
            s = "\\\\"
        elif c == 63 and i + 1 < len(b) and b[i + 1] == 63:
            s = "\\?"
        elif 32 <= c < 127:
            s = chr(c)
        else:
            s = "\\%03o" % c
        # an octal escape must not run into a digit after it
        if s.startswith("\\") and s[1:].isdigit() and i + 1 < len(b):
            nxt = b[i + 1]
            if 48 <= nxt <= 55:
                cur += s
                lines.append('"' + cur + '"')
                cur = ""
                continue
        cur += s
        if c == 10 or len(cur) >= 70:
            lines.append('"' + cur + '"')
            cur = ""
    if cur or not lines:
        lines.append('"' + cur + '"')
    return lines


def pieces(b):
    out = []
    for i in range(0, max(len(b), 1), CHUNK):
        out.append(b[i : i + CHUNK])
    return out


test = open(os.path.join(pkg, "printer_test.go")).read()
start = test.index("var data = []entry{")
body = test[start : test.index("\n}\n", start)]
entries = re.findall(r'\{"([^"]+)", "([^"]+)", ([^}]+)\}', body)
assert entries, "no data table"

MODES = {
    "0": "0",
    "export": "GPRT_EXPORT",
    "rawFormat": "GPRT_RAW_FORMAT",
    "normNumber": "GPRT_NORM_NUMBER",
    "idempotent": "GPRT_IDEMPOTENT",
    "allowTypeParams": "GPRT_ALLOW_TYPE_PARAMS",
}

files = []
for src, golden, _ in entries:
    for f in (src, golden):
        if f not in files:
            files.append(f)

w = sys.stdout.write
w("/* What Go's go/printer tests read, from src/go/printer of %s.\n" % gover)
w(" * Generated by tools/gen-go-printer-tests.sh; do not edit. */\n\n")
w("typedef struct GprtPiece {\n    const char *p;\n    long long n;\n} GprtPiece;\n\n")
w("#define GPRT_P(x) {x, (long long)sizeof(x) - 1}\n\n")
w("typedef struct GprtFile {\n    const char *name;\n    const GprtPiece *pieces;\n")
w("    int npieces;\n} GprtFile;\n\n")
w("/* printer_test.go's checkMode. */\n")
w("enum {\n    GPRT_EXPORT = 1 << 0,\n    GPRT_RAW_FORMAT = 1 << 1,\n")
w("    GPRT_NORM_NUMBER = 1 << 2,\n    GPRT_IDEMPOTENT = 1 << 3,\n")
w("    GPRT_ALLOW_TYPE_PARAMS = 1 << 4\n};\n\n")
w("typedef struct GprtEntry {\n    const char *source, *golden;\n    unsigned mode;\n")
w("} GprtEntry;\n\n")

names = [("testdata/" + f, os.path.join(pkg, "testdata", f)) for f in files]
names.append(("printer.go", os.path.join(pkg, "printer.go")))
for k, (name, path) in enumerate(names):
    data = open(path, "rb").read()
    w("static const GprtPiece gprt_file_%d[] = {\n" % k)
    for p in pieces(data):
        w("    GPRT_P(" + "\n           ".join(lit(p)) + "),\n")
    w("};\n\n")

w("static const GprtFile gprt_files[] = {\n")
for k, (name, _) in enumerate(names):
    w('    {"%s", gprt_file_%d, (int)(sizeof(gprt_file_%d) / sizeof(gprt_file_%d[0]))},\n'
      % (name, k, k, k))
w("};\n\n")

w("static const GprtEntry gprt_data[] = {\n")
for src, golden, mode in entries:
    m = " | ".join(MODES[x.strip()] for x in mode.split("|"))
    w('    {"%s", "%s", %s},\n' % (src, golden, m))
w("};\n")
PY

if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
