#!/bin/sh
# Regenerates src/xnet/idna_tables.c, src/xnet/idna_tables.h and
# tests/xnet_idna_test_gen.h from golang.org/x/net/idna, at the version Go
# vendors.
#
# x/net/idna is generated from golang.org/x/text/internal/export/idna, and the
# x/text side has the tests and the ucd package that reads the conformance
# file, so the generator runs there, at the x/text version that
# src/vendor/modules.txt names. The script checks first that the x/text copy is
# the vendored x/net one, apart from the import path and the generate lines.
# tools/gen-xnet/idna_gen_test.go is laid over a writable copy and run as a
# test, which lets it read the unexported tables and the test tables by name.
# Besides the tables and Go's own test cases, it writes what Go says about a
# corpus of strings and about every rune, as hashes, for
# tests/xnet_idna_test.c to compare against. IdnaTestV2.txt comes from
# unicode.org, for the Unicode version the tables are for.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=$(go env GOROOT)
gover=$(go env GOVERSION)
vendored="$goroot/src/vendor/golang.org/x/net/idna"

netver=$(sed -n 's|^# golang.org/x/net \(v[^ ]*\)$|\1|p' "$goroot/src/vendor/modules.txt")
ver=$(sed -n 's|^# golang.org/x/text \(v[^ ]*\)$|\1|p' "$goroot/src/vendor/modules.txt")
[ -n "$netver" ] && [ -n "$ver" ] ||
	{ echo "gen-xnet-idna: no golang.org/x/net or x/text in modules.txt" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'chmod -R u+w "$tmp" 2>/dev/null; rm -rf "$tmp"' EXIT

dir=$(cd "$tmp" && GOFLAGS=-mod=mod go mod download -json "golang.org/x/text@$ver" |
	sed -n 's|^[[:space:]]*"Dir": "\(.*\)",$|\1|p')
[ -d "$dir" ] || { echo "gen-xnet-idna: could not download golang.org/x/text@$ver" >&2; exit 1; }

cp -R "$dir" "$tmp/text"
chmod -R u+w "$tmp/text"
pkg="$tmp/text/internal/export/idna"

strip() {
	grep -v '^// Code generated\|^//go:generate\|^$' "$1" | sed 's|^package idna // import .*|package idna|'
}
for f in "$vendored"/*.go; do
	b=$(basename "$f")
	strip "$f" > "$tmp/vendored.go"
	strip "$pkg/$b" > "$tmp/text.go"
	cmp -s "$tmp/vendored.go" "$tmp/text.go" ||
		{ echo "gen-xnet-idna: $b differs between x/net and x/text $ver" >&2; exit 1; }
done

uver=$(sed -n 's|^const UnicodeVersion = "\(.*\)"$|\1|p' "$vendored/tables17.0.0.go")
curl -fsSL --retry 3 -m 600 -o "$tmp/IdnaTestV2.txt" \
	"https://www.unicode.org/Public/$uver/idna/IdnaTestV2.txt"

cp "$root/tools/gen-xnet/idna_gen_test.go" "$pkg/zz_gen_test.go"

banner="/* Derived from Go's src/vendor/golang.org/x/net/idna/%s.
 * Go source: $gover, golang.org/x/net $netver.
 *
 * Generated by tools/gen-xnet-idna.sh from the Go tables. Do not edit.
 *
 * Copyright 2016 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

"

test_banner="/* Test data for tests/xnet_idna_test.c, from golang.org/x/text $ver's
 * internal/export/idna tests and Unicode $uver's IdnaTestV2.txt, plus what
 * the package says about a corpus of strings and about every rune, as hashes.
 *
 * Generated by tools/gen-xnet-idna.sh. Do not edit.
 *
 * Copyright 2016 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

"

mkdir -p "$root/src/xnet"
(cd "$pkg" &&
	BURROW_XNET_SRC="$root/src/xnet" \
	BURROW_XNET_TESTS="$root/tests" \
	BURROW_XNET_BANNER="$banner" \
	BURROW_XNET_TEST_BANNER="$test_banner" \
	BURROW_XNET_IDNA_TEST="$tmp/IdnaTestV2.txt" \
	GOFLAGS=-mod=mod go test -count=1 -run '^TestZZGen$' .)
