#!/bin/sh
# Regenerates src/image/palette.c, the two palettes of image/color/palette,
# from Go's own palette.Plan9 and palette.WebSafe, so every entry is Go's and in
# Go's order. The Go on PATH should be the release the port follows.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/src/image/palette.c"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

cat > "$tmp/main.go" <<'GO'
package main

import (
	"fmt"
	"image/color"
	"image/color/palette"
)

func table(name string, p []color.Color) {
	fmt.Printf("static Color pal_%s_colors[%d] = {\n", name, len(p))
	for _, c := range p {
		v := c.(color.RGBA)
		fmt.Printf("    PAL(0x%02x, 0x%02x, 0x%02x, 0x%02x),\n", v.R, v.G, v.B, v.A)
	}
	fmt.Printf("};\n\n")
	fmt.Printf("const ColorPalette palette_%s = {pal_%s_colors, %d, %d, &burrow_type_Color};\n", name, name, len(p), len(p))
}

func main() {
	fmt.Print(`/* image/color/palette. Generated by tools/gen-palette.sh from Go's
 * palette.Plan9 and palette.WebSafe. Do not edit.
 *
 * Copyright 2013 The Go Authors. All rights reserved.
 * Copyright 2026 The burrow Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style licence that can be found
 * in the LICENSE file. */

#include "burrow/image/color/palette.h"

#define PAL(r, g, b, a) {&burrow__color_rgba_vt, {.rgba = {r, g, b, a}}}

`)
	table("plan9", palette.Plan9)
	fmt.Println()
	table("web_safe", palette.WebSafe)
}
GO

(cd "$tmp" && go mod init gen >/dev/null 2>&1 && go run . > "$out.tmp")
mv "$out.tmp" "$out"
