#!/bin/sh
# Regenerates tests/bzip2_test_gen.h: a set of bzip2 streams, Go's own test
# files and some made with bzip2(1), with what Go's compress/bzip2 reader makes
# of each of them, and of each of the small ones with single bits flipped, cut
# short and with bytes after the end. tests/bzip2_test.c reads every stream the
# same way and has to get the same bytes and the same error. bzip2(1) is only
# needed here, to make the streams, which are then part of the header.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/tests/bzip2_test_gen.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
goroot=$(go env GOROOT)

mkdir "$tmp/testdata"
cp "$goroot/src/compress/bzip2/testdata/"* "$tmp/testdata/"

cat > "$tmp/main.go" <<'GO'
package main

import (
	"bytes"
	"compress/bzip2"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
)

func lcg(x uint64) uint64 { return x*6364136223846793005 + 1442695040888963407 }

func words(n int) []byte {
	vocab := strings.Fields("the quick brown fox jumped over lazy dog and a of to in " +
		"is that it was for on are as with his they at be this from I have or by " +
		"one had not but what all were when we there can an your which their said " +
		"if do will each about how up out them then she many some so these would")
	var b []byte
	x := uint64(1)
	for len(b) < n {
		x = lcg(x)
		b = append(b, vocab[(x>>33)%uint64(len(vocab))]...)
		if x>>60 == 0 {
			b = append(b, '\n')
		} else {
			b = append(b, ' ')
		}
	}
	return b[:n]
}

func noise(n int, seed uint64) []byte {
	b := make([]byte, n)
	x := seed
	for i := range b {
		x = lcg(x)
		b[i] = byte(x >> 56)
	}
	return b
}

// Runs of one byte, from 1 to 600 long, so the first run-length stage has
// every count to write.
func runs(n int, seed uint64) []byte {
	var b []byte
	x := seed
	for len(b) < n {
		x = lcg(x)
		c := byte(x >> 56)
		k := 1 + int((x>>33)%600)
		for i := 0; i < k; i++ {
			b = append(b, c)
		}
	}
	return b[:n]
}

func bzip(level int, in []byte) []byte {
	cmd := exec.Command("bzip2", "-c", fmt.Sprintf("-%d", level))
	cmd.Stdin = bytes.NewReader(in)
	out, err := cmd.Output()
	if err != nil {
		panic(err)
	}
	return out
}

func file(name string) []byte {
	b, err := os.ReadFile("testdata/" + name)
	if err != nil {
		panic(err)
	}
	if strings.HasSuffix(name, ".base64") {
		b, err = base64.StdEncoding.DecodeString(string(b))
		if err != nil {
			panic(err)
		}
	}
	return b
}

// Reads r in 4096 byte reads to the first error, as the C test does.
func decode(in []byte) (int, string, string) {
	r := bzip2.NewReader(bytes.NewReader(in))
	h := sha256.New()
	buf := make([]byte, 4096)
	n := 0
	for {
		k, err := r.Read(buf)
		h.Write(buf[:k])
		n += k
		if err != nil {
			e := ""
			if err != io.EOF {
				e = err.Error()
			}
			return n, fmt.Sprintf("%x", h.Sum(nil)), e
		}
	}
}

type stream struct {
	name   string
	data   []byte
	mutate bool
}

func main() {
	streams := []stream{
		{"pass-random1", file("pass-random1.bz2"), false},
		{"pass-random2", file("pass-random2.bz2"), true},
		{"pass-sawtooth", file("pass-sawtooth.bz2"), false},
		{"fail-issue5747", file("fail-issue5747.bz2.base64"), false},
		{"random.data", file("random.data.bz2"), false},
		{"words 300000 -1", bzip(1, words(300000)), false},
		{"words 3000 -9", bzip(9, words(3000)), true},
		{"runs 20000 -9", bzip(9, runs(20000, 5)), true},
		{"empty", bzip(9, nil), true},
		{"one byte", bzip(1, []byte("x")), true},
		{"noise 2000 -3", bzip(3, noise(2000, 9)), true},
		{"words and runs", append(bzip(2, words(1000)), bzip(5, runs(3000, 6))...), true},
	}

	fmt.Print(`/* Generated by tools/gen-bzip2-tests.sh from Go's compress/bzip2. Do not
 * edit. */

#ifndef BURROW_TESTS_BZIP2_TEST_GEN_H
#define BURROW_TESTS_BZIP2_TEST_GEN_H

`)
	for i, s := range streams {
		enc := base64.StdEncoding.EncodeToString(s.data)
		fmt.Printf("/* %s, %d bytes. */\nstatic const char *const bzip2_stream_%d[] = {\n", s.name, len(s.data), i)
		for len(enc) > 0 {
			k := min(72, len(enc))
			fmt.Printf("    \"%s\",\n", enc[:k])
			enc = enc[k:]
		}
		fmt.Printf("    NULL,\n};\n\n")
	}

	fmt.Print(`typedef struct Bzip2Stream {
    const char *name;
    const char *const *b64;
    Int len;           /* what Go's reader gives */
    const char *sha256;
    const char *err;   /* "" for io.EOF */
} Bzip2Stream;

static const Bzip2Stream bzip2_streams[] = {
`)
	for i, s := range streams {
		n, sum, e := decode(s.data)
		fmt.Printf("    {\"%s\", bzip2_stream_%d, %d, \"%s\", \"%s\"},\n", s.name, i, n, sum, e)
	}
	fmt.Print("};\n\n")

	// Damage: kind 0 flips the bits of mask in byte pos, kind 1 cuts the
	// stream to pos bytes, kind 2 adds suffixes[pos] after it.
	suffixes := []string{"", "B", "BZ", "BZh", "x", "xy", "BZh0", "BZa9", "BZh91AY&SY"}
	fmt.Print(`static const char *const bzip2_suffixes[] = {
`)
	for _, s := range suffixes {
		fmt.Printf("    \"%s\",\n", s)
	}
	fmt.Print(`};

typedef struct Bzip2Damage {
    int stream;
    int kind;
    int pos;
    int mask;
    Int len;
    const char *sha256; /* the first 16 hex digits */
    const char *err;
} Bzip2Damage;

static const Bzip2Damage bzip2_damage[] = {
`)
	rows := 0
	for i, s := range streams {
		if !s.mutate {
			continue
		}
		n := len(s.data)
		step := 1
		if n > 200 {
			step = n / 200
		}
		emit := func(kind, pos, mask int, in []byte) {
			l, sum, e := decode(in)
			fmt.Printf("    {%d, %d, %d, %d, %d, \"%s\", \"%s\"},\n", i, kind, pos, mask, l, sum[:16], e)
			rows++
		}
		for p := 0; p < n; p++ {
			if p >= 64 && p%step != 0 && p < n-16 {
				continue
			}
			mask := 1 << (p % 8)
			d := bytes.Clone(s.data)
			d[p] ^= byte(mask)
			emit(0, p, mask, d)
			if p%4 == 0 {
				d = bytes.Clone(s.data)
				d[p] ^= 0xff
				emit(0, p, 0xff, d)
			}
		}
		for p := 0; p < n; p++ {
			if p >= 64 && p%step != 0 && p < n-16 {
				continue
			}
			emit(1, p, 0, s.data[:p])
		}
		for k, suf := range suffixes {
			emit(2, k, 0, append(bytes.Clone(s.data), suf...))
		}
	}
	fmt.Print("};\n\n#endif\n")
	fmt.Fprintf(os.Stderr, "%d streams, %d damaged\n", len(streams), rows)
}
GO

cd "$tmp"
go mod init gen >/dev/null 2>&1
go run . > "$out"
if command -v clang-format >/dev/null 2>&1; then
	clang-format -i "$out"
fi
echo "wrote $out"
