#!/bin/sh
# Regenerates tests/go_format_test_gen.h for the go/format tests. TestNode and
# TestSource in Go read format_test.go from disk, format it and check it comes
# out unchanged. Here every .go file of src/go/format goes in, since each one is
# already in gofmt style, and the tests run over all of them.
#
# A file can be bigger than the 64K MSVC takes in one string literal, so each
# one goes out as a list of pieces to put back together.
#
# GOROOT says which Go to read, and defaults to what go env says.
#
# Copyright 2026 The burrow Authors. All rights reserved.
# Use of this source code is governed by a BSD-style licence that can be found
# in the LICENSE file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
goroot=${GOROOT:-$(go env GOROOT)}
out="$root/tests/go_format_test_gen.h"

python3 - "$goroot" > "$out" <<'PY'
import os
import re
import sys

goroot = sys.argv[1]
pkg = os.path.join(goroot, "src", "go", "format")
gover = open(os.path.join(goroot, "VERSION")).readline().strip()

# Bytes of a file to each piece, well under what MSVC takes once escaped.
CHUNK = 12000

# The libc calls tools/check-banned.sh looks for. The first letter of a name
# like that goes out as an octal escape so the check does not take the text
# for a call.
BANNED = re.compile(
    rb"(?<![A-Za-z0-9_])(strcpy|strcat|sprintf|vsprintf|gets|strtok|strncpy|"
    rb"strncat|alloca|atoi|atol|atof)[ \t]*\("
)

# And the allocator names tools/check-banned.sh wants kept in the malloc
# backend, which it looks for as words, called or not.
BANNED_ALLOC = re.compile(
    rb"(?<![A-Za-z0-9_])(malloc|calloc|realloc|free|aligned_alloc|posix_memalign|"
    rb"_aligned_malloc|_aligned_realloc|_aligned_free)(?![A-Za-z0-9_])"
)


def lit(b):
    """b as C string literals, one line of the text to each."""
    lines, cur = [], ""
    hide = {m.start() for m in BANNED.finditer(b)}
    hide |= {m.start() for m in BANNED_ALLOC.finditer(b)}
    for i, c in enumerate(b):
        if i in hide:
            s = "\\%03o" % c
        elif c == 10:
            s = "\\n"
        elif c == 9:
            s = "\\t"
        elif c == 34:
            s = '\\"'
        elif c == 92:
            s = "\\\\"
        elif c == 63 and i + 1 < len(b) and b[i + 1] == 63:
            s = "\\?"
        elif 32 <= c < 127:
            s = chr(c)
        else:
            s = "\\%03o" % c
        # an octal escape must not run into a digit after it
        if s.startswith("\\") and s[1:].isdigit() and i + 1 < len(b):
            nxt = b[i + 1]
            if 48 <= nxt <= 55:
                cur += s
                lines.append('"' + cur + '"')
                cur = ""
                continue
        cur += s
        if c == 10 or len(cur) >= 70:
            lines.append('"' + cur + '"')
            cur = ""
    if cur or not lines:
        lines.append('"' + cur + '"')
    return lines


def pieces(b):
    out = []
    for i in range(0, max(len(b), 1), CHUNK):
        out.append(b[i : i + CHUNK])
    return out


names = sorted(f for f in os.listdir(pkg) if f.endswith(".go"))
# format_test.go first, the file Go's own tests use
names.remove("format_test.go")
names.insert(0, "format_test.go")

w = sys.stdout.write
w("/* What Go's go/format tests read, from src/go/format of %s.\n" % gover)
w(" * Generated by tools/gen-go-format-tests.sh; do not edit. */\n\n")
w("typedef struct GfmtPiece {\n    const char *p;\n    long long n;\n} GfmtPiece;\n\n")
w("#define GFMT_P(x) {x, (long long)sizeof(x) - 1}\n\n")
w("typedef struct GfmtFile {\n    const char *name;\n    const GfmtPiece *pieces;\n")
w("    int npieces;\n} GfmtFile;\n\n")
for k, name in enumerate(names):
    data = open(os.path.join(pkg, name), "rb").read()
    w("static const GfmtPiece gfmt_file_%d[] = {\n" % k)
    for p in pieces(data):
        w("    GFMT_P(" + "\n           ".join(lit(p)) + "),\n")
    w("};\n\n")

w("static const GfmtFile gfmt_files[] = {\n")
for k, name in enumerate(names):
    w('    {"%s", gfmt_file_%d, (int)(sizeof(gfmt_file_%d) / sizeof(gfmt_file_%d[0]))},\n'
      % (name, k, k, k))
w("};\n")
PY
